### ISSUE TITLE
Broadcast URI not set for Shared networks when IP(v4) range not provided

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#10114]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Network Setup / VM deployment
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.3 (But may be observed in all versions)
~~~

##### OS / ENVIRONMENT

Agnostic of OS

##### STEPS TO REPRODUCE

~~~
1. Create a network offering for Shared network with specifyVlan = false and no services ; enable the network offering
2. Create a shared network using this offering and provide only IPv4 gateway and netmask (no IP range provided)
3. Attempt deploying VM with the network created in step 2
~~~

##### EXPECTED RESULTS

~~~
Should check if required IP range is provided
~~~

##### ACTUAL RESULTS

~~~
Fails to create network due to an NPE (cause because no validations are made for the IPv4 range)
2024-12-16 21:35:57,913 DEBUG [c.c.a.t.Request] (AgentManager-Handler-20:null) (logid:) Seq 1-1666894812080597370: Processing:  { Ans: , MgmtId: 32987932524925, via: 1, Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":"false","details":"java.lang.NullPointerException
	at com.cloud.network.Networks$BroadcastDomainType.getSchemeValue(Networks.java:178)
	at com.cloud.network.Networks$BroadcastDomainType.getValue(Networks.java:232)
	at com.cloud.hypervisor.kvm.resource.BridgeVifDriver.plug(BridgeVifDriver.java:204)
	at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.createVif(LibvirtComputingResource.java:3337)
	at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.createVifs(LibvirtComputingResource.java:2951)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStartCommandWrapper.execute(LibvirtStartCommandWrapper.java:84)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStartCommandWrapper.execute(LibvirtStartCommandWrapper.java:49)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
	at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1929)
	at com.cloud.agent.Agent.processRequest(Agent.java:683)
	at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1106)
	at com.cloud.utils.nio.Task.call(Task.java:83)
	at com.cloud.utils.nio.Task.call(Task.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
","wait":"0","bypassHostMaintenance":"false"}}] }

~~~

**Comment by DaanHoogland** [comment]
fixed in #10168
