### ISSUE TITLE
Unable to create VM from ISO

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2641]
#### ISSUE TYPE
 
**Bug**

#### COMPONENT NAME

**CloudStack Agent**

#### CLOUDSTACK VERSION

**4.11.0.0**

#### CONFIGURATION

* **Advanced Networking**
* **KVM**
* **CEPH Storage (RBD pool)**

#### OS / ENVIRONMENT

**CentOS Linux release 7.4.1708**

#### Summary
Ubuntu 16.04 ISO is registered ([ISO link](http://releases.ubuntu.com/16.04/ubuntu-16.04.4-server-amd64.iso))
ISO status: ready.
When trying to create vm from ISO, getting error: unsupported configuration: only RAW volumes are supported by this storage pool

**Management server log**
~~~
2018-05-14 10:25:14,263 DEBUG [o.a.c.e.o.VolumeOrchestrator] (Work-Job-Executor-2:ctx-37bb2bb5 job-46/job-47 ctx-d1a0c838) (logid:46f24ebc) Unable to create Vol[5|vm=5|ROOT]:com.cloud.utils.exception.CloudRuntimeException: org.libvirt.LibvirtException: unsupported configuration: only RAW volumes are supported by this storage pool
2018-05-14 10:25:14,264 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-2:ctx-37bb2bb5 job-46/job-47 ctx-d1a0c838) (logid:46f24ebc) Unable to contact resource.
com.cloud.exception.StorageUnavailableException: Resource [StoragePool:3] is unreachable: Unable to create Vol[5|vm=5|ROOT]:com.cloud.utils.exception.CloudRuntimeException: org.libvirt.LibvirtException: unsupported configuration: only RAW volumes are supported by this storage pool
	at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.recreateVolume(VolumeOrchestrator.java:1336)
	at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.prepare(VolumeOrchestrator.java:1413)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1110)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:4927)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
	at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5090)
	at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:581)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:529)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
~~~
**Agent log**
~~~
2018-05-14 10:42:56,234 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-1:null) (logid:ab093391) Succesfully refreshed pool 9a2e9bd0-2218-373e-851c-e7c7176a3974 Capacity: 10199249412096 Used: 4794017843 Available: 10155745476608
2018-05-14 10:42:56,235 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-1:null) (logid:ab093391) Attempting to create volume 56df4307-6d19-4832-bcad-a54b840bca04 (RBD) in pool 9a2e9bd0-2218-373e-851c-e7c7176a3974 with size 21474836480
2018-05-14 10:42:56,237 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-1:null) (logid:ab093391) <volume>
<name>56df4307-6d19-4832-bcad-a54b840bca04</name>
<capacity>21474836480</capacity>
<target>
<format type='qcow2'/>
<permissions><mode>0744</mode></permissions></target>
</volume>

2018-05-14 10:42:56,244 DEBUG [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-1:null) (logid:ab093391) Failed to create volume:
com.cloud.utils.exception.CloudRuntimeException: org.libvirt.LibvirtException: unsupported configuration: only RAW volumes are supported by this storage pool
	at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.createPhysicalDiskByLibVirt(LibvirtStorageAdaptor.java:705)
	at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.createPhysicalDisk(LibvirtStorageAdaptor.java:664)
	at com.cloud.hypervisor.kvm.storage.LibvirtStoragePool.createPhysicalDisk(LibvirtStoragePool.java:115)
	at com.cloud.hypervisor.kvm.storage.KVMStorageProcessor.createVolume(KVMStorageProcessor.java:1323)
	at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.execute(StorageSubsystemCommandHandlerBase.java:119)
	at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.handleStorageCommands(StorageSubsystemCommandHandlerBase.java:58)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStorageSubSystemCommandWrapper.execute(LibvirtStorageSubSystemCommandWrapper.java:36)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStorageSubSystemCommandWrapper.execute(LibvirtStorageSubSystemCommandWrapper.java:30)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:75)
	at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1438)
	at com.cloud.agent.Agent.processRequest(Agent.java:563)
	at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:976)
	at com.cloud.utils.nio.Task.call(Task.java:83)
	at com.cloud.utils.nio.Task.call(Task.java:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-05-14 10:42:56,247 DEBUG [cloud.agent.Agent] (agentRequest-Handler-1:null) (logid:ab093391) Seq 4-4642648265865560075:  { Ans: , MgmtId: 168361987, via: 4, Ver: v1, Flags: 10, [{"org.apache.cloudstack.storage.command.CreateObjectAnswer":{"result":false,"details":"com.cloud.utils.exception.CloudRuntimeException: org.libvirt.LibvirtException: unsupported configuration: only RAW volumes are supported by this storage pool","wait":0}}] }
~~~

**Comment by izenk** [comment]
Found the same here: (CLOUDSTACK-10308)[https://issues.apache.org/jira/browse/CLOUDSTACK-10308]

**Comment by rhtyd** [comment]
This has been recently fixed in 4.11.1.0 milestone @izenk can you test latest 4.11 branch?

**Comment by izenk** [comment]
@rhtyd  unfortunately now, just using 4.11 LTS as company private cloud

**Comment by izenk** [comment]
works in 4.11.1
issue is closed
