### ISSUE TITLE
package.sh -d centos7   ERROR

### ISSUE THREAD

**Issue by saliven1970** [apache/cloudstack#2677]
##### ISSUE TYPE

 Bug Report
 ##### COMPONENT NAME

packaging

##### CLOUDSTACK VERSION

4.12 master

##### OS / ENVIRONMENT

CentOS 7.4 x64
java-1.8.0-openjdk-1.8.0.171-7.b10.el7.x86_64

##### SUMMARY

when cloudstack/packaging/centos7/cloud.spec

mvn -Psystemvm,developer -DskipTests $FLAGS clean package
fix to:
mvn -Psystemvm,developer $FLAGS clean package

then occur this ERROR.

use JDK1.8.0.161 build,This error will not occur.
Are unsafe encryption functions used in MockServerTest.java?

##### STEPS TO REPRODUCE

package.sh -d centos7 

##### EXPECTED RESULTS

Build Success

##### ACTUAL RESULTS

Running common.ClientTest
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.242 sec - in c ommon.ClientTest
 Running rdpclient.MockServerTest
 Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.454 sec <<< FA ILURE! - in rdpclient.MockServerTest
 testIsMockServerCanUpgradeConnectionToSsl(rdpclient.MockServerTest) Time elapse d: 0.45 sec <<< ERROR!
 javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabl ed or cipher suites are inappropriate)
 at sun.security.ssl.Handshaker.activate(Handshaker.java:529)
 at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java: 1492)
 at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl. java:1361)
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413 )
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397 )
 at rdpclient.MockServerTest.testIsMockServerCanUpgradeConnectionToSsl(MockServerTest.java:166)

Running streamer.ByteBufferTest
 Error in mock server: Received fatal alert: handshake_failure
 javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
 at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
 at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
 at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2038)
 at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
 at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl. java:1385)
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413 )
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397 )
 at streamer.debug.MockServer.run(MockServer.java:122)
 at java.lang.Thread.run(Thread.java:748)
 Tests run: 400, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.066 sec - in streamer.ByteBufferTest
 Running streamer.BaseElementTest
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec - in s treamer.BaseElementTest

Results :

Tests in error:
 MockServerTest.testIsMockServerCanUpgradeConnectionToSsl:166 ? SSLHandshake No ...

**Comment by rafaelweingartner** [comment]
This is a known issue and is being fixed at #2674

**Comment by DaanHoogland** [comment]
are you sure @rafaelweingartner #2674 is about configdrive. It doesn't seem related to me.

**Comment by rafaelweingartner** [comment]
@DaanHoogland 100% sure :)
Check my comment https://github.com/apache/cloudstack/pull/2674#issuecomment-391743061

There was another problem, which is this one that was causing trouble in some scenarios when building ACS. I discovered that with @khos2ow. This problem is fixed with my fourth commit there: 69961dc9067ffa1ae4460436825125718c5ad796

**Comment by DaanHoogland** [comment]
ah, I see. wonder if these will be autoclosed ;) bit confusing

**Comment by rafaelweingartner** [comment]
They should be

**Comment by khos2ow** [comment]
It will *not* be auto-closed, the #2674 body misses `Fixes #2677`.

**Comment by saliven1970** [comment]
This is a known issue and is being fixed at #2674
