### ISSUE TITLE
Unable to create local link issue (CS 4.11.1-rc1 + XCP-ng 7.4.1)

### ISSUE THREAD

**Issue by ikoula** [apache/cloudstack#2695]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Hypervisor controler
~~~

##### CLOUDSTACK VERSION

~~~
CS Version : 4.11.1-rc1 (fresh install)
~~~

##### CONFIGURATION

Management Server : CentOS 7 (fresh install)
Hypervisor : 2 x XCP-ng 7.4.1 (fresh install, in the same pool)
Zone : Advanced without SG (local storage enabled for both system & user VMs)

##### SUMMARY

Unable to create the local link network on the newly added host
AddHost API Call is succeeding but host stays in alert state since the local link cannot be created.

##### STEPS TO REPRODUCE

~~~
Add an XCP-ng 7.4.1 host under an Advanced Zone (I think the issue will also hit basic zones).
~~~

##### EXPECTED RESULTS

~~~
local link creation should be successful.
~~~

##### ACTUAL RESULTS

~~~
2018-06-05 11:19:44,110 WARN  [c.c.h.x.r.CitrixResourceBase] (DirectAgent-2:ctx-ed8cfa5d) (logid:8c5c169f) Unable to create local link network
The server failed to handle your request, due to an internal error.  The given message may give details useful for debugging the problem.
        at com.xensource.xenapi.Types.checkResponse(Types.java:1609)
        at com.xensource.xenapi.Connection.dispatch(Connection.java:395)
        at com.cloud.hypervisor.xenserver.resource.XenServerConnectionPool$XenServerConnection.dispatch(XenServerConnectionPool.java:457)
        at com.xensource.xenapi.VIF.plug(VIF.java:887)
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.plugDom0Vif(CitrixResourceBase.java:4056)
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.setupLinkLocalNetwork(CitrixResourceBase.java:4806)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixReadyCommandWrapper.execute(CitrixReadyCommandWrapper.java:52)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixReadyCommandWrapper.execute(CitrixReadyCommandWrapper.java:38)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.executeRequest(CitrixResourceBase.java:1728)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
~~~

Here is a more complete snippet from the management log during the addHost :
[addhost_xcp-ng_741.log](https://github.com/apache/cloudstack/files/2075157/addhost_xcp-ng_741.log)

xenopds seems to be the culprit :
~~~
[root@test-xen01 ~]# xe vif-param-list uuid=95e50cbb-80ce-692a-ef33-a3055b4e8b00
uuid ( RO)                        : 95e50cbb-80ce-692a-ef33-a3055b4e8b00
                     vm-uuid ( RO): 4313460b-55fe-40b0-afc3-7b1a3ab63cfd
               vm-name-label ( RO): Control domain on host: test-xen01
          allowed-operations (SRO): attach; plug
          current-operations (SRO):
                      device ( RO): 0
                         MAC ( RO): FE:FF:FF:FF:FF:FF
           MAC-autogenerated ( RO): false
                         MTU ( RO): 0
          currently-attached ( RO): false
          qos_algorithm_type ( RW):
        qos_algorithm_params (MRW):
    qos_supported_algorithms (SRO):
                other-config (MRW): nameLabel: link_local_network_vif
                network-uuid ( RO): b7c29721-af1b-d09d-aeb5-a6e43e8062a6
          network-name-label ( RO): cloud_link_local_network
                 io_read_kbs ( RO): <unknown>
                io_write_kbs ( RO): <unknown>
                locking-mode ( RW): network_default
                ipv4-allowed (SRW):
                ipv6-allowed (SRW):
     ipv4-configuration-mode ( RO): None
              ipv4-addresses ( RO):
                ipv4-gateway ( RO):
     ipv6-configuration-mode ( RO): None
              ipv6-addresses ( RO):
                ipv6-gateway ( RO):


[root@test-xen01 ~]# xe vif-plug uuid=95e50cbb-80ce-692a-ef33-a3055b4e8b00
The server failed to handle your request, due to an internal error.  The given message may give details useful for debugging the problem.
message: Object with type VM and id 4313460b-55fe-40b0-afc3-7b1a3ab63cfd does not exist in xenopsd

[root@cs-preprod-z1-p1-c1-xen01 ~]# systemctl status xenopsd-xc.service
● xenopsd-xc.service - VM manager for Xen using libxc
   Loaded: loaded (/usr/lib/systemd/system/xenopsd-xc.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/xenopsd-xc.service.d
           └─local.conf, slice.conf
   Active: active (running) since Mon 2018-06-04 17:41:19 CEST; 5min ago
     Docs: man:xenopsd-xc(1)
 Main PID: 28505 (xenopsd-xc)
   CGroup: /control.slice/xenopsd-xc.service
           └─28505 /usr/sbin/xenopsd-xc --config /etc/xenopsd.conf

[root@cs-preprod-z1-p1-c1-xen01 ~]# systemctl status xenopsd-xenlight.service
● xenopsd-xenlight.service - VM manager for Xen using libxenlight
   Loaded: loaded (/usr/lib/systemd/system/xenopsd-xenlight.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-06-04 15:49:52 CEST; 1h 56min ago
     Docs: man:xenopsd-xenlight(1)
 Main PID: 8317 (xenopsd-xenligh)
   CGroup: /system.slice/xenopsd-xenlight.service
           └─8317 /usr/sbin/xenopsd-xenlight --config /etc/xenopsd.conf
~~~

We are able to experiment in our lab environment as needed (including CS builds/reinstall or XCP reinstalls).

**Comment by rhtyd** [comment]
For reference, both xcp-ng 7.4.1 and 7.4.0 have the same product version set to 7.4.0. The following is from a 7.4.1 iso/installed xenserver host:
![screenshot from 2018-06-07 11-46-05](https://user-images.githubusercontent.com/95203/41081788-c0f752c0-6a49-11e8-815a-b280d0db122a.png)
I was able to deploy an advanced zone (without local storage) using xcp-ng 7.4.1 and could see systemvms start.

**Comment by ikoula** [comment]
Ok my bad, our tree was missing the latests modifications from plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java following a failed (?) rebase.
Using the 4.11.1-rc1 packages it's working as expected using XCP-ng 7.4.1

Sorry for the inconvenience, I'm closing this issue.

**Comment by rhtyd** [comment]
Thanks for sharing @ikoula, perhaps you can test again with 4.11.1.0-rc2 soon.
