### ISSUE TITLE
provisionCertificate api returns NPE when 'reconnect' parameter is used.

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#2753]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
api
~~~

##### CLOUDSTACK VERSION

~~~
4.12
~~~

##### SUMMARY

When executing the provisionCertificate api with reconnect parameter a NPE appears

##### STEPS TO REPRODUCE

~~~
```
2018-07-19 08:05:50,050 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-56:ctx-7e01f347 job-60) (logid:ac0ee859) Unexpected exception while executing org.apache.cloudstack.api.command.admin.ca.ProvisionCertificateCmd
java.lang.NullPointerException
	at com.cloud.agent.manager.ClusteredAgentManagerImpl.reconnect(ClusteredAgentManagerImpl.java:372)
	at org.apache.cloudstack.ca.CAManagerImpl.deployCertificate(CAManagerImpl.java:232)
	at org.apache.cloudstack.ca.CAManagerImpl.provisionCertificate(CAManagerImpl.java:194)
	at sun.reflect.GeneratedMethodAccessor273.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy217.provisionCertificate(Unknown Source)
	at org.apache.cloudstack.api.command.admin.ca.ProvisionCertificateCmd.execute(ProvisionCertificateCmd.java:95)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:150)
	at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:108)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:581)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:529)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-19 08:05:50,051 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-56:ctx-7e01f347 job-60) (logid:ac0ee859) Complete async job-60, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":530
```
~~~

##### EXPECTED RESULTS

~~~
Api call should succeed 
~~~

##### ACTUAL RESULTS

~~~
It fails with NPE 
~~~

**Comment by dhlaluku** [comment]
Fix provided in PR: https://github.com/apache/cloudstack/pull/2756
