### ISSUE TITLE
LDAP login java.lang.NullPointerException

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2853]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
Management server, API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

Advanced networking, LDAP integration

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708

##### SUMMARY

During LDAP user login java.lang.NullPointerException appeared.

##### STEPS TO REPRODUCE

- Create domain
- Set LDAP configuration for this domain (not for ROOT domain and not in GLOBAL SETTINGS)
- Import LDAP Accounts through "Add LDAP account" button
- Accounts are imported and enabled
-  Try to login with LDAP user

##### EXPECTED RESULTS

~~~
Login is successfull
~~~

##### ACTUAL RESULTS

LDAP connection was checked by ldapsearch command from management server with the same credentials.
User can bind and search.

~~~
2018-09-19 12:11:01,442 INFO  [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-cead411b) (logid:89449541) End cleanup expired async-jobs
2018-09-19 12:11:06,280 INFO  [o.a.c.l.LdapContextFactory] (qtp1595953398-17:ctx-4bbda8d3) (logid:68a8575d) LDAP SSL enabled.
2018-09-19 12:11:06,283 DEBUG [o.a.c.l.LdapContextFactory] (qtp1595953398-17:ctx-4bbda8d3) (logid:68a8575d) initializing ldap with provider url: ldaps://ldap.srv:636
2018-09-19 12:11:06,536 DEBUG [o.a.c.l.OpenLdapUserManagerImpl] (qtp1595953398-17:ctx-4bbda8d3) (logid:68a8575d) adding search filter for 'CN=demosso,OU=AADDC Users,DC=org,DC=com', using memberof
2018-09-19 12:11:06,597 INFO  [o.a.c.l.LdapContextFactory] (qtp1595953398-17:ctx-4bbda8d3) (logid:68a8575d) LDAP SSL enabled.
2018-09-19 12:11:06,599 DEBUG [o.a.c.l.LdapContextFactory] (qtp1595953398-17:ctx-4bbda8d3) (logid:68a8575d) initializing ldap with provider url: ldaps://ldap.srv:636
2018-09-19 12:11:06,788 ERROR [c.c.a.ApiServlet] (qtp1595953398-17:ctx-4bbda8d3) (logid:68a8575d) unknown exception writing api response
java.lang.NullPointerException
        at com.cloud.user.AccountManagerImpl.checkIfNotMovingAcrossDomains(AccountManagerImpl.java:1768)
        at com.cloud.user.AccountManagerImpl.moveUser(AccountManagerImpl.java:1721)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy39.moveUser(Unknown Source)
        at org.apache.cloudstack.ldap.LdapAuthenticator.authenticate(LdapAuthenticator.java:138)
        at org.apache.cloudstack.ldap.LdapAuthenticator.authenticate(LdapAuthenticator.java:78)
        at com.cloud.user.AccountManagerImpl.getUserAccount(AccountManagerImpl.java:2266)
        at com.cloud.user.AccountManagerImpl.authenticateUser(AccountManagerImpl.java:2107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy39.authenticateUser(Unknown Source)
        at com.cloud.api.ApiServer.loginUser(ApiServer.java:1048)
        at com.cloud.api.auth.DefaultLoginAPIAuthenticatorCmd.authenticate(DefaultLoginAPIAuthenticatorCmd.java:172)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:214)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:130)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:127)
        at com.cloud.api.ApiServlet.doPost(ApiServlet.java:94)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)
2018-09-19 12:11:06,902 INFO  [o.a.c.l.LdapContextFactory] (qtp1595953398-16:ctx-6b1fb2a2) (logid:7ff125ca) LDAP SSL enabled.
2018-09-19 12:11:06,904 DEBUG [o.a.c.l.LdapContextFactory] (qtp1595953398-16:ctx-6b1fb2a2) (logid:7ff125ca) initializing ldap with provider url: ldaps://ldap.srv:636
2018-09-19 12:11:07,093 DEBUG [o.a.c.l.OpenLdapUserManagerImpl] (qtp1595953398-16:ctx-6b1fb2a2) (logid:7ff125ca) adding search filter for 'CN=demosso,OU=AADDC Users,DC=org,DC=com', using memberof
2018-09-19 12:11:07,136 INFO  [o.a.c.l.LdapContextFactory] (qtp1595953398-16:ctx-6b1fb2a2) (logid:7ff125ca) LDAP SSL enabled.
2018-09-19 12:11:07,139 DEBUG [o.a.c.l.LdapContextFactory] (qtp1595953398-16:ctx-6b1fb2a2) (logid:7ff125ca) initializing ldap with provider url: ldaps://ldap.srv:636
2018-09-19 12:11:07,323 ERROR [c.c.a.ApiServlet] (qtp1595953398-16:ctx-6b1fb2a2) (logid:7ff125ca) unknown exception writing api response
java.lang.NullPointerException
        at com.cloud.user.AccountManagerImpl.checkIfNotMovingAcrossDomains(AccountManagerImpl.java:1768)
        at com.cloud.user.AccountManagerImpl.moveUser(AccountManagerImpl.java:1721)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy39.moveUser(Unknown Source)
        at org.apache.cloudstack.ldap.LdapAuthenticator.authenticate(LdapAuthenticator.java:138)
        at org.apache.cloudstack.ldap.LdapAuthenticator.authenticate(LdapAuthenticator.java:78)
        at com.cloud.user.AccountManagerImpl.getUserAccount(AccountManagerImpl.java:2266)
        at com.cloud.user.AccountManagerImpl.authenticateUser(AccountManagerImpl.java:2107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy39.authenticateUser(Unknown Source)
        at com.cloud.api.ApiServer.loginUser(ApiServer.java:1048)
        at com.cloud.api.auth.DefaultLoginAPIAuthenticatorCmd.authenticate(DefaultLoginAPIAuthenticatorCmd.java:172)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:214)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:130)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:130)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:127)
        at com.cloud.api.ApiServlet.doPost(ApiServlet.java:94)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)
2018-09-19 12:11:10,012 DEBUG [o.a.c.m.PrometheusExporterServerImpl] (Thread-26:null) (logid:) Prometheus exporter received client request from: 127.0.0.1
~~~

**Comment by DaanHoogland** [comment]
yes,
@izenk there are three types of configurations for LDAP.  It seems you are mixing them. The message you are getting is not clear and that is a bug to me, but...
Using the setting of the LDAP on domain level does not work with manual import LDAP account. I am not sure what you are trying to achieve.

If you want the automatic account synchronisation, or if I am misinterpreting what your setup is, please send a mail to dev@cloudstack.apace.org and I'll help you set it up.

Assuming you want to just manually import some accounts to LDAP, you can remove the LDAP binding on domain and set the server on global level.
If you want automatic import you then configure the CloudStack domain for use with LDAP using linkDomainToLdap. You should not add the parameter "ldapdomain".

Configuring the domain level ldap server is only useful for automatic synchronisation of accounts with LDAP within a domain. This setup will take some more effort.

**Comment by izenk** [comment]
@DaanHoogland thanks for clarifications
Where I can find description of these 3 types LDAP configurations (in 4.11 docs - no)?
As I understand, auto sync with LDAP is not possible in 4.11.1 because of [issue](https://github.com/apache/cloudstack/issues/2843)

What I want to achieve:
I have cs 4.11.1
Active Directory. In AD I have different groups
I want to create domains in CS (one cs domain = 1 group in AD), so people from group have access to specific domain in CS.

**Comment by DaanHoogland** [comment]
> In AD I have different groups.
> I want to create domains in CS (one cs domain = 1 group in AD), so people from specific group have access to specific domain in CS with auto sync. Is it possible (for 4.11.1)

This scenario is not implemented. What is implemented is that two LDAP groups can be linked to two accounts in a domain (autosync), or that a single domain is linked to LDAP and for each user in a group an account will be created in ACS. What you are trying to do might work but it wasn't designed like that.

**Comment by DaanHoogland** [comment]
Ok, than you need to not have the settings on domain level but on global level only. I know this sounds confusing but this is how it used to work and it remains backwards compatible with that functionality:

- Set LDAP configuration (not for a domain but in GLOBAL SETTINGS)
- Create domain
- call LinkDomainToLdap for the domain in which you automatic import to occur
- You don't have to import LDAP Accounts through the "Add LDAP account" button!
- Accounts are imported and enabled as users first login with valid ldap credentials

**Comment by izenk** [comment]
@DaanHoogland thank you, I'll try this.
But for what are the domain level LDAP settings is for?
What will happen if I add LDAP configuration globally and then for specific domain also add LDAP group setting on domain level?

**Comment by izenk** [comment]
@DaanHoogland sorry, Im confused a little..
if domain level setting is for automatic sync, why I must to setup parameters on GLOBAL level?

**Comment by DaanHoogland** [comment]
@izenk, I understand your confusion as it is not very clear indeed. The difference is auto-import or auto-sync.
LinkDomainToLdap is used for both, domain level settings are not.
Auto-import will not move users and will create an account per user.
Auto-sync will link an account to an LDAP group.

The last function you mention is not auto-sync but "just" auto-import. The "more granular" is auto-sync.

**Comment by izenk** [comment]
@DaanHoogland thanks.
Since "Link to LDAP" is not working in 4.11.1, I would like to use "Auto-import" while waiting for 4.11.2 with fixed "Link to LDAP". What are the steps for auto import? Should I start a thread in a maillist?

**Comment by rhtyd** [comment]
Is this still an issue? 4.11.2.0 is out, can you test @izenk ?
