### ISSUE TITLE
VR stop/start/reboot commands failed

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2862]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

KVM, Advanced networking

##### OS / ENVIRONMENT

Centos 7.4

##### SUMMARY

Stop/Start/Reboot command leads to VR inaccessibility. Only case is to restart VPC with "Clean up" options

##### STEPS TO REPRODUCE

Create VPC
Create multiple tiers (I have 6)
Create vms in every tier (in general 3 vm per tier)
Try VR operations: STOP/START or REBOOT

##### EXPECTED RESULTS

~~~
VR is restarted/ stopped/started
~~~

##### ACTUAL RESULTS

~~~
Resource [Host:4] is unreachable: Host 4: Unable to start instance due to Unable to start VM:38950734-d29e-49b3-b5f7-75f9b20a4207 due to error in finalizeStart, not retrying
~~~

**Comment by izenk** [comment]
apache2 service is not started even after VPC restart. Don't now if it connected to described problem...
There no even any log related to start of apache2
~~~
root@r-190-VM:~# grep apache /var/log/cloud.log
Tue Sep 25 13:59:41 UTC 2018 Setting up apache web server for VPC
2018-09-25 13:59:52,686  CsHelper.py copy:264 Copied /etc/apache2/vhost.template to /etc/apache2/sites-enabled/vhost-172.16.0.17.conf
2018-09-25 13:59:52,690  CsFile.py commit:66 Wrote edited file /etc/apache2/sites-enabled/vhost-172.16.0.17.conf
2018-09-25 13:59:54,456  CsHelper.py copy:264 Copied /etc/apache2/vhost.template to /etc/apache2/sites-enabled/vhost-172.16.0.1.conf
2018-09-25 13:59:54,461  CsFile.py commit:66 Wrote edited file /etc/apache2/sites-enabled/vhost-172.16.0.1.conf
2018-09-25 13:59:55,773  CsHelper.py copy:264 Copied /etc/apache2/vhost.template to /etc/apache2/sites-enabled/vhost-172.16.0.33.conf
2018-09-25 13:59:55,776  CsFile.py commit:66 Wrote edited file /etc/apache2/sites-enabled/vhost-172.16.0.33.conf
2018-09-25 13:59:57,076  CsHelper.py copy:264 Copied /etc/apache2/vhost.template to /etc/apache2/sites-enabled/vhost-172.16.0.49.conf
2018-09-25 13:59:57,080  CsFile.py commit:66 Wrote edited file /etc/apache2/sites-enabled/vhost-172.16.0.49.conf
2018-09-25 13:59:58,459  CsHelper.py copy:264 Copied /etc/apache2/vhost.template to /etc/apache2/sites-enabled/vhost-172.16.0.65.conf
2018-09-25 13:59:58,463  CsFile.py commit:66 Wrote edited file /etc/apache2/sites-enabled/vhost-172.16.0.65.conf
2018-09-25 13:59:59,926  CsHelper.py copy:264 Copied /etc/apache2/vhost.template to /etc/apache2/sites-enabled/vhost-172.16.0.81.conf
2018-09-25 13:59:59,930  CsFile.py commit:66 Wrote edited file /etc/apache2/sites-enabled/vhost-172.16.0.81.conf
~~~

**Comment by resmo** [comment]
we also hit this issue.

**Comment by rhtyd** [comment]
@resmo can you confirm if you tested 4.11.1.0 or the 4.11.2.0 RC2? I'm unable to reproduce this at least on KVM with 4.11.2.0 RC2, will test against vmware 5.5 next.

**Comment by rhtyd** [comment]
@izenk apache2 should be started by the post cloud-init script. Can you share output of systemctl status apache2, what error do you see? I could not reproduce the issue with either stop+start or rebooting of the VPC VR, it came up OK for me in case of CentOS7 KVM host. For the broken VR, can you share its /var/log/cloud.log file?

**Comment by resmo** [comment]
@rhtyd its 4.11.1.0

**Comment by rhtyd** [comment]
Thanks @resmo. @resmo @izenk can you describe your VPC (or isolated network) setups, do you have private gateway and/or additional services (vpn etc) or rules etc? In my two test setups (CentOS7 KVM and VMware 5.5 based), I could not reproduce the issue against latest 4.11.2.0 rc2 (latest 4.11 branch). About the apache2 process blocking VRs from starting, we've fixed that in 4.11.1.0 already, I could no longer reproduce that on vmware. /cc @PaulAngus

**Comment by rhtyd** [comment]
@resmo we'll need the /var/log/cloud.log from the VR when this happens as well as the management server logs when you reproduce the next time.

**Comment by rhtyd** [comment]
@resmo we'll need additional logs from an env/VRs where you're seeing the error to debug/investigate and fix this issue.

**Comment by izenk** [comment]
@rhtyd 
I reproduced the problem.
Management log:
~~~
2018-10-16 11:23:19,102 ERROR [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-147:ctx-edf7f753 job-3221/job-3222 ctx-ea
279b8a) (logid:e2c57742) process hasn't exited
2018-10-16 11:23:19,102 WARN  [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-147:ctx-edf7f753 job-3221/job-3222 ctx-ea
279b8a) (logid:e2c57742) Command: com.cloud.agent.api.Command failed while starting virtual router
2018-10-16 11:23:20,014 DEBUG [o.a.c.m.PrometheusExporterServerImpl] (Thread-26:null) (logid:) Prometheus exporter received client request from: 127.0.0.1
2018-10-16 11:23:20,210 WARN  [o.a.c.f.j.i.AsyncJobMonitor] (Timer-1:ctx-7e4bc9be) (logid:9c2c84b7) Task (job-3221) has been pending for 721 seconds
2018-10-16 11:23:20,210 WARN  [o.a.c.f.j.i.AsyncJobMonitor] (Timer-1:ctx-7e4bc9be) (logid:9c2c84b7) Task (job-3222) has been pending for 720 seconds
2018-10-16 11:23:20,554 DEBUG [o.a.c.s.SecondaryStorageManagerImpl] (secstorage-1:ctx-0e1cf9c6) (logid:377fefe1) Zone 1 is ready to launch secondary storage VM
2018-10-16 11:23:21,482 INFO  [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-b70ac705) (logid:c2946d52) Begin cleanup expired async-jobs
2018-10-16 11:23:21,487 INFO  [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-b70ac705) (logid:c2946d52) End cleanup expired async-jobs
2018-10-16 11:23:21,648 WARN  [c.c.a.d.ParamGenericValidationWorker] (qtp1595953398-787:ctx-149b3355 ctx-c8a9574f) (logid:9aa313e4) Received unknown parameters for command queryAsyncJobResult. Unknown parameters : projectid
2018-10-16 11:23:21,678 ERROR [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-147:ctx-edf7f753 job-3221/job-3222 ctx-ea279b8a) (logid:e2c57742) Failed to start instance VM[DomainRouter|r-191-VM]
com.cloud.utils.exception.ExecutionException: Unable to start  VM:0832cd60-327d-416f-8264-cbf5df37d921 due to error in finalizeStart, not retrying
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1223)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:4930)
        at sun.reflect.GeneratedMethodAccessor536.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5093)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:581)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:529)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
~~~

cloud.log from VR is also attached
**some notes:** attached log is finished on line:
~~~
2018-10-16 09:13:20,611  CsHelper.py execute:188 Executing: mount
~~~
This is the last line before I got exception above.
What I see it's that VR didn't get Link Local network. It got Link Local IP, but there were no connection from host to VR through Link Local IP. I can enter VR through VNC from host only.

[cloud.log](https://github.com/apache/cloudstack/files/2482319/cloud.log)

**Comment by rhtyd** [comment]
Thanks @izenk let me have a look

**Comment by rhtyd** [comment]
@izenk can you describe your KVM setup, are you using bridge based networking or openvswitch with vlan/vxlan/etc, is it normal adv zone (or with security groups)? The ` process hasn't exited` in the logs implies the VR programming did not complete quickly or the script failed internally in the VR.

Reading the cloud.log from the VR, the first problem I see is which implies either failure of the cloudstack kvm agent to create file in the VR or VR already processed this file:

    2018-09-25 14:14:04,139  configure.py main:1047 Unable to find and process databag for file: ip_associations.json.a1f78335-796f-495e-8e95-b606587b6a51, for json

After restart of the VR, the following suggests that the nic device was not found due to which several other failures such as failure to reconfigure vpn also failed:

    2018-10-16 07:24:46,274  CsAddress.py waitfordevice:250 Device eth2 cannot be configured - device was not found
     ...
     2018-10-16 09:13:20,590  configure.py main:1047 Unable to find and process databag for file: ip_associations.json.d9dbda9d-e218-4c3c-a3c2-864428771b3d, for json

Let me try to investigate the code and see if I reproduce it, meanwhile please answer my questions.

**Comment by izenk** [comment]
@rhtyd 
KVM with bridge based networking
Advanced Zone without security groups

**Comment by rhtyd** [comment]
I could not reproduce the similar error with stop+start. However, with rebooting a VR I could see similar log statements, but ultimately the VR was able to start and I could not reproduce the error. There have been several VR related fixes in 4.11.2-rc2 compared to 4.11.1 so it's likely the bug is not reproducible. Please check and increase your router aggregation timeout and see if that helps?
@izenk can you test against 4.11.2-rc2 using the latest 4.11.2 systemvmtemplate? See the voting thread on dev@ ML.

**Comment by rhtyd** [comment]
Given, you've a workaround for this issue and I could not reproduce this with latest 4.11 branch I'll move this to 4.11.3.0 milestone to avoid further blocking of rc3.

**Comment by izenk** [comment]
@rhtyd ok
Im trying to debug issue myself. So may be some guidelines from your side..

When I click "Start" - VR starts boot. I can connect to it by VNC.
On my installation VR (normally) has 4 interfaces:
loopback
eth0: linklocal (169)
eth1: public net (10.9.x.x)
eth2: vpc tier  

After connecting by VNC (while tested VR is in "Starting" state) I can see only 3 interafaces:
loopback
eth0: linklocal net is not working, I can **arping** 169.254.0.1 (what is on host(cloud0)), but can't **ping** 169.254.0.1
eth1: - public net is working normally

Note: Also I increased "router aggregation timeout" (router.aggregation.command.each.timeout) - what doesn't help. It seems even has no any effect: error about finalizing operation appeared after the same time as before increasing outer.aggregation.command.each.timeout.

**Comment by izenk** [comment]
@rhtyd 
Looks like I found the reason (not the root, but near)

<img width="995" alt="screen shot 2018-10-17 at 16 33 16" src="https://user-images.githubusercontent.com/6417697/47089951-8795c900-d22a-11e8-859f-1bc9a24f37f9.png">

**Comment by rhtyd** [comment]
@izenk can you confirm if you tested 4.11.1 or 4.11.2-rc2? A routing related bug was fixed which is in 4.11.2-rc2.

**Comment by izenk** [comment]
@rhtyd no, can't
I have only 4.11.1 which is 'production'

**Comment by rhtyd** [comment]
@izenk the routing issue you've shared has been fixed and is in 4.11.2-rc2: https://github.com/apache/cloudstack/pull/2791/files
You may wait for 4.11.2.0 release or try to manually apply changes in the VR scripts in your test VR.

**Comment by izenk** [comment]
@rhtyd got it. Thanks

**Comment by rhtyd** [comment]
Can you test with 4.11.2.0 @izenk ? This probably can be closed.

**Comment by andrijapanicsb** [comment]
Any update on this one ? I believe I was observing similar situation...

**Comment by ustcweizhou** [comment]
@andrijapanicsb were you using vpc with public ips in multiple ip ranges or private gateway ?

**Comment by rhtyd** [comment]
Can you test against 4.11.2.0 or 4.11.3.0 @izenk ?

**Comment by rhtyd** [comment]
I'm unable to reproduce with 4.11.3.0 or master, kindly reopen with details @izenk if you're still facing this issue.
