### ISSUE TITLE
adding Source NAT services to VPC network offering results into unhandled exception

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#2881]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR, VPC, Network offering
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### OS / ENVIRONMENT

CentOS7

##### SUMMARY

Adding a Source NAT service to a VPC network offering results in an Unhandled exception 

##### STEPS TO REPRODUCE

~~~
1. Add Network offering
2. Select VPC
3. Select Source NAT
Click OK
~~~

##### EXPECTED RESULTS

~~~
Proper error handling/submission
~~~

##### ACTUAL RESULTS

~~~
Exception, no meaningful message displayed to admin
~~~

`2018-10-05 11:01:22,034 ERROR [c.c.a.ApiServer] (qtp788117692-18:ctx-4f8a0a70 ctx-8ab1c790) (logid:51627999) unhandled exception executing api command: [Ljava.lang.String;@40a02183
com.cloud.exception.UnsupportedServiceException: Provider com.cloud.network.Network$Provider@11763e57 requires services: [com.cloud.network.Network$Service@4f9871a2]
	at com.cloud.network.element.NuageVspElement.verifyServicesCombination(NuageVspElement.java:424)
	at com.cloud.network.NetworkModelImpl.canProviderSupportServices(NetworkModelImpl.java:1510)
	at com.cloud.configuration.ConfigurationManagerImpl.createNetworkOffering(ConfigurationManagerImpl.java:4368)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy114.createNetworkOffering(Unknown Source)
	at org.apache.cloudstack.api.command.admin.network.CreateNetworkOfferingCmd.execute(CreateNetworkOfferingCmd.java:318)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:150)
	at com.cloud.api.ApiServer.queueCommand(ApiServer.java:732)
	at com.cloud.api.ApiServer.handleRequest(ApiServer.java:556)
	at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:310)
	at com.cloud.api.ApiServlet$1.run(ApiServlet.java:130)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:127)
	at com.cloud.api.ApiServlet.doPost(ApiServlet.java:94)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
2018-10-05 11:01:22,039 INFO  [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-76daf13c) (logid:4f96db3d) End cleanup expired async-jobs
2018-10-05 11:01:22,039 DEBUG [c.c.a.ApiServlet] (qtp78811769`

**Comment by rhtyd** [comment]
Ping @fmaximus can have a look at the exception in NuageVspElement::verifyServicesCombination ^^?

**Comment by rhtyd** [comment]
Ping @krissterckx ^^ can you comment? Thanks.

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack/pull/2889  is merged so I'll close this issue. Please reopen @borisstoyanov if you're able to reproduce a valid bug.

**Comment by borisstoyanov** [comment]
Thanks @rhtyd!
