### ISSUE TITLE
VMware hosted VM with ISO attached live migration failure

### ISSUE THREAD

**Issue by DagSonsteboSB** [apache/cloudstack#3027]
##### ISSUE TYPE
 * Bug Report (minor)

##### COMPONENT NAME
* CloudStack management

##### CLOUDSTACK VERSION
* 4.11.1
* 4.11.2-RC5 (hence possibly 4.11.2)

##### CONFIGURATION
* Advanced zone
* VMware vSphere 5.5u3
* CloudStack management versions as above
* VM with ISO attached

##### OS / ENVIRONMENT
* N/A

##### SUMMARY
* Migration of VM with ISO attached fails ungracefully.
* Not clear if this is a limitation of VMware 

##### STEPS TO REPRODUCE
* Create VM, attach ISO
* Attempt to migrate VM from one ESXi host to another.
* Observe GUI error:
`
MigrationCommand failed due to Exception: java.lang.RuntimeException Message: Currently connected device 'CD/DVD drive 1' uses backing '[] /usr/lib/vmware/isoimages/linux.iso', which is not accessible.
`

* Log error:
` 2018-11-14 13:54:37,747 WARN  [c.c.h.v.r.VmwareResource] (DirectAgent-69:ctx-ddc4714b 10.2.3.180, job-33/job-34, cmd: MigrateCommand) (logid:96e22c89) MigrationCommand failed due to Exception: java.lang.RuntimeException
Message: Currently connected device 'CD/DVD drive 1' uses backing '[] /usr/lib/vmware/isoimages/linux.iso', which is not accessible.`

`java.lang.RuntimeException: Currently connected device 'CD/DVD drive 1' uses backing '[] /usr/lib/vmware/isoimages/linux.iso', which is not accessible.
        at com.cloud.hypervisor.vmware.util.VmwareClient.waitForTask(VmwareClient.java:358)
        at com.cloud.hypervisor.vmware.mo.VirtualMachineMO.migrate(VirtualMachineMO.java:415)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:3814)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:444)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-11-14 13:54:37,748 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-69:ctx-ddc4714b) (logid:96e22c89) Seq 2-6622824727025025088: Response Received:
`

* VC error:

`
Currently connected device 'CD/DVD drive 1' uses backing '[] /usr/lib/vmware/isoimages/linux.iso', which is not accessible.
`

##### EXPECTED RESULTS
* Graceful error or successful migration.

##### ACTUAL RESULTS
* Errors as above.

**Comment by DagSonsteboSB** [comment]
Test applied was incorrect - the VMware tools ISO can not be used for this test since it is contained on the local ESXi file system.

When attaching an uploaded ISO the migration works OK, hence closing this ticket.
