### ISSUE TITLE
NPE observed in smoketests logs 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3060]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
DB 
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

NPE was noticed when observing the marvin smoketests

##### STEPS TO REPRODUCE

~~~
Not clear
~~~

```
{"alerts":["2018-10-02 13:51:06,441 [INFO] [The process haproxy is not running trying recover ] haproxy","2018-10-02 13:51:06,543 [INFO] [haproxy] The process haproxy is recovered successfully"],"timeStamp":"2018-10-02 13:51:06","result":true,"wait":0}}] }
2018-10-02 13:50:42,045 DEBUG [c.c.a.t.Request] (RouterStatusMonitor-1:ctx-509b28aa) (logid:559ed002) Seq 1-5704653352994867346: Received:  { Ans: , MgmtId: 7170582185804, via: 1(pr2749-t3052-xenserver-71-xs1), Ver: v1, Flags: 10, { GetRouterAlertsAnswer } }
2018-10-02 13:50:42,045 WARN  [c.c.n.r.VirtualNetworkApplianceManagerImpl] (RouterStatusMonitor-1:ctx-509b28aa) (logid:559ed002) Invalid last alert timestamp received while collecting alerts from router: r-189-VM
2018-10-02 13:50:42,646 WARN  [o.a.c.e.o.NetworkOrchestrator] (Network-Scavenger-1:ctx-81ce92af) (logid:6e69de77) Caught exception while running network gc: 
com.cloud.utils.exception.CloudRuntimeException: Caught: com.mysql.jdbc.JDBC4PreparedStatement@2551f54e: SELECT networks.id FROM networks  INNER JOIN network_offerings ON networks.network_offering_id=network_offerings.id  INNER JOIN op_networks ON networks.id=op_networks.id WHERE networks.removed IS NULL  AND  (op_networks.nics_count = ** NOT SPECIFIED **  AND op_networks.gc = ** NOT SPECIFIED **  AND op_networks.check_for_gc = ** NOT SPECIFIED ** )
	at com.cloud.utils.db.GenericDaoBase.customSearchIncludingRemoved(GenericDaoBase.java:507)
	at com.cloud.utils.db.GenericDaoBase.customSearch(GenericDaoBase.java:518)
	at com.cloud.network.dao.NetworkDaoImpl.findNetworksToGarbageCollect(NetworkDaoImpl.java:461)
	at sun.reflect.GeneratedMethodAccessor175.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy64.findNetworksToGarbageCollect(Unknown Source)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$NetworkGarbageCollector.reallyRun(NetworkOrchestrator.java:2761)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$NetworkGarbageCollector.runInContext(NetworkOrchestrator.java:2745)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
2018-10-02 13:50:42,667 DEBUG [c.c.a.r.v.VirtualRoutingResource] (DirectAgent-305:ctx-0f38cb9a) (logid:3cb81b5f) Processing ScriptConfigItem, executing update_config.py firewall_rules.json.d8cf9f0b-207c-46f1-a0ce-fb105edd630c took 1417ms
2018-10-02 13:50:42,667 WARN  [c.c.a.r.v.VirtualRoutingResource] (DirectAgent-305:ctx-0f38cb9a) (logid:3cb81b5f) Expected 1 answers while executing SetFirewallRulesCommand but received 2
2018-10-02 13:50:42,667 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-305:ctx-0f38cb9a) (logid:3cb81b5f) Seq 1-5704653352994867344: Response Received: 
```

**Comment by rhtyd** [comment]
@borisstoyanov any specific test?

**Comment by borisstoyanov** [comment]
no particular test/scenario, this seems like a recurring exception in the logs.

**Comment by rhtyd** [comment]
I've reported similar issue for master/4.12 here https://github.com/apache/cloudstack/issues/2935 already

**Comment by rhtyd** [comment]
Fixed by https://github.com/apache/cloudstack/pull/3115
