### ISSUE TITLE
CloudStack Simulator 4.12 - SQL exception

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#3064]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management server
~~~

##### CLOUDSTACK VERSION

~~~
4.12
~~~

##### CONFIGURATION

Simulator

##### SUMMARY

Exception in logs

```
WARN  [o.a.c.e.o.NetworkOrchestrator] (Network-Scavenger-1:ctx-d0e40172) (logid:9fcdf236) Caught exception while running network gc: 
com.cloud.utils.exception.CloudRuntimeException: Caught: com.mysql.jdbc.JDBC4PreparedStatement@55ac543: SELECT networks.id FROM networks  INNER JOIN network_offerings ON networks.network_offering_id=network_offerings.id  INNER JOIN op_networks ON networks.id=op_networks.id WHERE networks.removed IS NULL  AND  (op_networks.nics_count = ** NOT SPECIFIED **  AND op_networks.gc = ** NOT SPECIFIED **  AND op_networks.check_for_gc = ** NOT SPECIFIED ** )
	at com.cloud.utils.db.GenericDaoBase.customSearchIncludingRemoved(GenericDaoBase.java:507)
	at com.cloud.utils.db.GenericDaoBase.customSearch(GenericDaoBase.java:518)
	at com.cloud.network.dao.NetworkDaoImpl.findNetworksToGarbageCollect(NetworkDaoImpl.java:461)
	at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy100.findNetworksToGarbageCollect(Unknown Source)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$NetworkGarbageCollector.reallyRun(NetworkOrchestrator.java:2758)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$NetworkGarbageCollector.runInContext(NetworkOrchestrator.java:2742)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
```

##### STEPS TO REPRODUCE

Run simulator for 4.12 and monitor logs.

**Comment by wido** [comment]
Seeing the same issue on master. Not sure yet what this is.

**Comment by borisstoyanov** [comment]
I guess duplicated as #3060 ?
