### ISSUE TITLE
Multiple resource limits related exceptions during management server boot

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#3094]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
4.11.2
~~~

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

When Management server boots it produces plenty of exceptions like following:
```
com.cloud.exception.ResourceAllocationException: Maximum amount of resources of Type = 'secondary_storage' for Account Name = bitworks12625 in Domain Id = 11 is exceeded: Account Resource Limit = 11811160064, Current Account Resource Amount = 10737418240, Requested Resource Amount = 10737418240.
        at com.cloud.resourcelimit.ResourceLimitManagerImpl.checkAccountResourceLimit(ResourceLimitManagerImpl.java:465)
        at com.cloud.resourcelimit.ResourceLimitManagerImpl.access$100(ResourceLimitManagerImpl.java:107)
        at com.cloud.resourcelimit.ResourceLimitManagerImpl$1.doInTransactionWithoutResult(ResourceLimitManagerImpl.java:518)
        at com.cloud.utils.db.TransactionCallbackWithExceptionNoReturn.doInTransaction(TransactionCallbackWithExceptionNoReturn.java:25)
        at com.cloud.utils.db.TransactionCallbackWithExceptionNoReturn.doInTransaction(TransactionCallbackWithExceptionNoReturn.java:21)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:40)
        at com.cloud.resourcelimit.ResourceLimitManagerImpl.checkResourceLimit(ResourceLimitManagerImpl.java:512)
        at org.apache.cloudstack.storage.image.TemplateServiceImpl.handleTemplateSync(TemplateServiceImpl.java:424)
        at com.cloud.storage.download.DownloadListener.processConnect(DownloadListener.java:303)
        at com.cloud.agent.manager.AgentManagerImpl.notifyMonitorsOfConnection(AgentManagerImpl.java:570)
        at com.cloud.agent.manager.AgentManagerImpl.handleConnectedAgent(AgentManagerImpl.java:1111)
        at com.cloud.agent.manager.AgentManagerImpl.access$000(AgentManagerImpl.java:126)
        at com.cloud.agent.manager.AgentManagerImpl$HandleAgentConnectTask.runInContext(AgentManagerImpl.java:1195)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

They are related to snapshots amount and secondary storage.

##### STEPS TO REPRODUCE

~~~
1. Create account
2. Set account SS limit
3. Set account Snapshots limit
4. Create a snapshot within the limit
5. Reboot management server
~~~

##### EXPECTED RESULTS

~~~
No exceptions when resources are within limits.
~~~

##### ACTUAL RESULTS

~~~
Exceptions upon MS boot.
~~~

**Comment by rhtyd** [comment]
cc @shwstppr

**Comment by shwstppr** [comment]
Problem is probably not related to snapshots and resource limits, rather with templates. While registering templates with URL, the secondary storage size limit for the user is not checked. Since the actual size of the template is not known at the start while registering, after download and install secondary storage limit can be exceeded and this would cause resource limit exceptions when handleTemplateSync is called.

**Comment by rhtyd** [comment]
This is a corner case and by design, the download/registration of templates/isos on secondary storage may be kicked after management server restarts (or whenever the ssvm agent reconnects). The only reconciliation approach is to throw an exception after such an event happens to get it noticed where the user may contact admin for resolution.
