### ISSUE TITLE
CPVM sometimes does not work

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3142]
In an env with long running VMs and CPVM, when the management server is restarted at some point the CPVM stops working with following error seen in logs: /cc @glennwagner @PaulAngus 

```
2019-01-22 19:46:57,975 ERROR [cloud.consoleproxy.ConsoleProxyHttpHandlerHelper] (Thread-14722:null) decode token. host info is not found!
2019-01-22 19:46:57,980 WARN  [cloud.consoleproxy.ConsoleProxyAjaxHandler] (Thread-14722:null) Exception, 
java.lang.IllegalArgumentException
	at com.cloud.consoleproxy.ConsoleProxyAjaxHandler.doHandle(ConsoleProxyAjaxHandler.java:98)
	at com.cloud.consoleproxy.ConsoleProxyAjaxHandler.handle(ConsoleProxyAjaxHandler.java:51)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.lang.Thread.run(Thread.java:748)

```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
CPVM
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2.0
~~~

**Comment by rhtyd** [comment]
@glennwagner on debugging I found that the error came because one of the KVM host's agent was down/disconnected so console could not work. Please check in your env if vcenter/esxi hosts were Up when you found/reproduced that issue. This may happen when you restart management server(s) and they will try to reconnect to vcenters. 
Closing as it's not a bug, but host/agent state/connection issue.

**Comment by glennwagner** [comment]
@rhtyd Yesterday I only had one management server running, all the SVM's and hosts were in the Right UP state stll got the access denied

**Comment by rhtyd** [comment]
@Glenn can you share the cpvm logs when it happens the next time.
