### ISSUE TITLE
NPE when descriptor has VMware compatibility level 9

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack#3230]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

VMware ESXi 5.5

##### SUMMARY

In CloudStack 4.11.2, it's impossible to start a VM that has an existing VMware descriptor with a compatibility level below 10.

The bug manifests with a NullPointerException in com.cloud.hypervisor.vmware.mo.VirtualMachineMO.isMemoryHotAddSupported(VirtualMachineMO.java:3284 .

##### STEPS TO REPRODUCE

1. Have an existing CloudStack VM that was created under VMware ESX 5.1 or older
2. Upgrade VMware to at least 5.5
3. Stop the VM
4. Start the VM

##### EXPECTED RESULTS

The VM starts.

##### ACTUAL RESULTS

CloudStack fails to launch the VM, instead throwing the following stack trace.

~~~
 [ignored]failed toi get message for exception: null
Message: null

java.lang.NullPointerException
        at com.cloud.hypervisor.vmware.mo.VirtualMachineMO.isMemoryHotAddSupported(VirtualMachineMO.java:3284)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:1875)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:496)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
~~~

**Comment by onitake** [comment]
There is more to this issue: Since CloudStack never upgrades the VM descriptors to the current compatibility level, this exception will happen to all older VMs eventually, unless they are manually upgraded from within ESX.

**Comment by rhtyd** [comment]
Merged in https://github.com/apache/cloudstack/pull/3362
