### ISSUE TITLE
Unknown column 'mshost.uuid' in 'field list

### ISSUE THREAD

**Issue by elpoche** [apache/cloudstack#3514]
I have this problem when I upgrade version from 4.11.3 to 4.12

### ISSUE TYPE
 * Other

##### COMPONENT NAME

Problem on starting cloudstack-management

##### CLOUDSTACK VERSION
~~~
before upgrade: 4.11.3
after upgrade: 4.12
~~~

##### OS / ENVIRONMENT

Centos 6

##### SUMMARY

2019-04-22 22:47:51,230 WARN  [o.a.c.s.m.c.ResourceApplicationContext] (main:null) (logid:) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'cloudStackLifeCycle'; nested exception is com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.jdbc.JDBC4PreparedStatement@51b41740: **SELECT mshost.id, mshost.uuid, mshost.msid, mshost.runid, mshost.name, mshost.state, mshost.version, mshost.service_ip, mshost.service_port, mshost.last_update, mshost.removed, mshost.alert_count FROM mshost WHERE mshost**.last_update > '2019-04-23 01:45:21'  AND mshost.removed IS NULL 
2019-04-22 22:47:51,238 WARN  [o.e.j.w.WebAppContext] (main:null) (logid:) Failed startup of context o.e.j.w.WebAppContext@69b794e2{/client,file:///usr/share/cloudstack-management/webapp/,UNAVAILABLE}{/usr/share/cloudstack-management/webapp}
org.springframework.context.ApplicationContextException: Failed to start bean 'cloudStackLifeCycle'; nested exception is com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.jdbc.JDBC4PreparedStatement@51b41740: SELECT mshost.id, mshost.uuid, mshost.msid, mshost.runid, mshost.name, mshost.state, mshost.version, mshost.service_ip, mshost.service_port, mshost.last_update, mshost.removed, mshost.alert_count FROM mshost WHERE mshost.last_update > '2019-04-23 01:45:21'  AND mshost.removed IS NULL 
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:186)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:358)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:159)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:884)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:145)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:122)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:245)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:233)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:117)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:79)
	at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:71)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:58)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:62)
	at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:52)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:273)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.apache.cloudstack.ServerDaemon.start(ServerDaemon.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:241)
Caused by: com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.jdbc.JDBC4PreparedStatement@51b41740: SELECT mshost.id, mshost.uuid, mshost.msid, mshost.runid, mshost.name, mshost.state, mshost.version, mshost.service_ip, mshost.service_port, mshost.last_update, mshost.removed, mshost.alert_count FROM mshost WHERE mshost.last_update > '2019-04-23 01:45:21'  AND mshost.removed IS NULL 
	at com.cloud.utils.db.GenericDaoBase.searchIncludingRemoved(GenericDaoBase.java:428)
	at com.cloud.utils.db.GenericDaoBase.searchIncludingRemoved(GenericDaoBase.java:364)
	at com.cloud.utils.db.GenericDaoBase.listIncludingRemovedBy(GenericDaoBase.java:934)
	... 72 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: **Unknown column 'mshost.uuid' in 'field list'**
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	... 88 more
2019-04-22 22:47:51,248 INFO  [o.e.j.s.h.ContextHandler] (main:null) (logid:) Started o.e.j.s.h.MovedContextHandler@32a068d1{/,null,AVAILABLE}
2019-04-22 22:47:51,287 INFO  [o.e.j.s.AbstractConnector] (main:null) (logid:) Started ServerConnector@687080dc{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-04-22 22:47:51,287 INFO  [o.e.j.s.Server] (main:null) (logid:) Started @83725ms

Database details:
mysql> select * from mshost;
+----+-------------+---------------+---------------------+-------+----------+---------------+--------------+---------------------+---------+-------------+
| id | msid        | runid         | name                | state | version  | service_ip    | service_port | last_update         | removed | alert_count |
+----+-------------+---------------+---------------------+-------+----------+---------------+--------------+---------------------+---------+-------------+
|  1 | 52239792719 | 1555980491306 | mgmt01.cloudlab | Down  | 4.11.3.0 | 192.168.70.41 |         9090 | 2019-04-23 01:10:27 | NULL    |           0 |
+----+-------------+---------------+---------------------+-------+----------+---------------+--------------+---------------------+---------+-------------+
1 row in set (0.00 sec)

##### STEPS TO REPRODUCE
following the official upgrade 

##### EXPECTED RESULTS

update the database maybe fields

##### ACTUAL RESULTS

maybe this field is wrong

**Comment by rhtyd** [comment]
Upgrade path from 4.11.3.0 to 4.12.0.0 does not exist this is because 4.11.3.0 was released after 4.12.0.0. One way to fix your upgrade would be to manually run the path: engine/schema/src/main/resources/META-INF/db/schema-41120to41200.sql

**Comment by rhtyd** [comment]
Perhaps the upgrade docs could explicitly state which specific source/from versions are supported while upgrading to a CloudStack release. We'll try to address this in 4.13 and above.

**Comment by elpoche** [comment]
Ok, thanks for your answer!
