### ISSUE TITLE
Regression bug in 4.13.0.0-SNAPSHOT that affects KVM local storage migration

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#3521]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM, local storage, volume migration.
~~~

##### CLOUDSTACK VERSION

~~~
master (4.13.0.0-SNAPSHOT)
~~~

##### CONFIGURATION

KVM hosts, zone configured allowing to use local storage for user and system VMs.

##### SUMMARY

Tested with the current CloudStack master branch (4.13.0.0-SNAPSHOT) and it failed to migrate a VM with ROOT volume on local storage.

```
2019-06-14 05:52:57,051 WARN  [c.c.a.m.AgentManagerImpl] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Unsupported Command: Unsupported command issued: com.cloud.agent.api.BadCommand.  Are you sure you got the right type of server?
2019-06-14 05:52:57,070 WARN  [o.a.c.s.d.ObjectInDataStoreManagerImpl] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Unsupported data object (VOLUME, org.apache.cloudstack.storage.datastore.PrimaryDataStoreImpl@2e2f2a28), no need to delete from object in store ref table
2019-06-14 05:52:57,070 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Failed to copy volume
com.cloud.utils.exception.CloudRuntimeException: Copy operation failed in 'StorageSystemDataMotionStrategy.copyAsync': Storage verification failed on host 484a1f93-0b23-45bc-9156-1fcf21ef6778: Unsupported command issued: com.cloud.agent.api.BadCommand.  Are you sure you got the right type of server?
        at org.apache.cloudstack.storage.motion.StorageSystemDataMotionStrategy.copyAsync(StorageSystemDataMotionStrategy.java:1895)
        at org.apache.cloudstack.storage.motion.DataMotionServiceImpl.copyAsync(DataMotionServiceImpl.java:120)
        at org.apache.cloudstack.storage.volume.VolumeServiceImpl.migrateVolumes(VolumeServiceImpl.java:1621)
        at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.migrateVolumes(VolumeOrchestrator.java:1050)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:2778)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:5168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5271)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:583)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:531)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-14 05:52:57,071 DEBUG [o.a.c.e.o.VolumeOrchestrator] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Failed to migrated vm VM[User|i-2-2394-VM] along with its volumes. com.cloud.utils.exception.CloudRuntimeException: Copy operation failed in 'StorageSystemDataMotionStrategy.copyAsync': Storage verification failed on host 484a1f93-0b23-45bc-9156-1fcf21ef6778: Unsupported command issued: com.cloud.agent.api.BadCommand.  Are you sure you got the right type of server?
```

##### STEPS TO REPRODUCE

1. Start a VM on a KVM host with local storage;
2. Migrate the VM to another KVM host that has local storage

##### EXPECTED RESULTS

~~~
Success
~~~

##### ACTUAL RESULTS

~~~
Exception
~~~

**Comment by rhtyd** [comment]
Are you going to send a PR @GabrielBrascher?

**Comment by GabrielBrascher** [comment]
@rhtyd so far I am on debugging process but if I have a patch to submit I will update here.

**Comment by rhtyd** [comment]
Ping any update @GabrielBrascher ? cc @wido

**Comment by GabrielBrascher** [comment]
@rhtyd I have been able to reproduce the issue and fixed it with a "hotfix" patch. I will be soon opening a PR (probably today, 30 july).

**Comment by rhtyd** [comment]
Thanks @GabrielBrascher looking forward to it. I'm hoping to cut RC1 next week. It will help if all blockers get addressed by then.
