### ISSUE TITLE
Cloudstack management v4.12 does not start after trying to upgrade v4.13 

### ISSUE THREAD

**Issue by tarmof** [apache/cloudstack#3628]
I cannot start version 4.12 cloudstack-management any more.
It gives error;

2019-10-08 01:00:15,775 DEBUG [o.a.c.f.c.i.ConfigDepotImpl] (main:null) (logid:) Retrieving keys from RootCAProvider
2019-10-08 01:00:15,803 DEBUG [o.a.c.s.l.r.ExtensionRegistry] (main:null) (logid:) Registering extension [RootCAProvider] in [Ca Providers Registry]
2019-10-08 01:00:15,803 DEBUG [o.a.c.s.l.r.RegistryLifecycle] (main:null) (logid:) Registered org.apache.cloudstack.ca.provider.RootCAProvider@20e4e27f
2019-10-08 01:00:15,803 INFO [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Configuring CloudStack Components
2019-10-08 01:00:15,828 WARN [o.a.c.s.m.c.ResourceApplicationContext] (main:null) (logid:) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean '
cloudStackLifeCycle'; nested exception is java.lang.NullPointerException
2019-10-08 01:00:15,829 WARN [o.e.j.w.WebAppContext] (main:null) (logid:) Failed startup of context o.e.j.w.WebAppContext@58fdd99{/client,file:///usr/share/cloudstack-management/webapp/,UNAVAILABLE}{/usr/share/cloudstack-management/webapp}
org.springframework.context.ApplicationContextException: Failed to start bean 'cloudStackLifeCycle'; nested exception is java.lang.NullPointerException
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:186)
at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52)
at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:358)
at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:159)
at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:884)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:145)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:122)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:245)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:233)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:117)
at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:79)
at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37)
at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:71)
at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.(CloudStackSpringContext.java:58)
at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.(CloudStackSpringContext.java:62)
at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:52)
at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:273)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
at org.eclipse.jetty.server.Server.start(Server.java:418)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
at org.eclipse.jetty.server.Server.doStart(Server.java:385)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.apache.cloudstack.ServerDaemon.start(ServerDaemon.java:186)
at org.apache.cloudstack.ServerDaemon.main(ServerDaemon.java:103)
Caused by: java.lang.NullPointerException
at org.apache.cloudstack.utils.security.CertUtils.pemToPublicKey(CertUtils.java:145)
at org.apache.cloudstack.ca.provider.RootCAProvider.loadRootCAKeyPair(RootCAProvider.java:335)
at org.apache.cloudstack.ca.provider.RootCAProvider.setupCA(RootCAProvider.java:381)
... 55 more
2019-10-08 01:00:15,831 INFO [o.e.j.s.h.ContextHandler] (main:null) (logid:) Started o.e.j.s.h.MovedContextHandler@679b62af{/,null,AVAILABLE}
2019-10-08 01:00:15,850 INFO [o.e.j.s.AbstractConnector] (main:null) (logid:) Started ServerConnector@1a1d6a08{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-10-08 01:00:15,850 INFO [o.e.j.s.Server] (main:null) (logid:) Started @22604ms

**Comment by gngusen** [comment]
Please consult @rhtyd he will surely help
Sorry if this disrupts your question but I really need assistance. I am unable to add the host to the management server through the UI. They are separate machines in the same network. Please help

**Comment by andrijapanicsb** [comment]
did you restore to the DB backup from 4.12 (that you took before trying to upgrade to 4.13) ?
If so, stop mgmt, restore DB, and start 4.12 mgmt - easy as that.

What/why did upgrade fail to 4.13 - did you
1) have new records added in the guest_os  and/or guest_os_hypervisor tables?
2) did you register 4.11.3 systemVM template while on 4.12, before trying to upgrade to 4.13?

**Comment by tarmof** [comment]
Hello,

yes I restored DB from 4,12 backup,
but 4.12 mgmt does not start any more, giving error I post

So I also cannot register 4.11.3 systemVM template

BR,
Tarmo

**Comment by DaanHoogland** [comment]
@tarmof not sure what exactly is your problem but it has to do with certificate initialisation:
java.lang.NullPointerException
at org.apache.cloudstack.utils.security.CertUtils.pemToPublicKey(CertUtils.java:145)
at org.apache.cloudstack.ca.provider.RootCAProvider.loadRootCAKeyPair(RootCAProvider.java:335)
at org.apache.cloudstack.ca.provider.RootCAProvider.setupCA(RootCAProvider.java:381)

**Comment by rhtyd** [comment]
There seems to be an issue with the root ca pub/priv key in the db (not being able to convert the value in the db by the mangement server as a PublicKey instance).

**Comment by andrijapanicsb** [comment]
I've seen people just restore the old DB (mysql import) withOUT deleting the "upgraded" DB - so please make sure to:
-delete cloud* DBs
- create emtpy cloud and cloud_usage DBs
- import a proper mysql backup for both DBs
- make sure to start 4.12 binaries

Proper rollback should be possible always.

**Comment by andrijapanicsb** [comment]
@tarmof any update on this one, still an issue or should we close it?

**Comment by tarmof** [comment]
I do not have solution, I will try in January

Happy New Year!
BR
Tarmo

**Comment by rhtyd** [comment]
@tarmof can you re-open if this is still applicable, 4.12 is now a very old release; pl try upgrading to 4.14. Thanks.
