### ISSUE TITLE
Create volume or template from snapshot is broken

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#3783]
Hi,

I'm on 4.13 KVM + local storage, trying to create a volume or a template from a snapshot.
Cloudmonkey says:
```
(localcloud)  > create volume snapshotid=985f20b1-b57e-458e-983d-ce69848fe06c
 Error: (HTTP 530, error code 9999) <nil>
```

management-server.log says:

```
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpChannel] (qtp504527234-813:null) (logid:) HttpChannelOverHttp@5d83425d{r=1,c=false,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh4
35Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D} onContentComplete
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpChannel] (qtp504527234-813:null) (logid:) HttpChannelOverHttp@5d83425d{r=1,c=false,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh4
35Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D} onRequestComplete
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpInput] (qtp504527234-813:null) (logid:) HttpInputOverHTTP@23b3db24[c=0,q=0,[0]=null,s=STREAM] addContent EOF
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpConnection] (qtp504527234-813:null) (logid:) HttpConnection@12ce2981[p=HttpParser{s=END,0 of -1},g=HttpGenerator@5598102f{s=START}]=>HttpChannelOverHttp@5d83425d{r=1,c=false,a=IDLE,uri=//109-70-
140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0M
Lg2y2%2FJC30D8ThDc8%3D}<-DecryptedEndPoint@16f82720{/192.168.140.220:35676<->/192.168.140.220:8443,OPEN,fill=-,flush=-,to=3/30000}->HttpConnection@12ce2981[p=HttpParser{s=END,0 of -1},g=HttpGenerator@5598102f{s=START}]=>HttpChannelOverHttp
@5d83425d{r=1,c=false,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-4
3aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}->SocketChannelEndPoint@643edcc0{/192.168.140.220:35676<->/192.168.140.220:8443,OPEN,fill=-,flush=-,to=1/30000}{io=1/0,kio=1,kro=1}->SslConnection@28eec9b{NOT_HANDSHAKING,eio
=-1/-1,di=-1}=>HttpConnection@12ce2981[p=HttpParser{s=END,0 of -1},g=HttpGenerator@5598102f{s=START}]=>HttpChannelOverHttp@5d83425d{r=1,c=false,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoT
ueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D} parsed true HttpParser{s=END,0 of -1}
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpConnection] (qtp504527234-813:null) (logid:) releaseRequestBuffer HttpConnection@12ce2981[p=HttpParser{s=END,0 of -1},g=HttpGenerator@5598102f{s=START}]=>HttpChannelOverHttp@5d83425d{r=1,c=false
,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3
&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}<-DecryptedEndPoint@16f82720{/192.168.140.220:35676<->/192.168.140.220:8443,OPEN,fill=-,flush=-,to=3/30000}->HttpConnection@12ce2981[p=HttpParser{s=END,0 of -1},g=HttpGenerator@5598102f{s=START}]
=>HttpChannelOverHttp@5d83425d{r=1,c=false,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snaps
hotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}->SocketChannelEndPoint@643edcc0{/192.168.140.220:35676<->/192.168.140.220:8443,OPEN,fill=-,flush=-,to=1/30000}{io=1/0,kio=1,kro=1}->SslConnection@28eec9
b{NOT_HANDSHAKING,eio=-1/-1,di=-1}=>HttpConnection@12ce2981[p=HttpParser{s=END,0 of -1},g=HttpGenerator@5598102f{s=START}]=>HttpChannelOverHttp@5d83425d{r=1,c=false,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt23
3Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpChannel] (qtp504527234-813:null) (logid:) HttpChannelOverHttp@5d83425d{r=1,c=false,a=IDLE,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh4
35Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D} handle //192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt2
33Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpChannelState] (qtp504527234-813:null) (logid:) handling HttpChannelState@4b221e3{s=IDLE a=NOT_ASYNC i=true r=IDLE w=false}
2019-12-20 16:17:58,558 DEBUG [o.e.j.s.HttpChannel] (qtp504527234-813:null) (logid:) HttpChannelOverHttp@5d83425d{r=1,c=false,a=DISPATCHED,uri=//192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56
YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D} action DISPATCH
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.SecureRequestCustomizer] (qtp504527234-813:null) (logid:) Host 192-168-140-220.cloud.tld matched SNI X509@70dd183b(1,h=[cloud.tld],w=[cloud.tld])
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.Server] (qtp504527234-813:null) (logid:) REQUEST GET /client/api on HttpChannelOverHttp@5d83425d{r=1,c=false,a=DISPATCHED,uri=https://192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8h
ogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.h.g.GzipHandler] (qtp504527234-813:null) (logid:) org.eclipse.jetty.server.handler.gzip.GzipHandler@71d15f18 handle Request(GET https://192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc
8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D)@7b27ca9d in null
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.h.ContextHandler] (qtp504527234-813:null) (logid:) scope null||/client/api @ o.e.j.w.WebAppContext@64485a47{/client,file:///usr/share/cloudstack-management/webapp/,AVAILABLE}{/usr/share/cloudstack-management/webapp}
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.h.ContextHandler] (qtp504527234-813:null) (logid:) context=/client||/api @ o.e.j.w.WebAppContext@64485a47{/client,file:///usr/share/cloudstack-management/webapp/,AVAILABLE}{/usr/share/cloudstack-management/webapp}
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.session] (qtp504527234-813:null) (logid:) sessionHandler=org.eclipse.jetty.server.session.SessionHandler633075331==dftMaxIdleSec=1800
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.session] (qtp504527234-813:null) (logid:) session=null
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.ServletHandler] (qtp504527234-813:null) (logid:) servlet /client|/api|null -> apiServlet@e29c3ecb==com.cloud.api.ApiServlet,jsp=null,order=5,inst=true
2019-12-20 16:17:58,559 DEBUG [o.e.j.s.ServletHandler] (qtp504527234-813:null) (logid:) chain=null
2019-12-20 16:17:58,560 DEBUG [c.c.a.ApiServlet] (qtp504527234-813:ctx-664a7409) (logid:c215ab59) ===START===  192.168.140.220 -- GET  apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D
2019-12-20 16:17:58,563 DEBUG [c.c.a.ApiServer] (qtp504527234-813:ctx-664a7409 ctx-8094fb24) (logid:c215ab59) CIDRs from which account 'Acct[5b847740-6768-11e9-9a90-00163ea182ae-admin]' is allowed to perform API calls: 0.0.0.0/0,::/0
2019-12-20 16:17:58,568 DEBUG [o.e.j.u.t.ReservedThreadExecutor] (qtp504527234-798:null) (logid:) ReservedThreadExecutor@4e1ec5a2{s=1/2,p=0}@SelectorManager@ServerConnector@453da22c{SSL,[ssl, http/1.1]}{0.0.0.0:8443}@c7748c5 task=EatWhatYouKill@3ffc2173/SelectorProducer@53d0500d/IDLE/ReservedThreadExecutor@4e1ec5a2{s=1/2,p=0}@SelectorManager@ServerConnector@453da22c{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2019-12-20 16:17:58,568 DEBUG [o.e.j.u.t.s.EatWhatYouKill] (qtp504527234-798:null) (logid:) EatWhatYouKill@3ffc2173/SelectorProducer@53d0500d/IDLE/ReservedThreadExecutor@4e1ec5a2{s=1/2,p=0}@SelectorManager@ServerConnector@453da22c{SSL,[ssl, http/1.1]}{0.0.0.0:8443} run
2019-12-20 16:17:58,568 DEBUG [o.e.j.u.t.s.EatWhatYouKill] (qtp504527234-798:null) (logid:) EatWhatYouKill@3ffc2173/SelectorProducer@53d0500d/IDLE/ReservedThreadExecutor@4e1ec5a2{s=1/2,p=0}@SelectorManager@ServerConnector@453da22c{SSL,[ssl, http/1.1]}{0.0.0.0:8443} produce
2019-12-20 16:17:58,568 DEBUG [o.e.j.i.ManagedSelector] (qtp504527234-798:null) (logid:) action=null wakeup=false
2019-12-20 16:17:58,568 DEBUG [o.e.j.i.ChannelEndPoint] (qtp504527234-798:null) (logid:) Key interests updated 1 -> 0 on SocketChannelEndPoint@643edcc0{/192.168.140.220:35676<->/192.168.140.220:8443,OPEN,fill=-,flush=-,to=11/30000}{io=0/0,kio=0,kro=1}->SslConnection@28eec9b{NOT_HANDSHAKING,eio=-1/-1,di=-1}=>HttpConnection@12ce2981[p=HttpParser{s=END,0 of -1},g=HttpGenerator@5598102f{s=START}]=>HttpChannelOverHttp@5d83425d{r=1,c=false,a=DISPATCHED,uri=https://192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}
2019-12-20 16:17:58,568 DEBUG [o.e.j.i.ManagedSelector] (qtp504527234-798:null) (logid:) Selector sun.nio.ch.EPollSelectorImpl@7862a370 waiting on select
2019-12-20 16:17:58,589 ERROR [c.c.a.ApiServer] (qtp504527234-813:ctx-664a7409 ctx-8094fb24 ctx-a6c49977) (logid:c215ab59) unhandled exception executing api command: [Ljava.lang.String;@29d82096
java.lang.NullPointerException
        at com.cloud.configuration.ConfigurationManagerImpl.checkDiskOfferingAccess(ConfigurationManagerImpl.java:4520)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy126.checkDiskOfferingAccess(Unknown Source)
        at com.cloud.storage.VolumeApiServiceImpl.allocVolume(VolumeApiServiceImpl.java:676)
        at com.cloud.storage.VolumeApiServiceImpl.allocVolume(VolumeApiServiceImpl.java:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy199.allocVolume(Unknown Source)
        at org.apache.cloudstack.api.command.user.volume.CreateVolumeCmd.create(CreateVolumeCmd.java:212)
        at com.cloud.api.dispatch.CommandCreationWorker.handle(CommandCreationWorker.java:47)
        at com.cloud.api.dispatch.DispatchChain.dispatch(DispatchChain.java:37)
        at com.cloud.api.ApiDispatcher.dispatchCreateCmd(ApiDispatcher.java:88)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:682)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:582)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:310)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:130)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:127)
        at com.cloud.api.ApiServlet.doGet(ApiServlet.java:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)
2019-12-20 16:17:58,592 DEBUG [c.c.a.ApiServlet] (qtp504527234-813:ctx-664a7409 ctx-8094fb24 ctx-a6c49977) (logid:c215ab59) ===END===  192.168.140.220 -- GET  apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D
2019-12-20 16:17:58,592 DEBUG [o.e.j.s.session] (qtp504527234-813:null) (logid:) FinalSession=null old_session_manager=null this=org.eclipse.jetty.server.session.SessionHandler633075331==dftMaxIdleSec=1800
2019-12-20 16:17:58,592 DEBUG [o.e.j.s.h.ContextHandler] (qtp504527234-813:null) (logid:) scope null||/client/api @ o.e.j.s.h.MovedContextHandler@32cf48b7{/,null,AVAILABLE}
2019-12-20 16:17:58,592 DEBUG [o.e.j.s.Server] (qtp504527234-813:null) (logid:) handled=true async=false committed=false on HttpChannelOverHttp@5d83425d{r=1,c=false,a=DISPATCHED,uri=https://192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}
2019-12-20 16:17:58,592 DEBUG [o.e.j.s.HttpChannelState] (qtp504527234-813:null) (logid:) unhandle HttpChannelState@4b221e3{s=DISPATCHED a=NOT_ASYNC i=true r=IDLE w=false}
2019-12-20 16:17:58,592 DEBUG [o.e.j.s.HttpChannel] (qtp504527234-813:null) (logid:) HttpChannelOverHttp@5d83425d{r=1,c=false,a=COMPLETING,uri=https://192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D} action COMPLETE
2019-12-20 16:17:58,592 DEBUG [o.e.j.s.h.g.GzipHttpOutputInterceptor] (qtp504527234-813:null) (logid:) org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor@54de5078 exclude by status 530
2019-12-20 16:17:58,592 DEBUG [o.e.j.s.HttpChannel] (qtp504527234-813:null) (logid:) sendResponse info=null content=HeapByteBuffer@4d046cc7[p=0,l=75,c=32768,r=75]={<<<{"createvolumeres...rorcode":9999}}>>>-43fc-4e0c-a7ad-8...isuserdefined":} complete=true committing=true callback=Blocker@28389679{null}
2019-12-20 16:17:58,593 DEBUG [o.e.j.s.HttpChannel] (qtp504527234-813:null) (logid:) COMMIT for /client/api on HttpChannelOverHttp@5d83425d{r=1,c=true,a=COMPLETING,uri=https://192-168-140-220.cloud.tld:8443/client/api?apiKey=-Rt233Gc8hogf2d-mLvno6fzoTueIja8W_io56YM1Bh435Rk6dXex0w_t29X_sv2MMhbuM1k2GbS63chKglc4A&command=createVolume&response=json&snapshotid=d603641c-dff4-43aa-8da1-07afaa0a35d3&signature=zcUn58qI0MLg2y2%2FJC30D8ThDc8%3D}
530 null HTTP/1.1
Content-Type: application/json;charset=utf-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1;mode=block
content-security-policy: 1
content-security-policy: default-src=none
content-security-policy: script-src=self
content-security-policy: connect-src=self
content-security-policy: img-src=self
content-security-policy: style-src=self
```

**Comment by shwstppr** [comment]
@NuxRo will it be possible for you to test the fix in the reference PR

**Comment by NuxRo** [comment]
Thanks @shwstppr, I'll try this ASAP.

**Comment by NuxRo** [comment]
@shwstppr Thanks for the patch, I build new RPM and upgraded cloudstack-management.
I can now create volumes and templates from snapshotid.

One note though, this works from cloudmonkey, but still not from the web UI. Any thoughts on why that might be?

**Comment by shwstppr** [comment]
@NuxRo can you please share logs or screenshot of the error you are getting with web UI

**Comment by NuxRo** [comment]
Here's a log containing (among others, sorry for verbosity) the output when create volume from snapshot fails.
http://tmp.nux.ro/acsuifail.log

Nothing happens in the logs when I try to create a template from the snapshot, it's like the button has no action linked to it.

**Comment by DaanHoogland** [comment]
@NuxRo sounds like a known bug addressed in #3767/#3723. can you check? issue #3716

**Comment by NuxRo** [comment]
Definitely a case of #3716 for the template from snapshot issue, thanks.

**Comment by DaanHoogland** [comment]
@NuxRo, can you give @shwstppr a review on/spin of his patch?
