### ISSUE TITLE
Management Server

### ISSUE THREAD

**Issue by CobbyJ** [apache/cloudstack#3841]
Followed the exact install on the latest CentOS 7 fresh install and when i run "cloudstack-setup-management" i get the following errors

`[root@cloudstack dnspython]# cloudstack-setup-management
Traceback (most recent call last):
  File "/usr/bin/cloudstack-setup-management", line 24, in <module>
    from cloudutils.serviceConfigServer import cloudManagementConfig
  File "/usr/lib64/python2.7/site-packages/cloudutils/serviceConfigServer.py", line 17, in <module>
    from db import Database
  File "/usr/lib64/python2.7/site-packages/cloudutils/db.py", line 20, in <module>
    import mysql.connector
  File "/usr/lib64/python2.7/site-packages/mysql/connector/__init__.py", line 41, in <module>
    import dns.resolver
ImportError: No module named dns.resolver`

I did not miss anything in the install.

**Comment by CobbyJ** [comment]
Got it working by these commands

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python get-pip.py
pip install dnspython

Then run

cloudstack-setup-management

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/3854
