### ISSUE TITLE
VR Health check errors seen in logs

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3893]
Saw this on latest master env, this may need checking - 

```
2020-02-18 07:58:01,574 ERROR [c.c.n.r.VirtualNetworkApplianceManagerImpl] (RouterStatusMonitor-1:ctx-3bbeb667) (logid:e9e4832d) Fail to complete the FetchRouterHealthChecksResultTask! 
com.google.gson.JsonIOException: java.io.EOFException: End of input
	at com.google.gson.Streams.parse(Streams.java:49)
	at com.google.gson.Gson.fromJson(Gson.java:497)
	at com.google.gson.Gson.fromJson(Gson.java:467)
	at com.google.gson.Gson.fromJson(Gson.java:417)
	at com.cloud.network.router.VirtualNetworkApplianceManagerImpl.updateDbHealthChecksFromRouterResponse(VirtualNetworkApplianceManagerImpl.java:1518)
	at com.cloud.network.router.VirtualNetworkApplianceManagerImpl$FetchRouterHealthChecksResultTask.getFailingChecks(VirtualNetworkApplianceManagerImpl.java:1271)
	at com.cloud.network.router.VirtualNetworkApplianceManagerImpl$FetchRouterHealthChecksResultTask.runInContext(VirtualNetworkApplianceManagerImpl.java:1250)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: End of input
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:887)
	at com.google.gson.stream.JsonReader.nextValue(JsonReader.java:787)
	at com.google.gson.stream.JsonReader.objectValue(JsonReader.java:782)
	... 22 more

```
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR, logs
~~~

##### CLOUDSTACK VERSION

~~~
4.14/master
~~~

**Comment by rhtyd** [comment]
Needs investigating if this causes any side-effects - @DaanHoogland @andrijapanicsb

**Comment by andrijapanicsb** [comment]
Sounds like FR36 related code... I didn't observe this during testing...

**Comment by andrijapanicsb** [comment]
Tested on (15-commits old) master and works fine.
@rhtyd any specifics of the evn where you tested this?

**Comment by rhtyd** [comment]
@andrijapanicsb yes, latest master.

**Comment by rhtyd** [comment]
I think I saw this with simulator and with KVM.
