### ISSUE TITLE
similator NPE in solidfire plugin

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#4026]
An NPE occurs during deployment of a simulator environment.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Storage
Simulator
~~~

##### CLOUDSTACK VERSION

~~~
4.14 -- to be verified in older versions
~~~

##### CONFIGURATION

build with -Dsimulator and deploy simulator DB

##### OS / ENVIRONMENT

macos (but should be independent of OS

##### STEPS TO REPRODUCE

~~~
python ./tools/marvin/marvin/deployDataCenter.py -i setup/dev/dualsim.cfg
~~~

##### EXPECTED RESULTS

clean log with regular messages of progress

##### ACTUAL RESULTS

~~~
java.lang.NullPointerException
	at org.apache.cloudstack.storage.datastore.provider.SolidFireHostListener.hostAdded(SolidFireHostListener.java:81)
	at com.cloud.storage.listener.StoragePoolMonitor.processHostAdded(StoragePoolMonitor.java:84)
	at com.cloud.agent.manager.AgentManagerImpl.notifyMonitorsOfNewlyAddedHost(AgentManagerImpl.java:548)
	at com.cloud.agent.manager.AgentManagerImpl.handleDirectConnectAgent(AgentManagerImpl.java:1524)
	at com.cloud.resource.ResourceManagerImpl.createHostAndAgent(ResourceManagerImpl.java:2084)
	at com.cloud.resource.ResourceManagerImpl.discoverHostsFull(ResourceManagerImpl.java:804)
	at com.cloud.resource.ResourceManagerImpl.discoverHosts(ResourceManagerImpl.java:615)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy201.discoverHosts(Unknown Source)
	at com.cloud.agent.manager.MockAgentManagerImpl$SystemVMHandler.run(MockAgentManagerImpl.java:367)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~

**Comment by rhtyd** [comment]
NPE was fixed - https://github.com/apache/cloudstack/blob/master/plugins/storage/volume/solidfire/src/main/java/org/apache/cloudstack/storage/datastore/provider/SolidFireHostListener.java#L75
