### ISSUE TITLE
HTTP ERROR 503 Problem accessing /client/. Reason:      Service Unavailable

### ISSUE THREAD

**Issue by gnanasankar** [apache/cloudstack#4027]
HTTP ERROR 503 Problem accessing /client/. Reason:      Service Unavailable

**Comment by DaanHoogland** [comment]
this is not a proper issue report @gnanasankar please be very verbose on details of your problem.

**Comment by icsfot** [comment]
I have also had this issue, I have followed the centos instructions, looking at the error messages appears to be with the JDBC driver.  This was with an existing centos install and a fresh 

I'm pretty sure I have followed instructions to a t, been installing reinstalling for a day now, old jdbc drivers, the lot, still no luck, really appreciate someones help.

[root@machine.fot management]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

Error from management-server.log

2020-05-09 00:14:18,678 INFO  [c.c.u.d.Merovingian2] (main:null) (logid:) Cleaning up locks for 68289897081465
2020-05-09 00:14:18,680 INFO  [c.c.u.d.Merovingian2] (main:null) (logid:) Released 0 locks for 68289897081465
2020-05-09 00:14:18,875 INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Running system integrity checker com.cloud.upgrade.DatabaseUpgradeChecker@5f462e3b
2020-05-09 00:14:18,876 INFO  [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Grabbing lock to check for database upgrade.
2020-05-09 00:14:18,890 ERROR [c.c.u.d.DbUtil] (main:null) (logid:) GET_LOCK() throws exception
java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)

**Comment by rhtyd** [comment]
@icsfot what is your cloudstack, java and mysql version? Are you using distro provided mysql-java dependency?

**Comment by yanmaipian** [comment]
mysql:5.7.30-log
jdk:openjdk1.8.0_252
cloudstack:4.11
mysql-connector-python:8.0.20
mysql-connector-java:8.0.20

**Comment by rhtyd** [comment]
@yanmaipian mysql-connector-java 8.x will likely not work with CloudStack 4.11, can you try version 5.x such as https://centos.pkgs.org/7/centos-x86_64/mysql-connector-java-5.1.25-3.el7.noarch.rpm.html

**Comment by ccycv** [comment]
I have the same problem with a fresh install of CloudStack 4.13.0 on CentOS Linux release 7.8.2003 (Core)

**Comment by yanmaipian** [comment]
@rhtyd Using mysql-connector-java-5.1.25-3 to replace mysql-connector-java: 8.0.20 really solved, thank you very much.

**Comment by rhtyd** [comment]
This has been addressed in 4.14/master using Java11
