### ISSUE TITLE
Shared Network (without services) is being deleted when its NICs are assigned to VM

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#4096]
Shared Network (without services) is being deleted when its NICs are assigned to VM, resulting in NPE on fetching VM NIC details and deleting VM with NIC on deleted Network

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM, Network
~~~

##### CLOUDSTACK VERSION

~~~
4.13, 4.13.1
~~~

##### CONFIGURATION

Advanced zone
Shared Network

##### SUMMARY

Shared Network (without services) being used by some VMs is getting deleted irrespective of NICs assignment and resulting in error "Caught the Exception in VmIpFetchTask java.lang.NullPointerException" on fetching VM NIC details and deleting VM.

##### STEPS TO REPRODUCE

1. Create a Network Offering without services
1. Create a Shared Network using that Network Offering
2. Create a VM on that Shared Network
3. Delete the Network
4. Delete the VM

~~~

~~~

##### EXPECTED RESULTS

~~~
Shared Network (without services) should not be deleted when NICs are assigned to any VMs
~~~

##### ACTUAL RESULTS

Shared Network (without services) is being deleted when its NICs are assigned to VMs

~~~
2020-05-20 16:27:33,711 DEBUG [c.c.a.ApiServlet] (qtp504527234-15:ctx-1538b790 ctx-4bbb122c) (logid:5ec67ed3) ===END===  192.168.2.31 -- GET  command=deleteNetwork&id=b1549b7e-707d-4fde-80c2-680863ddd1ee&response=json&_=1589990310891
2020-05-20 16:27:33,715 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213) (logid:4058ade8) Executing AsyncJobVO {id:213, userId: 2, accountId: 2, instanceType: Network, instanceId: 210, cmd: org.apache.cloudstack.api.command.user.network.DeleteNetworkCmd, cmdInfo: {"response":"json","ctxUserId":"2","httpmethod":"GET","ctxStartEventId":"699","id":"b1549b7e-707d-4fde-80c2-680863ddd1ee","ctxDetails":"{\"interface com.cloud.network.Network\":\"b1549b7e-707d-4fde-80c2-680863ddd1ee\"}","ctxAccountId":"2","uuid":"b1549b7e-707d-4fde-80c2-680863ddd1ee","cmdEventType":"NETWORK.DELETE","_":"1589990310891"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 32987278280682, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}
2020-05-20 16:27:33,721 DEBUG [c.c.s.StatsCollector] (StatsCollector-1:ctx-cc3d0d47) (logid:7bf5da9b) AutoScaling Monitor is running...
2020-05-20 16:27:33,730 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) The network id=210 has active Nics, but shouldn't.
2020-05-20 16:27:33,733 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Network is not implemented: Ntwk[210|Guest|19]
2020-05-20 16:27:33,734 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Releasing 0 port forwarding rules for network id=210
2020-05-20 16:27:33,735 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Releasing 0 static nat rules for network id=210
2020-05-20 16:27:33,735 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) There are no port forwarding rules to apply for network id=210
2020-05-20 16:27:33,736 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) There are no port forwarding rules to apply for network id=210
2020-05-20 16:27:33,736 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) There are no static nat rules to apply for network id=210
2020-05-20 16:27:33,737 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) There are no static nat rules to apply for network id=210
2020-05-20 16:27:33,737 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Successfully released rules for network id=210 and # of rules now = 0
2020-05-20 16:27:33,737 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Successfully cleaned up portForwarding/staticNat rules for network id=210
2020-05-20 16:27:33,738 DEBUG [c.c.n.l.LoadBalancingRulesManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Found 0 lb rules to cleanup
2020-05-20 16:27:33,738 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Successfully cleaned up load balancing rules for network id=210
2020-05-20 16:27:33,742 DEBUG [c.c.n.f.FirewallManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Releasing 0 firewall rules for network id=210
2020-05-20 16:27:33,742 DEBUG [c.c.n.f.FirewallManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) There are no firewall rules to apply
2020-05-20 16:27:33,742 DEBUG [c.c.n.f.FirewallManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Successfully released firewall rules for network id=210 and # of rules now = 0
2020-05-20 16:27:33,746 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Successfully cleaned up firewallRules rules for network id=210
2020-05-20 16:27:33,747 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Successfully cleaned up NetworkACLs for network id=210
2020-05-20 16:27:33,748 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Network id=210 is destroyed successfully, cleaning up corresponding resources now.
2020-05-20 16:27:33,754 DEBUG [c.c.c.ConfigurationManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Delete Public IP Range (from user_ip_address, where vlan_db_d=4)
2020-05-20 16:27:33,755 DEBUG [c.c.c.ConfigurationManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Mark vlan as Remove vlan (vlan_db_id=4)
2020-05-20 16:27:33,755 DEBUG [c.c.c.ConfigurationManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Delete vlan_db_id=4 in pod_vlan_map
2020-05-20 16:27:33,755 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Deleted ip range for private network id=210
2020-05-20 16:27:33,765 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Complete async job-213, jobStatus: SUCCEEDED, resultCode: 0, result: org.apache.cloudstack.api.response.SuccessResponse/null/{"success":true}
2020-05-20 16:27:33,766 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Publish async job-213 complete on message bus
2020-05-20 16:27:33,766 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Wake up jobs related to job-213
2020-05-20 16:27:33,766 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Update db status for job-213
2020-05-20 16:27:33,766 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213 ctx-0ee06ef2) (logid:4058ade8) Wake up jobs joined with job-213 and disjoin all subjobs created from job- 213
2020-05-20 16:27:33,769 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-cbfaf115 job-213) (logid:4058ade8) Done executing org.apache.cloudstack.api.command.user.network.DeleteNetworkCmd for job-213
2020-05-20 16:27:33,769 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-11:ctx-cbfaf115 job-213) (logid:4058ade8) Remove job-213 from job monitoring

...

2020-05-20 16:28:18,710 ERROR [c.c.v.UserVmManagerImpl] (UserVm-ipfetch-2:ctx-ef54289c) (logid:ace81473) Caught the Exception in VmIpFetchTask
java.lang.NullPointerException
        at com.cloud.vm.UserVmManagerImpl$VmIpFetchTask.runInContext(UserVmManagerImpl.java:2389)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

...

2020-05-20 16:31:20,053 DEBUG [c.c.a.ApiServlet] (qtp504527234-19:ctx-c6cff5df) (logid:29db65cd) ===START===  192.168.2.31 -- GET  command=destroyVirtualMachine&response=json&id=207b110c-787d-4652-9f2a-2d70085856bc&expunge=true&volumeids=&_=1589990310897
2020-05-20 16:31:20,057 DEBUG [c.c.a.ApiServer] (qtp504527234-19:ctx-c6cff5df ctx-8885c1bd) (logid:29db65cd) CIDRs from which account 'Acct[d7c80a77-7f1a-11ea-9584-1e00730107ea-admin]' is allowed to perform API calls: 0.0.0.0/0,::/0
2020-05-20 16:31:20,070 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-12:ctx-5ec3b967 job-214) (logid:004ed9de) Add job-214 into job monitoring
2020-05-20 16:31:20,071 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (qtp504527234-19:ctx-c6cff5df ctx-8885c1bd) (logid:29db65cd) submit async job-214, details: AsyncJobVO {id:214, userId: 2, accountId: 2, instanceType: VirtualMachine, instanceId: 12, cmd: org.apache.cloudstack.api.command.admin.vm.DestroyVMCmdByAdmin, cmdInfo: {"response":"json","ctxUserId":"2","expunge":"true","httpmethod":"GET","ctxStartEventId":"704","id":"207b110c-787d-4652-9f2a-2d70085856bc","volumeids":"","ctxDetails":"{\"interface com.cloud.vm.VirtualMachine\":\"207b110c-787d-4652-9f2a-2d70085856bc\"}","ctxAccountId":"2","uuid":"207b110c-787d-4652-9f2a-2d70085856bc","cmdEventType":"VM.DESTROY","_":"1589990310897"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 32987278280682, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}
2020-05-20 16:31:20,072 DEBUG [c.c.a.ApiServlet] (qtp504527234-19:ctx-c6cff5df ctx-8885c1bd) (logid:29db65cd) ===END===  192.168.2.31 -- GET  command=destroyVirtualMachine&response=json&id=207b110c-787d-4652-9f2a-2d70085856bc&expunge=true&volumeids=&_=1589990310897
2020-05-20 16:31:20,074 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-12:ctx-5ec3b967 job-214) (logid:2e0e676a) Executing AsyncJobVO {id:214, userId: 2, accountId: 2, instanceType: VirtualMachine, instanceId: 12, cmd: org.apache.cloudstack.api.command.admin.vm.DestroyVMCmdByAdmin, cmdInfo: {"response":"json","ctxUserId":"2","expunge":"true","httpmethod":"GET","ctxStartEventId":"704","id":"207b110c-787d-4652-9f2a-2d70085856bc","volumeids":"","ctxDetails":"{\"interface com.cloud.vm.VirtualMachine\":\"207b110c-787d-4652-9f2a-2d70085856bc\"}","ctxAccountId":"2","uuid":"207b110c-787d-4652-9f2a-2d70085856bc","cmdEventType":"VM.DESTROY","_":"1589990310897"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 32987278280682, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}
2020-05-20 16:31:20,085 DEBUG [c.c.v.UserVmManagerImpl] (API-Job-Executor-12:ctx-5ec3b967 job-214 ctx-e7bff8ca) (logid:2e0e676a) Checking if there are any ongoing snapshots on the ROOT volumes associated with VM with ID 12
2020-05-20 16:31:20,086 DEBUG [c.c.v.UserVmManagerImpl] (API-Job-Executor-12:ctx-5ec3b967 job-214 ctx-e7bff8ca) (logid:2e0e676a) Found 1 no. of volumes of type ROOT for vm with VM ID 12
2020-05-20 16:31:20,086 DEBUG [c.c.v.UserVmManagerImpl] (API-Job-Executor-12:ctx-5ec3b967 job-214 ctx-e7bff8ca) (logid:2e0e676a) Checking status of snapshots for Volume with Volume Id: 36
2020-05-20 16:31:20,087 DEBUG [c.c.v.UserVmManagerImpl] (API-Job-Executor-12:ctx-5ec3b967 job-214 ctx-e7bff8ca) (logid:2e0e676a) The count of ongoing Snapshots for VM with ID 12 and disk type ROOT is 0
2020-05-20 16:31:20,087 DEBUG [c.c.v.UserVmManagerImpl] (API-Job-Executor-12:ctx-5ec3b967 job-214 ctx-e7bff8ca) (logid:2e0e676a) Found no ongoing snapshots on volume of type ROOT, for the vm with id 12
...
2020-05-20 16:31:46,955 DEBUG [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215 ctx-0e9f3f89) (logid:2e0e676a) VM[User|i-2-12-VM] is stopped on the host.  Proceeding to release resource held.
2020-05-20 16:31:46,958 DEBUG [c.c.u.d.T.Transaction] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215 ctx-0e9f3f89) (logid:2e0e676a) Rolling back the transaction: Time = 2 Name =  Work-Job-Executor-9; called by -TransactionLegacy.rollback:890-TransactionLegacy.removeUpTo:833-TransactionLegacy.close:657-Transaction.execute:43-Transaction.execute:47-NetworkOrchestrator.releaseNic:1941-NetworkOrchestrator.release:1929-VirtualMachineManagerImpl.advanceStop:1782-VirtualMachineManagerImpl.orchestrateStop:1622-VirtualMachineManagerImpl.orchestrateStop:5162-NativeMethodAccessorImpl.invoke0:-2-NativeMethodAccessorImpl.invoke:62
2020-05-20 16:31:46,958 WARN  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215 ctx-0e9f3f89) (logid:2e0e676a) Unable to release some network resources.
java.lang.NullPointerException
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$8.doInTransaction(NetworkOrchestrator.java:1972)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$8.doInTransaction(NetworkOrchestrator.java:1941)
        at com.cloud.utils.db.Transaction$2.doInTransaction(Transaction.java:50)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:40)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:47)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.releaseNic(NetworkOrchestrator.java:1941)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.release(NetworkOrchestrator.java:1929)
        at com.cloud.vm.VirtualMachineManagerImpl.advanceStop(VirtualMachineManagerImpl.java:1782)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStop(VirtualMachineManagerImpl.java:1622)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStop(VirtualMachineManagerImpl.java:5162)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5306)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:603)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:551)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-05-20 16:31:46,959 DEBUG [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215 ctx-0e9f3f89) (logid:2e0e676a) Successfully released storage resources for the vm VM[User|i-2-12-VM]
2020-05-20 16:31:46,968 ERROR [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215 ctx-0e9f3f89) (logid:2e0e676a) Invocation exception, caused by: java.lang.NullPointerException
2020-05-20 16:31:46,968 INFO  [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215 ctx-0e9f3f89) (logid:2e0e676a) Rethrow exception java.lang.NullPointerException
2020-05-20 16:31:46,968 DEBUG [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215) (logid:2e0e676a) Done with run of VM work job: com.cloud.vm.VmWorkStop for VM 12, job origin: 214
2020-05-20 16:31:46,968 ERROR [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-9:ctx-223abab2 job-214/job-215) (logid:2e0e676a) Unable to complete AsyncJobVO {id:215, userId: 2, accountId: 2, instanceType: null, instanceId: null, cmd: com.cloud.vm.VmWorkStop, cmdInfo: rO0ABXNyABdjb20uY2xvdWQudm0uVm1Xb3JrU3RvcALQ4GymiWjjAgABWgAHY2xlYW51cHhyABNjb20uY2xvdWQudm0uVm1Xb3Jrn5m2VvAlZ2sCAARKAAlhY2NvdW50SWRKAAZ1c2VySWRKAAR2bUlkTAALaGFuZGxlck5hbWV0ABJMamF2YS9sYW5nL1N0cmluZzt4cAAAAAAAAAACAAAAAAAAAAIAAAAAAAAADHQAGVZpcnR1YWxNYWNoaW5lTWFuYWdlckltcGwA, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 32987278280682, completeMsid: null, lastUpdated: null, lastPolled: null, created: Wed May 20 16:31:20 UTC 2020, removed: null}, job origin:214
java.lang.NullPointerException
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.getNicProfiles(NetworkOrchestrator.java:3782)
        at com.cloud.network.security.SecurityGroupManagerImpl.isVmSecurityGroupEnabled(SecurityGroupManagerImpl.java:1270)
        at com.cloud.network.security.SecurityGroupManagerImpl.handleVmStopped(SecurityGroupManagerImpl.java:520)
        at com.cloud.network.security.SecurityGroupManagerImpl.postStateTransitionEvent(SecurityGroupManagerImpl.java:1256)
        at com.cloud.network.security.SecurityGroupManagerImpl.postStateTransitionEvent(SecurityGroupManagerImpl.java:120)
        at com.cloud.utils.fsm.StateMachine2.transitTo(StateMachine2.java:142)
        at com.cloud.vm.VirtualMachineManagerImpl.stateTransitTo(VirtualMachineManagerImpl.java:1840)
        at com.cloud.vm.VirtualMachineManagerImpl.advanceStop(VirtualMachineManagerImpl.java:1806)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStop(VirtualMachineManagerImpl.java:1622)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStop(VirtualMachineManagerImpl.java:5162)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5306)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:603)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:551)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
~~~

**Comment by nvazquez** [comment]
Also reproducible in master
