### ISSUE TITLE
Fail to deploy VM with Ceph (Octopus) as primary storage

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4159]
Tried to deploy a VM using a template and custom compute offering with tags to match against a Ceph (Octopus) based primary storage, on Ubuntu 20.04 KVM (raspberrypi4).

The issue may be in rados-java (https://github.com/ceph/rados-java/blob/master/src/main/java/com/ceph/rados/Rados.java#L362) or something due to offering configuration or handling of the same; and upon failure and expunging of the VM, the root disk (marked as removed in DB) did not get remove from the Ceph pool:

```
2020-06-20 17:01:02,535 DEBUG [o.a.c.e.o.VolumeOrchestrator] (Work-Job-Executor-18:ctx-d056c1e3 job-636/job-637 ctx-c3cd8ca6) (logid:1cec6c16) Unable to create Vol[72|vm=76|ROOT]:java.lang.NoSuchFieldError: SIZE
        at com.ceph.rados.Rados.ioCtxCreate(Rados.java:362)
        at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.copyPhysicalDisk(LibvirtStorageAdaptor.java:1341)
        at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.copyPhysicalDisk(KVMStoragePoolManager.java:394)
        at com.cloud.hypervisor.kvm.storage.KVMStorageProcessor.copyTemplateToPrimaryStorage(KVMStorageProcessor.java:258)
        at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.execute(StorageSubsystemCommandHandlerBase.java:89)
        at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.handleStorageCommands(StorageSubsystemCommandHandlerBase.java:57)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStorageSubSystemCommandWrapper.execute(LibvirtStorageSubSystemCommandWrapper.java:36)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStorageSubSystemCommandWrapper.execute(LibvirtStorageSubSystemCommandWrapper.java:30)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1637)
        at com.cloud.agent.Agent.processRequest(Agent.java:644)
        at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1057)

```

Details:
```
root@rpi-mgmt:~# ceph --version
ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable)
root@rpi-mgmt:~# lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

Ping @wido @GabrielBrascher 

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Ceph
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

**Comment by rhtyd** [comment]
Note - if I create data disk and attach it to a VM (VM's root disk on NFS), that works.

**Comment by rhtyd** [comment]
Looks like the fix is there https://github.com/ceph/rados-java/commit/d59c6e5c499fffb0d5a62b0abdb7d1963992331e
We just need a new rados-java release

**Comment by rhtyd** [comment]
The issue was in rados-java, sent a PR https://github.com/ceph/rados-java/pull/42/files
Let's close this PR once rados-java does a new 0.6.0 release and we pull that in CloudStack (which now uses a more updated jna 5.5.0) cc @wido

**Comment by wido** [comment]
I've merged that PR at rados-java. I haven't run into this myself with Ceph Octopus, but good to know.

I'll try to get release 0.6.0 out of rados-java.

**Comment by rhtyd** [comment]
Thanks @wido

**Comment by wido** [comment]
I tagged rados-java 0.6.0. Now I need to find somebody who can put it in Maven Central.

**Comment by rhtyd** [comment]
+1 Once done, please also send a PR to 4.14 branch to bump the dependency version in pom.xml @wido thnx

**Comment by rhtyd** [comment]
Ping @wido reminder - as we're getting closer to work towards 4.15, can you help upload the latest rados-java release to maven? Thanks.

**Comment by wido** [comment]
@rhtyd The bindings are here online: http://ceph.o.auroraobjects.eu/rados-java/rados-java-0.6.0.tar.gz

Can you or @GabrielBrascher help me get this into Maven central?

**Comment by rhtyd** [comment]
Thanks @wido - sorry but I'm not sure (or have authorisation) to upload jar bundles, if there's an issue I can add it to https://github.com/rhtyd/cloudstack-nonoss

**Comment by GabrielBrascher** [comment]
@rhtyd @wido the artifacts for rados-java v0.6.0 are available at https://search.maven.org/artifact/com.ceph/rados

**Comment by GabrielBrascher** [comment]
@rhtyd I took the liberty and created PR #4287 updating the versions.
