### ISSUE TITLE
cannot delete registered template ?

### ISSUE THREAD

**Issue by dony71** [apache/cloudstack#4332]
I follow this instruction https://rohityadav.cloud/blog/cloudstack-rpi4-kvm/
Everything works OK but after add template, cannot delete 
event log show delete successful, but template still there 

https://imgur.com/a/MbL4Uc8

https://imgur.com/eQVPCBB

**Comment by dony71** [comment]
> I follow this instruction https://rohityadav.cloud/blog/cloudstack-rpi4-kvm/
> Everything works OK but after add template, I don't see any edit function
> Any setting for this?
> 
> https://ibb.co/WzK53b6

I notice also below error in mgmt log, not sure it;s related or not
```
2020-09-17 18:16:29,355 ERROR [c.c.u.PropertiesUtil] (main:null) (logid:) Unable to find properties file: commands.properties
```

**Comment by dony71** [comment]
I try upload vm image locally, but unsuccessful 
mgmt log shows 
```
2020-09-17 18:39:44,708 DEBUG [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-aec68f9b) (logid:b77efb4f) Zone 1 has 1 console proxy VM(s) in transition state
2020-09-17 18:39:45,490 DEBUG [o.a.c.s.SecondaryStorageManagerImpl] (secstorage-1:ctx-eae26131) (logid:e352bb28) Zone 1 is ready to launch secondary storage VM
2020-09-17 18:39:45,749 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-11:null) (logid:) Ping from Routing host 1(cloudstack-mgmt)
2020-09-17 18:39:45,750 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) Process host VM state report from ping process. host: 1
2020-09-17 18:39:45,750 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) Process VM state report. host: 1, number of records in report: 0
2020-09-17 18:39:45,763 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) Run missing VM report. current time: 1600393185763
2020-09-17 18:39:45,778 INFO  [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) Detected missing VM. host: 1, vm id: 2472(376222a4-de6d-417b-8ea5-4d4f369eb0bd), power state: PowerReportMissing, last state update: 2020/09/17T18:38:46.000Z
2020-09-17 18:39:45,779 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) vm id: 2472 - time since last state update(59763ms) has not passed graceful period yet
2020-09-17 18:39:45,806 INFO  [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) Detected missing VM. host: 1, vm id: 2473(6a6f45fd-0f70-4467-bac9-43991d8c565f), power state: PowerReportMissing, last state update: 2020/09/17T18:38:46.000Z
2020-09-17 18:39:45,806 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) vm id: 2473 - time since last state update(59763ms) has not passed graceful period yet
2020-09-17 18:39:45,806 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-11:null) (logid:) Done with process of VM state report. host: 1
2020-09-17 18:39:48,729 DEBUG [c.c.a.ApiServlet] (qtp1250121181-19:ctx-106018b7) (logid:da083f69) ===START===  10.1.33.237 -- GET  command=getUploadParamsForTemplate&response=json&name=Fedora%2032%20local&displayText=Fedora%2032%20for%20ARM64&zoneid=dd31b1e6-aa3e-47c9-b07f-0e950fe4f92a&format=QCOW2&isextractable=false&passwordEnabled=false&isdynamicallyscalable=false&osTypeId=6a024b54-f87b-11ea-afbb-dca632520b89&hypervisor=KVM&details%5B0%5D.rootDiskController=osdefault&ispublic=false&requireshvm=false&isfeatured=false&isrouting=false&_=1600392994301
2020-09-17 18:39:48,780 DEBUG [c.c.a.ApiServer] (qtp1250121181-19:ctx-106018b7 ctx-8c52fed9) (logid:da083f69) CIDRs from which account 'Acct[4344f34e-f87f-11ea-afbb-dca632520b89-admin]' is allowed to perform API calls: 0.0.0.0/0,::/0
2020-09-17 18:39:49,080 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (qtp1250121181-19:ctx-106018b7 ctx-8c52fed9) (logid:da083f69) template 206 is not in store:3, type:Image
2020-09-17 18:39:49,116 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (qtp1250121181-19:ctx-106018b7 ctx-8c52fed9) (logid:da083f69) template 206 is already in store:3, type:Image
2020-09-17 18:39:49,124 WARN  [c.c.t.HypervisorTemplateAdapter] (qtp1250121181-19:ctx-106018b7 ctx-8c52fed9) (logid:da083f69) There is no secondary storage VM for downloading template to image store Secondary
2020-09-17 18:39:49,128 DEBUG [c.c.u.d.T.Transaction] (qtp1250121181-19:ctx-106018b7 ctx-8c52fed9) (logid:da083f69) Rolling back the transaction: Time = 187 Name =  qtp1250121181-19; called by -TransactionLegacy.rollback:890-TransactionLegacy.removeUpTo:833-TransactionLegacy.close:657-Transaction.execute:38-Transaction.execute:47-HypervisorTemplateAdapter.createTemplateForPostUpload:292-TemplateManagerImpl.registerPostUploadInternal:360-TemplateManagerImpl.registerTemplateForPostUpload:422-NativeMethodAccessorImpl.invoke0:-2-NativeMethodAccessorImpl.invoke:62-DelegatingMethodAccessorImpl.invoke:43-Method.invoke:566
2020-09-17 18:39:49,234 ERROR [c.c.a.ApiServer] (qtp1250121181-19:ctx-106018b7 ctx-8c52fed9) (logid:da083f69) unhandled exception executing api command: [Ljava.lang.String;@4f26298
com.cloud.utils.exception.CloudRuntimeException: There is no secondary storage VM for downloading template to image store Secondary
        at com.cloud.template.HypervisorTemplateAdapter$1.doInTransaction(HypervisorTemplateAdapter.java:357)
        at com.cloud.template.HypervisorTemplateAdapter$1.doInTransaction(HypervisorTemplateAdapter.java:292)
        at com.cloud.utils.db.Transaction$2.doInTransaction(Transaction.java:50)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:40)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:47)
        at com.cloud.template.HypervisorTemplateAdapter.createTemplateForPostUpload(HypervisorTemplateAdapter.java:292)
        at com.cloud.template.TemplateManagerImpl.registerPostUploadInternal(TemplateManagerImpl.java:360)
        at com.cloud.template.TemplateManagerImpl.registerTemplateForPostUpload(TemplateManagerImpl.java:422)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy185.registerTemplateForPostUpload(Unknown Source)
        at org.apache.cloudstack.api.command.user.template.GetUploadParamsForTemplateCmd.execute(GetUploadParamsForTemplateCmd.java:158)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:759)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:583)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:310)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:130)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:127)
        at com.cloud.api.ApiServlet.doGet(ApiServlet.java:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1386)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-17 18:39:49,276 DEBUG [c.c.a.ApiServlet] (qtp1250121181-19:ctx-106018b7 ctx-8c52fed9) (logid:da083f69) ===END===  10.1.33.237 -- GET  command=getUploadParamsForTemplate&response=json&name=Fedora%2032%20local&displayText=Fedora%2032%20for%20ARM64&zoneid=dd31b1e6-aa3e-47c9-b07f-0e950fe4f92a&format=QCOW2&isextractable=false&passwordEnabled=false&isdynamicallyscalable=false&osTypeId=6a024b54-f87b-11ea-afbb-dca632520b89&hypervisor=KVM&details%5B0%5D.rootDiskController=osdefault&ispublic=false&requireshvm=false&isfeatured=false&isrouting=false&_=1600392994301
2020-09-17 18:39:50,111 DEBUG [c.c.s.StatsCollector] (StatsCollector-1:ctx-a8ab0e97) (logid:11a7ab52) HostStatsCollector is running...
2020-09-17 18:39:50,235 DEBUG [c.c.a.t.Request] (StatsCollector-1:ctx-a8ab0e97) (logid:11a7ab52) Seq 1-1543045822327816245: Received:  { Ans: , MgmtId: 2484758518717, via: 1(cloudstack-mgmt), Ver: v1, Flags: 10, { GetHostStatsAnswer } }
2020-09-17 18:39:51,168 DEBUG [c.c.s.StatsCollector] (StatsCollector-5:ctx-01a99418) (logid:a52e3967) StorageCollector is running...
2020-09-17 18:39:51,226 DEBUG [c.c.s.StatsCollector] (StatsCollector-5:ctx-01a99418) (logid:a52e3967) There is no secondary storage VM for secondary storage host Secondary
2020-09-17 18:39:51,243 DEBUG [c.c.h.o.r.Ovm3HypervisorGuru] (StatsCollector-5:ctx-01a99418) (logid:a52e3967) getCommandHostDelegation: class com.cloud.agent.api.GetStorageStatsCommand
2020-09-17 18:39:51,243 DEBUG [c.c.h.XenServerGuru] (StatsCollector-5:ctx-01a99418) (logid:a52e3967) We are returning the default host to execute commands because the command is not of Copy type.
2020-09-17 18:39:51,336 DEBUG [c.c.a.t.Request] (StatsCollector-5:ctx-01a99418) (logid:a52e3967) Seq 1-1543045822327816246: Received:  { Ans: , MgmtId: 2484758518717, via: 1(cloudstack-mgmt), Ver: v1, Flags: 10, { GetStorageStatsAnswer } }
2020-09-17 18:39:56,378 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (RouterStatusMonitor-1:ctx-3782f7b8) (logid:e59782e7) Found 0 routers to update status.
2020-09-17 18:39:56,382 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (RouterStatusMonitor-1:ctx-3782f7b8) (logid:e59782e7) Found 0 VPC's to update Redundant State.
2020-09-17 18:39:56,386 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (RouterStatusMonitor-1:ctx-3782f7b8) (logid:e59782e7) Found 0 networks to update RvR status.
2020-09-17 18:40:01,627 DEBUG [c.c.h.d.HostDaoImpl] (ClusteredAgentManager Timer:ctx-eaf7615d) (logid:dceaceb5) Resetting hosts suitable for reconnect
2020-09-17 18:40:01,632 DEBUG [c.c.h.d.HostDaoImpl] (ClusteredAgentManager Timer:ctx-eaf7615d) (logid:dceaceb5) Completed resetting hosts suitable for reconnect
2020-09-17 18:40:01,632 DEBUG [c.c.h.d.HostDaoImpl] (ClusteredAgentManager Timer:ctx-eaf7615d) (logid:dceaceb5) Acquiring hosts for clusters already owned by this management server
2020-09-17 18:40:01,635 DEBUG [c.c.h.d.HostDaoImpl] (ClusteredAgentManager Timer:ctx-eaf7615d) (logid:dceaceb5) Completed acquiring hosts for clusters already owned by this management server
2020-09-17 18:40:01,635 DEBUG [c.c.h.d.HostDaoImpl] (ClusteredAgentManager Timer:ctx-eaf7615d) (logid:dceaceb5) Acquiring hosts for clusters not owned by any management server
2020-09-17 18:40:01,637 DEBUG [c.c.h.d.HostDaoImpl] (ClusteredAgentManager Timer:ctx-eaf7615d) (logid:dceaceb5) Completed acquiring hosts for clusters not owned by any management server
2020-09-17 18:40:14,792 DEBUG [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-26af383d) (logid:7da16071) Zone 1 has 1 console proxy VM(s) in transition state
2020-09-17 18:40:15,504 DEBUG [o.a.c.s.SecondaryStorageManagerImpl] (secstorage-1:ctx-4771fc2d) (logid:7c72dd0f) Zone 1 is ready to launch secondary storage VM
```

**Comment by dony71** [comment]
resolved by reinstalling and reconfigure cloudstack-management
