### ISSUE TITLE
Unable to start console proxy vm for standby capacity

### ISSUE THREAD

**Issue by dony71** [apache/cloudstack#4334]
I follow installation at https://rohityadav.cloud/blog/cloudstack-rpi4-kvm/
Everything working except consoleproxy stop and cannot be restart
management-server.log shows
```
2020-09-18 17:50:21,883 WARN  [c.c.u.d.Merovingian2] (consoleproxy-1:ctx-add1d9ee) (logid:4ee49b96) Timed out on acquiring lock vm_instance2473 .  Waited for 1800seconds
com.cloud.utils.exception.CloudRuntimeException: Timed out on acquiring lock vm_instance2473 .  Waited for 1800seconds
	at com.cloud.utils.db.Merovingian2.acquire(Merovingian2.java:151)
	at com.cloud.utils.db.TransactionLegacy.lock(TransactionLegacy.java:386)
	at com.cloud.utils.db.GenericDaoBase.lockInLockTable(GenericDaoBase.java:1079)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy91.lockInLockTable(Unknown Source)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl.submitAsyncJob(AsyncJobManagerImpl.java:229)
	at com.cloud.vm.VirtualMachineManagerImpl.startVmThroughJobQueue(VirtualMachineManagerImpl.java:4737)
	at com.cloud.vm.VirtualMachineManagerImpl.advanceStart(VirtualMachineManagerImpl.java:904)
	at com.cloud.vm.VirtualMachineManagerImpl.advanceStart(VirtualMachineManagerImpl.java:883)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.startProxy(ConsoleProxyManagerImpl.java:544)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.allocCapacity(ConsoleProxyManagerImpl.java:978)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.expandPool(ConsoleProxyManagerImpl.java:1696)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.expandPool(ConsoleProxyManagerImpl.java:159)
	at com.cloud.vm.SystemVmLoadScanner.loadScan(SystemVmLoadScanner.java:121)
	at com.cloud.vm.SystemVmLoadScanner$1.reallyRun(SystemVmLoadScanner.java:91)
	at com.cloud.vm.SystemVmLoadScanner$1.runInContext(SystemVmLoadScanner.java:82)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-18 17:50:21,886 WARN  [o.a.c.f.j.i.AsyncJobManagerImpl] (consoleproxy-1:ctx-add1d9ee) (logid:4ee49b96) Unable to schedule async job for command com.cloud.vm.VmWorkStart, unexpected exception.
com.cloud.utils.exception.CloudRuntimeException: Failed to acquire lock in submitting async job: com.cloud.vm.VmWorkStart with timeout value = 1800
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl.submitAsyncJob(AsyncJobManagerImpl.java:230)
	at com.cloud.vm.VirtualMachineManagerImpl.startVmThroughJobQueue(VirtualMachineManagerImpl.java:4737)
	at com.cloud.vm.VirtualMachineManagerImpl.advanceStart(VirtualMachineManagerImpl.java:904)
	at com.cloud.vm.VirtualMachineManagerImpl.advanceStart(VirtualMachineManagerImpl.java:883)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.startProxy(ConsoleProxyManagerImpl.java:544)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.allocCapacity(ConsoleProxyManagerImpl.java:978)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.expandPool(ConsoleProxyManagerImpl.java:1696)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.expandPool(ConsoleProxyManagerImpl.java:159)
	at com.cloud.vm.SystemVmLoadScanner.loadScan(SystemVmLoadScanner.java:121)
	at com.cloud.vm.SystemVmLoadScanner$1.reallyRun(SystemVmLoadScanner.java:91)
	at com.cloud.vm.SystemVmLoadScanner$1.runInContext(SystemVmLoadScanner.java:82)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-18 17:50:21,888 WARN  [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-add1d9ee) (logid:4ee49b96) Runtime Exception while trying to start console proxy
com.cloud.utils.exception.CloudRuntimeException: Unable to schedule async job for command com.cloud.vm.VmWorkStart, unexpected exception.
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl.submitAsyncJob(AsyncJobManagerImpl.java:251)
	at com.cloud.vm.VirtualMachineManagerImpl.startVmThroughJobQueue(VirtualMachineManagerImpl.java:4737)
	at com.cloud.vm.VirtualMachineManagerImpl.advanceStart(VirtualMachineManagerImpl.java:904)
	at com.cloud.vm.VirtualMachineManagerImpl.advanceStart(VirtualMachineManagerImpl.java:883)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.startProxy(ConsoleProxyManagerImpl.java:544)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.allocCapacity(ConsoleProxyManagerImpl.java:978)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.expandPool(ConsoleProxyManagerImpl.java:1696)
	at com.cloud.consoleproxy.ConsoleProxyManagerImpl.expandPool(ConsoleProxyManagerImpl.java:159)
	at com.cloud.vm.SystemVmLoadScanner.loadScan(SystemVmLoadScanner.java:121)
	at com.cloud.vm.SystemVmLoadScanner$1.reallyRun(SystemVmLoadScanner.java:91)
	at com.cloud.vm.SystemVmLoadScanner$1.runInContext(SystemVmLoadScanner.java:82)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-18 17:50:21,890 INFO  [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-add1d9ee) (logid:4ee49b96) Unable to start console proxy vm for standby capacity, vm id : 2473, will recycle it and start a new one
```
v-2473-VM.log shows
```
2020-09-18 02:06:22.957+0000: starting up libvirt version: 6.0.0, package: 0ubuntu8.3 (Marc Deslauriers <marc.deslauriers@ubuntu.com> Thu, 30 Jul 2020 06:40:28 -0400), qemu version: 4.2.1Debian 1:4.2-3ubuntu6.5, kernel: 5.4.0-1018-raspi, hostname: cloudstack-mgmt
LC_ALL=C \
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
HOME=/var/lib/libvirt/qemu/domain-1-v-2473-VM \
XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-1-v-2473-VM/.local/share \
XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-1-v-2473-VM/.cache \
XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-1-v-2473-VM/.config \
QEMU_AUDIO_DRV=none \
/usr/bin/qemu-system-aarch64 \
-name guest=v-2473-VM,debug-threads=on \
-S \
-object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-v-2473-VM/master-key.aes \
-blockdev '{"driver":"file","filename":"/usr/share/AAVMF/AAVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"}' \
-blockdev '{"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/v-2473-VM_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"}' \
-machine virt-4.2,accel=kvm,usb=off,dump-guest-core=off,gic-version=2,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format \
-cpu host \
-m 1024 \
-overcommit mem-lock=off \
-smp 1,sockets=1,cores=1,threads=1 \
-uuid 6a6f45fd-0f70-4467-bac9-43991d8c565f \
-no-user-config \
-nodefaults \
-chardev socket,id=charmonitor,fd=35,server,nowait \
-mon chardev=charmonitor,id=monitor,mode=control \
-rtc base=utc \
-no-shutdown \
-boot strict=on \
-device pcie-root-port,port=0x8,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x1 \
-device pcie-root-port,port=0x9,chassis=2,id=pci.2,bus=pcie.0,addr=0x1.0x1 \
-device pcie-root-port,port=0xa,chassis=3,id=pci.3,bus=pcie.0,addr=0x1.0x2 \
-device pcie-root-port,port=0xb,chassis=4,id=pci.4,bus=pcie.0,addr=0x1.0x3 \
-device pcie-root-port,port=0xc,chassis=5,id=pci.5,bus=pcie.0,addr=0x1.0x4 \
-device pcie-root-port,port=0xd,chassis=6,id=pci.6,bus=pcie.0,addr=0x1.0x5 \
-device pcie-pci-bridge,id=pci.7,bus=pci.1,addr=0x0 \
-device pcie-root-port,port=0xe,chassis=8,id=pci.8,bus=pcie.0,addr=0x1.0x6 \
-device pcie-root-port,port=0xf,chassis=9,id=pci.9,bus=pcie.0,addr=0x1.0x7 \
-device qemu-xhci,id=usb,bus=pci.5,addr=0x0 \
-device virtio-scsi-pci,id=scsi0,num_queues=1,bus=pcie.0,addr=0x9 \
-device virtio-serial-pci,id=virtio-serial0,bus=pci.6,addr=0x0 \
-blockdev '{"driver":"file","filename":"/mnt/554c497b-2903-3ea6-8f13-cfe258e24c24/658443d0-d38e-4925-94f5-28e6372fae2b","node-name":"libvirt-3-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-3-format","read-only":true,"discard":"unmap","cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-3-storage","backing":null}' \
-blockdev '{"driver":"file","filename":"/mnt/554c497b-2903-3ea6-8f13-cfe258e24c24/fa3a600d-d7cf-4342-af92-b368a536c886","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-2-format","read-only":false,"discard":"unmap","cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-2-storage","backing":"libvirt-3-format"}' \
-device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,device_id=fa3a600dd7cf4342af92,drive=libvirt-2-format,id=scsi0-0-0-0,bootindex=2,write-cache=on,serial=fa3a600dd7cf4342af92 \
-blockdev '{"driver":"file","filename":"/usr/share/cloudstack-common/vms/systemvm.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}' \
-blockdev '{"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"}' \
-device scsi-cd,bus=scsi0.0,channel=0,scsi-id=0,lun=2,device_id=drive-scsi0-0-0-2,drive=libvirt-1-format,id=scsi0-0-0-2,bootindex=1 \
-netdev tap,fd=37,id=hostnet0,vhost=on,vhostfd=41 \
-device virtio-net-pci,netdev=hostnet0,id=net0,mac=0e:00:a9:fe:ba:fe,bus=pci.2,addr=0x0,rombar=0,romfile= \
-netdev tap,fd=44,id=hostnet1,vhost=on,vhostfd=46 \
-device virtio-net-pci,netdev=hostnet1,id=net1,mac=1e:00:33:00:00:01,bus=pci.3,addr=0x0,rombar=0,romfile= \
-netdev tap,fd=47,id=hostnet2,vhost=on,vhostfd=50 \
-device virtio-net-pci,netdev=hostnet2,id=net2,mac=1e:00:c8:00:00:05,bus=pci.4,addr=0x0,rombar=0,romfile= \
-chardev pty,id=charserial0 \
-serial chardev:charserial0 \
-chardev socket,id=charchannel0,fd=51,server,nowait \
-device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 \
-device usb-tablet,id=input0,bus=usb.0,port=1 \
-device usb-kbd,id=input1,bus=usb.0,port=2 \
-device usb-mouse,id=input2,bus=usb.0,port=3 \
-vnc 172.31.36.107:0,password \
-device virtio-gpu-pci,id=video0,max_outputs=1,bus=pci.8,addr=0x0 \
-device i6300esb,id=watchdog0,bus=pci.7,addr=0x1 \
-watchdog-action none \
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
-msg timestamp=on
2020-09-18 02:06:22.958+0000: Domain id=1 is tainted: high-privileges
2020-09-18 02:06:22.958+0000: Domain id=1 is tainted: host-cpu
char device redirected to /dev/pts/1 (label charserial0)
2020-09-18 02:07:04.974+0000: Domain id=1 is tainted: custom-ga-command
```
usage.log shows
```
2020-09-18 18:31:46,139 WARN  [commons.dbcp2.PoolingDataSource] (main:null) (logid:) PoolableConnectionFactory not linked to pool. Calling setPool() to fix the configuration.
2020-09-18 18:31:46,143 WARN  [db.Transaction.Transaction] (main:null) (logid:) Unable to load db configuration, using defaults with 5 connections. Falling back on assumed datasource on localhost:3306 using username:password=cloud:cloud. Please check your configuration
java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.cloud.utils.db.TransactionLegacy.initDataSource(TransactionLegacy.java:1032)
	at com.cloud.utils.db.TransactionLegacy.<clinit>(TransactionLegacy.java:1010)
	at com.cloud.utils.db.TransactionContextBuilder.interceptStart(TransactionContextBuilder.java:49)
	at com.cloud.utils.component.ComponentInstantiationPostProcessor$InterceptorDispatcher.intercept(ComponentInstantiationPostProcessor.java:116)
	at com.cloud.usage.dao.UsageDaoImpl_EnhancerByCloudStack_7a787d5e.createPartialSelectSql(<generated>)
	at com.cloud.utils.db.GenericDaoBase.<init>(GenericDaoBase.java:235)
	at com.cloud.usage.dao.UsageDaoImpl.<init>(UsageDaoImpl.java:76)
	at com.cloud.usage.dao.UsageDaoImpl_EnhancerByCloudStack_7a787d5e.<init>(<generated>)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:291)
	at net.sf.cglib.proxy.Enhancer$EnhancerFactoryData.newInstance(Enhancer.java:448)
	at net.sf.cglib.proxy.Enhancer.nextInstance(Enhancer.java:700)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:298)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:305)
	at com.cloud.utils.component.ComponentInstantiationPostProcessor.postProcessBeforeInstantiation(ComponentInstantiationPostProcessor.java:92)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1141)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:506)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
	at com.cloud.usage.UsageServer.start(UsageServer.java:52)
	at com.cloud.usage.UsageServer.main(UsageServer.java:41)
```

**Comment by DaanHoogland** [comment]
this seems to be a DB connection problem, @dony71 . Can you check?

**Comment by dony71** [comment]
M> this seems to be a DB connection problem, @dony71 . Can you check?

Will you clarify more what do you mean with DB connection problem?
Mysql is stored in same host where management installed
Also system vm up and running without any issue
proxy vm should be the same system vm image, right ?

**Comment by dony71** [comment]
below /var/log/cloud/cloud.out inside system vm
```
2020-09-21 22:48:10,016 INFO  [cloud.agent.AgentShell] (main:null) Agent started
2020-09-21 22:48:10,106 INFO  [cloud.agent.AgentShell] (main:null) Implementation Version is 4.14.0.0
2020-09-21 22:48:10,126 INFO  [cloud.agent.AgentShell] (main:null) agent.properties found at /usr/local/cloud/systemvm/conf/agent.properties
2020-09-21 22:48:10,407 INFO  [cloud.agent.AgentShell] (main:null) Defaulting to using properties file for storage
2020-09-21 22:48:10,442 INFO  [cloud.agent.AgentShell] (main:null) Defaulting to the constant time backoff algorithm
2020-09-21 22:48:10,722 INFO  [cloud.utils.LogUtils] (main:null) log4j configuration found at /usr/local/cloud/systemvm/conf/log4j-cloud.xml
2020-09-21 22:48:10,976 INFO  [cloud.agent.AgentShell] (main:null) Using default Java settings for IPv6 preference for agent connection
2020-09-21 22:48:12,278 INFO  [cloud.agent.Agent] (main:null) id is 4
2020-09-21 22:48:12,290 WARN  [storage.resource.NfsSecondaryStorageResource] (main:null) There is no storageip in /proc/cmdline, something wrong!
2020-09-21 22:48:12,503 INFO  [storage.resource.NfsSecondaryStorageResource] (main:null) config_ssl.sh found in /usr/local/cloud/systemvm/config_ssl.sh
2020-09-21 22:48:12,510 INFO  [storage.resource.NfsSecondaryStorageResource] (main:null) config_auth.sh found in /usr/local/cloud/systemvm/config_auth.sh
2020-09-21 22:48:12,516 INFO  [storage.resource.NfsSecondaryStorageResource] (main:null) _configIpFirewallScr found in /usr/local/cloud/systemvm/ipfirewall.sh
2020-09-21 22:48:12,541 INFO  [storage.resource.NfsSecondaryStorageResource] (main:null) Secondary storage runs in role templateProcessor
2020-09-21 22:48:13,333 ERROR [storage.resource.NfsSecondaryStorageResource] (main:null) Couldn't cast null to integer
2020-09-21 22:48:13,371 INFO  [storage.template.DownloadManagerImpl] (main:null) DownloadManager: starting additional services since we are inside system vm
2020-09-21 22:48:13,379 ERROR [storage.resource.NfsSecondaryStorageResource] (main:null) Couldn't cast null to integer
2020-09-21 22:48:14,890 INFO  [storage.template.DownloadManagerImpl] (main:null) listvmtmplt.sh found in /usr/local/cloud/systemvm/scripts/storage/secondary/listvmtmplt.sh
2020-09-21 22:48:14,918 INFO  [storage.template.DownloadManagerImpl] (main:null) createtmplt.sh found in /usr/local/cloud/systemvm/scripts/storage/secondary/createtmplt.sh
2020-09-21 22:48:14,940 INFO  [storage.template.DownloadManagerImpl] (main:null) listvolume.sh found in /usr/local/cloud/systemvm/scripts/storage/secondary/listvolume.sh
2020-09-21 22:48:14,958 INFO  [storage.template.DownloadManagerImpl] (main:null) createvolume.sh found in /usr/local/cloud/systemvm/scripts/storage/secondary/createvolume.sh
2020-09-21 22:48:15,094 INFO  [storage.template.UploadManagerImpl] (main:null) UploadManager: starting additional services since we are inside system vm
2020-09-21 22:48:15,492 INFO  [cloud.agent.Agent] (main:null) Agent [id = 4 : type = NfsSecondaryStorageResource : zone = 1 : pod = 1 : workers = 5 : host = 172.31.36.107 : port = 8250
2020-09-21 22:48:15,636 INFO  [utils.nio.NioClient] (main:null) Connecting to 172.31.36.107:8250
2020-09-21 22:48:15,674 INFO  [utils.nio.Link] (main:null) Conf file found: /usr/local/cloud/systemvm/conf/agent.properties
2020-09-21 22:48:20,506 INFO  [utils.nio.NioClient] (main:null) SSL: Handshake done
2020-09-21 22:48:20,524 INFO  [utils.nio.NioClient] (main:null) Connected to 172.31.36.107:8250
2020-09-21 22:48:20,883 INFO  [cloud.serializer.GsonHelper] (Agent-Handler-1:null) Default Builder inited.
2020-09-21 22:48:21,092 INFO  [cloud.agent.Agent] (Agent-Handler-2:null) Proccess agent startup answer, agent id = 0
2020-09-21 22:48:21,105 INFO  [cloud.agent.Agent] (Agent-Handler-2:null) Set agent id 0
2020-09-21 22:48:21,183 INFO  [cloud.agent.Agent] (Agent-Handler-2:null) Startup Response Received: agent id = 0
2020-09-21 22:48:21,341 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-2:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:48:21,460 WARN  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-2:null) addRouteToInternalIp: unable to determine same subnet: _eth1ip=null, dest ip=172.31.36.107, _eth1mask=null
2020-09-21 22:48:21,556 WARN  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-2:null) Error in configuring route to internal ip err=Error: inet address is expected rather than "null".
2020-09-21 22:48:21,560 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-2:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:48:22,806 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-2:null) created a thread to start post upload server
2020-09-21 22:48:23,150 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-5:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:48:23,309 INFO  [storage.template.DownloadManagerImpl] (agentRequest-Handler-5:null) found 0 volumes[]
2020-09-21 22:48:23,383 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-1:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:48:23,474 INFO  [handler.logging.LoggingHandler] (nioEventLoopGroup-2-1:null) [id: 0x8cb5e78f] REGISTERED
2020-09-21 22:48:23,498 INFO  [handler.logging.LoggingHandler] (nioEventLoopGroup-2-1:null) [id: 0x8cb5e78f] BIND(0.0.0.0/0.0.0.0:8210)
2020-09-21 22:48:23,522 INFO  [storage.resource.NfsSecondaryStorageResource] (Thread-1:null) Started post upload server on port 8210 with 15 workers
2020-09-21 22:48:23,539 INFO  [handler.logging.LoggingHandler] (nioEventLoopGroup-2-1:null) [id: 0x8cb5e78f, L:/0.0.0.0:8210] ACTIVE
2020-09-21 22:48:23,610 INFO  [storage.template.DownloadManagerImpl] (agentRequest-Handler-1:null) found 2 templates[/mnt/SecStorage/724a17aa-db70-33b6-be45-3d1cd28e116d/template/tmpl/1/4/, /mnt/SecStorage/724a17aa-db70-33b6-be45-3d1cd28e116d/template/tmpl/1/3/658443d0-d38e-4925-94f5-28e6372fae2b.qcow2]
2020-09-21 22:48:23,641 WARN  [storage.template.DownloadManagerImpl] (agentRequest-Handler-1:null) Post download installation was not completed for /mnt/SecStorage/724a17aa-db70-33b6-be45-3d1cd28e116d/template/tmpl/1/4
2020-09-21 22:48:24,121 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-2:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:48:24,144 INFO  [cloud.agent.Agent] (agentRequest-Handler-3:null) Processing agent ready command, agent id = 4
2020-09-21 22:48:24,148 INFO  [cloud.agent.Agent] (agentRequest-Handler-3:null) Set agent id 4
2020-09-21 22:48:24,212 INFO  [cloud.agent.Agent] (agentRequest-Handler-3:null) Ready command is processed for agent id = 4
2020-09-21 22:48:24,296 INFO  [cloud.agent.Agent] (agentRequest-Handler-4:null) Processing agent ready command, agent id = 4
2020-09-21 22:48:24,298 INFO  [cloud.agent.Agent] (agentRequest-Handler-4:null) Set agent id 4
2020-09-21 22:48:24,309 INFO  [cloud.agent.Agent] (agentRequest-Handler-4:null) Processed new management server list: 172.31.36.107@static
2020-09-21 22:48:24,319 INFO  [cloud.agent.Agent] (agentRequest-Handler-4:null) Ready command is processed for agent id = 4
2020-09-21 22:48:37,840 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-5:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:49:38,158 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-1:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:50:38,355 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-3:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
2020-09-21 22:51:38,575 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-4:null) Determined host 172.31.36.107 corresponds to IP 172.31.36.107
```

**Comment by dony71** [comment]
close this issue since DNS related issue
