### ISSUE TITLE
CS simulator docker hub image issues

### ISSUE THREAD

**Issue by Cloud-Mak** [apache/cloudstack#4347]
Hi all,
Getting below error while I tried running ACS GUI from CS simulator docker hub image in docker

```
HTTP ERROR: 503
Problem accessing /client/. Reason:
 Service UnavailablePowered by Jetty:// 

```
While checking the docker container logs, I could see lines indicating connection and authentication issues while connecting to DB. Detailed logs are in the link below.
https://gist.githubusercontent.com/Cloud-Mak/a09766d752f0688885b2416e4a9925c8/raw/bb418c87394e267f4b867bde8697b760c5924874/gistfile1.txt

Can people managing this image please look into this and fix it or give possible workaround? 

--
Makrand

**Comment by ravening** [comment]
Can you mention the steps which you followed to run the docker image?
First you need to start the simulator docker container. Then run the marvin docker to setup zone. Then you will be able to access the ui. 

I have run this several times and not encountered this issue so far

**Comment by Cloud-Mak** [comment]
Hello Rakesh,

I am following steps mentioned in description of image on Docker hub - https://hub.docker.com/r/cloudstack/simulator
From descrition - it looks like just using **doker run** is all you need to setup. Anywho, I even tried to run marvin DC setup step. Getting errors there as well. Check below logs and step. 
```
**makrand@mint-gl63:/tmp$ docker run -d --name cloudstack -d -p 8080:8080 cloudstack/simulator**

**makrand@mint-gl63:/tmp$ docker exec -it cloudstack bash**

**root@06d293d9a407:~# python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/advanced.cfg**

==== Log Folder Path: /tmp/MarvinLogs/DeployDataCenter__Sep_25_2020_16_14_32_1VH78N. All logs will be available here ====

=== TestClient Creation Failed===

root@06d293d9a407:~# cat /tmp/MarvinLogs/DeployDataCenter__Sep_25_2020_16_14_32_1VH78N/failed_plus_exceptions.txt 

**root@06d293d9a407:~# cat /tmp/MarvinLogs/DeployDataCenter__Sep_25_2020_16_14_32_1VH78N/runinfo.txt** 
2020-09-25 16:14:32,914 - DEBUG - Parsing Test data successful
2020-09-25 16:14:32,914 - DEBUG - Payload: {'account': 'admin', 'command': 'listUsers', 'response': 'json'}
2020-09-25 16:14:32,914 - DEBUG - ========Sending GET Cmd : listUsers=======
2020-09-25 16:14:32,916 - ERROR - __sendGetReqToCS : Exception Occurred: HTTPConnectionPool(host='localhost', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8de863ea10>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackConnection.py", line 189, in __sendGetReqToCS
    verify=self.httpsFlag)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8de863ea10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-09-25 16:14:32,917 - ERROR - marvinRequest : CmdName: <marvin.cloudstackAPI.listUsers.listUsersCmd object at 0x7f8de862d350> Exception: ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackConnection.py", line 364, in marvinRequest\n    raise self.__lastError\n', "ConnectionError: HTTPConnectionPool(host='localhost', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8de863ea10>: Failed to establish a new connection: [Errno 111] Connection refused',))\n"]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackConnection.py", line 364, in marvinRequest
    raise self.__lastError
ConnectionError: HTTPConnectionPool(host='localhost', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8de863ea10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-09-25 16:14:32,918 - ERROR -  Exception Occurred Under __createApiClient: ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackTestClient.py", line 144, in __createApiClient\n    list_user_res = self.__apiClient.listUsers(list_user)\n', '  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 2479, in listUsers\n    response = self.connection.marvinRequest(command, response_type=response, method=method)\n', '  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest\n    raise e\n', "ConnectionError: HTTPConnectionPool(host='localhost', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8de863ea10>: Failed to establish a new connection: [Errno 111] Connection refused',))\n"]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackTestClient.py", line 144, in __createApiClient
    list_user_res = self.__apiClient.listUsers(list_user)
  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 2479, in listUsers
    response = self.connection.marvinRequest(command, response_type=response, method=method)
  File "/usr/local/lib/python2.7/dist-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest
    raise e
ConnectionError: HTTPConnectionPool(host='localhost', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8de863ea10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-09-25 16:14:32,918 - ERROR - ==== Test Client Creation Failed ====
```
Am I overlooking anything?

I am on docker 19.0.3 and can see cloudstack container running.

**Comment by ravening** [comment]
I usually run the following commands

Start the simulator
```
docker run --name simulator -p 8080:8080 -d cloudstack/simulator
```


Start the marvin
```
docker run -ti --rm --name marvin --link simulator:8096 cloudstack/marvin
```

Deploy zone using marvin
```
docker run -ti --rm --link simulator:8096 cloudstack/marvin python /marvin/marvin/deployDataCenter.py -i /marvin/dev/advanced.cfg
```

if the above command fails then I usually get the ip of the `simulator` container and that in `mgtSvr` `dbSvr` section in `/marvin/dev/advanced.cfg` and run again

**Comment by Cloud-Mak** [comment]
@ravening 
Just cross checking.
1. So basically you're running two seperate containers simulator and marvin.  

2. Marvin container is being linked to simulator contianer while its getting created. (not able to understand the need to link two...doesn't docker have networking out of box?)

3. Finally initiatlizing the python script using "your command" from host OS.

4. (if above fails) Edit the mgtSvr and dbSvr values in /marvin/dev/advanced.cfg on Marvin container and tun the python "deployDataCenter.py" script on Marvin container.

Even After doing so - I am getting same error.

```
root@4034e81431d0:/marvin/dev# python /marvin/marvin/deployDataCenter.py -i /marvin/dev/advanced.cfg

==== Log Folder Path: /tmp/MarvinLogs/DeployDataCenter__Sep_29_2020_12_19_41_KKF3WZ. All logs will be available here ====

=== TestClient Creation Failed===

root@4034e81431d0:/tmp/MarvinLogs/DeployDataCenter__Sep_29_2020_12_19_41_KKF3WZ# cat runinfo.txt 
2020-09-29 12:19:41,884 - DEBUG - Parsing Test data successful
2020-09-29 12:19:41,885 - DEBUG - Payload: {'account': 'admin', 'command': 'listUsers', 'response': 'json'}
2020-09-29 12:19:41,885 - DEBUG - ========Sending GET Cmd : listUsers=======
2020-09-29 12:19:41,886 - ERROR - __sendGetReqToCS : Exception Occurred: HTTPConnectionPool(host='172.17.0.3', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11e4974950>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 189, in __sendGetReqToCS
    verify=self.httpsFlag)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='172.17.0.3', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11e4974950>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-09-29 12:19:41,887 - ERROR - marvinRequest : CmdName: <marvin.cloudstackAPI.listUsers.listUsersCmd object at 0x7f11e4974050> Exception: ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 364, in marvinRequest\n    raise self.__lastError\n', "ConnectionError: HTTPConnectionPool(host='172.17.0.3', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11e4974950>: Failed to establish a new connection: [Errno 111] Connection refused',))\n"]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 364, in marvinRequest
    raise self.__lastError
ConnectionError: HTTPConnectionPool(host='172.17.0.3', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11e4974950>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-09-29 12:19:41,888 - ERROR -  Exception Occurred Under __createApiClient: ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackTestClient.py", line 144, in __createApiClient\n    list_user_res = self.__apiClient.listUsers(list_user)\n', '  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 2605, in listUsers\n    response = self.connection.marvinRequest(command, response_type=response, method=method)\n', '  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest\n    raise e\n', "ConnectionError: HTTPConnectionPool(host='172.17.0.3', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11e4974950>: Failed to establish a new connection: [Errno 111] Connection refused',))\n"]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackTestClient.py", line 144, in __createApiClient
    list_user_res = self.__apiClient.listUsers(list_user)
  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 2605, in listUsers
    response = self.connection.marvinRequest(command, response_type=response, method=method)
  File "/usr/local/lib/python2.7/site-packages/marvin/cloudstackConnection.py", line 379, in marvinRequest
    raise e
ConnectionError: HTTPConnectionPool(host='172.17.0.3', port=8096): Max retries exceeded with url: /client/api?account=admin&command=listUsers&response=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11e4974950>: Failed to establish a new connection: [Errno 111] Connection refused',))
2020-09-29 12:19:41,888 - ERROR - ==== Test Client Creation Failed ====
root@4034e81431d0:/tmp/MarvinLogs/DeployDataCenter__Sep_29_2020_12_19_41_KKF3WZ# 

```

I just want to give GUI demo to someone....not intested in reinventing the wheel here.

**Comment by Cloud-Mak** [comment]
Installed the ping on Marvin to see if I can reach simulator by its name and IP. 

root@4034e81431d0:/tmp/MarvinLogs# ping simulator
PING 8096 (172.17.0.3) 56(84) bytes of data.
64 bytes from 8096 (172.17.0.3): icmp_seq=1 ttl=64 time=0.131 ms
64 bytes from 8096 (172.17.0.3): icmp_seq=2 ttl=64 time=0.076 ms
^C
--- 8096 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1031ms
rtt min/avg/max/mdev = 0.076/0.103/0.131/0.029 ms
root@4034e81431d0:/tmp/MarvinLogs# ping 172.17.0.3
PING 172.17.0.3 (172.17.0.3) 56(84) bytes of data.
64 bytes from 172.17.0.3: icmp_seq=1 ttl=64 time=0.132 ms
64 bytes from 172.17.0.3: icmp_seq=2 ttl=64 time=0.097 ms
^C
--- 172.17.0.3 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1014ms
rtt min/avg/max/mdev = 0.097/0.114/0.132/0.020 ms

**Comment by ravening** [comment]
> Installed the ping on Marvin to see if I can reach simulator by its name and IP. 
> 
> 
> 
> > root@4034e81431d0:/tmp/MarvinLogs# ping simulator
> 
> > PING 8096 (172.17.0.3) 56(84) bytes of data.
> 
> > 64 bytes from 8096 (172.17.0.3): icmp_seq=1 ttl=64 time=0.131 ms
> 
> > 64 bytes from 8096 (172.17.0.3): icmp_seq=2 ttl=64 time=0.076 ms
> 
> > ^C
> 
> > --- 8096 ping statistics ---
> 
> > 2 packets transmitted, 2 received, 0% packet loss, time 1031ms
> 
> > rtt min/avg/max/mdev = 0.076/0.103/0.131/0.029 ms
> 
> > root@4034e81431d0:/tmp/MarvinLogs# ping 172.17.0.3
> 
> > PING 172.17.0.3 (172.17.0.3) 56(84) bytes of data.
> 
> > 64 bytes from 172.17.0.3: icmp_seq=1 ttl=64 time=0.132 ms
> 
> > 64 bytes from 172.17.0.3: icmp_seq=2 ttl=64 time=0.097 ms
> 
> > ^C
> 
> 
> 
> > 
> 
> > --- 172.17.0.3 ping statistics ---
> 
> > 2 packets transmitted, 2 received, 0% packet loss, time 1014ms
> 
> > rtt min/avg/max/mdev = 0.097/0.114/0.132/0.020 ms
> 
> 
> 
> But seems I can't telnet to simulator on 8096 from Marvin
> 
> 
> 
> > root@4034e81431d0:/tmp/MarvinLogs# telnet 172.17.0.3 8096
> 
> > Trying 172.17.0.3...
> 
> > telnet: Unable to connect to remote host: Connection refused
> 
> > root@4034e81431d0:/tmp/MarvinLogs# telnet 172.17.0.3 8080
> 
> > Trying 172.17.0.3...
> 
> > Connected to 172.17.0.3.
> 
> > Escape character is '^]'.
> 
> > 
> 
> 
> 
> Here is how docker ps -a looks like 
> 
> 
> 
> ```
> 
> makrand@mint-gl63:~$ docker ps -a
> 
> CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                      NAMES
> 
> 4034e81431d0        cloudstack/marvin                                     "/bin/sh -c /bin/bash"   36 minutes ago      Up 36 minutes                                                  marvin
> 
> fc86aecc33bd        cloudstack/simulator                                  "/usr/bin/supervisord"   About an hour ago   Up About an hour    0.0.0.0:8080->8080/tcp, 8096/tcp           simulator
> 
> 593188cd5e2c        docker.elastic.co/kibana/kibana:7.8.0                 "/usr/local/bin/dumb…"   12 days ago         Up About an hour    0.0.0.0:5601->5601/tcp                     kibana
> 
> 47ba9727f41e        docker.elastic.co/elasticsearch/elasticsearch:7.8.0   "/tini -- /usr/local…"   12 days ago         Up About an hour    0.0.0.0:9200->9200/tcp, 9300/tcp           elasticsearch
> 
> 82ad0cb6df32        rancher/rancher                                       "entrypoint.sh"          12 days ago         Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   rancher
> 
> 
> 
> ```
> 
> 

I will run this in my setup and share you the result..

BTW, if you want ready made cloudstack with advanced zone already installed, you can refer to Dockerfile present in https://github.com/ravening/Cloudstack-Docker

**Comment by andrijapanicsb** [comment]
hi guys - may I kindly ask that we use mailing list user@ for support issues - and not GitHub - it will become garbage yard if we continue to do to. Thanks

**Comment by lmhetz** [comment]
I have a question for ravening, I have been trying to get the advanced zone docker working, and it tells me the repository does not exist.
What is the appropriate mailing list?

**Comment by DaanHoogland** [comment]
@lmhetz either dev@ or users@cloudstack.apache.org
