### ISSUE TITLE
JsonSyntaxException when creating API command response

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#4355]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
master/4.15
~~~

##### CONFIGURATION

~~~
N/A
~~~
##### OS / ENVIRONMENT

~~~
N/A
~~~

##### SUMMARY

Issues when API command response is generated. Exception at the log and API command result. The command works fine, but to whom using the API it seems to have failed.

##### STEPS TO REPRODUCE

~~~
Call an API command, e.g. prepareHostMaintenance or cancelHostMaintenance
~~~

##### EXPECTED RESULTS

~~~
Proper API response and no log exceptions on the management node
~~~

##### ACTUAL RESULTS

1. When calling API command via CloudMonkey:
```
> prepare hostformaintenance id=host-id
Error: async API failed for job b43bbdbf-fe65-436c-9e7e-7c48e4fbfea1
```

2. log at the management node:
```
2020-09-29 16:55:15,853 DEBUG [c.c.a.t.Request] (API-Job-Executor-4:ctx-4d783c5f job-55326 ctx-7d98f674) (logid:b43bbdbf) Seq 24-3700551518814994444: Received:  { Ans: , MgmtId: 2482717785957, via: 24(n06.2019.cldin.net), Ver: v1, Flags: 110, { MaintainAnswer } }
2020-09-29 16:55:15,874 DEBUG [c.c.r.ResourceState] (API-Job-Executor-4:ctx-4d783c5f job-55326 ctx-7d98f674) (logid:b43bbdbf) Resource state update: [id = 24; name = n06.2019.cldin.net; old state = Enabled; event = AdminAskMaintenance; new state = PrepareForMaintenance]
2020-09-29 16:55:15,917 DEBUG [c.c.r.ResourceManagerImpl] (API-Job-Executor-4:ctx-4d783c5f job-55326 ctx-7d98f674) (logid:b43bbdbf) Sent resource event EVENT_PREPARE_MAINTENANCE_AFTER to listener CapacityManagerImpl
2020-09-29 16:55:15,950 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-4:ctx-4d783c5f job-55326) (logid:b43bbdbf) Unexpected exception while executing org.apache.cloudstack.api.command.admin.host.PrepareForMaintenanceCmd
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object near assword":"c*****},"resourcestate":"Prepa
        at com.google.gson.Streams.parse(Streams.java:51)
        at com.google.gson.JsonParser.parse(JsonParser.java:83)
        at com.google.gson.JsonParser.parse(JsonParser.java:58)
        at com.google.gson.JsonParser.parse(JsonParser.java:44)
        at com.cloud.utils.HumanReadableJson.addElement(HumanReadableJson.java:52)
        at com.cloud.utils.HumanReadableJson.getHumanReadableBytesJson(HumanReadableJson.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl.convertHumanReadableJson(AsyncJobManagerImpl.java:352)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl.completeAsyncJob(AsyncJobManagerImpl.java:262)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:111)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:615)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:563)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object near assword":"c*****},"resourcestate":"Prepa
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1111)
        at com.google.gson.stream.JsonReader.nextInObject(JsonReader.java:737)
        at com.google.gson.stream.JsonReader.quickPeek(JsonReader.java:379)
        ... 24 more
2020-09-29 16:55:15,955 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-4:ctx-4d783c5f job-55326) (logid:b43bbdbf) Complete async job-55326, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"530","errortext":"com.google.gson.stream.MalformedJsonException: Unterminated object near assword":"c*****},"resourcestate":"Prepa"}
```

Note that the host got in the Maintenance state as expected and the issue is related only to the response.

**Comment by rhtyd** [comment]
@GabrielBrascher are you working on a fix? or can we triage that to someone else? thanks

**Comment by GabrielBrascher** [comment]
@rhtyd just started to look at this. Do you have any idea of what is causing it? Have anyone seen this as well?

**Comment by rhtyd** [comment]
cc @borisstoyanov @andrijapanicsb @vladimirpetrov @DaanHoogland @shwstppr @harikrishna-patnala @nvazquez

**Comment by DaanHoogland** [comment]
@rhtyd @GabrielBrascher it looks like the double quote (") at the end of the password value is missing. probably a bug in the password filtering code. (just a quick assessment, sorry if i just kicked in an open door)

**Comment by GabrielBrascher** [comment]
@rhtyd I discovered what caused this issue and how to reproduce.

It happens only with Hosts that have an OutOfBand driver (e.g. IPMI or Redfish) enabled.

The host password is passed on the response as _first letter +  "****"_. For instance, a password "password" then it is set as "p****" on the response object. More details at [OutOfBandManagementResponse.java#L98](https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/api/src/main/java/org/apache/cloudstack/api/response/OutOfBandManagementResponse.java#L98)

Code:
```this.setPassword(outOfBandManagementConfig.getPassword().substring(0, 1) + "****");```

However, the String that represents the Host response JSON object is being processed as:

```
..."outofbandmanagement":{"powerstate":"On","enabled":true,"driver":"redfish","address":"oob-kvm-node.address.net","port":"80","username":"root","password":"p*****}....
```

Probably something related to special character handling that resulted on the lack of `"` on the String that is processed into a JSON object. I will be testing a few options to fix it.

Keep you updated.

**Comment by GabrielBrascher** [comment]
@DaanHoogland you are right. I have a hunch of the cause but I still need to debug it.

_For some odd reason, GitHub sometimes does not update issues/PR messages to me, after I answered and refreshed the page then your answer appeared to me._

**Comment by GabrielBrascher** [comment]
Connected via remote debug on the JVM I was able to check the workflow. The password for Out of band response is obfuscated at _OutOfBandManagementResponse.java#L98_; then, the workflow will make that password as input to  _obfuscatePassword_ .

_constructor at OutOfBandManagementResponse.java#L98_
https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/api/src/main/java/org/apache/cloudstack/api/response/OutOfBandManagementResponse.java#L98

_obfuscatePassword method at AsyncJobManagerImpl.java#L478_
https://github.com/apache/cloudstack/blob/0f3f2a09370a18301db28ec3d28efe746b6437c9/framework/jobs/src/main/java/org/apache/cloudstack/framework/jobs/impl/AsyncJobManagerImpl.java#L478

The _obfuscatePassword_ method removes `"` and causes the JSON issue.

@DaanHoogland I am curious, why do we log password? Even knowing that it is obfuscated I am not sure of why we shuld log it.

With that said, I see two solutions for this bug:
1. fix _obfuscatePassword_, o
2. remove password from Host responses and log messages.

**Comment by DaanHoogland** [comment]
:D or three: return '"password": "<obfuscated>"' for any input :)
No real pref but one consideration: obfuscatePassword may be used in other places and all other results of the bug are not known yet. I think option 1 is your safest bet. maybe in combination with three 👯

**Comment by GabrielBrascher** [comment]
@DaanHoogland @rhtyd I've created PR #4387. The PR has 2 commits, the first contains the fix; the second commit deletes commented lines on the test class and adds JUnit tests for _obfuscatePassword_.
