### ISSUE TITLE
cloudstack management server error, /client/api 404 

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#4921]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
branch 4.15
~~~

##### CONFIGURATION

~~~
.basic network
~~~

##### OS / ENVIRONMENT

~~~
Centos7.4
~~~

##### STEPS TO REPRODUCE

~~~
 when I restart the management server use command as follows

 "service cloudstack-management restart"
~~~

##### EXPECTED RESULTS

~~~
 it can work
~~~

##### ACTUAL RESULTS

~~~
 login failed, api 404 not found.
but management-server process is running.
~~~

![image](https://user-images.githubusercontent.com/20500978/114839661-9adc7c00-9e08-11eb-8f2f-8c06840d58d3.png)

~~~
 the management server It did restart, but there are only two logs saw the screenshot below.
~~~
![image](https://user-images.githubusercontent.com/20500978/114839864-d5deaf80-9e08-11eb-90dc-dcec091f90e0.png)

~~~
when I saw the cloudstack-management.err, There is no useful information
~~~
![image](https://user-images.githubusercontent.com/20500978/114840336-4a195300-9e09-11eb-8d44-08e0ff946fbe.png)

~~~
then I login in use new UI.
~~~
![image](https://user-images.githubusercontent.com/20500978/114839985-f0188d80-9e08-11eb-88a3-cfee7dd0ac90.png)
![image](https://user-images.githubusercontent.com/20500978/114840011-f870c880-9e08-11eb-9365-29f8472af3da.png)
![image](https://user-images.githubusercontent.com/20500978/114840049-ff97d680-9e08-11eb-9731-c2c35650c2c3.png)

~~~
I don't know what happend, who can tell me how to find the point of the error. 
thanks 
~~~

**Comment by rhtyd** [comment]
Hi @staySober thanks for reporting - can you share:
- if you're able to access the legacy UI at `<hostname/domain/ip>:8080/client/legacy`?
- - Can you see any activity other than what you've pasted on the management server logs at `/var/log/cloudstack/management/management-server.log`? Can you share those logs with us?
- Is that a fresh/new installation or an upgraded environment?
- Is there a load balancer/proxy in between your browser and management server?

**Comment by rhtyd** [comment]
cc @shwstppr @Pearl1594 @Spaceman1984 @DaanHoogland

**Comment by staySober** [comment]
Is that a new installation， It operated normally for several days
on the legacy UI,  It seems to have the same mistake
![image](https://user-images.githubusercontent.com/20500978/114847986-d9763480-9e10-11eb-8ef9-b1d17c76fc36.png)

when I execute 'service cloudstack-management restart ' I just saw two logs again
![image](https://user-images.githubusercontent.com/20500978/114848167-00cd0180-9e11-11eb-9519-5ac64425e313.png)
So I was so confused that I didn't know where to start

This looks like a problem with the backend service. I guest

before I restart the management server , I just edit the global config 'secstorage.allowed.internal.sites=0.0.0.0/0'
I know the value '0.0.0.0/0' is mistake
when I restart the management server, It's not working properly. so I tried modifying this configuration directly from the database. But the situation has not changed
![image](https://user-images.githubusercontent.com/20500978/114848803-aaac8e00-9e11-11eb-8aa6-1ccd36182b55.png)


![image](https://user-images.githubusercontent.com/20500978/114848817-ae401500-9e11-11eb-87a3-91c7b3e58413.png)

at lastest, I remove the value , but server Still not normal

**Comment by rhtyd** [comment]
Can you share the Java JRE version and the mysql jar that maybe in class path. I saw some error around that. From logs it seems your management server is stuck.

**Comment by staySober** [comment]
sure，thank for you help me 

jdk version : openjdk 11.0.10
![image](https://user-images.githubusercontent.com/20500978/114849605-7f766e80-9e12-11eb-837a-986d3a67b0b3.png)

mysql version 5.6.51
![image](https://user-images.githubusercontent.com/20500978/114849718-9d43d380-9e12-11eb-995b-11c05a767412.png)

mysql-connector-java 8.0.19
![image](https://user-images.githubusercontent.com/20500978/114849885-c9f7eb00-9e12-11eb-90a0-db00d574f682.png)

If the information is insufficient, I will continue to add

**Comment by staySober** [comment]
i get the info from jstack as follows

```
jstack  12831
2021-04-16 10:45:32
Full thread dump OpenJDK 64-Bit Server VM (11.0.10+9-LTS mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fac68001c70, length=23, elements={
0x00007fac94015000, 0x00007fac94054800, 0x00007fac94057000, 0x00007fac9405d000,
0x00007fac9405f000, 0x00007fac94061000, 0x00007fac94063800, 0x00007fac94065800,
0x00007fac940d6000, 0x00007fac94272000, 0x00007fac94477800, 0x00007fac94479800,
0x00007fac9447b800, 0x00007fac9447d000, 0x00007fac9447f000, 0x00007fac94481000,
0x00007fac94483000, 0x00007fac94485000, 0x00007fac94487000, 0x00007fac94489000,
0x00007fac94448000, 0x00007fac944c0000, 0x00007fac68001000
}

"main" #1 prio=5 os_prio=0 cpu=687.88ms elapsed=144.19s tid=0x00007fac94015000 nid=0x3220 in Object.wait()  [0x00007fac9e77e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.10/Native Method)
	- waiting on <0x00000000d9739438> (a java.lang.Object)
	at java.lang.Object.wait(java.base@11.0.10/Object.java:328)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.join(QueuedThreadPool.java:567)
	- waiting to re-lock in wait() <0x00000000d9739438> (a java.lang.Object)
	at org.eclipse.jetty.server.Server.join(Server.java:550)
	at org.apache.cloudstack.ServerDaemon.start(ServerDaemon.java:191)
	at org.apache.cloudstack.ServerDaemon.main(ServerDaemon.java:104)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.54ms elapsed=144.18s tid=0x00007fac94054800 nid=0x3223 waiting on condition  [0x00007fac9887d000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.10/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.10/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.10/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.52ms elapsed=144.18s tid=0x00007fac94057000 nid=0x3224 in Object.wait()  [0x00007fac9877c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.10/Native Method)
	- waiting on <0x00000000d9400a50> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.10/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000000d9400a50> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.10/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.10/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.43ms elapsed=144.18s tid=0x00007fac9405d000 nid=0x3225 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.10ms elapsed=144.18s tid=0x00007fac9405f000 nid=0x3226 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=222.13ms elapsed=144.18s tid=0x00007fac94061000 nid=0x3227 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=0 cpu=411.41ms elapsed=144.18s tid=0x00007fac94063800 nid=0x3228 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=0.15ms elapsed=144.18s tid=0x00007fac94065800 nid=0x3229 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #10 daemon prio=8 os_prio=0 cpu=0.61ms elapsed=144.16s tid=0x00007fac940d6000 nid=0x322a in Object.wait()  [0x00007fac98176000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.10/Native Method)
	- waiting on <0x00000000d9401180> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.10/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000000d9401180> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.10/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.10/InnocuousThread.java:134)

"RMI TCP Accept-0" #12 daemon prio=5 os_prio=0 cpu=0.40ms elapsed=143.94s tid=0x00007fac94272000 nid=0x322c runnable  [0x00007fac7c169000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(java.base@11.0.10/Native Method)
	at java.net.AbstractPlainSocketImpl.accept(java.base@11.0.10/AbstractPlainSocketImpl.java:458)
	at java.net.ServerSocket.implAccept(java.base@11.0.10/ServerSocket.java:565)
	at java.net.ServerSocket.accept(java.base@11.0.10/ServerSocket.java:533)
	at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(jdk.management.agent@11.0.10/LocalRMIServerSocketFactory.java:52)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(java.rmi@11.0.10/TCPTransport.java:394)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(java.rmi@11.0.10/TCPTransport.java:366)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-14" #14 prio=5 os_prio=0 cpu=1.26ms elapsed=143.59s tid=0x00007fac94477800 nid=0x322e runnable  [0x00007fac3fffe000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.10/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.10/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.10/SelectorImpl.java:124)
	- locked <0x00000000d59b6660> (a sun.nio.ch.Util$2)
	- locked <0x00000000d59b6490> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.10/SelectorImpl.java:141)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:472)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:409)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$153/0x0000000840194040.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-15" #15 prio=5 os_prio=0 cpu=0.75ms elapsed=143.59s tid=0x00007fac94479800 nid=0x322f waiting on condition  [0x00007fac3fefd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d946ba98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:875)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:925)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-16" #16 prio=5 os_prio=0 cpu=0.17ms elapsed=143.59s tid=0x00007fac9447b800 nid=0x3230 runnable  [0x00007fac3fdfc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.10/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.10/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.10/SelectorImpl.java:124)
	- locked <0x00000000d59c1350> (a sun.nio.ch.Util$2)
	- locked <0x00000000d59c1200> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.10/SelectorImpl.java:141)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:472)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:409)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$153/0x0000000840194040.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-17-acceptor-0@3d1848cc-ServerConnector@3f6f6701{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}" #17 prio=3 os_prio=0 cpu=0.60ms elapsed=143.59s tid=0x00007fac9447d000 nid=0x3231 runnable  [0x00007fac3fcfb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(java.base@11.0.10/Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(java.base@11.0.10/ServerSocketChannelImpl.java:533)
	at sun.nio.ch.ServerSocketChannelImpl.accept(java.base@11.0.10/ServerSocketChannelImpl.java:285)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:702)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-18" #18 prio=5 os_prio=0 cpu=0.56ms elapsed=143.59s tid=0x00007fac9447f000 nid=0x3232 waiting on condition  [0x00007fac3fbfa000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d946ba98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:875)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:925)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-19" #19 prio=5 os_prio=0 cpu=0.55ms elapsed=143.59s tid=0x00007fac94481000 nid=0x3233 waiting on condition  [0x00007fac3faf9000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d946ba98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:875)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:925)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-20" #20 prio=5 os_prio=0 cpu=0.54ms elapsed=143.59s tid=0x00007fac94483000 nid=0x3234 waiting on condition  [0x00007fac3f9f8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d946ba98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:875)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:925)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-21" #21 prio=5 os_prio=0 cpu=0.45ms elapsed=143.59s tid=0x00007fac94485000 nid=0x3235 waiting on condition  [0x00007fac3f8f7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d946ba98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:875)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:925)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-22" #22 prio=5 os_prio=0 cpu=0.48ms elapsed=143.59s tid=0x00007fac94487000 nid=0x3236 waiting on condition  [0x00007fac3f7f6000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d946ba98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:875)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:925)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"qtp202125197-23" #23 prio=5 os_prio=0 cpu=0.47ms elapsed=143.59s tid=0x00007fac94489000 nid=0x3237 waiting on condition  [0x00007fac3f6f5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d946ba98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:875)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:925)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"org.eclipse.jetty.util.RolloverFileOutputStream" #24 daemon prio=5 os_prio=0 cpu=0.26ms elapsed=143.58s tid=0x00007fac94448000 nid=0x3238 in Object.wait()  [0x00007fac3f5f4000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.10/Native Method)
	- waiting on <0x00000000d946d9e0> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(java.base@11.0.10/Timer.java:553)
	- waiting to re-lock in wait() <0x00000000d946d9e0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(java.base@11.0.10/Timer.java:506)

"Scheduler-1730704097-1" #25 prio=5 os_prio=0 cpu=0.22ms elapsed=143.52s tid=0x00007fac944c0000 nid=0x323c waiting on condition  [0x00007fac3efed000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000d972c8d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.10/AbstractQueuedSynchronizer.java:2123)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.10/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.10/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.10/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.10/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.10/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)

"Attach Listener" #26 daemon prio=9 os_prio=0 cpu=1.95ms elapsed=0.10s tid=0x00007fac68001000 nid=0x32ed waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=17.49ms elapsed=144.18s tid=0x00007fac94051800 nid=0x3222 runnable  

"ParGC Thread#0" os_prio=0 cpu=4.63ms elapsed=144.19s tid=0x00007fac9402c800 nid=0x3221 runnable  

"ParGC Thread#1" os_prio=0 cpu=4.52ms elapsed=143.55s tid=0x00007fac6c001000 nid=0x3239 runnable  

"ParGC Thread#2" os_prio=0 cpu=4.45ms elapsed=143.55s tid=0x00007fac6c002800 nid=0x323a runnable  

"ParGC Thread#3" os_prio=0 cpu=3.71ms elapsed=143.55s tid=0x00007fac6c004000 nid=0x323b runnable  

"VM Periodic Task Thread" os_prio=0 cpu=112.21ms elapsed=143.93s tid=0x00007fac94277000 nid=0x322d waiting on condition  

JNI global refs: 21, weak refs: 0

```

**Comment by staySober** [comment]
I try fix it to reinstall cloudstack-management 

1. backup databases
2. uninstall cloudstack-managment
3.  reinstall cloudstack-management 
4.  execute cloudstack-setup-databases
5. cloudstack-setup-management
6.  Restore data from a backup to databases
7.  service cloudstack-management restart 

but now, the server is  HTTP ERROR 503 Service Unavailable
before I execute step 6,  the server is available

I don't know if I did the right steps to reinstall and restore the data
Correct me if I make a mistake

Thanks

**Comment by rhtyd** [comment]
It says error while decryption - your management server `key` (in db.properties and in key file at /etc/cloudstack/management/) file is wrong or invalid - please check @staySober - if this is a new/test environment, can you re-deploying from scratch.

**Comment by staySober** [comment]
Ok.  I fix it and my Database backup restore successfully. But I still don't  understand why the manager can block when I restart the server.  I guess the mistake may be due to I changed the manager configuration wrongly. 
Anyway.  Thank you for helping me

**Comment by rhtyd** [comment]
Thanks for confirming it was env/config issue, I'm closing the ticket on your remark @staySober - the manager was blocked because it couldn't decrypt some DB content which it logged as well.
