### ISSUE TITLE
Unable to add an additional manager

### ISSUE THREAD

**Issue by mhoffmann21** [apache/cloudstack#4928]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Cloudstack management server
~~~

##### CLOUDSTACK VERSION
~~~
4.15.0
~~~

##### CONFIGURATION

Two management servers and several kvm hosts, aggregated to one cluster.
Advanced networking is used, since there is no other option. Networking works fine.

The cloudstack ist configured so that both management servers are populated to the host ('host' global configuration parameter). The lb algorithm is roundrobin. 

Both management servers use the same ntp servers and have a connection.

##### OS / ENVIRONMENT
Ubuntu 20.04 LTS

##### SUMMARY
I'm not able to add an additional management server, following the official documentation.

##### STEPS TO REPRODUCE

- follow the instructions of the documentation, describing how to add another management server

##### EXPECTED RESULTS

~~~
The second management server is added und can be seen within the ui, without any error message inside the logs.
~~~

##### ACTUAL RESULTS

I followed the documentation on adding another management server.
After the second management server finishes the `cloudstack-setup-management` command and starts the cloudstack service, I got the following error within the `management.log` of the FIRST management server.

~~~
2021-04-15 17:35:42,971 ERROR  [c.c.c.d.ManagementServerHostDaoImpl] (Cluster-Heartbeat-1:ctx-9ae6e55f) (logid:d5142009) Unexpected exception,
com.cloud.utils.exception.CloudRuntimeException: Invalid cluster session detected, runId 1618500697537 is no longer valid
        at com.cloud.cluster.dao.ManagementServerHostDaoImpl.update(ManagementServerHostDaoImpl.java:144)
        at jdk.internal.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy184.update(Unknown Source)
        at com.cloud.cluster.ClusterManagerImpl$4.runInContext(ClusterManagerImpl.java:555)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.cloud.cluster.ClusterInvalidSessionException: runId 1618500697537 is no longer valid
        at com.cloud.cluster.dao.ManagementServerHostDaoImpl.update(ManagementServerHostDaoImpl.java:144)
        at jdk.internal.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        ... 22 more
~~~

The error repeats every second.
If I restart the first managment server, I get the error within the SECOND management server log. So both switched roles (that makes sense).

Furthermore, if both managers are running, I can only see one manager up in th UI (the one which has been started at last).
Also within the database (`cloud.mshost`) there is only one management server.

So my question here is, why the additional management server is not added, but the old one is replaced?
Do I miss a configuration detail, which is not mentioned in the docs?

Thanks in advance.

**Comment by rhtyd** [comment]
cc @Spaceman1984

**Comment by rhtyd** [comment]
cc @weizhouapache - do you remember doing any testing around multi-management setup with Ubuntu 20.40 when we recently added support in Ubuntu 20.04 cc @shwstppr @davidjumani

**Comment by weizhouapache** [comment]
@mhoffmann21 what command did you execute ?
arguments of `cloudstack-setup-management` on additional mgt servers is different from first mgt server.

**Comment by mhoffmann21** [comment]
@weizhouapache thx for answering. I followed the documentation.
On the first management node, I executed the `cloudstack-setup-databases` command, with the credentials for the database and user,  the `--deploy-as` argument and at the end the management IP of the node itself. 

As the documentation states, this is followed by the `cloudstack-setup-management` command. There are no arguments in the documentation.

On the second node, also as stated in the documentation, I executed the `cloudstack-setup-databases` without the `--deploy-as` argument, since the database has already been created and deployed by the first node. The argument at the end `-i` is followed by the management IP of the second node.

After that, the documentation says, that I have to execute the `cloudstack-setup-management` on the second node. There were no errors or failures. Every command was executed successfully. 

Hope this gives you an insight. :)

**Comment by Spaceman1984** [comment]
I am able to reproduce this error, I get the same behaviour after adding the second management server.

**Comment by weizhouapache** [comment]
@mhoffmann21 @Spaceman1984 
Is package `net-tools` installed on your management servers ?
if not, could you install it and retry ?

**Comment by mhoffmann21** [comment]
@weizhouapache @Spaceman1984 I installed `net-tools` on both management servers and it seems to work now. Nice!
Thx. 

What's the matter with the package? Is it possible to add this step to the documentation within the "Additional Management Server" part? That would be nice. :)

**Comment by rhtyd** [comment]
@mhoffmann21 I think we can add that as a debian depedency for the cloudstack-management pkg.

@Spaceman1984 can you propose a PR to add net-tools as dependency on cloudstack-management and test, thanks.

**Comment by Spaceman1984** [comment]
Sure @rhtyd

**Comment by weizhouapache** [comment]
> @weizhouapache @Spaceman1984 I installed `net-tools` on both management servers and it seems to work now. Nice!
> Thx.
> 
> What's the matter with the package? Is it possible to add this step to the documentation within the "Additional Management Server" part? That would be nice. :)

@mhoffmann21 that's good to know.

cloudstack gets the mac address of mgmt servers by command "ifconfig -a". however it is not installed by default in ubuntu 20.04 (maybe on some other OSes as well).
https://github.com/apache/cloudstack/blob/master/utils/src/main/java/com/cloud/utils/net/MacAddress.java#L99

@rhtyd would it be better to get mac address by other ways ?

**Comment by rhtyd** [comment]
Yes makes sense @weizhouapache we use `ip` or some other way (say use `/proc` sub-system).
@Spaceman1984 can you propose a PR with Wei's suggestion.

**Comment by mhoffmann21** [comment]
Nice to know! Thx for your help. :) Take care.

**Comment by Spaceman1984** [comment]
> Yes makes sense @weizhouapache we use `ip` or some other way (say use `/proc` sub-system).
> @Spaceman1984 can you propose a PR with Wei's suggestion.

I had a look at this, seems like it will take some effort to replace ifconfig with ip, I have added net-tools as a dependency in the meantime.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4951
