### ISSUE TITLE
CentOS 8: Lower version of dependency of libgcrypt prevents addition of hosts

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#4969]
During deployment of an ACS environment with CentOS 8 as the Management Server and hypervisor hosts, addition of hosts fail as required version of libgcrypt expected by libvirt 6.0 is 1.8.5 but available version of the corresponding library is 1.8.3.

##### COMPONENT NAME

~~~
Packaging
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### OS / ENVIRONMENT

Management Server: CentOS 8
Hypervisor Host(s): CentOS 8

##### SUMMARY
Issue on Hypervisor Host end: 
Due to the absence of the required version of libgcrypt, hosts fail to get added.

Issue on Management Server end:
After installing/upgrading the relevant package - libgcrypt on the hypervisor hosts, and adding them to the cluster, it is noticed that when template synchronization is initiated, the SSVM throws an exception, preventing template sync to proceed:
```
found 2 templates[/mnt/SecStorage/dc1eb1af-5b1b-3f0d-91aa-9a758b98ce07/template/tmpl/1/4/0c364cce-8288-3a92-9234-4ffde372aec7.qcow2, /mnt/SecStorage/dc1eb1af-5b1b-3f0d-91aa-9a758b98ce07/template/tmpl/1/3/b9b4f089-3de2-49d9-98d8-6c52785e8fd1.qcow2]
2021-04-28 10:13:15,508 WARN  [storage.template.TemplateLocation] (agentRequest-Handler-6:null) Cleaning up inconsistent information for QCOW2
2021-04-28 10:13:15,510 WARN  [cloud.agent.Agent] (agentRequest-Handler-6:null) Caught: 
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:702)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at com.cloud.storage.template.TemplateLocation.getTemplateInfo(TemplateLocation.java:180)
	at org.apache.cloudstack.storage.template.DownloadManagerImpl.gatherTemplateInfo(DownloadManagerImpl.java:905)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.execute(NfsSecondaryStorageResource.java:2145)
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.executeRequest(NfsSecondaryStorageResource.java:298)
	at com.cloud.storage.resource.PremiumSecondaryStorageResource.defaultAction(PremiumSecondaryStorageResource.java:64)
	at com.cloud.storage.resource.PremiumSecondaryStorageResource.executeRequest(PremiumSecondaryStorageResource.java:60)
	at com.cloud.agent.Agent.processRequest(Agent.java:661)
	at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1079)
	at com.cloud.utils.nio.Task.call(Task.java:83)
	at com.cloud.utils.nio.Task.call(Task.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

##### EXPECTED RESULTS

~~~
1. Hosts get added without any issue
2. Templates (Built-in CentOS template) gets downloaded and registered
~~~

##### ACTUAL RESULTS

~~~
Failure to setup hosts 
~~~

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4970
