### ISSUE TITLE
Unable to add ESXi Host

### ISSUE THREAD

**Issue by cafecat6503** [apache/cloudstack#4998]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

Management server

##### CLOUDSTACK VERSION

4.15.0

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT

Management server
- Ubuntu 20.04 

Hypervisor
- vCenter 6.7
- ESXI 6.7

##### SUMMARY
When I tried to add an ESXi host, I got an error message "Error 530 Unable to add host" and could not add the host.
This is a screenshot of the error.
![スクリーンショット 2021-05-06 101908](https://user-images.githubusercontent.com/20381860/117228858-ec4eb880-ae54-11eb-87a3-dab2c0f7c274.png)
In the "ESX/ESXi Host" field, I put the FQDN of my ESXi host.
I have also registered to vCenter with that FQDN.
Also, the zone's internal DNS server can resolve both forward and reverse DNS lookups.

##### STEPS TO REPRODUCE

1.  Create Zone.
2. Try to add ESXi host.

##### EXPECTED RESULTS

ESXi hosts can be added without error.

##### ACTUAL RESULTS
"Error 530 Unable to add Host" is displayed and ESXi host cannot be added.

This is Error log(/var/log
~~~
2021-05-06 00:43:50,808 INFO  [c.c.r.ResourceManagerImpl] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Trying to add a new host at http://<my-vCenter-fqdn>/home-dc1/cloud-cluster/<my-esxi-hostfqdn> in data center 1
2021-05-06 00:43:50,808 INFO  [c.c.h.v.VmwareServerDiscoverer] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Discover host. dc: 1, pod: 1, cluster: 2, uri host: <my-vCenter-fqdn>
2021-05-06 00:43:51,179 INFO  [c.c.h.v.VmwareServerDiscoverer] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Detected private network label : vSwitch0
2021-05-06 00:43:51,179 DEBUG [c.c.h.v.r.VmwareContextFactory] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) initialize VmwareContext. url: https://<my-vCenter-fqdn>/sdk/vimService, username: administrator@vsphere.local, password: 4********
2021-05-06 00:43:51,384 INFO  [c.c.h.v.u.VmwareContext] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) New VmwareContext object, current outstanding count: 2
2021-05-06 00:43:51,408 ERROR [c.c.h.v.u.VmwareContext] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Path element points to an un-existing inventory entity
2021-05-06 00:43:51,409 ERROR [c.c.h.v.m.VmwareManagerImpl] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Unable to find host from inventory path: /home-dc1/cloud-cluster/<my-esxi-hostfqdn>
2021-05-06 00:43:51,409 INFO  [c.c.h.v.VmwareServerDiscoverer] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Found 0 hosts.
2021-05-06 00:43:51,409 ERROR [c.c.h.v.VmwareServerDiscoverer] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Unable to find host or cluster based on url: /home-dc1/cloud-cluster/<my-esxi-hostfqdn>
2021-05-06 00:43:51,410 INFO  [c.c.h.v.u.VmwareContext] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Disconnecting VMware session
2021-05-06 00:43:51,415 WARN  [c.c.r.ResourceManagerImpl] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Unable to find the server resources at http://<my-vCenter-fqdn>/home-dc1/cloud-cluster/<my-esxi-hostfqdn>
2021-05-06 00:43:51,415 INFO  [c.c.u.e.CSExceptionErrorCode] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Could not find exception: com.cloud.exception.DiscoveryException in error code list for exceptions
2021-05-06 00:43:51,416 WARN  [o.a.c.a.c.a.h.AddHostCmd] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Exception:
com.cloud.exception.DiscoveryException: Unable to add the host
        at com.cloud.resource.ResourceManagerImpl.discoverHostsFull(ResourceManagerImpl.java:826)
        at com.cloud.resource.ResourceManagerImpl.discoverHosts(ResourceManagerImpl.java:612)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy188.discoverHosts(Unknown Source)
        at org.apache.cloudstack.api.command.admin.host.AddHostCmd.execute(AddHostCmd.java:142)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:764)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:588)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:321)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:134)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:131)
        at com.cloud.api.ApiServlet.doPost(ApiServlet.java:98)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1386)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-06 00:43:51,421 INFO  [c.c.a.ApiServer] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Unable to add the host
2021-05-06 00:43:51,422 DEBUG [c.c.a.ApiServlet] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) ===END===  10.41.7.133 -- POST  command=addHost&response=json
~~~

**Comment by rhtyd** [comment]
cc @sureshanaparti @harikrishna-patnala @nvazquez can you triage?

**Comment by rhtyd** [comment]
@cafecat6503 based on the logs, it seems your vSphere DC has no hosts:

```
2021-05-06 00:43:51,409 ERROR [c.c.h.v.m.VmwareManagerImpl] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Unable to find host from inventory path: /home-dc1/cloud-cluster/<my-esxi-hostfqdn>
2021-05-06 00:43:51,409 INFO  [c.c.h.v.VmwareServerDiscoverer] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Found 0 hosts.
...
2021-05-06 00:43:51,415 WARN  [c.c.r.ResourceManagerImpl] (qtp1644231115-16:ctx-9d55a0d4 ctx-5805610d) (logid:bda73b7f) Unable to find the server resources at http://<my-vCenter-fqdn>/home-dc1/cloud-cluster/<my-esxi-hostfqdn>
```

Can you if your DC has any host? (url in logs pointing to /home-dc1/cloud-cluster/<my-esxi-hostfqdn>)

You need to add your hosts to the cluster under a DC in vSphere before adding them in cloudstack. Also check the cluster name and DC name. (Do they match what you configured while you deployed the zone, or in the cluster where you're adding the host?)

**Comment by nvazquez** [comment]
Hi @cafecat6503 let us know if you still can reproduce the issue after the steps mentioned above by @rhtyd

**Comment by cafecat6503** [comment]
こんにちは。
はい、ホストはcloudstackに追加する前にDCに追加されています。
DCの名前もclusterの名前も正しいです。 @rhtyd

**Comment by rhtyd** [comment]
@cafecat6503 based on the logs, CloudStack failed to find any hosts in the DC/cluster. Please try again, check the full path. You can confirm the path and list DC/hosts by using `govc` - https://github.com/vmware/govmomi/releases
And then try again to add the hosts to your CloudStack cluster.
(PS. I had to use google translate to understand what you meant - hope I got that right)

**Comment by rhtyd** [comment]
Thanks @cafecat6503 closing on your remark. Please try to add hosts using the right path, if you've the same issue again even after passing the right parameter, pl re-open the ticket.
