### ISSUE TITLE
No have Virtual Routers , secondary-vm and consoleproxy-vm agent state wrong

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#5000]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
 VR
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### STEPS TO REPRODUCE

~~~

I split six virtual machines from a single physical machine to install the highly available CloudStack，
The machine allocation is as follows
10.13.56.6 manager1
10.13.56.7 manager2
10.13.56.8 client1
10.13.56.9 client2
10.13.56.10 ha1
10.13.56.11 ha2

 /24 network
basic network model
single netCard 

I have a virtual IP 10.13.56.88 for cloudstack HA
I install cloudstack 4.15 

when I add client1 and client2 to cloudstack compute nodes successfully，
I saw system VMs agent state is wrong  and Virtual Routers not automatically created

so I login v-1-VM and s-2-VM， They can `Ping` each other
but they unable to `Ping` gateway (10.13.56.254) successfully

I don't know what happend , I have successfully run CloudStack and managed KVM on three physical machines using the tutorial
So what's wrong with me? Please help me, thanks
~~~

##### EXPECTED RESULTS

~~~
s-2-VM and s-2-VM agent state is up 
and Virtual Routers automatically create
~~~

##### ACTUAL RESULTS

~~~
system VMs agent state is wrong  and Virtual Routers not automatically created
~~~
![image](https://user-images.githubusercontent.com/20500978/117253309-ad7f2980-ae79-11eb-9030-dcaa77fecedb.png)
![image](https://user-images.githubusercontent.com/20500978/117253335-b1ab4700-ae79-11eb-8140-79f0ca8e2459.png)
![image](https://user-images.githubusercontent.com/20500978/117254315-d653ee80-ae7a-11eb-9ed9-7e7f42d2d029.png)

**Comment by rhtyd** [comment]
@staySober let me suggest some checks:
- When you deployed the zone, did you specify a VLAN for the public network range?
- Do you have any invalid network configuration that may stop the connections, for example firewall, vpn and mtu settings?
- The IP you're trying to ping to/from, is this on the management network
- If this is on KVM, you can ssh into the KVM host; run tcpdump to see where packets are dropped/firewalled; in general tcpdump is your friend

**Comment by weizhouapache** [comment]
@staySober can you upload /var/log/cloud.log in these two systemvms ?
it might be helpful.

**Comment by staySober** [comment]
I am sure the firewalled is disable 
and I didn't  specify a VLAN for the public network range
and I the IP (10.13.56.254) is the network gateway. 
I split up six virtual machines on one physical machine to deploy these applications,
I used to do tests on multiple physical machines, and they were all successful at that time,
Could it be a problem of applying virtual machines to virtual machines on top of virtual machines? This problem may involve layer 2 virtualization technology, I am not very familiar with it



two systemvms have the same logs in the following

```
2021-05-06 06:21:31,466 INFO  [cloud.agent.Agent] (main:null) Attempted to connee
ct to the server, but received an unexpected exception, trying again...
com.cloud.utils.exception.NioConnectionException: No route to host
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:101)
        at com.cloud.agent.Agent.start(Agent.java:294)
        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)
        at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:44
22)
        at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:406)
        at com.cloud.agent.AgentShell.start(AgentShell.java:512)

        at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:406)
        at com.cloud.agent.AgentShell.start(AgentShell.java:512)
        at com.cloud.agent.AgentShell.main(AgentShell.java:547)
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:476)
        at java.base/sun.nio.ch.Net.connect(Net.java:468)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.javaa
:694)
        at com.cloud.utils.nio.NioClient.init(NioClient.java:56)
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:95)
        ... 6 more
2021-05-06 06:21:36,466 INFO  [cloud.agent.Agent] (main:null) Connecting to hostt
:10.13.56.88
2021-05-06 06:21:36,467 INFO  [utils.nio.NioClient] (main:null) Connecting to 100
.13.56.88:8250
2021-05-06 06:21:39,529 ERROR [utils.nio.NioConnection] (main:null) Unable to inn
itialize the threads.
java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:476)
        at java.base/sun.nio.ch.Net.connect(Net.java:468)
@       

        at java.base/sun.nio.ch.Net.connect(Net.java:476)
        at java.base/sun.nio.ch.Net.connect(Net.java:468)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.javaa
:694)
        at com.cloud.utils.nio.NioClient.init(NioClient.java:56)
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:95)
        at com.cloud.agent.Agent.start(Agent.java:294)
        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)
        at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:44
22)
        at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:406)
        at com.cloud.agent.AgentShell.start(AgentShell.java:512)
        at com.cloud.agent.AgentShell.main(AgentShell.java:547)
2021-05-06 06:21:39,530 INFO  [utils.nio.NioClient] (main:null) NioClient connecc
tion closed
2021-05-06 06:21:39,530 INFO  [cloud.agent.Agent] (main:null) Attempted to connee
ct to the server, but received an unexpected exception, trying again...
com.cloud.utils.exception.NioConnectionException: No route to host
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:101)
        at com.cloud.agent.Agent.start(Agent.java:294)
        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)
        at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:44
22)

        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)
        at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:44
22)
        at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:406)
        at com.cloud.agent.AgentShell.start(AgentShell.java:512)
        at com.cloud.agent.AgentShell.main(AgentShell.java:547)
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:476)
        at java.base/sun.nio.ch.Net.connect(Net.java:468)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.javaa
:694)
        at com.cloud.utils.nio.NioClient.init(NioClient.java:56)
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:95)
        ... 6 more
2021-05-06 06:21:44,530 INFO  [cloud.agent.Agent] (main:null) Connecting to hostt
:10.13.56.88
2021-05-06 06:21:44,531 INFO  [utils.nio.NioClient] (main:null) Connecting to 100
.13.56.88:8250
2021-05-06 06:21:47,593 ERROR [utils.nio.NioConnection] (main:null) Unable to inn
itialize the threads.
java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)

java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:476)
        at java.base/sun.nio.ch.Net.connect(Net.java:468)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.javaa
:694)
        at com.cloud.utils.nio.NioClient.init(NioClient.java:56)
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:95)
        at com.cloud.agent.Agent.start(Agent.java:294)
        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)
        at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:44
22)
        at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:406)
        at com.cloud.agent.AgentShell.start(AgentShell.java:512)
        at com.cloud.agent.AgentShell.main(AgentShell.java:547)
2021-05-06 06:21:47,594 INFO  [utils.nio.NioClient] (main:null) NioClient connecc
tion closed
2021-05-06 06:21:47,594 INFO  [cloud.agent.Agent] (main:null) Attempted to connee
ct to the server, but received an unexpected exception, trying again...
com.cloud.utils.exception.NioConnectionException: No route to host
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:101)
        at com.cloud.agent.Agent.start(Agent.java:294)
        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)

        at com.cloud.agent.Agent.start(Agent.java:294)
        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)
        at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:44
22)
        at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:406)
        at com.cloud.agent.AgentShell.start(AgentShell.java:512)
        at com.cloud.agent.AgentShell.main(AgentShell.java:547)
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:476)
        at java.base/sun.nio.ch.Net.connect(Net.java:468)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.javaa
:694)
        at com.cloud.utils.nio.NioClient.init(NioClient.java:56)
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:95)
        ... 6 more
2021-05-06 06:21:52,594 INFO  [cloud.agent.Agent] (main:null) Connecting to hostt
:10.13.56.88
2021-05-06 06:21:52,595 INFO  [utils.nio.NioClient] (main:null) Connecting to 100
.13.56.88:8250
2021-05-06 06:21:55,657 ERROR [utils.nio.NioConnection] (main:null) Unable to inn
itialize the threads.
java.net.NoRouteToHostException: No route to host

        at com.cloud.agent.AgentShell.main(AgentShell.java:547)
2021-05-06 09:48:54,345 INFO  [utils.nio.NioClient] (main:null) NioClient connecc
tion closed
2021-05-06 09:48:54,345 INFO  [cloud.agent.Agent] (main:null) Attempted to connee
ct to the server, but received an unexpected exception, trying again...
com.cloud.utils.exception.NioConnectionException: No route to host
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:101)
        at com.cloud.agent.Agent.start(Agent.java:294)
        at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:455)
        at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:44
22)
        at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:406)
        at com.cloud.agent.AgentShell.start(AgentShell.java:512)
        at com.cloud.agent.AgentShell.main(AgentShell.java:547)
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:476)
        at java.base/sun.nio.ch.Net.connect(Net.java:468)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.javaa
:694)
        at com.cloud.utils.nio.NioClient.init(NioClient.java:56)
        at com.cloud.utils.nio.NioConnection.start(NioConnection.java:95)
        ... 6 more

```

**Comment by weizhouapache** [comment]
@staySober can you share the output of `brctl show` or `bridge link show` on kvm hosts ?
do you use bridge or vxlan or ovs for isolation ?

**Comment by staySober** [comment]
@weizhouapache 
![image](https://user-images.githubusercontent.com/20500978/117280809-8d5d6380-ae95-11eb-8d9f-fcd998ef7f3d.png)
![image](https://user-images.githubusercontent.com/20500978/117280834-977f6200-ae95-11eb-89d5-e63e4ce64fe2.png)

I don't use bridge or vxlan or ovs for isolation beacuse I don't know anything about them.

**Comment by staySober** [comment]
I found that the automatically created templating system could not ping other machines on the same network segment as the host
for example , kvm client IP(10.13.56.9)  secondarystoragevm IP(10.13.56.22)  manager1 IP(10.13.56.6)
the IP(10.13.56.22) can not ping 10.13.56.9

**Comment by weizhouapache** [comment]
> I found that the automatically created templating system could not ping other machines on the same network segment as the host
> for example , kvm client IP(10.13.56.9) secondarystoragevm IP(10.13.56.22) manager1 IP(10.13.56.6)
> the IP(10.13.56.22) can not ping 10.13.56.9

what's the output of `ip addr show cloudbr0` and `ip addr show ens192` ?

**Comment by staySober** [comment]
KVM host machine info
![image](https://user-images.githubusercontent.com/20500978/117283227-2b522d80-ae98-11eb-8c5d-ba0d54cec5bb.png)
![image](https://user-images.githubusercontent.com/20500978/117283263-3311d200-ae98-11eb-8c80-244f72be701b.png)

**Comment by weizhouapache** [comment]
@staySober the host looks good.
are the ips configured correctly in s-2-VM ?

**Comment by staySober** [comment]
@weizhouapache s-2-VM ip config is self-configured. I think it right. I didn't edit it
I have successfully set up a cluster of physical machines, but not in this virtual machine environment where a single physical machine is partitioned

I guess there is something wrong with the configuration of the virtual machine network created in the virtual machine. I read in other articles that it may be necessary to use the two-layer virtual machine technology, but I am not quite sure about it. I plan to try using the physical machine to build a high-availability cloudstack cluster tomorrow

by the way, what should I do when I use keepalived make a virtual IP and to config two cloudstack-manager server. can you give me some simple instructions ?  I plan to install two manager server

**Comment by rhtyd** [comment]
@staySober do you actually have a valid network where the L3 configuration (the configured IP ranges and gateway) would work? Do you see anything in `tcpdump` (what's causing packets to be dropped)?

Instead of complicated management server setup with VRRP/virtual-IP, just set them up with specific IPs and for KVM use the software based LB see https://www.shapeblue.com/software-based-agent-lb-for-cloudstack and for user-facing you can setup an nginx-reverse proxy with SSL termination.

**Comment by weizhouapache** [comment]
> @weizhouapache s-2-VM ip config is self-configured. I think it right. I didn't edit it
> I have successfully set up a cluster of physical machines, but not in this virtual machine environment where a single physical machine is partitioned
> 
> I guess there is something wrong with the configuration of the virtual machine network created in the virtual machine. I read in other articles that it may be necessary to use the two-layer virtual machine technology, but I am not quite sure about it. I plan to try using the physical machine to build a high-availability cloudstack cluster tomorrow

I use/have used nested environment (vms in vm) for long time. There is no network issue.
I suspect it is caused by firewall (iptables rules). if you want to continue on the troubleshooting, please check firewall rules by `iptables-save` and retry after `iptables -F`

> 
> by the way, what should I do when I use keepalived make a virtual IP and to config two cloudstack-manager server. can you give me some simple instructions ? I plan to install two manager server

you may refer to https://www.redhat.com/sysadmin/keepalived-basics

**Comment by staySober** [comment]
@weizhouapache thanks for your help. actually, My firewall is off. I'm deployed on a Centos7 system. default firewall is firewalld. also I not install iptables. I will continue to check my network configuration thanks

**Comment by staySober** [comment]
@weizhouapache @rhtyd I found the reason, Incorrect network configuration on VMARE EXSI is causing the problem.
The promiscuous mode and MAC address change pseudo transport in the VM Network configuration need to be set to accept
![image](https://user-images.githubusercontent.com/20500978/117404011-c18b5f80-af3b-11eb-9208-bd3b9fc25242.png)
Thank you for your help, I will close the issue

**Comment by weizhouapache** [comment]
@staySober cool. nice to know it.
it might be much helpful for those who create nested environment over vmware.

**Comment by rhtyd** [comment]
Thanks for sharing @staySober
