### ISSUE TITLE
Why HA host label.hastate show 'Ineligible'

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#5041]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### STEPS TO REPRODUCE

~~~
I want to use Host HA, So I configure the tag `ha.tag=ha` and tagged the host Client1 with 'ha'. Then I restarted the cloudstack-management server. 
But after I logged back in, I saw the client1 Host  label.hastate = 'Ineligible' .
and the Host HA is not working properly
I am so confused that there is something wrong with my configuration, please help me
~~~

##### EXPECTED RESULTS

```
1. client1 Host Ha enable and label.hastate is displayed correctly 
2.  Host HA can working correctly
```
##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/20500978/119757182-2997ea80-bed7-11eb-93da-2fbdf2b029e8.png)

~~~

~~~

**Comment by DaanHoogland** [comment]
@staySober did you configure a HAProvider? If so can you find any exceptions in the logs of the agent and/or the management server?

**Comment by staySober** [comment]
@DaanHoogland yes, I configured the label.haprovider = `kvmhaprovider` .  I will to check the logs

**Comment by rhtyd** [comment]
@staySober I think it's already fixed in 4.15.1, can you check using nightly builds: https://download.cloudstack.org/testing/nightly/latest/ and close this.

**Comment by rhtyd** [comment]
Example: http://qa.cloudstack.cloud:8080/client/#/host/3a4a15a8-1d67-4913-9afe-d0240d643195 from latest UI build
![Screenshot from 2021-05-27 19-13-17](https://user-images.githubusercontent.com/95203/119836772-9fc03f80-bf1f-11eb-88f1-944bce572a15.png)

**Comment by staySober** [comment]
`4.15.1.0Ovm3 SystemVm template not found. Ovm3 hypervisor is not used, so not failing upgrade
2021-05-28 15:23:50,893 DEBUG [c.c.u.d.Upgrade41500to41510] (main:null) (logid:) Updating Hyperv System Vms
2021-05-28 15:23:50,896 ERROR [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Unable to upgrade the database
com.cloud.utils.exception.CloudRuntimeException: 4.15.1.0Hyperv SystemVm template not found. Cannot upgrade system Vms
        at com.cloud.upgrade.dao.Upgrade41500to41510.updateSystemVmTemplates(Upgrade41500to41510.java:210)
        at com.cloud.upgrade.DatabaseUpgradeChecker.updateSystemVmTemplates(DatabaseUpgradeChecker.java:254)
        at com.cloud.upgrade.DatabaseUpgradeChecker.upgrade(DatabaseUpgradeChecker.java:273)
        at com.cloud.upgrade.DatabaseUpgradeChecker.check(DatabaseUpgradeChecker.java:377)
        at org.apache.cloudstack.spring.lifecycle.CloudStackExtendedLifeCycle.checkIntegrity(CloudStackExtendedLifeCycle.java:64)
        at org.apache.cloudstack.spring.lifecycle.CloudStackExtendedLifeCycle.start(CloudStackExtendedLifeCycle.java:54)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:144)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:121)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:244)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:249)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:232)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:116)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:78)
        at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37)
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:70)
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:57)
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:61)
        at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:51)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)
        at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
                                                                                                                                                                                               `


why I upgrade to 4.15.1 get this error, I never used Hyperv  in my cloudstack, and I try to upload Hyperv  system Vms template but the error still exist

**Comment by DaanHoogland** [comment]
@staySober does the upgrade fail because of this? I don't think this ERROR is FATAL.

Also, is this related to the earlier issue or is this a new one, please?

**Comment by staySober** [comment]
@DaanHoogland is this not related to the earlier issue. I follow the suggestion of @rhtyd , Try to upgrade from cloudstack4.15 to cloudstack4.15.1 to fix HA state error.But When I finished installing cloudstack4.15.1, I starting cloudstack4.15 management server I get this error. And the server is 503 
![image](https://user-images.githubusercontent.com/20500978/119952017-25e78f00-bfcf-11eb-9c4f-25b968f0e027.png)

**Comment by DaanHoogland** [comment]
ok, than the upgrade went wrong, You should not have to have the systemvm template for a hypervisor type you don't use. We'll need to investigate. But let's take care not to mix up issues.

The message you get does mean that the upgrade procedure considered hyperv to be in use in your system. it iterates through the list of hypervisors and encounters one that is of type Hyperv.

**Comment by staySober** [comment]
@DaanHoogland 
Okay I'm sorry I'm not very good at expressing myself.
Thanks help me

**Comment by DaanHoogland** [comment]
@staySober, let's try to isolate the issue. I think you better restore your DB from before the upgrade and than make sure there is no hypervisor in the system that is of type Hyperv. Best check the DB as well (Hyperv is enum value 4)

**Comment by staySober** [comment]
@DaanHoogland
sure, I check the DB. 
![image](https://user-images.githubusercontent.com/20500978/119956387-a1e3d600-bfd3-11eb-997c-19c5cd228b1c.png)
There doesn't seem to be an instance of HyperV in my VM instance

 What I am doing now is reinitializing the database for 4.15.1. Then I restored the database from 4.15 to the management node from 4.15.1. Now, service running. But some info was wrong. I think this due to I restored the database from 4.15 backup. 
management.servers display my version 4.15.0, But I already upgrade to 4.15.1.Of course it's not a big deal, right.

I think there are some errors in the two versions of the code after I upgraded. It is not the database data problem.

**Comment by DaanHoogland** [comment]
@staySober It is not the `vm_instance` tabel but the field `hypervisor_type` in the table `host` to look for the the value of `Hyperv`.

If you restored the DB fully the table `version` should no longer contain a record with `version.version` = '4.15.1.0` and the management server will start the upgrade anew.

If there is no `host` entry of `hypervisor_type` 'Hyperv' the upgrade should not be looking for the systemvm record for it.

You may be right about the software but I still think it is a DB problem. If it is software that would probably lead to many more people complaining about the same issue as work on 4.15.1.0 is underway for many months now.

**Comment by staySober** [comment]
Thank you for your help. I will check this problem according to your tips. If it can be solved successfully, I will close the issue.

**Comment by staySober** [comment]
![image](https://user-images.githubusercontent.com/20500978/120303220-349cb180-c301-11eb-893b-dead46a711c3.png)
I rollback cloudstack to 4.15.0 and restore db, but the error was also exist. I don't know what happened.

**Comment by staySober** [comment]
And finally I figured out why the error exsit. Because I have a empty cluster  hypervisor_type is hyperv.  But no have any instance. I think is the point to make the mistake.
Thanks a lot everyone

**Comment by staySober** [comment]
@rhtyd @DaanHoogland 
hi friends，I update cloudstack-management server to 4.15.1. and config ha tag,  the host label.hastate also show `Ineligible`. what's wrong with me? why Host HA function doesn't work 
![image](https://user-images.githubusercontent.com/20500978/120469999-9fb7b800-c3d5-11eb-904d-ff971a23e541.png)
![image](https://user-images.githubusercontent.com/20500978/120470019-a5150280-c3d5-11eb-9dd5-e4f177fe9d83.png)

**Comment by rhtyd** [comment]
Hi @staySober - can you share your env details (which distro is that?) and have you tried clearing your cache? (try the UI in incognito mode or do Ctrl+Shift+R)

**Comment by staySober** [comment]
Sure,  CentOS Linux release 7.9.2009 (Core), cloudstack 4.15.1-SNAPSHOT. cluster hypervisor is KVM.
and I try to cleaned cache but it was seem no changed

![image](https://user-images.githubusercontent.com/20500978/120577009-417ee980-c456-11eb-8ff9-12b29283021b.png)
![image](https://user-images.githubusercontent.com/20500978/120577037-4f346f00-c456-11eb-8216-2796fcefecbe.png)
