### ISSUE TITLE
Host HA consoleproxy vm migration failed 

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#5069]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
consoleproxy vm HA
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1-SNAPSHOT
~~~

##### STEPS TO REPRODUCE

~~~
I test Host high availability features, I have two host, client1 as a HA host, Client2 as a normal host.
when I try to power off Client2. The Host HA  function runs successfully after a while.
but the system vm `consoleproxy` migration state anomaly. it's still on client2 and agent status is disconnected.

~~~
![image](https://user-images.githubusercontent.com/20500978/120627928-bd008b00-c496-11eb-97b8-688fd20e184a.png)
![image](https://user-images.githubusercontent.com/20500978/120628068-db668680-c496-11eb-8514-43241099d686.png)

~~~
So i want to solve the problem. but when I want to deleted this vm and make it  auto redeloy. But management-server report error as follow
~~~
![image](https://user-images.githubusercontent.com/20500978/120628597-719aac80-c497-11eb-8906-1a5870172da2.png)
~~~
but the error report not clear. I think it not due to the insufficient system resources.
now I can't bring the consoleproxy vm back to normal use. I also use command `cloudstack-sysvmadm` to fix it. but it's also seem no used.

what should I do to fix it?
~~~

##### EXPECTED RESULTS

~~~
three system vms successful migration
~~~

##### ACTUAL RESULTS

~~~
just two vms (secondarystoragevm. virutalRoutervm) successful migration
~~~

**Comment by staySober** [comment]
Zone 1 is ready to launch console proxy
2021-06-03 18:45:25,637 DEBUG [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Expand console proxy standby capacity for zone test-zone
2021-06-03 18:45:25,638 INFO  [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) No stopped console proxy is available, need to allocate a new console proxy
2021-06-03 18:45:25,638 DEBUG [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Assign console proxy from a newly started instance for request from data center : 1
2021-06-03 18:45:25,646 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Found existing network configuration for offering [Network Offering [6-Guest-DefaultSharedNetworkOfferingWithSGService]: Ntwk[204|Guest|6]
2021-06-03 18:45:25,646 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Releasing lock for Acct[56b21825-c388-11eb-bf97-000c299380b6-system]
2021-06-03 18:45:25,648 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Found existing network configuration for offering [Network Offering [3-Control-System-Control-Network]: Ntwk[202|Control|3]
2021-06-03 18:45:25,648 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Releasing lock for Acct[56b21825-c388-11eb-bf97-000c299380b6-system]
2021-06-03 18:45:25,651 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Found existing network configuration for offering [Network Offering [2-Management-System-Management-Network]: Ntwk[201|Management|2]
2021-06-03 18:45:25,651 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Releasing lock for Acct[56b21825-c388-11eb-bf97-000c299380b6-system]
2021-06-03 18:45:25,655 INFO  [c.c.v.VirtualMachineManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) allocating virtual machine from template:47ce7664-c388-11eb-bf97-000c299380b6 with hostname:v-84-VM and 3 networks
2021-06-03 18:45:25,657 DEBUG [c.c.v.VirtualMachineManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Allocating entries for VM: VM[ConsoleProxy|v-84-VM]
2021-06-03 18:45:25,657 DEBUG [c.c.v.VirtualMachineManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Allocating nics for VM[ConsoleProxy|v-84-VM]
2021-06-03 18:45:25,658 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Allocating nic for vm VM[ConsoleProxy|v-84-VM] in network Ntwk[204|Guest|6] with requested profile NicProfile[0-0-null-null-null]
2021-06-03 18:45:25,664 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Allocating nic for vm VM[ConsoleProxy|v-84-VM] in network Ntwk[202|Control|3] with requested profile null
2021-06-03 18:45:25,668 DEBUG [o.a.c.e.o.NetworkOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Allocating nic for vm VM[ConsoleProxy|v-84-VM] in network Ntwk[201|Management|2] with requested profile null
2021-06-03 18:45:25,671 DEBUG [c.c.v.VirtualMachineManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Allocating disks for VM[ConsoleProxy|v-84-VM]
2021-06-03 18:45:25,671 INFO  [o.a.c.e.o.VolumeOrchestrator] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) adding disk object ROOT-84 to v-84-VM
2021-06-03 18:45:25,674 DEBUG [c.c.v.VirtualMachineManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Allocation completed for VM: VM[ConsoleProxy|v-84-VM]
2021-06-03 18:45:25,675 DEBUG [c.c.a.ConsoleProxyAlertAdapter] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) received console proxy alert
2021-06-03 18:45:25,676 DEBUG [c.c.a.ConsoleProxyAlertAdapter] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) New console proxy created, zone: test-zone, proxy: v-84-VM, public IP: null, private IP: null
2021-06-03 18:45:25,681 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Sync job-384 execution on object VmWorkJobQueue.84
2021-06-03 18:45:27,053 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-6d5f0847) (logid:892ca502) Execute sync-queue item: SyncQueueItemVO {id:268, queueId: 268, contentType: AsyncJob, contentId: 384, lastProcessMsid: 52237140150, lastprocessNumber: 1, lastProcessTime: Thu Jun 03 18:45:27 CST 2021, created: Thu Jun 03 18:45:25 CST 2021}
2021-06-03 18:45:27,054 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (AsyncJobMgr-Heartbeat-1:ctx-6d5f0847) (logid:892ca502) Schedule queued job-384
2021-06-03 18:45:27,056 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:06a147ba) Add job-384 into job monitoring
2021-06-03 18:45:27,059 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Executing AsyncJobVO {id:384, userId: 1, accountId: 1, instanceType: null, instanceId: null, cmd: com.cloud.vm.VmWorkStart, cmdInfo: rO0ABXNyABhjb20uY2xvdWQudm0uVm1Xb3JrU3RhcnR9cMGsvxz73gIAC0oABGRjSWRMAAZhdm9pZHN0ADBMY29tL2Nsb3VkL2RlcGxveS9EZXBsb3ltZW50UGxhbm5lciRFeGNsdWRlTGlzdDtMAAljbHVzdGVySWR0ABBMamF2YS9sYW5nL0xvbmc7TAAGaG9zdElkcQB-AAJMAAtqb3VybmFsTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAEXBoeXNpY2FsTmV0d29ya0lkcQB-AAJMAAdwbGFubmVycQB-AANMAAVwb2RJZHEAfgACTAAGcG9vbElkcQB-AAJMAAlyYXdQYXJhbXN0AA9MamF2YS91dGlsL01hcDtMAA1yZXNlcnZhdGlvbklkcQB-AAN4cgATY29tLmNsb3VkLnZtLlZtV29ya5-ZtlbwJWdrAgAESgAJYWNjb3VudElkSgAGdXNlcklkSgAEdm1JZEwAC2hhbmRsZXJOYW1lcQB-AAN4cAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAVHQAGVZpcnR1YWxNYWNoaW5lTWFuYWdlckltcGwAAAAAAAAAAHBwcHBwcHBwcHA, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 52237140150, completeMsid: null, lastUpdated: null, lastPolled: null, created: Thu Jun 03 18:45:25 CST 2021, removed: null}
2021-06-03 18:45:27,059 DEBUG [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Run VM work job: com.cloud.vm.VmWorkStart for VM 84, job origin: 230
2021-06-03 18:45:27,060 DEBUG [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Execute VM work job: com.cloud.vm.VmWorkStart{"dcId":0,"userId":1,"accountId":1,"vmId":84,"handlerName":"VirtualMachineManagerImpl"}
2021-06-03 18:45:27,064 DEBUG [c.c.c.CapacityManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) VM state transitted from :Stopped to Starting with event: StartRequestedvm's original host id: null new host id: null host id before state transition: null
2021-06-03 18:45:27,064 DEBUG [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Successfully transitioned to start state for VM[ConsoleProxy|v-84-VM] reservation id = 8dddf14f-6c67-4bf5-88b8-e1c914c8f6d5
2021-06-03 18:45:27,066 DEBUG [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Deploy avoids pods: null, clusters: null, hosts: null
2021-06-03 18:45:27,067 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) DeploymentPlanner allocation algorithm: null
2021-06-03 18:45:27,068 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Trying to allocate a host and storage pools from dc:1, pod:null,cluster:null, requested cpu: 500, requested ram: (1.00 GB) 1073741824
2021-06-03 18:45:27,068 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Is ROOT volume READY (pool already allocated)?: No
2021-06-03 18:45:27,068 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Deploy avoids pods: null, clusters: null, hosts: null
2021-06-03 18:45:27,069 DEBUG [c.c.d.FirstFitPlanner] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Searching all possible resources under this Zone: 1
2021-06-03 18:45:27,069 DEBUG [c.c.d.FirstFitPlanner] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Listing clusters in order of aggregate capacity, that have (at least one host with) enough CPU and RAM capacity under this Zone: 1
2021-06-03 18:45:27,074 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Checking resources in Cluster: 1 under Pod: 1
2021-06-03 18:45:27,074 INFO  [c.c.a.m.a.i.FirstFitAllocator] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688 FirstFitRoutingAllocator) (logid:17220ef6)  Guest VM is requested with Cusotm[UEFI] Boot Type false
2021-06-03 18:45:27,074 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688 FirstFitRoutingAllocator) (logid:17220ef6) Looking for hosts in dc: 1  pod:1  cluster:1
2021-06-03 18:45:27,076 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688 FirstFitRoutingAllocator) (logid:17220ef6) FirstFitAllocator has 0 hosts to check for allocation: []
2021-06-03 18:45:27,077 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688 FirstFitRoutingAllocator) (logid:17220ef6) Found 0 hosts for allocation after prioritization: []
2021-06-03 18:45:27,077 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688 FirstFitRoutingAllocator) (logid:17220ef6) Looking for speed=500Mhz, Ram=1024 MB
2021-06-03 18:45:27,077 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688 FirstFitRoutingAllocator) (logid:17220ef6) Host Allocator returning 0 suitable hosts
2021-06-03 18:45:27,077 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) No suitable hosts found
2021-06-03 18:45:27,077 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) No suitable hosts found under this Cluster: 1
2021-06-03 18:45:27,077 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Could not find suitable Deployment Destination for this VM under any clusters, returning. 
2021-06-03 18:45:27,078 DEBUG [c.c.d.FirstFitPlanner] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Searching all possible resources under this Zone: 1
2021-06-03 18:45:27,078 DEBUG [c.c.d.FirstFitPlanner] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Listing clusters in order of aggregate capacity, that have (at least one host with) enough CPU and RAM capacity under this Zone: 1
2021-06-03 18:45:27,080 DEBUG [c.c.d.FirstFitPlanner] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Removing from the clusterId list these clusters from avoid set: [1]
2021-06-03 18:45:27,080 DEBUG [c.c.d.FirstFitPlanner] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) No clusters found after removing disabled clusters and clusters in avoid list, returning.
2021-06-03 18:45:27,084 DEBUG [c.c.c.CapacityManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) VM state transitted from :Starting to Stopped with event: OperationFailedvm's original host id: null new host id: null host id before state transition: null
2021-06-03 18:45:27,084 ERROR [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Invocation exception, caused by: com.cloud.exception.InsufficientServerCapacityException: Unable to create a deployment for VM[ConsoleProxy|v-84-VM]Scope=interface com.cloud.dc.DataCenter; id=1
2021-06-03 18:45:27,085 INFO  [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384 ctx-43aed688) (logid:17220ef6) Rethrow exception com.cloud.exception.InsufficientServerCapacityException: Unable to create a deployment for VM[ConsoleProxy|v-84-VM]Scope=interface com.cloud.dc.DataCenter; id=1
2021-06-03 18:45:27,085 DEBUG [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Done with run of VM work job: com.cloud.vm.VmWorkStart for VM 84, job origin: 230
2021-06-03 18:45:27,085 ERROR [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Unable to complete AsyncJobVO {id:384, userId: 1, accountId: 1, instanceType: null, instanceId: null, cmd: com.cloud.vm.VmWorkStart, cmdInfo: rO0ABXNyABhjb20uY2xvdWQudm0uVm1Xb3JrU3RhcnR9cMGsvxz73gIAC0oABGRjSWRMAAZhdm9pZHN0ADBMY29tL2Nsb3VkL2RlcGxveS9EZXBsb3ltZW50UGxhbm5lciRFeGNsdWRlTGlzdDtMAAljbHVzdGVySWR0ABBMamF2YS9sYW5nL0xvbmc7TAAGaG9zdElkcQB-AAJMAAtqb3VybmFsTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAEXBoeXNpY2FsTmV0d29ya0lkcQB-AAJMAAdwbGFubmVycQB-AANMAAVwb2RJZHEAfgACTAAGcG9vbElkcQB-AAJMAAlyYXdQYXJhbXN0AA9MamF2YS91dGlsL01hcDtMAA1yZXNlcnZhdGlvbklkcQB-AAN4cgATY29tLmNsb3VkLnZtLlZtV29ya5-ZtlbwJWdrAgAESgAJYWNjb3VudElkSgAGdXNlcklkSgAEdm1JZEwAC2hhbmRsZXJOYW1lcQB-AAN4cAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAVHQAGVZpcnR1YWxNYWNoaW5lTWFuYWdlckltcGwAAAAAAAAAAHBwcHBwcHBwcHA, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 52237140150, completeMsid: null, lastUpdated: null, lastPolled: null, created: Thu Jun 03 18:45:25 CST 2021, removed: null}, job origin:230
com.cloud.exception.InsufficientServerCapacityException: Unable to create a deployment for VM[ConsoleProxy|v-84-VM]Scope=interface com.cloud.dc.DataCenter; id=1
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1119)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5499)
	at jdk.internal.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
	at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5666)
	at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-03 18:45:27,086 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Complete async job-384, jobStatus: FAILED, resultCode: 0, result: rO0ABXNyADdjb20uY2xvdWQuZXhjZXB0aW9uLkluc3VmZmljaWVudFNlcnZlckNhcGFjaXR5RXhjZXB0aW9uAAAAAFZNT3ACAAFaABVhZmZpbml0eUdyb3Vwc0FwcGxpZWR4cgAxY29tLmNsb3VkLmV4Y2VwdGlvbi5JbnN1ZmZpY2llbnRDYXBhY2l0eUV4Y2VwdGlvbgAAAABWTU91AgACTAACaWR0ABBMamF2YS9sYW5nL0xvbmc7TAAFc2NvcGV0ABFMamF2YS9sYW5nL0NsYXNzO3hyACJjb20uY2xvdWQuZXhjZXB0aW9uLkNsb3VkRXhjZXB0aW9ueeiOG_HkRMcCAAJMAAtjc0Vycm9yQ29kZXQAE0xqYXZhL2xhbmcvSW50ZWdlcjtMAAZpZExpc3R0ABVMamF2YS91dGlsL0FycmF5TGlzdDt4cgATamF2YS5sYW5nLkV4Y2VwdGlvbtD9Hz4aOxzEAgAAeHIAE2phdmEubGFuZy5UaHJvd2FibGXVxjUnOXe4ywMABEwABWNhdXNldAAVTGphdmEvbGFuZy9UaHJvd2FibGU7TAANZGV0YWlsTWVzc2FnZXQAEkxqYXZhL2xhbmcvU3RyaW5nO1sACnN0YWNrVHJhY2V0AB5bTGphdmEvbGFuZy9TdGFja1RyYWNlRWxlbWVudDtMABRzdXBwcmVzc2VkRXhjZXB0aW9uc3QAEExqYXZhL3V0aWwvTGlzdDt4cHEAfgANdAA6VW5hYmxlIHRvIGNyZWF0ZSBhIGRlcGxveW1lbnQgZm9yIFZNW0NvbnNvbGVQcm94eXx2LTg0LVZNXXVyAB5bTGphdmEubGFuZy5TdGFja1RyYWNlRWxlbWVudDsCRio8PP0iOQIAAHhwAAAAFHNyABtqYXZhLmxhbmcuU3RhY2tUcmFjZUVsZW1lbnRhCcWaJjbdhQIACEIABmZvcm1hdEkACmxpbmVOdW1iZXJMAA9jbGFzc0xvYWRlck5hbWVxAH4ACkwADmRlY2xhcmluZ0NsYXNzcQB-AApMAAhmaWxlTmFtZXEAfgAKTAAKbWV0aG9kTmFtZXEAfgAKTAAKbW9kdWxlTmFtZXEAfgAKTAANbW9kdWxlVmVyc2lvbnEAfgAKeHABAAAEX3QAA2FwcHQAJmNvbS5jbG91ZC52bS5WaXJ0dWFsTWFjaGluZU1hbmFnZXJJbXBsdAAeVmlydHVhbE1hY2hpbmVNYW5hZ2VySW1wbC5qYXZhdAAQb3JjaGVzdHJhdGVTdGFydHBwc3EAfgARAQAAFXtxAH4AE3EAfgAUcQB-ABVxAH4AFnBwc3EAfgARAP____9wdAAvamRrLmludGVybmFsLnJlZmxlY3QuR2VuZXJhdGVkTWV0aG9kQWNjZXNzb3IyNjBwdAAGaW52b2tlcHBzcQB-ABECAAAAK3B0ADFqZGsuaW50ZXJuYWwucmVmbGVjdC5EZWxlZ2F0aW5nTWV0aG9kQWNjZXNzb3JJbXBsdAAhRGVsZWdhdGluZ01ldGhvZEFjY2Vzc29ySW1wbC5qYXZhcQB-ABp0AAlqYXZhLmJhc2V0AAcxMS4wLjExc3EAfgARAgAAAjZwdAAYamF2YS5sYW5nLnJlZmxlY3QuTWV0aG9kdAALTWV0aG9kLmphdmFxAH4AGnEAfgAecQB-AB9zcQB-ABEBAAAAa3EAfgATdAAiY29tLmNsb3VkLnZtLlZtV29ya0pvYkhhbmRsZXJQcm94eXQAGlZtV29ya0pvYkhhbmRsZXJQcm94eS5qYXZhdAAPaGFuZGxlVm1Xb3JrSm9icHBzcQB-ABEBAAAWInEAfgATcQB-ABRxAH4AFXEAfgAmcHBzcQB-ABEBAAAAZnEAfgATdAAgY29tLmNsb3VkLnZtLlZtV29ya0pvYkRpc3BhdGNoZXJ0ABhWbVdvcmtKb2JEaXNwYXRjaGVyLmphdmF0AAZydW5Kb2JwcHNxAH4AEQEAAAJscQB-ABN0AD9vcmcuYXBhY2hlLmNsb3Vkc3RhY2suZnJhbWV3b3JrLmpvYnMuaW1wbC5Bc3luY0pvYk1hbmFnZXJJbXBsJDV0ABhBc3luY0pvYk1hbmFnZXJJbXBsLmphdmF0AAxydW5JbkNvbnRleHRwcHNxAH4AEQEAAAAwcQB-ABN0AD5vcmcuYXBhY2hlLmNsb3Vkc3RhY2subWFuYWdlZC5jb250ZXh0Lk1hbmFnZWRDb250ZXh0UnVubmFibGUkMXQAG01hbmFnZWRDb250ZXh0UnVubmFibGUuamF2YXQAA3J1bnBwc3EAfgARAQAAADdxAH4AE3QAQm9yZy5hcGFjaGUuY2xvdWRzdGFjay5tYW5hZ2VkLmNvbnRleHQuaW1wbC5EZWZhdWx0TWFuYWdlZENvbnRleHQkMXQAGkRlZmF1bHRNYW5hZ2VkQ29udGV4dC5qYXZhdAAEY2FsbHBwc3EAfgARAQAAAGZxAH4AE3QAQG9yZy5hcGFjaGUuY2xvdWRzdGFjay5tYW5hZ2VkLmNvbnRleHQuaW1wbC5EZWZhdWx0TWFuYWdlZENvbnRleHRxAH4ANnQAD2NhbGxXaXRoQ29udGV4dHBwc3EAfgARAQAAADRxAH4AE3EAfgA5cQB-ADZ0AA5ydW5XaXRoQ29udGV4dHBwc3EAfgARAQAAAC1xAH4AE3QAPG9yZy5hcGFjaGUuY2xvdWRzdGFjay5tYW5hZ2VkLmNvbnRleHQuTWFuYWdlZENvbnRleHRSdW5uYWJsZXEAfgAycQB-ADNwcHNxAH4AEQEAAAI4cQB-ABNxAH4ALXEAfgAucQB-ADNwcHNxAH4AEQIAAAIDcHQALmphdmEudXRpbC5jb25jdXJyZW50LkV4ZWN1dG9ycyRSdW5uYWJsZUFkYXB0ZXJ0AA5FeGVjdXRvcnMuamF2YXEAfgA3cQB-AB5xAH4AH3NxAH4AEQIAAAEIcHQAH2phdmEudXRpbC5jb25jdXJyZW50LkZ1dHVyZVRhc2t0AA9GdXR1cmVUYXNrLmphdmFxAH4AM3EAfgAecQB-AB9zcQB-ABECAAAEaHB0ACdqYXZhLnV0aWwuY29uY3VycmVudC5UaHJlYWRQb29sRXhlY3V0b3J0ABdUaHJlYWRQb29sRXhlY3V0b3IuamF2YXQACXJ1bldvcmtlcnEAfgAecQB-AB9zcQB-ABECAAACdHB0AC5qYXZhLnV0aWwuY29uY3VycmVudC5UaHJlYWRQb29sRXhlY3V0b3IkV29ya2VycQB-AEhxAH4AM3EAfgAecQB-AB9zcQB-ABECAAADPXB0ABBqYXZhLmxhbmcuVGhyZWFkdAALVGhyZWFkLmphdmFxAH4AM3EAfgAecQB-AB9zcgAfamF2YS51dGlsLkNvbGxlY3Rpb25zJEVtcHR5TGlzdHq4F7Q8p57eAgAAeHB4c3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAEO9zcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAHcEAAAAAHhzcgAOamF2YS5sYW5nLkxvbmc7i-SQzI8j3wIAAUoABXZhbHVleHEAfgBSAAAAAAAAAAF2cgAXY29tLmNsb3VkLmRjLkRhdGFDZW50ZXJT6CQa0tO2XAIAAHhwAA
2021-06-03 18:45:27,086 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Publish async job-384 complete on message bus
2021-06-03 18:45:27,086 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Wake up jobs related to job-384
2021-06-03 18:45:27,086 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Update db status for job-384
2021-06-03 18:45:27,087 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Wake up jobs joined with job-384 and disjoin all subjobs created from job- 384
2021-06-03 18:45:27,090 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Done executing com.cloud.vm.VmWorkStart for job-384
2021-06-03 18:45:27,090 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (Work-Job-Executor-148:ctx-ff76d905 job-230/job-384) (logid:17220ef6) Remove job-384 from job monitoring
2021-06-03 18:45:27,093 WARN  [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-601a371f) (logid:eb9c1423) Exception while trying to start console proxy

**Comment by rhtyd** [comment]
@staySober can you test in a fresh 4.15.1.0 RC1 (see email on dev@ and user@) env?

**Comment by staySober** [comment]
@rhtyd I see the cloudstack 4.15.1-snapshot is update. 
but when I try again, the  consoleproxy vm migration successfully.
I will test in a new env again

**Comment by rhtyd** [comment]
As per the logs your host/cluster couldn't be selected for cpvm to start and failed, check if they were enabled or had enough cpu/mem resources.

**Comment by staySober** [comment]
now, everything is working fine. I will closed it
