### ISSUE TITLE
Can not add KVM host to cloudstack, the cloudstack agent has errors

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#5191]
##### ISSUE TYPE

 * Other

##### CLOUDSTACK VERSION
- CloudStack 4.15.0.0

##### KVM Host 
- system: oracle8

#### Cloudstack agent version
cloudstack-common-4.15.1.0-1.el8.x86_64
cloudstack-agent-4.15.1.0-1.el8.x86_64

####  KVM host network 
using bond and Basic Networks in [Configuring the Network Bridges for Basic Networks](http://docs.cloudstack.apache.org/projects/archived-cloudstack-installation/zh_CN/latest/hypervisor/kvm.html#install-and-configure-the-agent)

```
NAME             UUID                                  TYPE      DEVICE    
Bridge cloudbr0  d4b789ba-7321-548d-dabd-5c4150da0266  bridge    cloudbr0  
cloud0           d1ab5ec4-d8a0-45d3-9a45-43326748a2b0  bridge    cloud0    
bond0            ad33d8b0-1f7b-cab9-9447-ba07f855b143  bond      bond0     
bond0.136        8a52cc3f-e1dd-79e4-b950-923a4c8735a4  vlan      bond0.136 
bond0-slave      b186f945-cc80-911d-668c-b51be8596980  ethernet  eno2      
bond0-slave      abf4c85b-57cc-4484-4fa9-b4a71689c359  ethernet  eno1      
Bond bond0.291   8da63d5d-d8dd-c7e7-a834-405b83d0b5a5  bond      bond0.291 
Bridge cloudbr1  6df8d4a7-7ee1-528a-dcf9-20d35734f675  bridge    cloudbr1
```

qemu version:
```
qemu-kvm-block-gluster-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-kvm-block-curl-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-kvm-block-iscsi-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-kvm-core-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch
qemu-kvm-block-ssh-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-kvm-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-guest-agent-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-kvm-block-rbd-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-img-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
qemu-kvm-common-4.2.0-48.module+el8.4.0+20158+f6690737.x86_64
libvirt-daemon-driver-qemu-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
```

libvirt version
```
libvirt-daemon-driver-storage-logical-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-storage-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-kvm-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-docs-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-secret-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-client-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-storage-gluster-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-gobject-3.0.0-1.el8.x86_64
libvirt-lock-sanlock-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-admin-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-glib-3.0.0-1.el8.x86_64
libvirt-daemon-driver-storage-rbd-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-gconfig-3.0.0-1.el8.x86_64
libvirt-daemon-driver-storage-mpath-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-dbus-1.3.0-2.module+el8.3.0+7860+a7792d29.x86_64
libvirt-nss-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-interface-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-config-nwfilter-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-bash-completion-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-config-network-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
python3-libvirt-6.0.0-1.module+el8.3.0+7860+a7792d29.x86_64
libvirt-daemon-driver-storage-core-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-storage-iscsi-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-storage-disk-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-nodedev-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-network-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-storage-scsi-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-devel-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-nwfilter-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-storage-iscsi-direct-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-libs-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64
libvirt-daemon-driver-qemu-6.0.0-35.0.1.module+el8.4.0+20171+f6690737.x86_64

```

The libvirtd config:
listen_tls=0
listen_tcp=0

The libvirt works fine ,when the cloudstack-agent not started. But when the  cloudstack-agent start ,the libvirt has errors.

The error is 
```
Jul 08 13:49:25 wqdccls006.cn.infra libvirtd[637851]: Cannot recv data: Input/output error
Jul 08 13:49:38 wqdccls006.cn.infra libvirtd[637851]: End of file while reading data: Input/output error
Jul 08 13:49:38 wqdccls006.cn.infra libvirtd[637851]: End of file while reading data: Input/output error
Jul 08 13:49:38 wqdccls006.cn.infra libvirtd[637851]: Cannot recv data: Input/output error
Jul 08 13:49:50 wqdccls006.cn.infra libvirtd[637851]: End of file while reading data: Input/output error
Jul 08 13:49:50 wqdccls006.cn.infra libvirtd[637851]: End of file while reading data: Input/output error
Jul 08 13:49:50 wqdccls006.cn.infra libvirtd[637851]: Cannot recv data: Input/output error
Jul 08 13:50:02 wqdccls006.cn.infra libvirtd[637851]: End of file while reading data: Input/output error
Jul 08 13:50:02 wqdccls006.cn.infra libvirtd[637851]: End of file while reading data: Input/output error
Jul 08 13:50:02 wqdccls006.cn.infra libvirtd[637851]: Cannot recv data: Input/output error
```

The cloud stack agent error:
```
2021-07-08 13:33:02,948 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Agent started
2021-07-08 13:33:02,951 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Implementation Version is 4.15.1.0
2021-07-08 13:33:02,952 INFO  [cloud.agent.AgentShell] (main:null) (logid:) agent.properties found at /etc/cloudstack/agent/agent.properties
2021-07-08 13:33:02,963 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: workers
2021-07-08 13:33:02,963 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: guest.network.device
2021-07-08 13:33:02,963 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: private.network.device
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: port
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: resource
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: pod
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: zone
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: guid
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: hypervisor.type
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: public.network.device
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: cluster
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: iscsi.session.cleanup.enabled
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: local.storage.uuid
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: domr.scripts.dir
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: keystore.passphrase
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: LibvirtComputingResource.id
2021-07-08 13:33:02,964 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Found property: host
2021-07-08 13:33:02,964 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Defaulting to using properties file for storage
2021-07-08 13:33:02,965 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Defaulting to the constant time backoff algorithm
2021-07-08 13:33:02,966 INFO  [cloud.utils.LogUtils] (main:null) (logid:) log4j configuration found at /etc/cloudstack/agent/log4j-cloud.xml
2021-07-08 13:33:02,974 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Using default Java settings for IPv6 preference for agent connection
2021-07-08 13:33:02,977 DEBUG [cloud.agent.AgentShell] (main:null) (logid:) Checking to see if agent.pid exists.
2021-07-08 13:33:02,985 DEBUG [cloud.utils.ProcessUtil] (main:null) (logid:) Executing: bash -c echo $PPID 
2021-07-08 13:33:02,999 DEBUG [cloud.utils.ProcessUtil] (main:null) (logid:) Executing while with timeout : 120000
2021-07-08 13:33:03,000 DEBUG [cloud.utils.ProcessUtil] (main:null) (logid:) Execution is successful.
2021-07-08 13:33:03,032 INFO  [cloud.agent.Agent] (main:null) (logid:) id is 0
2021-07-08 13:33:03,032 DEBUG [cloud.resource.ServerResourceBase] (main:null) (logid:) Retrieving network interface: cloudbr0
2021-07-08 13:33:03,033 DEBUG [cloud.resource.ServerResourceBase] (main:null) (logid:) Retrieving network interface: cloudbr0
2021-07-08 13:33:03,033 DEBUG [cloud.resource.ServerResourceBase] (main:null) (logid:) Retrieving network interface: null
2021-07-08 13:33:03,034 DEBUG [cloud.resource.ServerResourceBase] (main:null) (logid:) Retrieving network interface: null
2021-07-08 13:33:03,039 ERROR [kvm.resource.LibvirtComputingResource] (main:null) (logid:) uefi properties file not found due to: Unable to find file uefi.properties.
2021-07-08 13:33:03,046 DEBUG [resource.virtualnetwork.VirtualRoutingResource] (main:null) (logid:) The router.aggregation.command.each.timeout in seconds is set to 600
2021-07-08 13:33:03,046 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in the classpath
2021-07-08 13:33:03,046 DEBUG [utils.script.Script] (main:null) (logid:) System resource: null
2021-07-08 13:33:03,047 DEBUG [utils.script.Script] (main:null) (logid:) Classpath resource: null
2021-07-08 13:33:03,047 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh
2021-07-08 13:33:03,047 DEBUG [utils.script.Script] (main:null) (logid:) Current binaries reside at /usr/share/cloudstack-agent/lib
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/share/cloudstack-agent/lib/scripts/vm/hypervisor/update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/share/cloudstack-agent/lib/scripts/vm/update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/share/cloudstack-agent/lib/scripts/update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/share/cloudstack-agent/lib/update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/share/cloudstack-agent/update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/share/update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /update_host_passwd.sh
2021-07-08 13:33:03,057 DEBUG [utils.script.Script] (main:null) (logid:) Searching in environment.properties
2021-07-08 13:33:03,058 DEBUG [utils.script.Script] (main:null) (logid:) environment.properties says scripts should be in /usr/share/cloudstack-common
2021-07-08 13:33:03,058 DEBUG [utils.script.Script] (main:null) (logid:) Looking for update_host_passwd.sh in /usr/share/cloudstack-common/scripts/vm/hypervisor/update_host_passwd.sh
2021-07-08 13:33:03,058 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in the classpath
2021-07-08 13:33:03,058 DEBUG [utils.script.Script] (main:null) (logid:) System resource: null
2021-07-08 13:33:03,058 DEBUG [utils.script.Script] (main:null) (logid:) Classpath resource: null
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Current binaries reside at /usr/share/cloudstack-agent/lib
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/cloudstack-agent/lib/scripts/vm/network/vnet/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/cloudstack-agent/lib/scripts/vm/network/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/cloudstack-agent/lib/scripts/vm/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/cloudstack-agent/lib/scripts/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/cloudstack-agent/lib/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/cloudstack-agent/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /modifyvlan.sh
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Searching in environment.properties
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) environment.properties says scripts should be in /usr/share/cloudstack-common
2021-07-08 13:33:03,059 DEBUG [utils.script.Script] (main:null) (logid:) Looking for modifyvlan.sh in /usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvlan.sh
........
........
2021-07-08 13:33:03,750 ERROR [kvm.resource.LibvirtConnection] (Agent-Handler-1:null) (logid:) Connection with libvirtd is broken: invalid connection pointer in virConnectGetVersion
2021-07-08 13:33:03,750 DEBUG [kvm.resource.LibvirtConnection] (Agent-Handler-1:null) (logid:) Opening a new libvirtd connection to: qemu:///system
2021-07-08 13:33:03,752 INFO  [kvm.storage.LibvirtStorageAdaptor] (Agent-Handler-1:null) (logid:) Found existing defined storage pool 9fbb8324-cb0d-4980-9e3e-5e58e1e821fc, using it.
2021-07-08 13:33:03,752 INFO  [kvm.storage.LibvirtStorageAdaptor] (Agent-Handler-1:null) (logid:) Trying to fetch storage pool 9fbb8324-cb0d-4980-9e3e-5e58e1e821fc from libvirt
2021-07-08 13:33:03,752 DEBUG [kvm.resource.LibvirtConnection] (Agent-Handler-1:null) (logid:) Looking for libvirtd connection at: qemu:///system
2021-07-08 13:33:03,761 DEBUG [kvm.storage.LibvirtStorageAdaptor] (Agent-Handler-1:null) (logid:) Succesfully refreshed pool 9fbb8324-cb0d-4980-9e3e-5e58e1e821fc Capacity: (49.98 GB) 53660876800 Used: (1.31 GB) 1410043904 Available: (48.66 GB) 52250832896
2021-07-08 13:33:03,763 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Executing: hostname 
2021-07-08 13:33:03,764 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Executing while with timeout : 500
2021-07-08 13:33:03,764 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Execution is successful.
2021-07-08 13:33:03,765 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Executing: hostname 
2021-07-08 13:33:03,765 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Executing while with timeout : 500
2021-07-08 13:33:03,766 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Execution is successful.
2021-07-08 13:33:03,785 INFO  [cloud.serializer.GsonHelper] (Agent-Handler-1:null) (logid:) Default Builder inited.
2021-07-08 13:33:03,803 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Sending Startup: Seq 0-0:  { Cmd , MgmtId: -1, via: 0, Ver: v1, Flags: 1, [{"com.cloud.agent.api.StartupRoutingCommand":{"cpuSockets":"2","cpus":"32","speed":"3700","memory":"810287943680","dom0MinMemory":"1073741824","poolSync":"false","supportsClonedVolumes":"false","caps":"hvm,snapshot","pool":"/root","hypervisorType":"KVM","hostDetails":{"Host.OS.Kernel.Version":"5.4.17-2102.202.5.el8uek.x86_64","com.cloud.network.Networks.RouterPrivateIpStrategy":"HostLocal","secured":"true","Host.OS":"Red"},"hostTags":[],"groupDetails":{},"type":"Routing","dataCenter":"1","pod":"1","cluster":"1","guid":"aa8cc72c-e343-3da0-a1a7-1b537bd887a0-LibvirtComputingResource","name":"wqdccls006.cn.infra","id":"0","version":"4.15.1.0","iqn":"iqn.1988-12.com.oracle:a5cc7aca2ba6","publicIpAddress":"10.67.36.200","publicNetmask":"255.255.252.0","publicMacAddress":"20:67:7c:0d:d2:a0","privateIpAddress":"10.67.36.200","privateMacAddress":"20:67:7c:0d:d2:a0","privateNetmask":"255.255.252.0","storageIpAddress":"10.67.36.200","storageNetmask":"255.255.252.0","storageMacAddress":"20:67:7c:0d:d2:a0","resourceName":"LibvirtComputingResource","gatewayIpAddress":"10.67.39.254","msHostList":"10.67.36.27","wait":"0","bypassHostMaintenance":"false"}},{"com.cloud.agent.api.StartupStorageCommand":{"totalSize":"(0 bytes) 0","poolInfo":{"uuid":"9fbb8324-cb0d-4980-9e3e-5e58e1e821fc","host":"10.67.36.200","localPath":"/var/lib/libvirt/images","hostPath":"/var/lib/lib
virt/images","poolType":"Filesystem","capacityBytes":"(49.98 GB) 53660876800","availableBytes":"(48.66 GB) 52250832896"},"resourceType":"STORAGE_POOL","hostDetails":{},"type":"Storage","dataC
enter":"1","pod":"1","guid":"aa8cc72c-e343-3da0-a1a7-1b537bd887a0-LibvirtComputingResource","name":"wqdccls006.cn.infra","id":"0","version":"4.15.1.0","resourceName":"LibvirtComputingResource
","msHostList":"10.67.36.27","wait":"0","bypassHostMaintenance":"false"}}] }
2021-07-08 13:33:03,803 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Startup task created
2021-07-08 13:33:03,816 DEBUG [cloud.agent.Agent] (Agent-Handler-2:null) (logid:) Received response: Seq 0-0:  { Ans: , MgmtId: 345051675185, via: -1, Ver: v1, Flags: 100000, [{"com.cloud.age
nt.api.StartupAnswer":{"hostId":"0","pingInterval":"60","result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2021-07-08 13:33:03,816 DEBUG [cloud.agent.Agent] (Agent-Handler-2:null) (logid:) Startup task cancelled
2021-07-08 13:33:03,816 INFO  [cloud.agent.Agent] (Agent-Handler-2:null) (logid:) Proccess agent startup answer, agent id = 0
2021-07-08 13:33:03,816 INFO  [cloud.agent.Agent] (Agent-Handler-2:null) (logid:) Set agent id 0
2021-07-08 13:33:03,819 DEBUG [cloud.agent.Agent] (agentRequest-Handler-2:null) (logid:) Request:Seq -1--1:  { Cmd , MgmtId: -1, via: -1, Ver: v1, Flags: 111, [{"com.cloud.agent.api.ReadyComm
and":{"_details":"java.lang.IllegalArgumentException: Can't add host: 10.67.36.200 with hostOS: Red into a cluster,in which there are CentOS hosts added","wait":"0","bypassHostMaintenance":"f
alse"}}] }
2021-07-08 13:33:03,820 DEBUG [cloud.agent.Agent] (agentRequest-Handler-2:null) (logid:) Processing command: com.cloud.agent.api.ReadyCommand
2021-07-08 13:33:03,820 DEBUG [cloud.agent.Agent] (agentRequest-Handler-2:null) (logid:) Not ready to connect to mgt server: java.lang.IllegalArgumentException: Can't add host: 10.67.36.200 w
ith hostOS: Red into a cluster,in which there are CentOS hosts added

```

The main err log has two:
```
2021-07-08 13:56:45,796 ERROR [kvm.resource.LibvirtComputingResource] (main:null) (logid:) uefi properties file not found due to: Unable to find file uefi.properties.
2021-07-08 13:56:46,473 ERROR [kvm.resource.LibvirtConnection] (Agent-Handler-1:null) (logid:) Connection with libvirtd is broken: invalid connection pointer in virConnectGetVersion
```

Could you please give some advices to handle this problem?

The releated issue: 
- https://github.com/apache/cloudstack/issues/4054
- https://github.com/apache/cloudstack/issues/3509

**Comment by xuanyuanaosheng** [comment]
The cloudstack manager error log:
```
2021-07-08 15:18:31,304 DEBUG [c.c.a.m.AgentManagerImpl] (AgentConnectTaskPool-631:ctx-8e89dfde) (logid:2789886a) Failed to handle host connection: 
java.lang.IllegalArgumentException: Can't add host: 10.67.36.200 with hostOS: Red into a cluster,in which there are CentOS hosts added
        at com.cloud.hypervisor.kvm.discoverer.LibvirtServerDiscoverer.createHostVOForConnectedAgent(LibvirtServerDiscoverer.java:456)
        at com.cloud.resource.ResourceManagerImpl.dispatchToStateAdapters(ResourceManagerImpl.java:1719)
        at com.cloud.resource.ResourceManagerImpl.createHostVO(ResourceManagerImpl.java:1946)
        at com.cloud.resource.ResourceManagerImpl.createHostVOForConnectedAgent(ResourceManagerImpl.java:2278)
        at jdk.internal.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy188.createHostVOForConnectedAgent(Unknown Source)
        at com.cloud.agent.manager.AgentManagerImpl.handleConnectedAgent(AgentManagerImpl.java:1097)
        at com.cloud.agent.manager.AgentManagerImpl$HandleAgentConnectTask.runInContext(AgentManagerImpl.java:1194)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-07-08 15:18:31,306 WARN  [c.c.a.m.AgentManagerImpl] (AgentConnectTaskPool-631:ctx-8e89dfde) (logid:2789886a) Unable to create attache for agent: Seq 0-0:  { Cmd , MgmtId: -1, via: 0, Ver: v1, Flags: 1, [{"com.cloud.
agent.api.StartupRoutingCommand":{"cpuSockets":"2","cpus":"32","speed":"3700","memory":"810287943680","dom0MinMemory":"1073741824","poolSync":"false","supportsClonedVolumes":"false","caps":"hvm,snapshot","pool":"/root","
hypervisorType":"KVM","hostDetails":{"Host.OS.Kernel.Version":"5.4.17-2102.202.5.el8uek.x86_64","com.cloud.network.Networks.RouterPrivateIpStrategy":"HostLocal","secured":"true","Host.OS":"Red"},"hostTags":[],"groupDetai
ls":{},"type":"Routing","dataCenter":"1","pod":"1","cluster":"1","guid":"aa8cc72c-e343-3da0-a1a7-1b537bd887a0-LibvirtComputingResource","name":"wqdccls006.cn.infra","id":"0","version":"4.15.1.0","iqn":"iqn.1988-12.com.or
acle:a5cc7aca2ba6","publicIpAddress":"10.67.36.200","publicNetmask":"255.255.252.0","publicMacAddress":"20:67:7c:0d:d2:a0","privateIpAddress":"10.67.36.200","privateMacAddress":"20:67:7c:0d:d2:a0","privateNetmask":"255.2
55.252.0","storageIpAddress":"10.67.36.200","storageNetmask":"255.255.252.0","storageMacAddress":"20:67:7c:0d:d2:a0","resourceName":"LibvirtComputingResource","gatewayIpAddress":"10.67.39.254","msHostList":"10.67.36.27",
"wait":"0"}},{"com.cloud.agent.api.StartupStorageCommand":{"totalSize":"(0 bytes) 0","poolInfo":{"uuid":"9fbb8324-cb0d-4980-9e3e-5e58e1e821fc","host":"10.67.36.200","localPath":"/var/lib/libvirt/images","hostPath":"/var/
lib/libvirt/images","poolType":"Filesystem","capacityBytes":"(49.98 GB) 53660876800","availableBytes":"(48.64 GB) 52229767168"},"resourceType":"STORAGE_POOL","hostDetails":{},"type":"Storage","dataCenter":"1","pod":"1","
guid":"aa8cc72c-e343-3da0-a1a7-1b537bd887a0-LibvirtComputingResource","name":"wqdccls006.cn.infra","id":"0","version":"4.15.1.0","resourceName":"LibvirtComputingResource","msHostList":"10.67.36.27","wait":"0"}}] }
2021-07-08 15:18:31,350 WARN  [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-11:null) (logid:) Throwing away a request because it came through as the first command on a connect: Seq 0--1:  { Cmd , MgmtId: -1, via: 0, V
er: v1, Flags: 111, [{"com.cloud.agent.api.ShutdownCommand":{"reason":"sig.kill","removeHost":"false","wait":"0"}}] }
2021-07-08 15:18:31,375 WARN  [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-13:null) (logid:) Throwing away a request because it came through as the first command on a connect: Seq 0-1:  { Cmd , MgmtId: -1, via: 0, Ve
r: v1, Flags: 11, [{"com.cloud.agent.api.PingRoutingWithNwGroupsCommand":{"newGroupStates":{},"_hostVmStateReport":{},"_gatewayAccessible":"true","_vnetAccessible":"true","hostType":"Routing","hostId":"0","wait":"0"}}] }
2021-07-08 15:18:32,344 INFO  [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-14:null) (logid:) Connection from /10.67.36.200 closed but no cleanup was done.
2021-07-08 15:18:32,784 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-8:null) (logid:) Ping from Routing host 18(wqdccls005.cn.infra)

```

**Comment by weizhouapache** [comment]
@xuanyuanaosheng 
you have added a CentOS 7 host in a cluster, now you are trying to add a oracle8 host, right ?
It is not supported I think.

**Comment by slavkap** [comment]
@xuanyuanaosheng, the error means that the OS is Red but it is expected CentOS, you can check [compatibility matrix](http://docs.cloudstack.apache.org/en/latest/releasenotes/compat.html) if can help

**Comment by shwstppr** [comment]
@xuanyuanaosheng As @weizhouapache you are trying to add different hosts in the same cluster. You may try adding a new cluster and then adding your host there.

**Comment by xuanyuanaosheng** [comment]
As @shwstppr said one cluster can not add different OS host. I add a new cluster, and it works.  @slavkap  Thanks.
@weizhouapache  Thanks for you help.

**Comment by xuanyuanaosheng** [comment]
I will close this issue. Thanks for your help.
