### ISSUE TITLE
Creating snapshot of volume attached to stopped VM which is migrated to other cluster, is not working

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#5372]
Creating a snapshot of volume attached to a stopped VM (VM is just migrated to a different cluster) is failing with the below error.

2021-08-25 09:33:36,270 ERROR [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-10:ctx-9f22db0f job-445/job-446 ctx-05260d9e) (logid:89f585a1) Take snapshot: 63 failed
com.cloud.utils.exception.CloudRuntimeException: backup snapshot exception: Exception: java.lang.Exception
Message: Unable to find related disk device for volume. volume path: bb3b5a94ca474c2ab678c40391d70ab5
        at org.apache.cloudstack.storage.snapshot.SnapshotServiceImpl.backupSnapshot(SnapshotServiceImpl.java:301)
        at org.apache.cloudstack.storage.snapshot.DefaultSnapshotStrategy.backupSnapshot(DefaultSnapshotStrategy.java:171)
        at com.cloud.storage.snapshot.SnapshotManagerImpl.backupSnapshotToSecondary(SnapshotManagerImpl.java:1213)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Volume snapshots
~~~

##### CLOUDSTACK VERSION

~~~
4.11, main
~~~

##### STEPS TO REPRODUCE

~~~
1. Create a VM in Cluster1
2. Stop the VM
3. Migrate the VM to a different storage pool in another cluster Cluster2
4. Create a data disk
5. Attach the data volume to the stopped VM above
6. Create snapshot of data volume
~~~

##### EXPECTED RESULTS

~~~
Successful snapshot creation.
~~~

##### ACTUAL RESULTS

~~~
Failed to create snapshot
~~~

**Comment by ravening** [comment]
One question. How can I migrate vm to another cluster when its stopped? You can migrate only the disk to another storage pool right?
