### ISSUE TITLE
Editing name / description / CIDR of network fails due to missing dns service in network offering (VPC)

### ISSUE THREAD

**Issue by Hudratronium** [apache/cloudstack#5556]
##### ISSUE TYPE

 * Bug Report
 * Other

##### COMPONENT NAME

~~~
UI
API
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### CONFIGURATION

advanced networking
custome vpc offering without dns / dhcp services provided
custome network offering without dns / dhcp services provided

##### SUMMARY

Editing / updating the network name, description and CIDR fails due to missing service dns in the network offering.

##### STEPS TO REPRODUCE

~~~
- create costume service offering for a vpc / guest network without dns service provided
- deploy a network using the offering
- in the network details click on the pencel and change values for name / description / CIDR
- Error is diplayed 
~~~

##### EXPECTED RESULTS

~~~
- updating name / decription / CIDR with values provided in the mask
~~~

##### ACTUAL RESULTS

- Error displayed in gui
![error](https://user-images.githubusercontent.com/79725167/136479495-c714d8df-f8b3-4ed2-a6b4-243b0e7aa2db.jpg)

- no values changed
- following the error of the management-server log, which is the same for all cases
~~~
2021-10-08 01:57:03,489 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-13:ctx-6c95adeb job-1006) (logid:e6512a5d) Unexpected exception while executing org.apache.cloudstack.api.command.user.network.UpdateNetworkCmd
com.cloud.exception.UnsupportedServiceException: Service Dns is not supported by the network offering com.cloud.api.query.vo.NetworkOfferingJoinVO$$EnhancerByCGLIB$$f896e@3d
        at com.cloud.network.NetworkServiceImpl.getNetworkOfferingServiceCapabilities(NetworkServiceImpl.java:2025)
        at com.cloud.network.NetworkServiceImpl.updateGuestNetwork(NetworkServiceImpl.java:2254)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy261.updateGuestNetwork(Unknown Source)
        at org.apache.cloudstack.api.command.user.network.UpdateNetworkCmd.execute(UpdateNetworkCmd.java:164)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:108)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
~~~

**Comment by DaanHoogland** [comment]
@Hudratronium I cannot reproduce this in 4.16. Can you try that please?

**Comment by DaanHoogland** [comment]
@Hudratronium your stack-trace shows:
```
at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
```

do you have any juniper-contrail elements configured?

**Comment by Hudratronium** [comment]
Hi @DaanHoogland 
no dont't have anything like juniper-contrail configured.

Seems like it is fixed with the last update. Was able to change the entries as expected.
Thanks for your work. And i will close this issue.
