### ISSUE TITLE
Failed to create kubernetes cluster on vmware

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5566]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Kubernetes
~~~

##### CLOUDSTACK VERSION

~~~
4.16/main
~~~

##### CONFIGURATION

advanced zone

##### OS / ENVIRONMENT

vmware7
vmware 6.7

##### SUMMARY

Got exception when create kubernetes cluster on vmware7 and vmware 6.7
##### STEPS TO REPRODUCE

~~~

upload k8s ISO
create k8s cluster
~~~

##### EXPECTED RESULTS

~~~

succeed
~~~

##### ACTUAL RESULTS

failed with exception

~~~
2021-10-08 11:58:54,277 WARN  [c.c.h.v.r.VmwareResource] (DirectAgent-8:ctx-17d2186c 10.0.34.105, job-44/job-46, cmd: StartCommand) (logid:19158d62) Disk chain length for the VM is greater than one, this is not supported
2021-10-08 11:58:54,277 INFO  [c.c.h.v.u.VmwareHelper] (DirectAgent-8:ctx-17d2186c 10.0.34.105, job-44/job-46, cmd: StartCommand) (logid:19158d62) [ignored]failed to get message for exception: Unsupported VM disk chain length: 2
2021-10-08 11:58:54,277 WARN  [c.c.h.v.r.VmwareResource] (DirectAgent-8:ctx-17d2186c 10.0.34.105, job-44/job-46, cmd: StartCommand) (logid:19158d62) StartCommand failed due to Exception: com.cloud.utils.exception.CloudRuntimeException
Message: Unsupported VM disk chain length: 2

com.cloud.utils.exception.CloudRuntimeException: Unsupported VM disk chain length: 2
at com.cloud.hypervisor.vmware.resource.VmwareResource.resizeRootDiskOnVMStart(VmwareResource.java:2900)
at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:2163)
at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:555)
at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)

~~~

**Comment by weizhouapache** [comment]
@Pearl1594 
can you please have look at this issue ?

cc @nvazquez
