### ISSUE TITLE
Exception while reboot VM with forced=true by normal user

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5742]
Got an exception

Reboot Instance
(L2) Parameter hostid can only be specified by a Root Admin, permission denied

```
2021-12-02 09:28:37,287 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-30:ctx-91fdb9c8 job-48) (logid:ee2cf4f6) Unexpected exception while executing org.apache.cloudstack.api.command.user.vm.RebootVMCmd
com.cloud.exception.PermissionDeniedException: Parameter hostid can only be specified by a Root Admin, permission denied
        at com.cloud.vm.UserVmManagerImpl.getDestinationHost(UserVmManagerImpl.java:5278)
        at com.cloud.vm.UserVmManagerImpl.startVirtualMachine(UserVmManagerImpl.java:5121)
        at com.cloud.vm.UserVmManagerImpl.forceRebootVirtualMachine(UserVmManagerImpl.java:1081)
        at com.cloud.vm.UserVmManagerImpl.rebootVirtualMachine(UserVmManagerImpl.java:1026)
        at com.cloud.vm.UserVmManagerImpl.rebootVirtualMachine(UserVmManagerImpl.java:3130)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI/API
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
Closing this as the fix PR got merged. @weizhouapache If you still notice this issue, please reopen. Thanks.

**Comment by weizhouapache** [comment]
> Closing this as the fix PR got merged. @weizhouapache If you still notice this issue, please reopen. Thanks.

thanks for fixing it @sureshanaparti
