### ISSUE TITLE
AgentManager-SSLHandshakeHandler SSL error

### ISSUE THREAD

**Issue by sotheareth** [apache/cloudstack#5805]
1. I try to build and run apache cloudstack in my local <br/> from https://github.com/apache/cloudstack

2. follow these step until the run jetty step under Build CloudStack <br/>
$ mvn -pl :cloud-client-ui jetty:run            # Run the management server on port 8080
<br/> from https://cwiki.apache.org/confluence/display/CLOUDSTACK/Setting+up+CloudStack+Development+Environment+on+Linux

3. getting below error: <br/>
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-5:null) (logid:) SSL error caught during wrap data: Empty server certificate chain, for local address=/192.168.0.104:8250, remote address=/192.168.0.104:56606.
WARN  [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-11:null) (logid:) This SSL engine was forced to close inbound due to end of stream.
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:733)
	at com.cloud.utils.nio.Link.doHandshakeUnwrap(Link.java:490)
	at com.cloud.utils.nio.Link.doHandshake(Link.java:618)
	at com.cloud.utils.nio.NioConnection$1.run(NioConnection.java:216)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-11:null) (logid:) Failed to send server's CLOSE message due to socket channel's failure.
INFO  [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-7:null) (logid:) Connection from /192.168.0.104 closed but no cleanup was done. <br/><br/>
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-11:null) (logid:) SSL error caught during wrap data: Empty server certificate chain, for local address=/192.168.0.104:8250, remote address=/192.168.0.104:56610.
WARN  [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-4:null) (logid:) This SSL engine was forced to close inbound due to end of stream.
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:733)
	at com.cloud.utils.nio.Link.doHandshakeUnwrap(Link.java:490)
	at com.cloud.utils.nio.Link.doHandshake(Link.java:618)
	at com.cloud.utils.nio.NioConnection$1.run(NioConnection.java:216)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-4:null) (logid:) Failed to send server's CLOSE message due to socket channel's failure.
INFO  [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-8:null) (logid:) Connection from /192.168.0.104 closed but no cleanup was done.
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-5:null) (logid:) SSL error caught during wrap data: Empty server certificate chain, for local address=/192.168.0.104:8250, remote address=/192.168.0.104:56612.
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-5:null) (logid:) SSL error caught during wrap data: Empty server certificate chain, for local address=/192.168.0.104:8250, remote address=/192.168.0.104:56616.
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-4:null) (logid:) SSL error caught during wrap data: Empty server certificate chain, for local address=/192.168.0.104:8250, remote address=/192.168.0.104:56618.
WARN  [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-9:null) (logid:) This SSL engine was forced to close inbound due to end of stream.
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:283)
	at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:733)
	at com.cloud.utils.nio.Link.doHandshakeUnwrap(Link.java:490)
	at com.cloud.utils.nio.Link.doHandshake(Link.java:618)
	at com.cloud.utils.nio.NioConnection$1.run(NioConnection.java:216)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-9:null) (logid:) Failed to send server's CLOSE message due to socket channel's failure.

I stucked and I'm new to apache cloudstack and my environments: ubuntu 20.04.<br/>
Can anyone suggest me how to fix that issue?

**Comment by rohityadavcloud** [comment]
@sotheareth are you running KVM agent (cloudstack-agent) on the same host? Can you redeploy your dev-test env, or re-add the host with ssh allowed on root user using password (in sshd_config you've to permit root login by password). Alternatively, you can also explore using mbx: https://github.com/shapeblue/mbx
The specific user-shared network branch may not be ready for testing yet, cc @weizhouapache

**Comment by sotheareth** [comment]
@rohityadavcloud 
- I installed cloudstack-agent on the same host and 
- already allow sshd_config for root: 
   `PermitRootLogin yes and PasswordAuthentication yes`
- I did not try your https://github.com/shapeblue/mbx yet

**Comment by rohityadavcloud** [comment]
@sotheareth Assuming you're doing something for testing, you can set the `ca.plugin.root.auth.strictness` global setting to false temporarily (this doesn't require restarting mgmt server) and then go to UI->Infra->Hosts-> select the host -> click the provision certificate button (this will re-initiatlise the host certificates). Then you can change the auth strictness global setting to true again and restart `cloudstack-agent`.
The possible cause for this issue is usually that when adding the KVM host the certificates for some reason weren't correctly setup (you may check logs to investigate further).

**Comment by sotheareth** [comment]
@rohityadavcloud 
- I'm not sure if run from source code it requires to install cloudstack-agent or is there any cloudstack-agent startup when I run from jetty.
- after I change ca.plugin.root.auth.strictness = false and it works fine
- I can add secondary storage - success
- now I have another issue 
I cannot add new host - error said 'Error 530 Unable to add the host'
and I check there is no any record for host table in datatabase

```
* Zone Name : primary-zone
* Pod name: primary-pod
* Cluster name: primary-cluster
* Host: 192.168.100.105
* Username: root
* Password: ...
```

- how does cloudstack look up the host?

**Comment by nvazquez** [comment]
Hi @sotheareth - the cloudstack-agent package needs to be installed on your KVM host (assuming you are using KVM). Also, check if the port 8250 is open as it is the port the management server and the host agent connect to

**Comment by rohityadavcloud** [comment]
@sotheareth were you able to get help? If not can you join our dev mailing list and continue there - 
https://cloudstack.apache.org/mailing-lists.html

Or additional resources:
https://github.com/shapeblue/hackerbook/blob/main/2-dev.md
