### ISSUE TITLE
Unable to start a VM due to insufficient capacity

### ISSUE THREAD

**Issue by alynio** [apache/cloudstack#5868]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Private use
~~~

##### CLOUDSTACK VERSION
~~~
4.16.
~~~

##### CONFIGURATION
~~~
Advance with 3 nics:
cloudbr - mgmt 
cloudbr1 - public
cloudbr0 - guest

Single server with nfs, mgmt, kvm
priamry and secondary storage from same nfs - space ~5TB

1 switch
1 firewall 
~~~~
##### OS / ENVIRONMENT
~~~~
CentOS 8
~~~~

##### SUMMARY
~~~~
~~~~
##### STEPS TO REPRODUCE
~~~~
try to use ISO or Templates same result  starting vm with 0.5GHz, 2048MiB and 10GB disk
~~~~

##### EXPECTED RESULTS
~~~~
Jan 15 19:16:07 kvm.cloud java[49839]: com.cloud.exception.InsufficientVirtualNetworkCapacityException: Unable to allocate vnet as a part of network Ntwk[208|Guest|8] implement Scope=interface com.cloud.dc.DataCenter; id=2
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.network.guru.GuestNetworkGuru.allocateVnet(GuestNetworkGuru.java:298)
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.network.guru.GuestNetworkGuru.implement(GuestNetworkGuru.java:327)
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.network.guru.ExternalGuestNetworkGuru.implement(ExternalGuestNetworkGuru.java:136)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.implementNetwork(NetworkOrchestrator.java:1329)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.implementNetwork(NetworkOrchestrator.java:1189)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepare(NetworkOrchestrator.java:1863)
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1201)
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5802)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5967)
Jan 15 19:16:07 kvm.cloud java[49839]:         at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
Jan 15 19:16:07 kvm.cloud java[49839]:         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 15 19:16:07 kvm.cloud java[49839]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jan 15 19:16:07 kvm.cloud java[43609]: libvirt: QEMU Driver error : Domain not found: no domain with matching name 'i-2-27-VM'
Jan 15 19:16:07 kvm.cloud java[43609]: INFO  [kvm.resource.LibvirtConnection] (agentRequest-Handler-4:) (logid:24cbf81b) No existing libvirtd connection found. Opening a new one
Jan 15 19:16:07 kvm.cloud libvirtd[41573]: Failed to connect socket to '/var/run/libvirt/virtlxcd-sock': No such file or directory
Jan 15 19:16:07 kvm.cloud libvirtd[41573]: End of file while reading data: Input/output error
Jan 15 19:16:07 kvm.cloud java[43609]: libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/virtlxcd-sock': No such file or directory
Jan 15 19:16:07 kvm.cloud java[43609]: WARN  [kvm.resource.LibvirtConnection] (agentRequest-Handler-4:) (logid:24cbf81b) Can not find a connection for Instance i-2-27-VM. Assuming the default connection.
Jan 15 19:16:07 kvm.cloud java[43609]: libvirt: QEMU Driver error : Domain not found: no domain with matching name 'i-2-27-VM'
Jan 15 19:16:07 kvm.cloud java[43609]: libvirt: QEMU Driver error : Domain not found: no domain with matching name 'i-2-27-VM'
Jan 15 19:16:07 kvm.cloud java[43609]: libvirt: QEMU Driver error : Domain not found: no domain with matching name 'i-2-27-VM'
Jan 15 19:16:08 kvm.cloud java[43609]: libvirt: QEMU Driver error : Domain not found: no domain with matching name 'i-2-27-VM'
Jan 15 19:16:08 kvm.cloud java[43609]: libvirt: QEMU Driver error : Domain not found: no domain with matching name 'i-2-27-VM'
Jan 15 19:16:08 kvm.cloud java[43609]: WARN  [kvm.resource.LibvirtKvmAgentHook] (agentRequest-Handler-4:) (logid:24cbf81b) Groovy script '/etc/cloudstack/agent/hooks/libvirt-vm-state-change.groovy' is not available. Transformations will>
Jan 15 19:16:08 kvm.cloud java[43609]: WARN  [kvm.resource.LibvirtKvmAgentHook] (agentRequest-Handler-4:) (logid:24cbf81b) Groovy scripting engine is not initialized. Data transformation skipped.
Jan 15 19:16:08 kvm.cloud java[49839]: ERROR [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-7:ctx-9f0df607 job-249/job-250 ctx-e5be9f11) (logid:24cbf81b) Invocation exception, caused by: com.cloud.exception.InsufficientServerCapacityE>
Jan 15 19:16:08 kvm.cloud java[49839]: INFO  [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-7:ctx-9f0df607 job-249/job-250 ctx-e5be9f11) (logid:24cbf81b) Rethrow exception com.cloud.exception.InsufficientServerCapacityException: Unabl>
Jan 15 19:16:08 kvm.cloud java[49839]: ERROR [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-7:ctx-9f0df607 job-249/job-250) (logid:24cbf81b) Unable to complete AsyncJobVO {id:250, userId: 2, accountId: 2, instanceType: null, instanceId:>
Jan 15 19:16:08 kvm.cloud java[49839]: com.cloud.exception.InsufficientServerCapacityException: Unable to create a deployment for VM instance {id: "27", name: "i-2-27-VM", uuid: "3c24b3a8-ff8c-4366-af2d-b382d92b0f76", type="User"}Scope=>
Jan 15 19:16:08 kvm.cloud java[49839]:         at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1162)
Jan 15 19:16:08 kvm.cloud java[49839]:         at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5802)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Jan 15 19:16:08 kvm.cloud java[49839]:         at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
Jan 15 19:16:08 kvm.cloud java[49839]:         at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5967)
Jan 15 19:16:08 kvm.cloud java[49839]:         at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
Jan 15 19:16:08 kvm.cloud java[49839]:         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
Jan 15 19:16:08 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
Jan 15 19:16:08 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
Jan 15 19:16:08 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
Jan 15 19:16:08 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
Jan 15 19:16:08 kvm.cloud java[49839]:         at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
Jan 15 19:16:08 kvm.cloud java[49839]:         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 15 19:16:08 kvm.cloud java[49839]:         at java.base/java.lang.Thread.run(Thread.java:829)
~~~~
##### ACTUAL RESULTS
~~~
VM not started
~~~

**Comment by weizhouapache** [comment]
@alynio 
could you please share the configuration of physical networks ?
from the log, it looks the gues vlan is not configured correctly.
`
Jan 15 19:16:07 kvm.cloud java[49839]: com.cloud.exception.InsufficientVirtualNetworkCapacityException: Unable to allocate vnet as a part of network Ntwk[208|Guest|8] implement Scope=interface com.cloud.dc.DataCenter; id=2
`

ps: it looks you run all services in a host. I suggest you to use mbx by Rohit (https://github.com/shapeblue/mbx)
Refer to https://rohityadav.cloud/files/talks/ccc21-mbx.pdf

**Comment by alynio** [comment]
I have made same diagnostics and and find out:
1. connection from systemvm:

> root@v-21-VM:/var/log/cloud# curl -kv http://www.onet.pl
> *  Trying 54.192.230.48:80...
> * Connected to www.onet.pl (54.192.230.48) port 80 (#0)
> > GET / HTTP/1.1
> > Host: www.onet.pl
> > User-Agent: curl/7.74.0
> > Accept: */*
> >
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 301 Moved Permanently
> < Content-Type: text/html
> < Content-Length: 162
> < Connection: keep-alive
> < Server: Ring Publishing - Accelerator
> < Date: Wed, 19 Jan 2022 14:45:34 GMT
> < Location: https://www.onet.pl/
> < set-cookie: acc_segment=93; Path=/; Max-Age=604800
> < vary: user-agent
> < X-Cache: Miss from cloudfront
> < Via: 1.1 2e8f70eb03b681aa6bd8c18fff081f80.cloudfront.net (CloudFront)
> < X-Amz-Cf-Pop: WAW50-C1
> < X-Amz-Cf-Id: P3dUXCWKwekRRvjmZEFTYvjsxcpqNP1PSCyV_uNERnSN3e_QezBq5g==
> <
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body>
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> * Connection #0 to host www.onet.pl left intact
> 
2. next 

> root@v-21-VM:/var/log/cloud# curl -kv http://192.168.0.252:8250
> *   Trying 192.168.0.252:8250...
> * connect to 192.168.0.252 port 8250 failed: No route to host
> * Failed to connect to 192.168.0.252 port 8250: No route to host
> * Closing connection 0
> curl: (7) Failed to connect to 192.168.0.252 port 8250: No route to host
> 

3. next

> root@v-21-VM:/var/log/cloud# ping 192.168.0.252
> PING 192.168.0.252 (192.168.0.252): 56 data bytes
> 64 bytes from 192.168.0.252: icmp_seq=0 ttl=64 time=0.070 ms
> 64 bytes from 192.168.0.252: icmp_seq=1 ttl=64 time=0.055 ms
> 64 bytes from 192.168.0.252: icmp_seq=2 ttl=64 time=0.062 ms
> ^C--- 192.168.0.252 ping statistics ---
> 3 packets transmitted, 3 packets received, 0% packet loss
> round-trip min/avg/max/stddev = 0.055/0.062/0.070/0.000 ms
> 

4. again test

> root@v-21-VM:/var/log/cloud# curl -kv http://192.168.0.252:8250
> *   Trying 192.168.0.252:8250...
> * connect to 192.168.0.252 port 8250 failed: No route to host
> * Failed to connect to 192.168.0.252 port 8250: No route to host
> * Closing connection 0
> curl: (7) Failed to connect to 192.168.0.252 port 8250: No route to host
> 

5. check routes

> root@v-21-VM:/var/log/cloud# ip r
> default via 192.168.12.252 dev eth2
> 8.8.8.8 via 192.168.0.1 dev eth1
> 169.254.0.0/16 dev eth0 proto kernel scope link src 169.254.143.165
> 192.168.0.0/24 dev eth1 proto kernel scope link src 192.168.0.53
> 192.168.12.0/24 dev eth2 proto kernel scope link src 192.168.12.20
> 

Any idea why it dosn't work correctly?

**Comment by weizhouapache** [comment]
> * 192.168.0.252

is `192.168.0.252` your management server ip ?

please check the firewall rules on mgmt server and v-21-VM.
please upload the result of command `iptables-save` if you need help.

**Comment by sureshanaparti** [comment]
> > * 192.168.0.252
> 
> is `192.168.0.252` your management server ip ?
> 
> please check the firewall rules on mgmt server and v-21-VM. please upload the result of command `iptables-save` if you need help.

Hi @alynio Can you check / share these details please.
