### ISSUE TITLE
Cannot deploy a VM - IO_URING is not supported with Advanced virtualization

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#6252]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM agent
~~~

##### CLOUDSTACK VERSION

~~~
main and CS versions that support io uring
~~~

##### CONFIGURATION

Basic network

##### OS / ENVIRONMENT

Rocky Linux on CS managements and agents

libvirt/qemu version with Advanced virtualization
Compiled against library: libvirt 7.6.0
Using library: libvirt 7.6.0
Using API: QEMU 7.6.0
Running hypervisor: QEMU 6.0.0

##### STEPS TO REPRODUCE

~~~
install Advanced virtualization on the agents
deploy a VM
~~~

##### EXPECTED RESULTS

~~~
The VM is successfully deployed
~~~

##### ACTUAL RESULTS

~~~
org.libvirt.LibvirtException: unsupported configuration: io uring is not supported by this QEMU binary
        at org.libvirt.ErrorHandler.processError(Unknown Source)
        at org.libvirt.ErrorHandler.processError(Unknown Source)
        at org.libvirt.Connect.domainCreateXML(Unknown Source)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.startVM(LibvirtComputingResource.java:1774)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStartCommandWrapper.execute(LibvirtStartCommandWrapper.java:86)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStartCommandWrapper.execute(LibvirtStartCommandWrapper.java:46)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1806)
        at com.cloud.agent.Agent.processRequest(Agent.java:660)
        at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1078)
        at com.cloud.utils.nio.Task.call(Task.java:83)
        at com.cloud.utils.nio.Task.call(Task.java:29)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

~~~

**Comment by nvazquez** [comment]
Fixed on #6253
