### ISSUE TITLE
Veeam v11.0.1.1261 doesn't work with Cloudstack

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#6465]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Veeam Backup
~~~

##### CLOUDSTACK VERSION

~~~
Cloudstack 4.16.1
~~~

##### SUMMARY

When testing Veeam v11.0.1.1261,  the restoration of the executed backup jobs, they are not listed by CloudStack, either in the UI or via cloudmonkey.

##### LOGS
```
022-06-09 03:56:42,404 ERROR [o.a.c.b.BackupManagerImpl](backgroundtaskpollmanager-2:ctx-7b902d72) (logid:3a83e4bd) Failed to sync backup usage metrics and out-of-band backups due to: [DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO backups (backups.uuid, backups.vm_id, backups.external_id, backups.type, backups.date, backups.size, backups.protected_size, backups.status, backups.backup_offering_id, backups.account_id, backups.domain_id, backups.zone_id) VALUES (_binary'38982c57-a15d-4357-ac03-7d0ede3906fa', 334, null, null, null, 1320157184, 13988368893, 'BackedUp', 4, 23, 16, 1)].
com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO backups (backups.uuid, backups.vm_id, backups.external_id, backups.type, backups.date, backups.size, backups.protected_size, backups.status, backups.backup_offering_id, backups.account_id, backups.domain_id, backups.zone_id) VALUES (_binary'38982c57-a15d-4357-ac03-7d0ede3906fa', 334, null, null, null, 1320157184, 13988368893, 'BackedUp', 4, 23, 16, 1)
        at com.cloud.utils.db.GenericDaoBase.persist(GenericDaoBase.java:1462)
        at jdk.internal.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy307.persist(Unknown Source)
        at org.apache.cloudstack.backup.VeeamBackupProvider$1.doInTransactionWithoutResult(VeeamBackupProvider.java:299)
        at com.cloud.utils.db.TransactionCallbackNoReturn.doInTransaction(TransactionCallbackNoReturn.java:25)
        at com.cloud.utils.db.Transaction$2.doInTransaction(Transaction.java:50)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:40)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:47)
        at org.apache.cloudstack.backup.VeeamBackupProvider.syncBackups(VeeamBackupProvider.java:256)
        at org.apache.cloudstack.backup.BackupManagerImpl$BackupSyncTask.runInContext(BackupManagerImpl.java:1034)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'type' cannot be null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        … 38 more
```

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6555
