### ISSUE TITLE
ConfigDrive Exception after 4.17 upgrade (unable to start/migrate VMs)

### ISSUE THREAD

**Issue by FStelzer** [apache/cloudstack#6490]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Network Offerings
~~~

##### CLOUDSTACK VERSION
~~~
4.17
~~~

##### CONFIGURATION
Network offering: L2 Network, Specify VLAN, Enabled ConfigDrive

##### OS / ENVIRONMENT
Rocky Linux 8

##### SUMMARY
Unable to migrate or start any VMs using the network offering with the config drive.
This always results in the following exception:

2022-06-23 07:10:48,056 ERROR [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-2:ctx-dd9564ec job-1057/job-1058 ctx-f64a4301) (logid:dd88bfcd) Invocation exception, caused by: java.lang.ClassCastException: class com.cloud.agent.api.Answer cannot be cast to class com.cloud.agent.api.HandleConfigDriveIsoAnswer (com.cloud.agent.api.Answer and com.cloud.agent.api.HandleConfigDriveIsoAnswer are in unnamed module of loader 'app')
2022-06-23 07:10:48,059 INFO  [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-2:ctx-dd9564ec job-1057/job-1058 ctx-f64a4301) (logid:dd88bfcd) Rethrow exception java.lang.ClassCastException: class com.cloud.agent.api.Answer cannot be cast to class com.cloud.agent.api.HandleConfigDriveIsoAnswer (com.cloud.agent.api.Answer and com.cloud.agent.api.HandleConfigDriveIsoAnswer are in unnamed module of loader 'app')
2022-06-23 07:10:48,059 ERROR [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-2:ctx-dd9564ec job-1057/job-1058) (logid:dd88bfcd) Unable to complete AsyncJobVO: {id:1058, userId: 2, accountId: 2, instanceType: null, instanceId: null, cmd: com.cloud.vm.VmWorkStart, cmdInfo: rO0ABXNyABhjb20uY2xvdWQudm0uVm1Xb3JrU3RhcnR9cMGsvxz73gIAC0oABGRjSWRMAAZhdm9pZHN0ADBMY29tL2Nsb3VkL2RlcGxveS9EZXBsb3ltZW50UGxhbm5lciRFeGNsdWRlTGlzdDtMAAljbHVzdGVySWR0ABBMamF2YS9sYW5nL0xvbmc7TAAGaG9zdElkcQB-AAJMAAtqb3VybmFsTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAEXBoeXNpY2FsTmV0d29ya0lkcQB-AAJMAAdwbGFubmVycQB-AANMAAVwb2RJZHEAfgACTAAGcG9vbElkcQB-AAJMAAlyYXdQYXJhbXN0AA9MamF2YS91dGlsL01hcDtMAA1yZXNlcnZhdGlvbklkcQB-AAN4cgATY29tLmNsb3VkLnZtLlZtV29ya5-ZtlbwJWdrAgAESgAJYWNjb3VudElkSgAGdXNlcklkSgAEdm1JZEwAC2hhbmRsZXJOYW1lcQB-AAN4cAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAFHQAGVZpcnR1YWxNYWNoaW5lTWFuYWdlckltcGwAAAAAAAAAAXBzcgAOamF2YS5sYW5nLkxvbmc7i-SQzI8j3wIAAUoABXZhbHVleHIAEGphdmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAAAAAAAAJzcQB-AAgAAAAAAAAAHXBwcHNxAH4ACAAAAAAAAAABcHNyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3CAAAABAAAAABdAAKVm1QYXNzd29yZHQAHHJPMEFCWFFBRG5OaGRtVmtYM0JoYzNOM2IzSmt4cA, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 264216228867562, completeMsid: null, lastUpdated: null, lastPolled: null, created: Thu Jun 23 07:10:46 UTC 2022, removed: null}, job origin:1057
java.lang.ClassCastException: class com.cloud.agent.api.Answer cannot be cast to class com.cloud.agent.api.HandleConfigDriveIsoAnswer (com.cloud.agent.api.Answer and com.cloud.agent.api.HandleConfigDriveIsoAnswer are in unnamed module of loader 'app')
	at com.cloud.network.element.ConfigDriveNetworkElement.createConfigDriveIso(ConfigDriveNetworkElement.java:603)
	at com.cloud.network.element.ConfigDriveNetworkElement.addPasswordAndUserdata(ConfigDriveNetworkElement.java:226)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareElement(NetworkOrchestrator.java:1620)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareNic(NetworkOrchestrator.java:1946)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepare(NetworkOrchestrator.java:1880)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1177)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
	at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5439)
	at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-06-23 07:10:48,073 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (Work-Job-Executor-2:ctx-dd9564ec job-1057/job-1058) (logid:dd88bfcd) Remove job-1058 from job monitoring
2022-06-23 07:10:48,095 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-2:ctx-e21e3f09 job-1057) (logid:dd88bfcd) Unexpected exception while executing org.apache.cloudstack.api.command.admin.vm.StartVMCmdByAdmin
java.lang.ClassCastException: class com.cloud.agent.api.Answer cannot be cast to class com.cloud.agent.api.HandleConfigDriveIsoAnswer (com.cloud.agent.api.Answer and com.cloud.agent.api.HandleConfigDriveIsoAnswer are in unnamed module of loader 'app')
	at com.cloud.network.element.ConfigDriveNetworkElement.createConfigDriveIso(ConfigDriveNetworkElement.java:603)
	at com.cloud.network.element.ConfigDriveNetworkElement.addPasswordAndUserdata(ConfigDriveNetworkElement.java:226)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareElement(NetworkOrchestrator.java:1620)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepareNic(NetworkOrchestrator.java:1946)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepare(NetworkOrchestrator.java:1880)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1177)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5315)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
	at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5439)
	at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

##### STEPS TO REPRODUCE
Migrate or start a VM using a network offering with configdrive after upgrading to 4.17

For now I would be fine with removing the config drive from the offering. (We only use it on intial vm creation).
But as the UI does not allow doing this I'm unsure on how to safely do so in the DB.
Do i just delete the entry from ntwk_service_map ?

**Comment by slavkap** [comment]
@FStelzer, did you upgrade the system VMs (e.g. virtual router, secondary storage VM and the console proxy)? Can you try to recreate them if you didn't after the upgrade

**Comment by FStelzer** [comment]
@slavkap thanks, that did it. I read about the live patching in the upgrade guide and didn't think it necessary. The mgmt server exception made me suspect a code bug.

Thanks for your help.

**Comment by weizhouapache** [comment]
@FStelzer 
has the issue been solved ?

**Comment by FStelzer** [comment]
@weizhouapache yes, thanks. the recreate of the system VMs was all that was needed
