### ISSUE TITLE
Problem With Creating Isolated Network 

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#6727]
##### ISSUE TYPE
 * Bug Report
##### CLOUDSTACK VERSION
CloudStack 4.17.0.1-snapshot.20220904

##### CONFIGURATION
Advance Network
2 physical Network Interface
Vmware Hypervisor : 1vSwitch0 and 1vds

##### SUMMARY
i installed cloudstack from nightly version and in wizard stage i set guest vlan range but after the installation was complete i realized that it wasn't set up and i had trouble building the isolated network. i couldn't connect any vms to this network. but after adding the vlan manually everything became ok.

##### STEPS TO REPRODUCE
com.cloud.exception.InsufficientVirtualNetworkCapacityException: Unable to allocate vnet as a part of network Network {"id": 219, "name": "MyIsolated", "uuid": "67de4f3a-4c47-4ebe-9b05-83a02a7bd4ca", "networkofferingid": 9} implement Scope=interface com.cloud.dc.DataCenter; id=2
        at com.cloud.network.guru.GuestNetworkGuru.allocateVnet(GuestNetworkGuru.java:334)
        at com.cloud.network.guru.GuestNetworkGuru.implement(GuestNetworkGuru.java:363)
        at com.cloud.network.guru.ExternalGuestNetworkGuru.implement(ExternalGuestNetworkGuru.java:154)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.implementNetwork(NetworkOrchestrator.java:1339)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.implementNetwork(NetworkOrchestrator.java:1199)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.prepare(NetworkOrchestrator.java:1873)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1177)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5315)
        at jdk.internal.reflect.GeneratedMethodAccessor839.invoke(Unknown Source)
##### EXPECTED RESULTS
Guest Vlan Range Set Correctly

##### ACTUAL RESULTS
![Untitled](https://user-images.githubusercontent.com/104001728/189525513-64c0129c-de61-4109-85e1-8d458c2307f2.png)

**Comment by weizhouapache** [comment]
@ahmadamirahmadi007 
it looks not like a bug.

the "VLAN/VNI" is empty for the guest physical network.
please click "Physical Network 2", then click "Update physical network" icon on the top right corner and input  vlan range ( for example 1100-1200, make sure you have configured vlan correctly on your upsteam router) .

**Comment by ahmadamirahmadi007** [comment]
i know. i also had to manually insert it after the wizard process. while in stable version after configuring VLAN in wizard that is automatically set

**Comment by shwstppr** [comment]
@ahmadamirahmadi007 In which stable version this behaviour was different?
I think the new UI always allowed updating VLAN for a particular traffic type in the zone wizard
![Screenshot from 2022-09-12 15-40-56](https://user-images.githubusercontent.com/153340/189629780-586d94dd-9a77-49d2-9e26-c14f39778ad2.png)
Removing this from 4.17.1.0 milestone from now
