### ISSUE TITLE
Failed to update VM, due to: Invalid cpu speed value, specify a value between 1 and 2147483647 - UI bug

### ISSUE THREAD

**Issue by ccycv** [apache/cloudstack#6780]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0, 4.17.1
~~~

##### CONFIGURATION

~~~
NA
~~~
##### OS / ENVIRONMENT

Ubuntu 20.04, CentOS 7.9

##### SUMMARY
~~~
If I try to edit any settings under instance, I always get the same error, no matter if is not related to CPU.
~~~
##### STEPS TO REPRODUCE

~~~
There are no specific steps, just try to edit or add new value.
~~~

##### EXPECTED RESULTS

~~~
No error
~~~

##### ACTUAL RESULTS

~~~
2022-09-28 11:31:07,972 ERROR [c.c.a.ApiServer] (qtp1462044018-8587:ctx-4c809300 ctx-86f28f31) (logid:09b4a52b) unhandled exception executing api command: [Ljava.lang.String;@768c17d5
com.cloud.utils.exception.CloudRuntimeException: Failed to update VM, due to: Invalid cpu speed value, specify a value between 1 and 2147483647
        at org.apache.cloudstack.api.command.user.vm.UpdateVMCmd.execute(UpdateVMCmd.java:271)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:163)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:776)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:600)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:327)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:145)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:142)
        at com.cloud.api.ApiServlet.doGet(ApiServlet.java:96)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.cloud.exception.InvalidParameterValueException: Invalid cpu speed value, specify a value between 1 and 2147483647
        at com.cloud.vm.UserVmManagerImpl.validateCustomParameters(UserVmManagerImpl.java:1179)
        at com.cloud.vm.UserVmManagerImpl.verifyVmLimits(UserVmManagerImpl.java:2661)
        at com.cloud.vm.UserVmManagerImpl.updateVirtualMachine(UserVmManagerImpl.java:2767)
        ... 58 more
~~~

**Comment by ccycv** [comment]
![image](https://user-images.githubusercontent.com/23322009/192769039-cdaca118-91c1-4641-b1f6-e4bc4af78dd9.png)

**Comment by DaanHoogland** [comment]
> > @ccycv I just tried adding a `keyboard` setting in 4.17.1.0 and it worked without hiccup. Than I added `cpu.corespersocket` again without hiccup. Can you share your service-offering for this VM? Maybe the itch is there.
> 
> I just tested again, this occurs only if you have "cpuSpeed".

right, so you have an offering that allows for that?

**Comment by ccycv** [comment]
> > > @ccycv I just tried adding a `keyboard` setting in 4.17.1.0 and it worked without hiccup. Than I added `cpu.corespersocket` again without hiccup. Can you share your service-offering for this VM? Maybe the itch is there.
> > 
> > 
> > I just tested again, this occurs only if you have "cpuSpeed".
> 
> right, so you have an offering that allows for that?

Yes, if I deploy with such offering or set the CPU speed at deploy.

**Comment by DaanHoogland** [comment]
> > > > @ccycv I just tried adding a `keyboard` setting in 4.17.1.0 and it worked without hiccup. Than I added `cpu.corespersocket` again without hiccup. Can you share your service-offering for this VM? Maybe the itch is there.
> > > 
> > > 
> > > I just tested again, this occurs only if you have "cpuSpeed".
> > 
> > 
> > right, so you have an offering that allows for that?
> 
> Yes, if I deploy with such offering or set the CPU speed at deploy.

ok, i'll give it some more try

**Comment by DaanHoogland** [comment]
@ccycv can you please specify the offering here (or the cli you used. I can not reproduce this so far.
