### ISSUE TITLE
vmware: snapshot operation failure with VMs on datastorecluster

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#6894]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware hypervisor plugin
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1.0
~~~

##### CONFIGURATION

Advanced zone with VMware hypervisor having datastore-cluster storage

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Snapshot operations fails for VMs that have volumes on datastore cluster.
Seen with VMs that have correct DB records wrt vCenter

##### STEPS TO REPRODUCE

~~~
Deploy a VM with volumes on DatastoreCluster storage
Initiate a snapshot operation - create, delete, revert
~~~

##### EXPECTED RESULTS

~~~
Snapshot operation works without any error
~~~

##### ACTUAL RESULTS
Snapshot operation fails

~~~
2022-11-11 05:12:27,677 ERROR [c.c.h.v.m.VmwareStorageManagerImpl] (DirectAgent-19:ctx-80524b18 10.1.35.103, job-138/job-139, cmd: DeleteVMSnapshotCommand) (logid:b16f018f) failed to delete vm snapshot i-2-11-VM_VS_20221111045555 of vm i-2-11-VM due to null
java.lang.NullPointerException
	at com.cloud.hypervisor.vmware.mo.HypervisorHostHelper.findDatastoreWithBackwardsCompatibility(HypervisorHostHelper.java:241)
	at com.cloud.hypervisor.vmware.manager.VmwareStorageManagerImpl.getDatastoreAsManagedObjectReference(VmwareStorageManagerImpl.java:1327)
	at com.cloud.hypervisor.vmware.manager.VmwareStorageManagerImpl.setVolumeToPathAndSize(VmwareStorageManagerImpl.java:1302)
	at com.cloud.hypervisor.vmware.manager.VmwareStorageManagerImpl.execute(VmwareStorageManagerImpl.java:1367)
	at com.cloud.hypervisor.vmware.manager.VmwareStorageManagerImpl.execute(VmwareStorageManagerImpl.java:95)
	at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:5427)
	at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:574)
	at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6907

**Comment by vladimirpetrov** [comment]
LGTM based on manual testing.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6912
