### ISSUE TITLE
cloudstack-setup-management causes failure on EL7

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7108]
I'm not sure if this is a blocker at this time. The failure is caused by mysql-connector dependency:

```
[root@qa1-vmw8-test-7848d32d-vmw-mgmt1 ~]# cloudstack-setup-management
Traceback (most recent call last):
  File "/usr/bin/cloudstack-setup-management", line 24, in <module>
    from cloudutils.serviceConfigServer import cloudManagementConfig
  File "/usr/lib64/python3.6/site-packages/cloudutils/serviceConfigServer.py", line 17, in <module>
    from .db import Database
  File "/usr/lib64/python3.6/site-packages/cloudutils/db.py", line 20, in <module>
    import mysql.connector
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/__init__.py", line 32, in <module>
    from .connection_cext import CMySQLConnection
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 40, in <module>
    from .abstracts import MySQLConnectionAbstract
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 33
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[root@qa1-vmw8-test-7848d32d-vmw-mgmt1 ~]# python --version
Python 2.7.5
[root@qa1-vmw8-test-7848d32d-vmw-mgmt1 ~]# python3 --version
Python 3.6.8
[root@qa1-vmw8-test-7848d32d-vmw-mgmt1 ~]# pip3 freeze
importlib-resources==5.4.0
libvirt-python==4.5.0
mysql-connector-python==8.0.32
netaddr==0.8.0
protobuf==3.19.6
zipp==3.6.0
```

However, installing mysql-connector-python version 8.0.19 works:

```
[root@qa1-vmw8-test-7848d32d-vmw-mgmt1 ~]# pip3 install mysql-connector-python==8.0.19
[root@qa1-vmw8-test-7848d32d-vmw-mgmt1 ~]# cloudstack-setup-management
Starting to configure CloudStack Management Server:
Configure CloudStack Management Server ...[OK]
CloudStack Management Server setup is Done!
Please ensure ports 8080, 8250, 8443, and 9090 are opened and not firewalled for the management server and not in use by other processes on this host.
```

**Comment by rohityadavcloud** [comment]
cc just FYI @DaanHoogland @weizhouapache - to be noted that new mysql-connector dependency can have issues. I found we already install a specific mysql-connector version so this isn't an issue.

**Comment by weizhouapache** [comment]
@rohityadavcloud 
yes, this is a known issue. we have fixed it in trillian.
https://github.com/shapeblue/Trillian/commit/6de930030683f88422b623a7b250b704f065a847
