### ISSUE TITLE
[4.18/main] CPVM does not work after live-patch

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#7123]
Steps to reproduce the issue
- deploy 4.17.2.0 environment
- upgrade to 4.18.0.0 nightly
- live-patch CPVM
- open vm console

some errors logs in /var/log/cloud.log

```
2023-01-23 11:55:07,946 INFO  [cloud.agent.Agent] (agentRequest-Handler-4:null) Set agent id 3
2023-01-23 11:55:07,952 INFO  [cloud.consoleproxy.ConsoleProxy] (Console-Proxy-Main:null) Setting reconnectMaxRetry=5
2023-01-23 11:55:07,953 INFO  [cloud.consoleproxy.ConsoleProxyBaseServerFactoryImpl] (Console-Proxy-Main:null) create HTTP server instance at port: 80
2023-01-23 11:55:07,956 INFO  [cloud.agent.Agent] (agentRequest-Handler-4:null) Processed new management server list: 10.0.32.246@static
2023-01-23 11:55:07,957 INFO  [cloud.agent.Agent] (agentRequest-Handler-4:null) Ready command is processed for agent id = 3
2023-01-23 11:55:07,957 INFO  [resource.consoleproxy.ConsoleProxyResource] (agentRequest-Handler-4:null) Receive ReadyCommand, response with ReadyAnswer
2023-01-23 11:55:08,001 ERROR [cloud.consoleproxy.ConsoleProxyNoVNCServer] (Console-Proxy-Main:null) Cannot read the VNC port from the file /root/vncport setting it to 8080
java.nio.file.NoSuchFileException: /root/vncport
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
        at java.base/java.nio.file.Files.readString(Files.java:3284)
        at java.base/java.nio.file.Files.readString(Files.java:3243)
        at com.cloud.consoleproxy.ConsoleProxyNoVNCServer.getVNCPort(ConsoleProxyNoVNCServer.java:47)
        at com.cloud.consoleproxy.ConsoleProxy.getNoVNCServer(ConsoleProxy.java:406)
        at com.cloud.consoleproxy.ConsoleProxy.startupHttpMain(ConsoleProxy.java:396)
        at com.cloud.consoleproxy.ConsoleProxy.start(ConsoleProxy.java:363)
        at com.cloud.consoleproxy.ConsoleProxy.startWithContext(ConsoleProxy.java:348)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.cloud.agent.resource.consoleproxy.ConsoleProxyResource$1.runInContext(ConsoleProxyResource.java:346)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-01-23 11:55:08,344 INFO  [cloud.consoleproxy.ConsoleProxy] (Console-Proxy-Main:null) Listening for HTTP CMDs on port 8001
2023-01-23 11:58:10,585 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-12:null) Get resource request for /resource/noVNC/vnc.html
2023-01-23 11:58:10,613 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-12:null) Sent file /resource/noVNC/vnc.html with content type text/html
2023-01-23 11:58:11,151 ERROR [cloud.consoleproxy.ConsoleProxyHttpHandlerHelper] (qtp265708179-40:null) decode token. host info is not found!
2023-01-23 11:58:11,226 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-13:null) Get resource request for /resource/noVNC/app/images/error.svg
2023-01-23 11:58:11,231 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-13:null) file does not exist/resource/noVNC/app/images/error.svg

```

this seems to be caused by #6577 

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
CPVM
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@nvazquez 
can you have  a look ?

**Comment by nvazquez** [comment]
@weizhouapache thanks, a workaround would be recreating the CPVM, I will work on a fix

**Comment by nvazquez** [comment]
@weizhouapache I could not reproduce the issue with the CPVM, however after livepatching the SSVM it got in Disconnected state so I had to recreate it. The exception logged does not stop the CPVM server, it returns the default port 8080: https://github.com/apache/cloudstack/pull/6577/files#diff-9415c2561c0483bb73c2c99f0479fd76f8f799b91317eb91faf6c3f25583237fR49

**Comment by weizhouapache** [comment]
> NoSuchFileException

@nvazquez 
ah ok, so only the error is printed, the process will continue.

thanks for checking.

closing it then.
