### ISSUE TITLE
tests should only run when applicable for adv-sg zone in such env

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7155]
##### ISSUE TYPE

 * Documentation Report
 * testing/CI

##### COMPONENT NAME

~~~
marvin
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

~~~
advanced zone with security groups.
~~~

##### SUMMARY

when an advanced zone with security groups is used to test for regressions, a lot of errors occur.
an example
```
ERROR: test suite for <class 'tests.smoke.test_router_dns.TestRouterDns'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/marvin/tests/smoke/test_router_dns.py", line 92, in setUpClass
    zoneid=cls.zone.id)
  File "/usr/local/lib/python3.6/site-packages/marvin/lib/base.py", line 3562, in create
    return Network(apiclient.createNetwork(cmd).__dict__)
  File "/usr/local/lib/python3.6/site-packages/marvin/cloudstackAPI/cloudstackAPIClient.py", line 2981, in createNetwork
    response = self.connection.marvinRequest(command, response_type=response, method=method)
  File "/usr/local/lib/python3.6/site-packages/marvin/cloudstackConnection.py", line 381, in marvinRequest
    raise e
  File "/usr/local/lib/python3.6/site-packages/marvin/cloudstackConnection.py", line 376, in marvinRequest
    raise self.__lastError
  File "/usr/local/lib/python3.6/site-packages/marvin/cloudstackConnection.py", line 310, in __parseAndGetResponse
    response_cls)
  File "/usr/local/lib/python3.6/site-packages/marvin/jsonHelper.py", line 155, in getResultObj
    raise cloudstackException.CloudstackAPIException(respname, errMsg)
marvin.cloudstackException.CloudstackAPIException: Execute cmd: createnetwork failed, due to: errorCode: 431, errorText:Only shared guest network can be created in security group enabled zone
```

this is not necessary as we know beforehand that these tests will fail.
Tests need to be properly tagged to not run in these environments.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
test will not run
~~~

##### ACTUAL RESULTS

~~~
test runs and fails
~~~

**Comment by weizhouapache** [comment]
good start ! 
@DaanHoogland

**Comment by lak7** [comment]
I would love to handle this issue. Can you assign this issue to me.

**Comment by DaanHoogland** [comment]
go ahead @lak7 , create a PR and we'll go from there. Note however that creating a test environment with an advanced zone with security groups and a marvin test environment in no small feat if you are new to the project.

**Comment by lak7** [comment]
Thanks! I will try my best.

**Comment by DaanHoogland** [comment]
@lak7 I am unassigning you . please feel free to pick up when ready anyway

**Comment by adithyanms-debug** [comment]
Hey guys i am new to open source contribution is it great to work with this issue as a beginner. If i can how should i approach this

**Comment by DaanHoogland** [comment]
@adithyanms-debug maybe this resolving this is not hard, but creating a list of tests that should not run in an advanced-zone with Security groups is. a regression test suite should be run against/inb such a zone and failures assessed to be genuine or due to not being applicable in such an environment. I will run such a test suite and link the results here.

https://github.com/apache/cloudstack/pull/12198#issuecomment-3805657704 should lead to the results that need addressing. Feel free to reclude yourself @adithyanms-debug , as it is maybe not so much a beginners issue.
