### ISSUE TITLE
Kubernetes scale up on 4.17.2.0

### ISSUE THREAD

**Issue by tuanhoangth1603** [apache/cloudstack#7504]
Hello,
Have a good day team !
I created a Kubernetes cluster with two control nodes and one worker. Then I tried to manually scale up by adding three more workers, but an error message appeared on the dashboard saying _"Scaling failed for Kubernetes cluster: K8S-Dev, unable to update network rules."_ I checked the management log and found details about the error.
```
2023-05-09 18:13:38,304 DEBUG [c.c.u.d.T.Transaction] (API-Job-Executor-105:ctx-567d2785 job-2167 ctx-c4f4e780) (logid:2277cf45) Rolling back the transaction: Time = 29 Name =  API-Job-Executor-105; called by -TransactionLegacy.rollback:888-TransactionLegacy.removeUpTo:831-TransactionLegacy.close:655-Transaction.execute:38-FirewallManagerImpl.createFirewallRule:242-FirewallManagerImpl.createIngressFirewallRule:194-GeneratedMethodAccessor846.invoke:-1-DelegatingMethodAccessorImpl.invoke:43-Method.invoke:566-AopUtils.invokeJoinpointUsingReflection:344-ReflectiveMethodInvocation.invokeJoinpoint:198-ReflectiveMethodInvocation.proceed:163
2023-05-09 18:13:38,321 ERROR [c.c.k.c.a.KubernetesClusterActionWorker] (API-Job-Executor-105:ctx-567d2785 job-2167 ctx-c4f4e780) (logid:2277cf45) Scaling failed for Kubernetes cluster : K8S-Dev, unable to update network rules
com.cloud.exception.NetworkRuleConflictException: The range specified, 2222-2227, conflicts with rule 216 which has 2222-2224
        at com.cloud.network.firewall.FirewallManagerImpl.detectRulesConflict(FirewallManagerImpl.java:470)
        at com.cloud.network.firewall.FirewallManagerImpl$1.doInTransaction(FirewallManagerImpl.java:255)
        at com.cloud.network.firewall.FirewallManagerImpl$1.doInTransaction(FirewallManagerImpl.java:242)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:40)
        at com.cloud.network.firewall.FirewallManagerImpl.createFirewallRule(FirewallManagerImpl.java:242)
        at com.cloud.network.firewall.FirewallManagerImpl.createIngressFirewallRule(FirewallManagerImpl.java:194)
        at jdk.internal.reflect.GeneratedMethodAccessor846.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:52)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy276.createIngressFirewallRule(Unknown Source)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterResourceModifierActionWorker.provisionFirewallRules(KubernetesClusterResourceModifierActionWorker.java:446)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterScaleWorker.scaleKubernetesClusterNetworkRules(KubernetesClusterScaleWorker.java:148)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterScaleWorker.scaleUpKubernetesClusterSize(KubernetesClusterScaleWorker.java:369)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterScaleWorker.scaleKubernetesClusterSize(KubernetesClusterScaleWorker.java:405)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterScaleWorker.scaleCluster(KubernetesClusterScaleWorker.java:439)
        at com.cloud.kubernetes.cluster.KubernetesClusterManagerImpl.scaleKubernetesCluster(KubernetesClusterManagerImpl.java:1315)
        at org.apache.cloudstack.api.command.user.kubernetes.cluster.ScaleKubernetesClusterCmd.execute(ScaleKubernetesClusterCmd.java:162)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:163)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:106)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-05-09 18:13:38,333 INFO  [c.c.k.c.a.KubernetesClusterActionWorker] (API-Job-Executor-105:ctx-567d2785 job-2167 ctx-c4f4e780) (logid:2277cf45) Revoking launch permission for systemVM template
2023-05-09 18:13:38,343 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-105:ctx-567d2785 job-2167) (logid:2277cf45) Complete async job-2167, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"530","errortext":"Scaling failed for Kubernetes cluster : CFOX-Dev, unable to update network rules"}
```
I see the message "The range specified, 2222-2227, conflicts with rule 216 which has 2222-2224". 
Does CloudStack have a function to replace conflicting rules? If not, how can we manually or auto-scale? 
My cluster has changed to Alert status, and I cannot do anything now except stop or delete the cluster.
Additionally, how can I put my cluster back to Health status? I have checked, and all pods in the cluster are still working fine.
Thanks !

**Comment by shwstppr** [comment]
@tuanhoangth1603 During scaling CloudStack tries to redo the firewall and portforwarding rules depending on the new cluster size. From your logs, it appears that it was not able to delete the old firewall rule and encountered an error while creating a new one. You may need to check how many node VMs the cluster is having right now and does listKubernetesClusters API returns the same size. If it is 6 (new size) then you may delete the firewall rule 2222-2224, add a new firewall rule 2222-2227 and verify if the portforwarding rules are correctly set. Thereafter KubernetesClusterStatusScanner should reconcile the cluster state.

**Comment by shwstppr** [comment]
@tuanhoangth1603 also, is this(issue while scaling) happening for all clusters in your env or just with this particular cluster?

**Comment by tuanhoangth1603** [comment]
Hi @shwstppr,
I tried scaling on a new cluster and didn't encounter a similar error. Perhaps the issue is only on the current cluster. I have created an additional instance that shares a network with this current cluster and added a firewall rule for that instance. Will doing so affect the automatic redo of the firewall rule when k8s scales?
Thanks !

**Comment by tuanhoangth1603** [comment]
@shwstppr 
Here is output of listKubernetesClusters API and screenshots of the instances list, firewall rules, and portwarding rules.
(I have changed some information for security reasons but it does not affect the information that you need.)
**CFOX-Dev** is the alerting cluster which I want to fix the state.
Thanks for your help !
https://gist.github.com/tuanhoangth1603/dc4c6484e8dc8a83a020871108d0f1ec
![image](https://github.com/apache/cloudstack/assets/38004836/b72e06b3-602d-4422-97aa-0613a2b68ce7)
![image](https://github.com/apache/cloudstack/assets/38004836/bba81ca2-0178-4066-b083-1db06e7cc63b)
![image](https://github.com/apache/cloudstack/assets/38004836/7db2fdab-9059-421f-8a30-22ec45c6af33)
![image](https://github.com/apache/cloudstack/assets/38004836/3252f33e-a17f-41ba-ae52-fa1a03b4cfc4)
![image](https://github.com/apache/cloudstack/assets/38004836/bac11d63-5065-45bc-8f42-5a3264e31a92)

**Comment by shwstppr** [comment]
@tuanhoangth1603 it seems your last 3 nodes never joined the k8s cluster due to error. In this case, I need to check but the only way to restore would be removing the extra node VMs alongwith the firewall and portforwarding rules. I'll check the code and may give you steps to proceed  tomorrow.

**Comment by weizhouapache** [comment]
this seems to be because there are 2 cks clusters deployed on same isolated network.

**Comment by weizhouapache** [comment]
It looks the first (pf port 2224) and last (pf port 2228)worker nodes worked well 
the other 3 (pf port 2225/2226/2227) did not .

it would be good to upload some logs in the control nodes and the 3 worker nodes with issues.

**Comment by weizhouapache** [comment]
scale up and scale down worked fine with CKS 1.26.6 ISO on my 4.18.1.0-snapshot environment

**Comment by DaanHoogland** [comment]
@tuanhoangth1603 , as it seems to work on current environement, I am closing this issue. Please reopen or open a new one if you feel there is still a problem.
