### ISSUE TITLE
[4.18] Restarting cloudstack-agent on Rocky Linux or RHEL does not work

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#7616]
After updating version.sh (see #7570) on rocky8/kvm nodes, restarting of cloudstack-agent failed with error

```
2023-06-09 14:49:01,657 DEBUG [c.c.a.m.AgentManagerImpl] (AgentConnectTaskPool-9:ctx-f3c5da4e) (logid:7f27c10b) Failed to handle host connection:
java.lang.IllegalArgumentException: Can't add host: 10.0.32.193 with hostOS: Rocky Linux into a cluster,in which there are Rocky hosts added
        at com.cloud.hypervisor.kvm.discoverer.LibvirtServerDiscoverer.createHostVOForConnectedAgent(LibvirtServerDiscoverer.java:474)
        at com.cloud.resource.ResourceManagerImpl.dispatchToStateAdapters(ResourceManagerImpl.java:1997)
        at com.cloud.resource.ResourceManagerImpl.createHostVO(ResourceManagerImpl.java:2224)
        at com.cloud.resource.ResourceManagerImpl.createHostVOForConnectedAgent(ResourceManagerImpl.java:2556)
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### OS / ENVIRONMENT

4.18

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
this has been fixed via #7620
thanks @DaanHoogland
