### ISSUE TITLE
Agent state isn't up

### ISSUE THREAD

**Issue by HtainL** [apache/cloudstack#7827]
##### ISSUE TYPE
 Other
 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
Agent State
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION
 Advanced Networking

##### OS / ENVIRONMENT

ubuntu 22.04 LTS

##### SUMMARY

After deployment cs4.18 with ubuntu 22.04, ssvm and cpvm agent state isn't up. Installed with different kvm host. 
![image](https://github.com/apache/cloudstack/assets/134905472/c49d312c-b570-440c-a254-0e0f9f560077)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by HtainL** [comment]
[management-server.log](https://github.com/apache/cloudstack/files/12287557/management-server.log)

I would like to provide managementserver.log. Please kindly help me.

**Comment by DaanHoogland** [comment]
it looks like you have an network issue @HtainL :+1: 
```
2023-08-03 06:40:14,748 WARN  [o.a.c.s.SecondaryStorageManagerImpl] (secstorage-1:ctx-57222487) (logid:ec80f579) Unable to start secondary storage VM [1] due to [Resource [Host:1] is unreachable: Host 1: Unable to start s-1-VM].
com.cloud.exception.AgentUnavailableException: Resource [Host:1] is unreachable: Host 1: Unable to start s-1-VM
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1339)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5351)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
	at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5475)
	at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.cloud.exception.OperationTimedoutException: Commands 3689011044769857557 to Host 1 timed out after 3600
	at com.cloud.agent.manager.AgentAttache.send(AgentAttache.java:444)
	at com.cloud.agent.manager.AgentManagerImpl.send(AgentManagerImpl.java:462)
	at com.cloud.agent.manager.AgentManagerImpl.send(AgentManagerImpl.java:1006)
	... 21 more
```

Try to log on to the ssvm and
- ping the management server.
- run `ssvm-check.sh`

**Comment by HtainL** [comment]
Issue have been solved, the error was network issue. Management can't ping the agent host.
