### ISSUE TITLE
Upload Template / ISO From local failed

### ISSUE THREAD

**Issue by levindecaro** [apache/cloudstack#7981]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### CONFIGURATION

KVM
Advanced Networking

##### OS / ENVIRONMENT

Oracle Linux 9.2

##### SUMMARY

Fresh install ACS 4.18.1 with letsencrypts cert installed, tried to upload qcow2 template or ISO from local but failed, register template from remote URL template are ok.

No process bar appeared, res
##### STEPS TO REPRODUCE

Upload a qcow2 format from local 

~~~
N/A

~~~

![image](https://github.com/apache/cloudstack/assets/36956864/3ca469fb-0363-4e7f-b995-88cae543deea)

##### EXPECTED RESULTS

~~~
Template should be uploaded successfully.
~~~

##### ACTUAL RESULTS

![image](https://github.com/apache/cloudstack/assets/36956864/5e28a468-3447-4358-b26e-9b2c5c5a9c71)

~~~


```
2023-09-19 23:19:24,993 INFO  [handler.logging.LoggingHandler] (nioEventLoopGroup-2-1:null) [id: 0x777c7e67, L:/0.0.0.0:8210] READ COMPLETE
2023-09-19 23:19:25,023 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-2:null) HEADER: SIGNATURE=u0p7CCNWJ4Fiz2aLh0D/0qhJYDs=
2023-09-19 23:19:25,025 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-2:null) HEADER: METADATA=XLapWnsiqHmOvDOFkrveFbw08pWeGo0Y8KyuGVRWH69pBY9a3LaO8KfDx9aDfBj2TjlmJdHJWusgi2Zet5TWiuCtnYQPBGprXL0a7P+7prgfxXyXhouwOjpJRmhD8vpxkGc9fVE55pIyvLmKyJbjOc6gntIqABXIEUg+e8Glr00YVf0gkR4b7+UW3LcQwXDDfowfjEAXFlotFmnqdje+EBbUazB+ABly2wW9UCItNjX+7LYsbXrSovF0qVUIgcUx1LNJ2kWTW31hmpUIUa4fPczKLknnu+JFMJoI1Ec7Y/oixVoigqWcTXL+tUJAH4QPFZHFCqTPKykiy0qQqujonpmrof7DbnvaSvH+EIGz+NG+I7XOAkLVVBrhIvknuPfWCvDxb5hAymQvzxk6dtB2ZyIhm4nP/v3VYSbQFIp+GxEwdoM7aUfc8ovDnmPWukafZuvOVZG5NN9oEmeA56W4pEtsKZ7+VBv5AbyCCp9TsltVRVZPKyj5z+4lmhZGO8RDN2ZOUM2jhfXgQSoobqDMifLwfywU6xxKjSN7XQaG00Cl52aNYe+kuHhwEoGfTOqWmEm6uzkVuFiiBQgHPNdmHkzx9cKlSRCeqOmU8Mx+TCVXZgwEr3RiITfIg1ZP3hmIi6RoVX6Id8q1VreQow==
2023-09-19 23:19:25,026 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-2:null) HEADER: EXPIRES=2023-09-20T00:19:06.336Z
2023-09-19 23:19:25,026 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-2:null) HEADER: HOST=ssvm.lab.example.com
2023-09-19 23:19:25,027 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-2:null) HEADER: CONTENT_LENGTH=725221594
2023-09-19 23:19:25,028 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-2:null) URI: uuid=43d7be4b-6c2c-4619-90c5-2b5021c0fc17
2023-09-19 23:19:25,037 INFO  [storage.resource.NfsSecondaryStorageResource] (nioEventLoopGroup-3-2:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-19 23:19:25,055 ERROR [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-2:null) post request validation failed
com.cloud.exception.InvalidParameterValueException: The one time post url is already used and the upload is in ERROR state.
	at org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource.createUploadEntity(NfsSecondaryStorageResource.java:3267)
	at org.apache.cloudstack.storage.resource.HttpUploadServerHandler.channelRead0(HttpUploadServerHandler.java:168)
	at org.apache.cloudstack.storage.resource.HttpUploadServerHandler.channelRead0(HttpUploadServerHandler.java:65)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:315)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:429)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
<!-- Paste verbatim command output between quotes below -->

~~~

**Comment by levindecaro** [comment]
Have another try to eliminate all possible UI, browser or Network problem.

Did a upload test with CMK, curl inside ssvm, the post request are paused and waiting for data.



```
URL=https://ssvm.lab.example.com/upload/77312ce8-b2fa-4820-be39-73548c2f1463

curl --connect-timeout 1800 --max-time 1800 -X POST "$URL" -H "X-Signature:$SIGNATURE" -H "X-Metadata:$METADATA" -H "X-expires:$EXPIRES" -F "file=@OL7U9_x86_64-kvm-b145.qcow2" -v -H "Connection: keep-alive" -H "Keep-Alive: timeout=5, max=100"
```

```
*   Trying 172.20.240.11:443...
* Connected to ssvm.lab.example.com (172.20.240.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.lab.example.com
*  start date: Sep 19 22:10:34 2023 GMT
*  expire date: Dec 18 22:10:33 2023 GMT
*  subjectAltName: host "ssvm.lab.example.com" matched cert's "*.lab.example.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> POST /upload/77312ce8-b2fa-4820-be39-73548c2f1463 HTTP/1.1
> Host: ssvm.lab.example.com
> User-Agent: curl/7.74.0
> Accept: */*
> X-Signature:f7vN87mYSojst5bkQ/DaIY9HwvQ=
> X-Metadata:0eORF2irrmWs2AlCl2/SuZqf2MT3OIYMq4KUCAzC0zCdwST8C/pKblF4QpX2bBKXc6rzZYwvaJzvI8MOJKf/EwW700UXiSzvjpy6BOfNufQVBHzA79t7fcBEnFZEhEa1Xccs3emZ4VImrlc99tqHwi2fkMjb+NbUONh2PY94RrPuUQkmIIS3DPZS9A6bzhgEgCwVitMzhBzWpJtsqr6YB6PzIujvRjRb5IyW8tP5prlBegrDw4yTYBwVmsp+wJTWig1Q2mw8lXvLUysoyrGa1zWzUWjNi+9ZFgNTPYJ1HyyibZkNne7RyE0/SnrEn0B3GtQ5J4qzHRazwr+RfUAT4nSuucVZ36Id12n7kqUCslT4tcjPV8rpyVLU7ALjlbj2JdAdoUwkjRHdnAmv7iEFIjuCLiy28NOeOQAYtPCgbP1XLQBxiNsm0kJfokKY74BmPIzbhvr+ECBv0mP4j5liYGBnYUNkBOL9hjOCyGf+pX3l+J34Wy67mf54w5FPuND0Y6ZY03cXWarp6ZLueqjN0Gs1nzuO1GGypdKluqVbeYFGoiLL74ka0+mkRkn3zoT7k59EMpJiktboEf0pdae5wjR6OzHZ6H/SuJkZFGSmdOLp6fXRywfJoEeD6LbjQtLR2VM3jmvjX8xIa7HBMjk=
> X-expires:2023-09-20T13:30:37.972Z
> Connection: keep-alive
> Keep-Alive: timeout=5, max=100
> Content-Length: 725221595
> Content-Type: multipart/form-data; boundary=------------------------401774914bef730e
> Expect: 100-continue
>
* Done waiting for 100-continue
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Proxy Error
< Date: Wed, 20 Sep 2023 12:30:38 GMT
< Server: Apache
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, OPTIONS
< Access-Control-Allow-Headers: x-requested-with, content-type, origin, authorization, accept, client-security-token, x-signature, x-metadata, x-expires
< Content-Length: 283
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
* we are done reading and this is set to close, stop send
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```




cloud.log

```
2023-09-20 12:30:38,449 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) HEADER: SIGNATURE=f7vN87mYSojst5bkQ/DaIY9HwvQ=
2023-09-20 12:30:38,451 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) HEADER: METADATA=0eORF2irrmWs2AlCl2/SuZqf2MT3OIYMq4KUCAzC0zCdwST8C/pKblF4QpX2bBKXc6rzZYwvaJzvI8MOJKf/EwW700UXiSzvjpy6BOfNufQVBHzA79t7fcBEnFZEhEa1Xccs3emZ4VImrlc99tqHwi2fkMjb+NbUONh2PY94RrPuUQkmIIS3DPZS9A6bzhgEgCwVitMzhBzWpJtsqr6YB6PzIujvRjRb5IyW8tP5prlBegrDw4yTYBwVmsp+wJTWig1Q2mw8lXvLUysoyrGa1zWzUWjNi+9ZFgNTPYJ1HyyibZkNne7RyE0/SnrEn0B3GtQ5J4qzHRazwr+RfUAT4nSuucVZ36Id12n7kqUCslT4tcjPV8rpyVLU7ALjlbj2JdAdoUwkjRHdnAmv7iEFIjuCLiy28NOeOQAYtPCgbP1XLQBxiNsm0kJfokKY74BmPIzbhvr+ECBv0mP4j5liYGBnYUNkBOL9hjOCyGf+pX3l+J34Wy67mf54w5FPuND0Y6ZY03cXWarp6ZLueqjN0Gs1nzuO1GGypdKluqVbeYFGoiLL74ka0+mkRkn3zoT7k59EMpJiktboEf0pdae5wjR6OzHZ6H/SuJkZFGSmdOLp6fXRywfJoEeD6LbjQtLR2VM3jmvjX8xIa7HBMjk=
2023-09-20 12:30:38,452 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) HEADER: EXPIRES=2023-09-20T13:30:37.972Z
2023-09-20 12:30:38,453 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) HEADER: HOST=ssvm.lab.example.com
2023-09-20 12:30:38,454 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) HEADER: CONTENT_LENGTH=725221595
2023-09-20 12:30:38,456 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) URI: uuid=77312ce8-b2fa-4820-be39-73548c2f1463
2023-09-20 12:30:38,778 INFO  [storage.resource.NfsSecondaryStorageResource] (nioEventLoopGroup-3-1:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:30:38,797 INFO  [storage.resource.NfsSecondaryStorageResource] (nioEventLoopGroup-3-1:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:30:39,076 INFO  [storage.resource.NfsSecondaryStorageResource] (nioEventLoopGroup-3-1:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:30:39,123 INFO  [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) base directory: /mnt/SecStorage/3d6c5617-7b66-38c3-b5bd-f58804d588b3/template/tmpl/2/264
2023-09-20 12:31:11,967 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-1:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:32:12,153 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-3:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:33:12,365 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-5:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:34:12,548 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-2:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:35:12,696 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-4:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
2023-09-20 12:35:38,352 ERROR [storage.resource.HttpUploadServerHandler] (nioEventLoopGroup-3-1:null) file receive failed or connection closed prematurely.
2023-09-20 12:36:12,846 INFO  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-1:null) Determined host nfs.lab.example.com corresponds to IP 10.10.10.90
```

**Comment by rajujith** [comment]
@levindecaro This could happen if the SSVM is unable to access the secondary storage properly. Could you try listing the files in the secondary storage mount point from the SSVM? there may be other causes too. 

Try listing files under " /mnt/SecStorage/3d6c5617-7b66-38c3-b5bd-f58804d588b3/template/tmpl/2/264" as well.

**Comment by levindecaro** [comment]
@rajujith  there are no problem with secondary storage as well listing files. I'd cross checked the directory was created by ssvm when receiving the post request, however tcpdump shown no data where send over the port afterwards. As said, registering a remote URL iso/qcow2 template are no problem at all. I could narrow down it is http serving problem most likely.

**Comment by rajujith** [comment]
@levindecaro  you are probably right, I see your comment on #7442 . cc @shwstppr

**Comment by rajujith** [comment]
@levindecaro  In my lab setup upload ISO worked fine with ACS 4.18.1. Unable to reproduce the issue. Is there a specific repro step you would be able to share?

**Comment by levindecaro** [comment]
@rajujith thank for your test result, I'd found out there are egress ACL on switch vlan port cause blocking https return path between client side, and the cmk/curl test is not relevant to prove the result, it is not working test sample.

I close this issue for now, and sorry for wasted your time. Appreciated for your help again.
