### ISSUE TITLE
improve logging in vmware resource method

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#8291]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
vmware
~~~

##### CLOUDSTACK VERSION

~~~
all 4.19 and before
~~~

##### SUMMARY

`VmwareResource.execute(MigrateCommand)` creates an error message:
```
Message: null

        at com.cloud.vm.VirtualMachineManagerImpl.migrate(VirtualMachineManagerImpl.java:2433)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrate(VirtualMachineManagerImpl.java:2323)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrate(VirtualMachineManagerImpl.java:5181)
        at sun.reflect.GeneratedMethodAccessor934.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
```
this may be due to three objects in the method: hyperHost, morDc, destHyperHost and is obfuscating an error condition either in the call or on the vmware side.

This issue was encountered in the migrate execution but will possibly be present as a general issue.

##### STEPS TO REPRODUCE

unknown

~~~

~~~

##### EXPECTED RESULTS

~~~
a clear indication of the error state and if possible of the cause
~~~

##### ACTUAL RESULTS

~~~
null
~~~

**Comment by DaanHoogland** [comment]
fixed by #8300
