### ISSUE TITLE
Some issues with managed/unmanaged VMs on KVM

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#8439]
1. There is an issue  while importing a VM with a Basic zone network:
- if you chose to set a random IP address:

```
2024-01-03 16:51:26,068 ERROR [o.a.c.v.UnmanagedVMsManagerImpl] (API-Job-Executor-10:ctx-bcae51d0 job-864 ctx-e872b0fb) (logid:016f507c) Failed to import NICs while importing vm: i-2-58-VM
com.cloud.exception.InsufficientVirtualNetworkCapacityException: Unable to acquire Guest IP  address for network Network {"id": 204, "name": "defaultGuestNetwork", "uuid": "2c6b7a88-939a-42b1-8a5e-d9641071bff8",
 "networkofferingid": 7}Scope=interface com.cloud.dc.DataCenter; id=1
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.importNic(NetworkOrchestrator.java:4582)
```

- if you use a predetermined IP address the import fails with
```

2024-01-03 16:52:49,765 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:ctx-a94ebd23 job-865) (logid:0f522606) Complete async job-865, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudsta
ck.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"530","errortext":"IP address 10.2.32.49 for NIC(ID: 0) is not available in network(ID: 2c6b7a88-939a-42b1-8a5e-d9641071bff8)"}
```

2. If the storage pool is of type block for the volumes of an unmanaged VM, CS cannot find the pools. The select DB query tries to list by path and host_address which are taken from the libvirt XML disk definition and are not correct (for example it gets the volume path /dev/storpool-byid/bgu4.b.8wm instead of the actual primary storage path /dev/storpool-byid/. Also StorPool for example doesn't have a host described in the XML definition). Probably this issue will appear with similar storage plugins.

3. Issue with VMs with RBD storage pool. You can unmanage a VM on Ceph storage but the listing of unmanaged VMs fails because libvirt cannot access the RBD volumes.

```
2024-01-04 11:56:55,383 DEBUG [utils.script.Script] (agentRequest-Handler-2:null) (logid:43ccc964) Executing command [qemu-img info -U cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a ].
2024-01-04 11:56:55,388 WARN  [utils.script.Script] (agentRequest-Handler-2:null) (logid:43ccc964) Execution of process [2868475] for command [qemu-img info -U cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a ] f
ailed.
2024-01-04 11:56:55,388 DEBUG [utils.script.Script] (agentRequest-Handler-2:null) (logid:43ccc964) Exit value of process [2868475] for command [qemu-img info -U cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a ] 
is [1].
2024-01-04 11:56:55,389 WARN  [utils.script.Script] (agentRequest-Handler-2:null) (logid:43ccc964) Process [2868475] for command [qemu-img info -U cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a ] encountered th
e error: [qemu-img: Could not open 'cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a': Could not open 'cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a': No such file or directory].
2024-01-04 11:56:55,389 INFO  [resource.wrapper.LibvirtGetUnmanagedInstancesCommandWrapper] (agentRequest-Handler-2:null) (logid:43ccc964) Unable to retrieve unmanaged instance info. org.apache.cloudstack.utils.
qemu.QemuImgException: qemu-img: Could not open 'cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a': Could not open 'cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a': No such file or directory
java.lang.RuntimeException: org.apache.cloudstack.utils.qemu.QemuImgException: qemu-img: Could not open 'cloudstack/d3638e01-955c-4702-8433-b62fe4bc680a': Could not open 'cloudstack/d3638e01-955c-4702-8433-b62fe
4bc680a': No such file or directory
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtGetUnmanagedInstancesCommandWrapper.getUnmanagedInstanceDisks(LibvirtGetUnmanagedInstancesCommandWrapper.java:191)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtGetUnmanagedInstancesCommandWrapper.getUnmanagedInstance(LibvirtGetUnmanagedInstancesCommandWrapper.java:135)
```

##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
tested with https://github.com/apache/cloudstack/pull/8433
~~~

##### OS / ENVIRONMENT

Rocky linux 8.5

**Comment by DaanHoogland** [comment]
@slavkap,
Do you consider any of these issues a blocker?
Does it make sense to split the issue in three tickets?

**Comment by slavkap** [comment]
@DaanHoogland, it is not a blocker except if somebody uses the Basic network (the first issue).
2 and 3 probably can be fixed first with some limitation in the code that it works only for NFS and shared storage

**Comment by slavkap** [comment]
@shwstppr, yes, I will work on the second issue and probably will try to fix the problem with Ceph. For the first one, I need to understand the whole feature and right now I don't have much time :(

**Comment by DaanHoogland** [comment]
NOTE; that the second item of point 1 is still an issue. I am working on it in #8488 . Not sure if we should keep this issue open for that, but it is not completely solved yet.
