### ISSUE TITLE
High load on management server due to stale KVM agent

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#8517]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Other

##### COMPONENT NAME

~~~
KVM, Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1, Any
~~~

##### CONFIGURATION

KVM 

##### OS / ENVIRONMENT

Rocky 8 KVM, Management server

##### SUMMARY

Removed KVM host with agent management server IP configured pointing to a new management server leads to high CPU load on the management server. 

![Screenshot 2024-01-16 at 3 43 51 PM](https://github.com/apache/cloudstack/assets/5229147/3ccaef2f-ffa8-4cc5-aceb-31fc2721edd6)

We can see the below logs in the management server: 
```

2024-01-16 10:14:00,089 WARN  [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-381:null) (logid:) SSL Handshake has taken more than 30s to connect to: /10.1.35.66:46493. Please investigate this connection.
2024-01-16 10:14:00,099 WARN  [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-29:null) (logid:) SSL Handshake has taken more than 30s to connect to: /10.1.35.66:46475. Please investigate this connection.

```
##### STEPS TO REPRODUCE

~~~
1. Remove a KVM host. Restart the agent. 
2. Reinstall the management server or run cloudstack-setup-database
3. Watch the Management server CPU load. 

OR

1. Update the agent.properties of a KVM host to point it to an existing management server where the host is not added.
2. Restart the cloudstack agent.
3. Wait for a few minutes until the management server CPU load goes very high. 
~~~

**Comment by DaanHoogland** [comment]
this is a bad bug, @rajujith . I know some people are explicitely using this scenario in operations, so it should be supported. Can you confirm the the host/agent is not added to the cloud-installation?

**Comment by weizhouapache** [comment]
> this is a bad bug, @rajujith . I know some people are explicitely using this scenario in operations, so it should be supported. Can you confirm the the host/agent is not added to the cloud-installation?

@DaanHoogland 
the issue is easy to reproduce: reinstall cloudstack database on management server
the running cloudstack-agent will try to connect the management server with old configuration, again and again.

the workaround is also very simple: stop cloudstack-agent on kvm hosts, and add hosts on cloudstack UI if needed.

**Comment by rajujith** [comment]
> this is a bad bug, @rajujith . I know some people are explicitely using this scenario in operations, so it should be supported. Can you confirm the the host/agent is not added to the cloud-installation?

Agent is not added to cloudstack and the workaround is to stop the agent. However it would be nice to have it fixed.

**Comment by DaanHoogland** [comment]
should I up the level from major to critical on this, @rajujith @weizhouapache ?

**Comment by weizhouapache** [comment]
> should I up the level from major to critical on this, @rajujith @weizhouapache ?

@DaanHoogland 
I do not think it is a major/critical issue.
when users reinstall an environment, they should better stop all running cloudstack services (management, usage, agent).

**Comment by DaanHoogland** [comment]
right, there is an issue when the management is reachable to rogue agents, but that is an operational issue. I was thinking we must guard against that.

**Comment by rajujith** [comment]
Rogue agents shoudn't have the ability to create high load on the management server and crash it.

**Comment by rohityadavcloud** [comment]
Assigned to @weizhouapache - perhaps we can explore a simpler solution where the management server can send a shutdown command to stale/old KVM agents?

**Comment by sureshanaparti** [comment]
Fixed in #9258

**Comment by rajujith** [comment]
This appears to be resurfaced based on my tests in 4.20.2. I followed the same steps in the description, and the issue was observed.

```
top - 07:16:52 up  1:56,  1 user,  load average: 180.34, 221.31, 256.94
Threads: 1398 total, 274 running, 1124 sleeping,   0 stopped,   0 zombie
%Cpu(s): 44.1 us, 54.7 sy,  0.0 ni,  0.2 id,  0.0 wa,  0.7 hi,  0.3 si,  0.0 st
MiB Mem :   3647.9 total,    179.5 free,   2742.0 used,    969.9 buff/cache
MiB Swap:   2048.0 total,   1866.6 free,    181.4 used.    905.9 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  82376 cloud     20   0 6230580   1.3g  23664 R   7.2  36.6   0:00.38 AgentManager-SS
  81100 cloud     20   0 6230580   1.3g  23664 R   4.6  36.6   0:00.80 AgentManager-SS
  32927 cloud     20   0 6230580   1.3g  23664 R   4.2  36.6   0:10.65 AgentManager-SS
  82370 cloud     20   0 6230580   1.3g  23664 R   3.9  36.6   0:00.29 AgentManager-SS
  82417 cloud     20   0 6230580   1.3g  23664 R   3.9  36.6   0:00.28 AgentManager-SS
  32916 cloud     20   0 6230580   1.3g  23664 R   1.0  36.6   0:11.19 AgentManager-SS
```
```

top - 07:13:23 up  1:53,  1 user,  load average: 185.76, 273.26, 279.84
Tasks: 174 total,   1 running, 173 sleeping,   0 stopped,   0 zombie
%Cpu0  : 50.7 us, 48.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.3 hi,  0.3 si,  0.0 st
%Cpu1  : 52.5 us, 46.8 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.7 hi,  0.0 si,  0.0 st
MiB Mem :   3647.9 total,    214.9 free,   2708.2 used,    968.2 buff/cache
MiB Swap:   2048.0 total,   1866.6 free,    181.4 used.    939.7 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  31231 cloud     20   0 5875884   1.3g  23664 S 196.2  36.4  80:28.26 java
```
```

2025-11-27 07:13:49,097 ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-46:[]) (logid:) SSL error caught during unwrap data: Received fatal alert: certificate_unknown, for local address=/10.1.34.116:8250, remote address=/10.1.32.118:51200. The client may have invalid ca-certificates.
2025-11-27 07:13:49,117 ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-289:[]) (logid:) SSL error caught during unwrap data: Received fatal alert: certificate_unknown, for local address=/10.1.34.116:8250, remote address=/10.1.32.118:49778. The client may have invalid ca-certificates.
2025-11-27 07:13:49,201 WARN  [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-925:[]) (logid:) This SSL engine was forced to close inbound due to end of stream. javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:794)
	at com.cloud.utils.nio.Link.doHandshakeUnwrap(Link.java:492)
```

@weizhouapache @sureshanaparti

**Comment by sureshanaparti** [comment]
@rajujith @weizhouapache @shwstppr Checked with _backoff.seconds_ parameter set to 15 secs in agent.properties, noticed the same issue (and management server is not responding until all the agents are stopped). The earlier wait fix is applied, and issue is not seen with it. It's regression in 4.20.1 & 4.20.2 only. cc @DaanHoogland

**Comment by sureshanaparti** [comment]
Fixed with #12153
