### ISSUE TITLE
VM Console not working for noVNC using cloudstack UI 4.19.0

### ISSUE THREAD

**Issue by yashi4engg** [apache/cloudstack#8648]
##### ISSUE TYPE

 * Other

##### SUMMARY
Console not working . We have mysql ssl enabled and console proxy ssl is disabled for now. 

Failed to connect/access token expired. 

While checking logs on CCVM ..we see vnc auth failed. 

2024-02-12 21:48:43,659 INFO  [consoleproxy.vnc.NoVncClient] (Thread-256:null) Connecting to VNC server x.x.x.x:5907 ...
2024-02-12 21:48:43,901 INFO  [vnc.security.VncTLSSecurity] (Thread-256:null) Processing VNC TLS security
2024-02-12 21:48:43,901 INFO  [utils.nio.Link] (Thread-256:null) Conf file found: /usr/local/cloud/systemvm/conf/agent.properties
2024-02-12 21:48:44,052 INFO  [vnc.security.VncAuthSecurity] (Thread-256:null) VNC server requires password authentication
2024-02-12 21:48:44,061 INFO  [vnc.security.VncAuthSecurity] (Thread-256:null) Finished VNCAuth security
2024-02-12 21:48:44,061 ERROR [consoleproxy.vnc.NoVncClient] (Thread-256:null) Connection to VNC server failed: wrong password.
2024-02-12 21:48:44,061 ERROR [consoleproxy.vnc.NoVncClient] (Thread-256:null) Connection to VNC server failed: wrong password. - Reason: Authentication failed
2024-02-12 21:51:45,383 INFO  [cloud.consoleproxy.ConsoleProxyGCThread] (Console Proxy GC Thread:null) Dropping com.cloud.consoleproxy.ConsoleProxyNoVncClient@7161db7c which has not been used for 181 seconds
2024-02-12 21:53:43,902 ERROR [cloud.consoleproxy.ConsoleProxyNoVNCHandler] (Connector-Scheduler-af9bf5f-1:null) Error on websocket
org.eclipse.jetty.websocket.api.CloseException: java.util.concurrent.TimeoutException: Idle timeout expired: 300001/300000 ms
  at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:564)
  at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:172)
  at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:539)
  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:317)
  at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140)
  at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407)
  at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
  at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 300001/300000 ms
  ... 8 more
2024-02-12 21:54:51,214 INFO  [cloud.agent.Agent] (Agent-Handler-3:null) Lost connection to host: x.x.x.x. Attempting reconnection while we still have 0 commands in progress.
2024-02-12 21:54:51,216 INFO  [utils.nio.NioClient] (Agent-Handler-3:null) NioClient connection closed

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rajujith** [comment]
@yashi4engg  could you share the cloudstack and hypervisor type and version where this issue is observed?

**Comment by yashi4engg** [comment]
@rajujith  -- cloudstack version 4.19 , Hypervisor - KVM with OEL8 , 

We have mysql and cloudstack mgmt installed on same node where mysql is ssl enabled.

**Comment by weizhouapache** [comment]
can you destroy CPVM and retry ?
@yashi4engg

**Comment by yashi4engg** [comment]
@weizhouapache  -- I tried that but still not working and getting same error.

**Comment by weizhouapache** [comment]
> @weizhouapache -- I tried that but still not working and getting same error.

@yashi4engg 
do all vms have the same issue ? or only a specific vm ?

**Comment by yashi4engg** [comment]
@weizhouapache -- All VMs facing same issue .

**Comment by weizhouapache** [comment]
> @weizhouapache -- All VMs facing same issue .

@yashi4engg 
can you check if all packages (management, agent) and systemvm template have all been upgraded to 4.19.0 ?

**Comment by yashi4engg** [comment]
All packages for 4.19 as this is new setup with 4.19 .

KVM hypervisors with OEL8.9. mysql is ssl enabled.

**Comment by yashi4engg** [comment]
@weizhouapache  WE have enabled FIPS for hosts and cloudstack and then it started giving VNc console errors.

**Comment by weizhouapache** [comment]
> @weizhouapache WE have enabled FIPS for hosts and cloudstack and then it started giving VNc console errors.

Each cloudstack VM has a VNC password. unfortunately it is not supported in FIPS mode.

please refer to 
https://people.redhat.com/pbonzini/qemu-test-doc/_build/html/topics/vnc_005fsecurity.html#vnc_005fsec_005fpassword

**Comment by rohityadavcloud** [comment]
FIPS isn't a support config yet I think @yashi4engg cc @weizhouapache can advise.
