### ISSUE TITLE
Cannot list external VMware instances

### ISSUE THREAD

**Issue by ahmedali6** [apache/cloudstack#8768]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### OS / ENVIRONMENT

OS:
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

VSphere version: 8.0.0.10000

VCenter version: 8.0.0.10000

VMware ESXI version: 8.0.2

##### SUMMARY

Unable to list VMware instances.

##### STEPS TO REPRODUCE

~~~
Go to Tools -> Import-Export Instances

Then try listing VMware instances.
~~~

##### EXPECTED RESULTS

~~~
A list of VMware instances
~~~

##### ACTUAL RESULTS

Request failed with status code 530
![image](https://github.com/apache/cloudstack/assets/87921765/8739c407-d2e3-4e39-8088-90d395668cf7)

Logs

```
2024-03-10 02:25:29,117 DEBUG [c.c.a.ApiServlet] (qtp239372207-421:ctx-d980ca78) (logid:0799977b) ===START===  192.168.121.1 -- GET  command=readyForShutdown&response=json
2024-03-10 02:25:29,117 DEBUG [c.c.a.ApiServlet] (qtp239372207-421:ctx-d980ca78) (logid:0799977b) Two factor authentication is already verified for the user 2, so skipping
2024-03-10 02:25:29,122 DEBUG [c.c.a.ApiServer] (qtp239372207-421:ctx-d980ca78 ctx-e6ba8468) (logid:0799977b) CIDRs from which account 'Account [{"accountName":"admin","id":2,"uuid":"5ab32169-de76-11ee-8e14-52540026c04b"}]' is allowed to perform API calls: 0.0.0.0/0,::/0
2024-03-10 02:25:29,124 INFO  [o.a.c.a.DynamicRoleBasedAPIAccessChecker] (qtp239372207-421:ctx-d980ca78 ctx-e6ba8468) (logid:0799977b) Account [Account [{"accountName":"admin","id":2,"uuid":"5ab32169-de76-11ee-8e14-52540026c04b"}]] is Root Admin or Domain Admin, all APIs are allowed.
2024-03-10 02:25:29,125 WARN  [o.a.c.a.ProjectRoleBasedApiAccessChecker] (qtp239372207-421:ctx-d980ca78 ctx-e6ba8468) (logid:0799977b) Project is null, ProjectRoleBasedApiAccessChecker only applies to projects, returning API [readyForShutdown] for user [User {"username":"admin","uuid":"5ab44076-de76-11ee-8e14-52540026c04b"}.] as allowed.
2024-03-10 02:25:29,125 DEBUG [o.a.c.a.StaticRoleBasedAPIAccessChecker] (qtp239372207-421:ctx-d980ca78 ctx-e6ba8468) (logid:0799977b) RoleService is enabled. We will use it instead of StaticRoleBasedAPIAccessChecker.
2024-03-10 02:25:29,126 DEBUG [o.a.c.r.ApiRateLimitServiceImpl] (qtp239372207-421:ctx-d980ca78 ctx-e6ba8468) (logid:0799977b) API rate limiting is disabled. We will not use ApiRateLimitService.
2024-03-10 02:25:29,127 DEBUG [c.c.a.ApiServlet] (qtp239372207-421:ctx-d980ca78 ctx-e6ba8468) (logid:0799977b) ===END===  192.168.121.1 -- GET  command=readyForShutdown&response=json
2024-03-10 02:25:29,139 INFO  [c.c.h.v.u.VmwareContext] (qtp239372207-311:ctx-5073117b ctx-38bc5c9d) (logid:0c7d98a1) New VmwareContext object, current outstanding count: 10
2024-03-10 02:25:29,413 INFO  [c.c.h.v.u.VmwareHelper] (qtp239372207-311:ctx-5073117b ctx-38bc5c9d) (logid:0c7d98a1) Unable to retrieve unmanaged instance info. Standalone host is not supported
2024-03-10 02:25:29,617 INFO  [c.c.h.v.u.VmwareHelper] (qtp239372207-311:ctx-5073117b ctx-38bc5c9d) (logid:0c7d98a1) Unable to retrieve unmanaged instance info. Standalone host is not supported
2024-03-10 02:25:29,617 ERROR [c.c.a.ApiServer] (qtp239372207-311:ctx-5073117b ctx-38bc5c9d) (logid:0c7d98a1) unhandled exception executing api command: [Ljava.lang.String;@1ff4e239
java.lang.NullPointerException
	at com.cloud.api.ApiResponseHelper.createUnmanagedInstanceResponse(ApiResponseHelper.java:5129)
	at org.apache.cloudstack.api.command.admin.zone.ListVmwareDcVmsCmd.execute(ListVmwareDcVmsCmd.java:101)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:172)
	at com.cloud.api.ApiServer.queueCommand(ApiServer.java:782)
	at com.cloud.api.ApiServer.handleRequest(ApiServer.java:603)
	at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:347)
	at com.cloud.api.ApiServlet$1.run(ApiServlet.java:154)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:151)
	at com.cloud.api.ApiServlet.doGet(ApiServlet.java:105)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-03-10 02:25:29,619 DEBUG [c.c.a.ApiServlet] (qtp239372207-311:ctx-5073117b ctx-38bc5c9d) (logid:0c7d98a1) ===END===  192.168.121.1 -- GET  datacentername=Datacenter&vcenter=vsphere.local&username=Administrator%40vSphere.local&command=listVmwareDcVms&response=json
2024-03-10 02:25:30,668 DEBUG [c.c.s.StatsCollector] (StatsCollector-1:ctx-9b94ae3e) (logid:19839e61) HostStatsCollector is running to process 1 UP hosts
2024-03-10 02:25:30,717 DEBUG [c.c.a.t.Request] (StatsCollector-1:ctx-9b94ae3e) (logid:19839e61) Seq 1-3541236681996763337: Received:  { Ans: , MgmtId: 90520733270091, via: 1(cloud-stack-1), Ver: v1, Flags: 10, { GetHostStatsAnswer } }
2024-03-10 02:25:32,560 DEBUG [o.a.c.h.HAManagerImpl] (BackgroundTaskPollManager-3:ctx-c33c9316) (logid:0f897e1b) HA health check task is running...
2024-03-10 02:25:34,782 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-13:null) (logid:) SeqA 2-408: Processing Seq 2-408:  { Cmd , MgmtId: -1, via: 2, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"1","_loadInfo":"{
  "connections": [
    {
      "id": 2,
      "clientInfo": "",
      "host": "192.168.121.135",
      "port": 5903,
      "tag": "65701e99-0ac6-461c-b550-cbdf72a682d0",
      "createTime": 1710034939644,
      "lastUsedTime": 1710037534654,
      "sessionUuid": "724bb6f9-91f6-4bc8-8e5a-7652892b4ffb"
    }
  ],
  "removedSessions": []
}","wait":"0","bypassHostMaintenance":"false"}}] }
2024-03-10 02:25:34,923 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-13:null) (logid:) SeqA 2-408: Sending Seq 2-408:  { Ans: , MgmtId: 90520733270091, via: 2, Ver: v1, Flags: 100010, [{"com.cloud.agent.api.AgentControlAnswer":{"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }

```

**Comment by rajujith** [comment]
@ahmedali6  the log errors mentions that you are using a standalone ESXi host and it is not supported.

**Comment by ahmedali6** [comment]
My mistake I configured it in the wrong way. Thanks!

**Comment by NickLi1014** [comment]
@ahmedali6 
Please tell me how to solve it? I also encountered the same problem!

**Comment by ahmedali6** [comment]
@NickLi1014 Add a host following this video https://www.youtube.com/watch?v=M3dOX_8wQrs.
