### ISSUE TITLE
Unable to import qcow2 image present on shared/local to a custom offering

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8785]
ISSUE TYPE

BUG 

Component Name

Import, kvm 

CLOUDSTACK VERSION

Cloudstack version 4.19 

SUMMARY

Unable to import qcow2 image present on shared/local to a custom offering

Steps to reproduce the issue

1. Create a custom service offering

![custom-offering](https://github.com/apache/cloudstack/assets/1401014/289985d7-9279-4782-9a99-ef9dd114f721)

2. Have a qcow2 file present in the shared storage/localstorage 

3. Navigate to tools> Import > kvm > 

![Screenshot 2024-03-14 at 10 20 16 AM](https://github.com/apache/cloudstack/assets/1401014/77603904-8f5d-40c0-8ed3-93faf49194c6)

![Screenshot 2024-03-13 at 1 58 56 PM](https://github.com/apache/cloudstack/assets/1401014/dfb6124d-fd0e-4a6f-b707-a121a9238660)

4. Exception 

![Screenshot 2024-03-13 at 1 59 06 PM](https://github.com/apache/cloudstack/assets/1401014/2cd5a784-543e-4a04-85d9-aa2f9b18c5d5)

Logs
----

```

2024-03-12 13:50:12,144 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-87:ctx-cd9f62c7 job-409803) (logid:273d199c) Unexpected exception while executing org.apache.cloudstack.api.command.admin.vm.ImportVmCmd
java.lang.NumberFormatException: For input string: "null"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.cloud.vm.UserVmManagerImpl.commitUserVm(UserVmManagerImpl.java:4524)
	at com.cloud.vm.UserVmManagerImpl.importVM(UserVmManagerImpl.java:8230)


```

Actual Behaviour

The qcow2 file is not getting imported successfully with a custom offering

Expected Behaviour

The qcow2 file should get imported successfully with a custom offering

**Comment by kiranchavala** [comment]
This issue occurs even when " Import vm instance from remote kvm host is selected "

Screenshot 2024-03-14 at 11.36.22 AM

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/8813
