### ISSUE TITLE
OOBM Sends the Reset Command to DRAC if Hypervisor is in PowerOff State

### ISSUE THREAD

**Issue by rahultolearn59** [apache/cloudstack#8918]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

When a hypervisor with RHEL8/9 running on a Dell PowerEdge Server gets into the power-off state, the ACS management system cannot fence it to recover the VMs on another hypervisor as it keeps sending DRAC a system reset request. Still, Drac has Poweron as the only option while its server is in a power-off state.
I waited for 1-2 hours to conclude. 
As soon as I power on the server manually, VMs are restored on different hypervisors immediately.

I think the server's power status should be checked first, and a power-on/reset command should be sent accordingly. 

##### STEPS TO REPRODUCE

~~~
Power off the hypervisor.
~~~

##### EXPECTED RESULTS

~~~
VMs should be recovered on active hypervisor.
~~~

##### ACTUAL RESULTS

~~~
VMs were not able to recover
~~~

**Comment by DaanHoogland** [comment]
@rahultolearn59 , I think it pays to send a mail to users@cloudstack.apache.org about this. I have no experience with DRAC but I am sure there are plenty of users that do. Not sure if what you say is a matter of configuration and if others have a work around for it.

**Comment by rahultolearn59** [comment]
Thanks, @DaanHoogland! Just for FYI; this is the exception message I see in the logs.
2024-04-16 22:43:30,146 WARN  [o.a.c.h.t.BaseHATask] (pool-4-thread-1:null) (logid:3e5b7727) Exception occurred while running RecoveryTask on a resource: org.apache.cloudstack.ha.provider.HARecoveryException:  OOBM service is not configured or enabled for this host <drac-domain>
org.apache.cloudstack.ha.provider.HARecoveryException:  OOBM service is not configured or enabled for this host <drac-domain>
	at org.apache.cloudstack.kvm.ha.KVMHAProvider.recover(KVMHAProvider.java:83)
	at org.apache.cloudstack.kvm.ha.KVMHAProvider.recover(KVMHAProvider.java:42)
	at org.apache.cloudstack.ha.task.RecoveryTask.performAction(RecoveryTask.java:43)
	at org.apache.cloudstack.ha.task.BaseHATask$1.call(BaseHATask.java:86)
	at org.apache.cloudstack.ha.task.BaseHATask$1.call(BaseHATask.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.cloudstack.utils.redfish.RedfishException: Failed to get System power state for host 'GET' with request 'https://<drac-domain>/redfish/v1/Systems/System.Embedded.1/Actions/ComputerSystem.Reset: <drac-domain>'. The expected HTTP status code is '2XX' but it got '409'.

**Comment by rohityadavcloud** [comment]
Were the VMs using a HA-enabled service offering @rahultolearn59 ?

**Comment by rahultolearn59** [comment]
Yes, @rohityadavcloud; as soon as we manually power on the host, VMs are moved to another KVM host.

**Comment by tanganellilore** [comment]
Hi team,
same issue on my test case.
If I simulate a disruption with powering off the server, idrac command fail.

If i simulate a disruption like power off machine and idrac not reachable, idrac command fail.

In both case host remain in "fancing" ad libitum until i restart the server or idrac will be reachable.
All vm on this host remain on this host in all tests, until i degraded node manually from UI.

OOBM command in a powerd off host, return an exit code 1 (like reset for recovery state).

I read some of your code and i think that error can be on these two pices:
https://github.com/apache/cloudstack/blob/b215abc30a22d6b11f016b8f402981445140f577/server/src/main/java/org/apache/cloudstack/ha/HAManagerImpl.java#L523-L529
and
https://github.com/apache/cloudstack/blob/b215abc30a22d6b11f016b8f402981445140f577/server/src/main/java/org/apache/cloudstack/ha/task/FenceTask.java#L48-L53

because function return always true on `fancing` state and due to the fact that OOBM go in exception, result will be `false` and we not going out to the "loop" of fancing.

One workaround could be introduce how may attempts we can wait until host change state to `inegilible` or `disabled`, like for recovery, or manage reset and powerOff OOBM error to avoid exception

**Comment by rohityadavcloud** [comment]
@rahultolearn59 @tanganellilore I think you're both mixing Host-HA with VM-HA, VM HA is still achievable without configuring Host-HA feature at all. For Host-HA to work, you'll need to ensure you're using the right oobm plugin & it's configured properly. On some Linux env such as EL8/9, you may need to install a specific version of ipmitool to get the oobm working with ipmi (this is due to the CLI/tool issue). This is mentioned here: https://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html#out-of-band-management:

_

> IPMI based out-of-band management and Host HA may not work on Centos 8 using the default ipmitool version - Installing ipmitool-1.8.18-12.el8_1.x86_64.rpm may solve the problem. Make sure to test the ipmitool on your physical equipment before using the IPMI-based out-of-band management and Host HA features.

_
