### ISSUE TITLE
Cloustack agent (4.18.1.0) status stuck on activating 

### ISSUE THREAD

**Issue by Ash6990** [apache/cloudstack#9010]
● cloudstack-agent.service - CloudStack Agent
     Loaded: loaded (/lib/systemd/system/cloudstack-agent.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2024-04-30 16:00:42 IST; 6s ago
       Docs: http://www.cloudstack.org/
    Process: 16062 ExecStart=/usr/bin/java $JAVA_OPTS $JAVA_DEBUG -cp $CLASSPATH $JAVA_CLASS (code=exited, status=67)
   Main PID: 16062 (code=exited, status=67)
        CPU: 5.778s

agent logs---------------------

2024-04-30 16:00:53,973 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Agent started
2024-04-30 16:00:53,983 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Implementation Version is 4.18.1.0
2024-04-30 16:00:53,988 INFO  [cloud.agent.AgentShell] (main:null) (logid:) agent.properties found at /etc/cloudstack/agent/agent.properties
2024-04-30 16:00:54,097 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Defaulting to using properties file for storage
2024-04-30 16:00:54,100 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Defaulting to the constant time backoff algorithm
2024-04-30 16:00:54,221 INFO  [cloud.utils.LogUtils] (main:null) (logid:) log4j configuration found at /etc/cloudstack/agent/log4j-cloud.xml
2024-04-30 16:00:54,222 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Using default Java settings for IPv6 preference for agent connection
2024-04-30 16:00:54,425 INFO  [cloud.agent.Agent] (main:null) (logid:) id is 
2024-04-30 16:00:54,435 INFO  [cloud.resource.ServerResourceBase] (main:null) (logid:) Trying to autodiscover this resource's private network interface.
2024-04-30 16:00:54,449 INFO  [cloud.resource.ServerResourceBase] (main:null) (logid:) Using NIC [name:docker0 (docker0)] as private NIC.
2024-04-30 16:00:54,462 ERROR [kvm.resource.LibvirtComputingResource] (main:null) (logid:) uefi properties file not found due to: Unable to find file uefi.properties.
2024-04-30 16:00:54,623 INFO  [kvm.resource.LibvirtComputingResource] (main:null) (logid:) Failed to find passphrase for keystore: cloud.jks
2024-04-30 16:00:54,652 INFO  [kvm.resource.LibvirtConnection] (main:null) (logid:) No existing libvirtd connection found. Opening a new one
2024-04-30 16:00:55,089 INFO  [kvm.resource.LibvirtComputingResource] (main:null) (logid:) IO uring driver for Qemu: enabled
2024-04-30 16:00:55,286 INFO  [kvm.storage.KVMStoragePoolManager] (main:null) (logid:) adding storage adaptor for com.cloud.hypervisor.kvm.storage.LinstorStorageAdaptor
2024-04-30 16:00:55,299 INFO  [kvm.storage.KVMStoragePoolManager] (main:null) (logid:) adding storage adaptor for com.cloud.hypervisor.kvm.storage.StorPoolStorageAdaptor
2024-04-30 16:00:55,301 WARN  [kvm.storage.KVMStoragePoolManager] (main:null) (logid:) Duplicate StorageAdaptor type PowerFlex, not loading com.cloud.hypervisor.kvm.storage.ScaleIOStorageAdaptor
2024-04-30 16:00:55,302 INFO  [kvm.storage.KVMStoragePoolManager] (main:null) (logid:) adding storage adaptor for com.cloud.hypervisor.kvm.storage.IscsiAdmStorageAdaptor
2024-04-30 16:00:55,305 INFO  [kvm.resource.LibvirtComputingResource] (main:null) (logid:) No libvirt.vif.driver specified. Defaults to BridgeVifDriver.
2024-04-30 16:00:55,325 ERROR [kvm.resource.LibvirtComputingResource] (main:null) (logid:) Failed to get private nic name
2024-04-30 16:00:55,326 ERROR [cloud.agent.AgentShell] (main:null) (logid:) Unable to start agent: 
javax.naming.ConfigurationException: Failed to get private nic name
	at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.configure(LibvirtComputingResource.java:1178)
	at com.cloud.agent.Agent.<init>(Agent.java:190)
	at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:452)
	at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:431)
	at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:415)
	at com.cloud.agent.AgentShell.start(AgentShell.java:511)
	at com.cloud.agent.AgentShell.main(AgentShell.java:541)

**Comment by weizhouapache** [comment]
@Ash6990 
Have the bridges (cloudbrX) been configured  ? 
If not, please refer to the cloudstack document how to setup a kvm host.
