### ISSUE TITLE
noVNC connection timed out

### ISSUE THREAD

**Issue by z-mio** [apache/cloudstack#9039]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
noVNC
~~~

##### CLOUDSTACK VERSION

`cloudstack-agent 4.19.0.1`
`cloudstack-management 4.19.0.1`
`cloudstack-usage 4.19.0.1`
`cloudstack-common 4.19.0.1`
`CPVM systemvmtemplate-4.19.0-kvm`

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

`Ubuntu 22.04.4 LTS` 

##### SUMMARY

I encountered the same issue as #8303. I manually replaced `${VNCPORT}` with 8443 in `/etc/iptables/rules.v4`, and then re-executed `/opt/cloud/bin/setup/postinit.sh`

After the modification, the VNC console page can be opened, but it is always connected

I watched a lot of tutorials, but nothing worked

##### STEPS TO REPRODUCE

~~~
sed -i 's/${VNCPORT}/8443/g' /etc/iptables/rules.v4
sh /opt/cloud/bin/setup/postinit.sh
tail -f /var/log/cloud/cloud.out
~~~

##### EXPECTED RESULTS

~~~
noVNC can be loaded normally
~~~

##### ACTUAL RESULTS

The noVNC console kept connecting until it timed out

![](https://img.155155155.xyz/i/2024/05/66376bd08bfd9.webp)

This is the log

<details>
<summary>/var/log/cloud/cloud.out</summary>

~~~
2024-05-05 10:05:54,362 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-70:null) Get resource request for /resource/noVNC/vnc.html
2024-05-05 10:05:54,367 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-70:null) Sent file /resource/noVNC/vnc.html with content type text/html
2024-05-05 10:05:56,402 INFO  [cloud.consoleproxy.ConsoleProxyNoVNCHandler] (qtp18310625-36:null) Get websocket connection request from remote IP : 103.77.211.193
2024-05-05 10:05:56,481 INFO  [cloud.consoleproxy.ConsoleProxyNoVncClient] (Thread-72:null) Connect to VNC server directly. host: 38.xx.221.14, port: 5901
2024-05-05 10:05:56,505 INFO  [consoleproxy.vnc.NoVncClient] (Thread-72:null) Connecting to VNC server 38.xx.221.14:5901 ...
2024-05-05 10:09:01,071 INFO  [cloud.consoleproxy.ConsoleProxyGCThread] (Console Proxy GC Thread:null) Dropping com.cloud.consoleproxy.ConsoleProxyNoVncClient@4b621b07 which has not been used for 184 seconds
2024-05-05 10:10:56,482 ERROR [cloud.consoleproxy.ConsoleProxyNoVNCHandler] (Connector-Scheduler-371c7f21-1:null) Error on websocket
org.eclipse.jetty.websocket.api.CloseException: java.util.concurrent.TimeoutException: Idle timeout expired: 300001/300000 ms
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:564)
        at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:172)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:539)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:317)
        at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillableFail(SslConnection.java:591)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillInterestedFailed(SslConnection.java:419)
        at org.eclipse.jetty.io.ssl.SslConnection$2.failed(SslConnection.java:170)
        at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140)
        at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407)
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
        at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 300001/300000 ms
        ... 8 more
~~~

</details>

**Comment by weizhouapache** [comment]
It looks the kvm host uses public ip

Can you check if 38.xx.221.14:5901 is open from
- the host itself
- the CPVM
- any other servers

**Comment by z-mio** [comment]
> It looks the kvm host uses public ip
> 
> Can you check if 38.xx.221.14:5901 is open from
> 
> * the host itself
> * the CPVM
> * any other servers

CPVM and host are two public ip

host ip: `38.xx.221.14`
CPVM ip: `38.xx.221.245`

**host itself:**
~~~
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 38.xx.221.14:5900       0.0.0.0:*               LISTEN      2785/qemu-system-x8
tcp        0      0 38.xx.221.14:5901       0.0.0.0:*               LISTEN      2783/qemu-system-x8
~~~

**CPVM:**
~~~
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      2615/java
tcp        0      0 38.xx.221.245:8443      103.77.211.193:33727    ESTABLISHED 2615/java
tcp        0      0 192.168.1.14:43112      38.xx.221.14:5901       ESTABLISHED 2615/java
~~~

**Comment by weizhouapache** [comment]
> 38.xx.221.14:5901

@z-mio 
can you run `telnet 38.xx.221.14 5901` in the CPVM ?

**Comment by z-mio** [comment]
> @z-mio can you run `telnet 38.xx.221.14 5901` in the CPVM ?

@weizhouapache  

![](https://img.155155155.xyz/i/2024/05/663882ed86736.webp)

**Comment by z-mio** [comment]
> 然后分享登录 `/var/log/cloud.log`打印 CPVM ?

@weizhouapache 

ok, here's the full log
[cloud.log](https://github.com/apache/cloudstack/files/15219635/cloud.log)

**Comment by weizhouapache** [comment]
normally kvm host uses private IP
When open a vm console, ACS adds a route in the CPVM for kvm host

```
2024-05-06 10:42:13,131 DEBUG [resource.consoleproxy.ConsoleProxyResource] (Thread-14:null) Successfully executed process [53393] for command [/bin/bash -c ip route add 38.xx.221.14 via 192.168.1.1 ].
2024-05-06 10:42:13,133 DEBUG [resource.consoleproxy.ConsoleProxyResource] (Thread-14:null) addRouteToInternalIp: added route to internal ip=38.xx.221.14 via 192.168.1.1
```

unfortunately it causes your issue with vm console, as your kvm host uses a public IP.

**Comment by weizhouapache** [comment]
Not a typical setup
route may not be added if the kvm host is in the same subnet as public/private IP of CPVM.

marked this as a bug

**Comment by z-mio** [comment]
@weizhouapache 

Thank you very much.

I changed the public IP (38.xx.221.14) of the host to a private IP (192.168.1.188), and I was able to connect to the VPC.

(This issue had been bothering me for 3 days 😭

**Comment by weizhouapache** [comment]
> @weizhouapache
> 
> Thank you very much.
> 
> I changed the public IP (38.xx.221.14) of the host to a private IP (192.168.1.188), and I was able to connect to the VPC.
> 
> (This issue had been bothering me for 3 days 😭

@z-mio 
thanks for the update
I will close this issue

**Comment by DaanHoogland** [comment]
> @weizhouapache
> 
> Thank you very much.
> 
> I changed the public IP (38.xx.221.14) of the host to a private IP (192.168.1.188), and I was able to connect to the VPC.
> 
> (This issue had been bothering me for 3 days 😭

@z-mio , great that you have figured it now. If you have a location in the documentation that could be improved , feel free to submit a PR or point to it.
