### ISSUE TITLE
Error while trying to create a volume from a volume snapshot that sometimes result in snapshot loss

### ISSUE THREAD

**Issue by winterhazel** [apache/cloudstack#9538]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM, Volume Snapshot
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.0
~~~

##### OS / ENVIRONMENT

1 Zone, 1 Pod, 1 Cluster
Advanced networking
1 KVM host (Ubuntu 24.04) 
1 Management Server (Ubuntu 24.04)
NFS primary storage

##### SUMMARY

Trying to create a volume from a volume snapshot results in an error that sometimes removes the snapshot.

##### STEPS TO REPRODUCE

When `snapshot.backup.to.secondary` is disabled, the following procedure sometimes results in an error at the last step:

1. Take volume snapshot A of VM X
2. Take volume snapshot B of VM X
3. Create a volume from snapshot A
4. Create a volume from snapshot B

When this happens, the second volume is not created, and sometimes volume snapshot B is removed from the primary storage.

##### EXPECTED RESULTS

~~~
Volume is created from volume snapshot
~~~

##### ACTUAL RESULTS

~~~
Volume is not created, and the snapshot is sometimes lost
~~~

**Comment by DaanHoogland** [comment]
@winterhazel as #9270 is still being discussed, I am marking this for 4.21 for now. cc @slavkap @JoaoJandre

**Comment by nvazquez** [comment]
Hi @winterhazel - is this issue still applicable now that #9270 is merged? If not, can it be closed?

**Comment by winterhazel** [comment]
@nvazquez yes, it is still applicable. #9270 does not handle this issue.

**Comment by DaanHoogland** [comment]
@winterhazel , this sounds like a critical bug. Any idea of the likelyhood and/or the cause?

**Comment by winterhazel** [comment]
> [@winterhazel](https://github.com/winterhazel) , this sounds like a critical bug. Any idea of the likelyhood and/or the cause?

@DaanHoogland I did not look into what was causing this issue back then, but I remember that I was only able to reproduce this when attempting to create a volume from a Macchinina root disk volume snapshot. I recall that I also executed the described procedure for root disks with Ubuntu and CentOS, but did not get any error. Perhaps it is related to the volume snapshot's size?

**Comment by DaanHoogland** [comment]
ah, that small template has been giving more problems, maybe we should try increasing the size of(in spite of it not needing it) just to see. In the mean while I think we do not need this issue as macchinina is not for anything but testing. cc @NuxRo

**Comment by abh1sar** [comment]
I failed to reproduce the issue with the steps provided. Also played with different configs.

>> Macchinina root disk volume snapshot
>> 1. Take volume snapshot A of VM X
>> 2. Take volume snapshot B of VM X
>> 3. Create a volume from snapshot A
>> 4. Create a volume from snapshot B
 
* Created multiple snapshots with `kvm.snapshot.enabled` config set to both `true` and `false`
* Created multiple snapshots with `snapshot.backup.to.secondary` config set to both `true` and `false`
* Created multiple snapshots with `kvm.incremental.snapshot` config set to both `true` and `false`

I didn't see any errors while trying to create volumes from the snapshots.

@winterhazel any more info (regarding errors /logs) or a way to repro will be much appreciated.

**Comment by winterhazel** [comment]
@abh1sar thank you for having a look.

My configurations are the following:

- `kvm.snapshot.enabled`: `true`
- `snapshot.backup.to.secondary`: `false`
- `kvm.incremental.snapshot`: `false`

Reproducing the described steps in 4.21.0.0 still yields me an exception in step 4. I attemped some times but did not witness the snapshot loss though.

In the logs, there's the following stacktrace:

```
2025-10-02 02:46:04,789 DEBUG [o.a.c.s.s.SnapshotServiceImpl] (API-Job-Executor-17:[ctx-fd54c6b0, job-867, ctx-5e45a0da]) (logid:bb565e90) Failed to copy snapshot java.lang.RuntimeException: InvocationTargetException when invoking RPC callback for command: copySnapshotAsyncCallback
	at org.apache.cloudstack.framework.async.AsyncCallbackDispatcher.dispatch(AsyncCallbackDispatcher.java:155)
	at org.apache.cloudstack.framework.async.InplaceAsyncCallbackDriver.performCompletionCallback(InplaceAsyncCallbackDriver.java:25)
	at org.apache.cloudstack.framework.async.AsyncCallbackDispatcher.complete(AsyncCallbackDispatcher.java:127)
	at org.apache.cloudstack.storage.motion.AncientDataMotionStrategy.copyAsync(AncientDataMotionStrategy.java:552)
	at org.apache.cloudstack.storage.motion.DataMotionServiceImpl.copyAsync(DataMotionServiceImpl.java:88)
	at org.apache.cloudstack.storage.motion.DataMotionServiceImpl.copyAsync(DataMotionServiceImpl.java:117)
	at org.apache.cloudstack.storage.snapshot.SnapshotServiceImpl.backupSnapshot(SnapshotServiceImpl.java:454)
	at org.apache.cloudstack.storage.snapshot.DefaultSnapshotStrategy.backupSnapshot(DefaultSnapshotStrategy.java:204)
	at org.apache.cloudstack.snapshot.SnapshotHelper.backupSnapshotToSecondaryStorageIfNotExists(SnapshotHelper.java:180)
	at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.createVolumeFromSnapshot(VolumeOrchestrator.java:594)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy3/jdk.proxy3.$Proxy257.createVolumeFromSnapshot(Unknown Source)
	at com.cloud.storage.VolumeApiServiceImpl.createVolumeFromSnapshot(VolumeApiServiceImpl.java:1106)
	at com.cloud.storage.VolumeApiServiceImpl.createVolume(VolumeApiServiceImpl.java:1055)
	at com.cloud.storage.VolumeApiServiceImpl.createVolume(VolumeApiServiceImpl.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:109)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy3/jdk.proxy3.$Proxy283.createVolume(Unknown Source)
	at org.apache.cloudstack.api.command.user.volume.CreateVolumeCmd.execute(CreateVolumeCmd.java:224)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:173)
	at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:110)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:689)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:637)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.apache.cloudstack.framework.async.AsyncCallbackDispatcher.dispatch(AsyncCallbackDispatcher.java:149)
	... 53 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.cloud.storage.CreateSnapshotPayload.getAsyncBackup()" because "createSnapshotPayload" is null
	at org.apache.cloudstack.storage.snapshot.SnapshotServiceImpl.copySnapshotAsyncCallback(SnapshotServiceImpl.java:499)
	... 58 more

2025-10-02 02:46:04,809 DEBUG [c.c.a.m.ClusteredAgentManagerImpl] (AgentManager-Handler-5:[]) (logid:) SeqA 10-: Sending 185
2025-10-02 02:46:04,830 DEBUG [o.a.c.s.SnapshotHelper] (API-Job-Executor-17:[ctx-fd54c6b0, job-867, ctx-5e45a0da]) (logid:bb565e90) Expunge template for Snapshot [Snapshot {"id":9,"name":"m2","state":"BackedUp","uuid":"5cdedc5f-da82-4292-beb4-a795b44f9f81","version":"2.2","volumeId":96}] is called for primary storage role. Not expunging it, but we will still expunge the database reference of the snapshot for image storage role if any
```

**Comment by abh1sar** [comment]
@winterhazel Thanks for the log. But the exception doesn't contain the actual failure reason. 
Could you please look in the log around the exception (or with the same logid) for any relevant failures or other exception?

**Comment by abh1sar** [comment]
Thanks @winterhazel could you please share the full mgmt server log around this time? Would be useful to look at other related log messages.
The Exception above says that copying of the snapshot from Primary to Secondary storage for Volume Creation failed. But it doesn't say anything about the reason for the copy failure.

**Comment by winterhazel** [comment]
@abh1sar looking at the agent's logs, it seems that the `cp` in `managesnapshot.sh` to copy from primary to secondary fails because the directory `/mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75` does not exist in secondary, which is weird as there is a `mkdir` right before.

```
2025-10-07 21:59:49,730 DEBUG [storage.resource.StorageSubsystemCommandHandlerBase] (agentRequest-Handler-3:[]) (logid:119c7f19) Executing command CopyCommand: [{"srcTO":{"org.apache.cloudstack.storage.to.SnapshotObjectTO":{"path":"/mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da","volume":{"uuid":"b568488d-1b5c-49e2-b3e6-19a1a764cbb8","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"8f989a84-e691-3a8f-bbcf-14ec8b839ce5","name":"pri","id":1,"poolType":"NetworkFilesystem","host":"192.168.122.10","path":"/export/primary","port":2049,"url":"NetworkFilesystem://192.168.122.10/export/primary/?ROLE=Primary&STOREUUID=8f989a84-e691-3a8f-bbcf-14ec8b839ce5","isManaged":false}},"name":"ROOT-74","size":52428800,"path":"b568488d-1b5c-49e2-b3e6-19a1a764cbb8","volumeId":75,"vmName":"i-2-74-VM","accountId":2,"format":"QCOW2","provisioningType":"THIN","poolId":1,"id":75,"deviceId":0,"hypervisorType":"KVM","directDownload":false,"deployAsIs":false,"followRedirects":false},"dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"8f989a84-e691-3a8f-bbcf-14ec8b839ce5","name":"pri","id":1,"poolType":"NetworkFilesystem","host":"192.168.122.10","path":"/export/primary","port":2049,"url":"NetworkFilesystem://192.168.122.10/export/primary/?ROLE=Primary&STOREUUID=8f989a84-e691-3a8f-bbcf-14ec8b839ce5","isManaged":false}},"vmName":"i-2-74-VM","name":"a","hypervisorType":"KVM","id":2,"quiescevm":false,"physicalSize":0,"accountId":2,"followRedirects":false}},"destTO":{"org.apache.cloudstack.storage.to.SnapshotObjectTO":{"path":"snapshots/2/75","volume":{"uuid":"b568488d-1b5c-49e2-b3e6-19a1a764cbb8","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"8f989a84-e691-3a8f-bbcf-14ec8b839ce5","name":"pri","id":1,"poolType":"NetworkFilesystem","host":"192.168.122.10","path":"/export/primary","port":2049,"url":"NetworkFilesystem://192.168.122.10/export/primary/?ROLE=Primary&STOREUUID=8f989a84-e691-3a8f-bbcf-14ec8b839ce5","isManaged":false}},"name":"ROOT-74","size":52428800,"path":"b568488d-1b5c-49e2-b3e6-19a1a764cbb8","volumeId":75,"vmName":"i-2-74-VM","accountId":2,"format":"QCOW2","provisioningType":"THIN","poolId":1,"id":75,"deviceId":0,"hypervisorType":"KVM","directDownload":false,"deployAsIs":false,"followRedirects":false},"dataStore":{"com.cloud.agent.api.to.NfsTO":{"_url":"nfs://192.168.122.10/export/secondary","_role":"Image"}},"vmName":"i-2-74-VM","name":"a","hypervisorType":"KVM","id":2,"quiescevm":false,"physicalSize":0,"accountId":2,"followRedirects":false}},"executeInSequence":false,"options":{"snapshot.backup.to.secondary":"false","fullSnapshot":"true"},"options2":{},"wait":21600,"bypassHostMaintenance":false}].
2025-10-07 21:59:49,731 DEBUG [agent.properties.AgentPropertiesFileHandler] (agentRequest-Handler-3:[]) (logid:119c7f19) Property [hypervisor.uri] has empty or null value. Using default value [null].
2025-10-07 21:59:49,731 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Looking for libvirtd connection at: qemu:///system
2025-10-07 21:59:49,739 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Can not find KVM connection for Instance: i-2-74-VM, continuing.
2025-10-07 21:59:49,740 DEBUG [agent.properties.AgentPropertiesFileHandler] (agentRequest-Handler-3:[]) (logid:119c7f19) Property [hypervisor.uri] has empty or null value. Using default value [null].
2025-10-07 21:59:49,740 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Looking for libvirtd connection at: lxc:///
2025-10-07 21:59:49,740 INFO  [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) No existing libvirtd connection found. Opening a new one
2025-10-07 21:59:49,741 DEBUG [agent.properties.AgentPropertiesFileHandler] (agentRequest-Handler-3:[]) (logid:119c7f19) Property [libvirt.events.enabled] has empty or null value. Using default value [false].
2025-10-07 21:59:49,741 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Libvirt event listening is disabled, not setting up event loop
2025-10-07 21:59:49,745 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Can not find LXC connection for Instance: i-2-74-VM, continuing.
2025-10-07 21:59:49,745 WARN  [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Can not find a connection for Instance i-2-74-VM. Assuming the default connection.
2025-10-07 21:59:49,745 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Looking for libvirtd connection at: qemu:///system
2025-10-07 21:59:49,748 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Attempting to create storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a (NetworkFilesystem) in libvirt
2025-10-07 21:59:49,751 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Looking for libvirtd connection at: qemu:///system
2025-10-07 21:59:49,755 WARN  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a was not found running in libvirt. Need to create it.
2025-10-07 21:59:49,755 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Didn't find an existing storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a by UUID, checking for pools with duplicate paths
2025-10-07 21:59:49,758 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Checking path of existing pool e409d730-8af7-4815-a35a-64a477e5aedf against pool we want to create
2025-10-07 21:59:49,772 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Checking path of existing pool 8f989a84-e691-3a8f-bbcf-14ec8b839ce5 against pool we want to create
2025-10-07 21:59:49,796 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Checking path of existing pool c08f4f65-7793-3fe4-bb4a-8207dbb34b8b against pool we want to create
2025-10-07 21:59:49,836 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Checking path of existing pool cc9d9a67-4b15-32b1-b401-f432ffcd85d1 against pool we want to create
2025-10-07 21:59:49,852 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Attempting to create storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a
2025-10-07 21:59:49,852 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) <pool type='netfs' xmlns:fs='http://libvirt.org/schemas/storagepool/fs/1.0'>
2025-10-07 21:59:49,853 DEBUG [utils.script.Script] (agentRequest-Handler-3:[]) (logid:119c7f19) Executing command [/bin/bash -c mountpoint -q /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a ].
2025-10-07 21:59:49,871 WARN  [utils.script.Script] (agentRequest-Handler-3:[]) (logid:119c7f19) Execution of process [13173] for command [/bin/bash -c mountpoint -q /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a ] failed.
2025-10-07 21:59:49,871 DEBUG [utils.script.Script] (agentRequest-Handler-3:[]) (logid:119c7f19) Exit value of process [13173] for command [/bin/bash -c mountpoint -q /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a ] is [32].
2025-10-07 21:59:49,871 WARN  [utils.script.Script] (agentRequest-Handler-3:[]) (logid:119c7f19) Process [13173] for command [/bin/bash -c mountpoint -q /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a ] encountered the error: [32].
2025-10-07 21:59:49,947 DEBUG [utils.script.Script] (agentRequest-Handler-3:[]) (logid:119c7f19) Executing command [/bin/bash -c mountpoint -q /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a ].
2025-10-07 21:59:49,963 DEBUG [utils.script.Script] (agentRequest-Handler-3:[]) (logid:119c7f19) Successfully executed process [13180] for command [/bin/bash -c mountpoint -q /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a ].
2025-10-07 21:59:49,964 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Trying to fetch storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a from libvirt
2025-10-07 21:59:49,964 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Looking for libvirtd connection at: qemu:///system
2025-10-07 21:59:49,984 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Successfully refreshed pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a Capacity: (96.88 GB) 104028176384 Used: (44.57 GB) 47854911488 Available: (52.32 GB) 56173264896
2025-10-07 21:59:49,985 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Trying to fetch storage pool 8f989a84-e691-3a8f-bbcf-14ec8b839ce5 from libvirt
2025-10-07 21:59:49,985 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Looking for libvirtd connection at: qemu:///system
2025-10-07 21:59:50,012 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Successfully refreshed pool 8f989a84-e691-3a8f-bbcf-14ec8b839ce5 Capacity: (96.88 GB) 104028176384 Used: (44.52 GB) 47801434112 Available: (52.37 GB) 56226742272
2025-10-07 21:59:50,029 DEBUG [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-3:[]) (logid:119c7f19) Executing command [/usr/share/cloudstack-common/scripts/storage/qcow2/managesnapshot.sh -b /mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da -n fc6bec25-28ff-483a-99da-f6917542c4da -p /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75 -t 2c7300fd-c557-4923-a8cc-480ad733c612 ].
2025-10-07 21:59:50,077 WARN  [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-3:[]) (logid:119c7f19) Execution of process [13181] for command [/usr/share/cloudstack-common/scripts/storage/qcow2/managesnapshot.sh -b /mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da -n fc6bec25-28ff-483a-99da-f6917542c4da -p /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75 -t 2c7300fd-c557-4923-a8cc-480ad733c612 ] failed.
2025-10-07 21:59:50,077 DEBUG [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-3:[]) (logid:119c7f19) Exit value of process [13181] for command [/usr/share/cloudstack-common/scripts/storage/qcow2/managesnapshot.sh -b /mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da -n fc6bec25-28ff-483a-99da-f6917542c4da -p /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75 -t 2c7300fd-c557-4923-a8cc-480ad733c612 ] is [2].
2025-10-07 21:59:50,078 WARN  [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-3:[]) (logid:119c7f19) Process [13181] for command [/usr/share/cloudstack-common/scripts/storage/qcow2/managesnapshot.sh -b /mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da -n fc6bec25-28ff-483a-99da-f6917542c4da -p /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75 -t 2c7300fd-c557-4923-a8cc-480ad733c612 ] encountered the error: [cp: cannot create regular file '/mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75/2c7300fd-c557-4923-a8cc-480ad733c612': No such file or directoryFailed to backup fc6bec25-28ff-483a-99da-f6917542c4da for disk /mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da to /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75].
2025-10-07 21:59:50,078 DEBUG [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-3:[]) (logid:119c7f19) Failed to backup snaptshot: cp: cannot create regular file '/mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75/2c7300fd-c557-4923-a8cc-480ad733c612': No such file or directoryFailed to backup fc6bec25-28ff-483a-99da-f6917542c4da for disk /mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da to /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75
2025-10-07 21:59:50,079 DEBUG [kvm.storage.KVMStorageProcessor] (agentRequest-Handler-3:[]) (logid:119c7f19) This backup is temporary, not deleting snapshot [/mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da] on primary storage [8f989a84-e691-3a8f-bbcf-14ec8b839ce5]
2025-10-07 21:59:50,079 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Attempting to remove storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a from libvirt
2025-10-07 21:59:50,079 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:[]) (logid:119c7f19) Looking for libvirtd connection at: qemu:///system
2025-10-07 21:59:50,085 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a has no corresponding secret. Not removing any secret.
2025-10-07 21:59:50,110 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:[]) (logid:119c7f19) Storage pool 29506a35-fd13-3d28-9ea5-f38d05dbfe5a was successfully removed from libvirt.
2025-10-07 21:59:50,122 DEBUG [cloud.agent.Agent] (agentRequest-Handler-3:[]) (logid:119c7f19) Seq 1-224617031415103660:  { Ans: , MgmtId: 117375486344555, via: 1, Ver: v1, Flags: 10, [{"org.apache.cloudstack.storage.command.CopyCmdAnswer":{"result":"false","details":"cp: cannot create regular file '/mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75/2c7300fd-c557-4923-a8cc-480ad733c612': No such file or directoryFailed to backup fc6bec25-28ff-483a-99da-f6917542c4da for disk /mnt/8f989a84-e691-3a8f-bbcf-14ec8b839ce5/snapshots/fc6bec25-28ff-483a-99da-f6917542c4da to /mnt/29506a35-fd13-3d28-9ea5-f38d05dbfe5a/snapshots/2/75","wait":"0","bypassHostMaintenance":"false"}}] }
```

**Comment by DaanHoogland** [comment]
@winterhazel , is this relevant for 22 onwards? (can we still reproduce?) cc @sureshanaparti .

**Comment by DaanHoogland** [comment]
ping @winterhazel @sureshanaparti @abh1sar @vladimirpetrov @harikrishna-patnala Is this serious enough to persue in the coming months?

**Comment by winterhazel** [comment]
> ping [@winterhazel](https://github.com/winterhazel) [@sureshanaparti](https://github.com/sureshanaparti) [@abh1sar](https://github.com/abh1sar) [@vladimirpetrov](https://github.com/vladimirpetrov) [@harikrishna-patnala](https://github.com/harikrishna-patnala) Is this serious enough to persue in the coming months?

@DaanHoogland I think we can close this one. I am not able to reproduce the snapshot loss anymore, and the copy failure seems more like a permissioning issue with the environment I was using at that time.
