### ISSUE TITLE
Delete edge vr showing internal server error.

### ISSUE THREAD

**Issue by hulucc** [apache/cloudstack#9847]
Bug Report

VR

4.18.2

```
cloudstack-0 cloudstack ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-91:ctx-f65e2666 job-174) (logid:4dce969b) Unexpected exception while executing org.apache.cloudstack.api.command.admin.router.DestroyRouterCmd
cloudstack-0 cloudstack java.lang.NullPointerException
cloudstack-0 cloudstack         at com.cloud.network.NetworkModelImpl.getUserDataUpdateProvider(NetworkModelImpl.java:928)
cloudstack-0 cloudstack         at com.cloud.network.element.ConfigDriveNetworkElement.postStateTransitionEvent(ConfigDriveNetworkElement.java:322)
cloudstack-0 cloudstack         at com.cloud.network.element.ConfigDriveNetworkElement.postStateTransitionEvent(ConfigDriveNetworkElement.java:94)
cloudstack-0 cloudstack         at com.cloud.utils.fsm.StateMachine2.transitTo(StateMachine2.java:142)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.stateTransitTo(VirtualMachineManagerImpl.java:2248)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.advanceExpunge(VirtualMachineManagerImpl.java:614)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.advanceExpunge(VirtualMachineManagerImpl.java:594)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.expunge(VirtualMachineManagerImpl.java:583)
cloudstack-0 cloudstack         at com.cloud.network.router.NetworkHelperImpl.destroyRouter(NetworkHelperImpl.java:272)
cloudstack-0 cloudstack         at com.cloud.network.router.VirtualNetworkApplianceManagerImpl.destroyRouter(VirtualNetworkApplianceManagerImpl.java:405)
cloudstack-0 cloudstack         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cloudstack-0 cloudstack         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
cloudstack-0 cloudstack         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cloudstack-0 cloudstack         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
cloudstack-0 cloudstack         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
cloudstack-0 cloudstack         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
cloudstack-0 cloudstack         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
cloudstack-0 cloudstack         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
cloudstack-0 cloudstack         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
cloudstack-0 cloudstack         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
cloudstack-0 cloudstack         at com.sun.proxy.$Proxy280.destroyRouter(Unknown Source)
cloudstack-0 cloudstack         at org.apache.cloudstack.api.command.admin.router.DestroyRouterCmd.execute(DestroyRouterCmd.java:97)
cloudstack-0 cloudstack         at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:163)
cloudstack-0 cloudstack         at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:112)
cloudstack-0 cloudstack         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
cloudstack-0 cloudstack         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cloudstack-0 cloudstack         at java.base/java.lang.Thread.run(Thread.java:829)
```

##### STEPS TO REPRODUCE
1. Create edge zone
2. Create shared network without using direct download system template
3. Destory the vr systemvm will cause the error.

##### EXPECTED RESULTS
1. delete the vr without any error

##### ACTUAL RESULTS
1. internal server error

**Comment by sureshanaparti** [comment]
Hi @hulucc I could reproduce this issue with 4.19.1, fixed here: #10255.

**Comment by sureshanaparti** [comment]
Fix PR is merged, closing this.
