### ISSUE TITLE
Unable to deploy a vm  from direct download templates on 4.18.2.x releases

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#9860]
ISSUE TYPE

Bug

COMPONENT NAME

Component: Bug

CLOUDSTACK VERSION

Cloudstack version 4.18.2.4

SUMMARY

Unable to deploy a vm's  from direct download templates

**Steps to reproduce the behaviour**

1. Register a direct download template  

2. Deploy a vm from a direct download template 

3. Deployment fails

Logs 

```
2024-10-28 05:46:23,352 DEBUG [c.c.c.CapacityManagerImpl] (qtp1690859824-16:ctx-b0ed8197 ctx-a76f8643) (logid:2020d42d) VM instance {"id":8,"instanceName":"i-2-8-VM","type":"User","uuid":"9f55705e-fd9b-4e27-bca6-dc5a88b9f341"} state transited from [Stopped] to [Error] with event [OperationFailedToError]. VM's original host: null, new host: null, host before state transition: null
2024-10-28 05:46:23,368 ERROR [c.c.a.ApiServer] (qtp1690859824-16:ctx-b0ed8197 ctx-a76f8643) (logid:2020d42d) unhandled exception executing api command: [Ljava.lang.String;@4838a1ed
com.cloud.utils.exception.CloudRuntimeException: Template 204 has not been completely downloaded to zone 1
        at com.cloud.template.TemplateManagerImpl.getTemplateSize(TemplateManagerImpl.java:2016)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopU

```
          
![Screenshot 2024-10-28 at 1 53 55 PM](https://github.com/user-attachments/assets/d03ac138-4512-40bc-9613-3dc6d804d5f8)

 
 
This issue is only observed on 4.18.2.X

Tested On 4.18.1.1  and the issue was not observed 
 
Expected Behaviour

The deployments should succeed on 4.18.2.X environments

**Comment by harikrishna-patnala** [comment]
@kiranchavala is this working on 4.19 and main branches ?

**Comment by kiranchavala** [comment]
@harikrishna-patnala its working fine on 4.19.1 releases

**Comment by GutoVeronezi** [comment]
Hello @kiranchavala, thanks for opening the issue.

4.18 is EOL (https://cwiki.apache.org/confluence/display/CLOUDSTACK/LTS) and as yourself stated, it is not happening on 4.19.1.  Therefore, I will close this issue.

Furthermore, take a look at your issue from last year (#8037) and PR #8093.
