### ISSUE TITLE
veeam B&R : ERROR while removing instance from backup offering 

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#9896]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Logging
~~~

##### CLOUDSTACK VERSION

~~~
4.20-SNAPSHOT
~~~

##### CONFIGURATION

Veeam B&R provider configured with Veeam Backup and replication 12.2 

##### SUMMARY

On removing the backup offering on an instance, although it gets removed there is an error in the management server log. The async job result is "success". 
```

2024-11-06 07:38:54,643 DEBUG [o.a.c.b.v.VeeamClient] (API-Job-Executor-22:[ctx-f25b54d6, job-723, ctx-fd699c6a]) (logid:c2072895) Response received in GET request is: [HttpResponseProxy{HTTP/1.1 400 BadRequest [Cache-Control: private, Content-Length: 264, Content-Type: application/xml, Server: Microsoft-HTTPAPI/2.0, X-Frame-Options: SAMEORIGIN, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=31536000, X-Content-Type-Options: nosniff, Date: Wed, 06 Nov 2024 07:38:54 GMT] ResponseEntityProxy{[Content-Type: application/xml,Content-Length: 264,Chunked: false]}}] for URL: [https://10.0.35.79:9398/api//jobs/null/includes].
2024-11-06 07:38:54,643 DEBUG [o.a.c.b.v.VeeamClient] (API-Job-Executor-22:[ctx-f25b54d6, job-723, ctx-fd699c6a]) (logid:c2072895) HTTP request failed, status code is [400], response is: [HttpResponseProxy{HTTP/1.1 400 BadRequest [Cache-Control: private, Content-Length: 264, Content-Type: application/xml, Server: Microsoft-HTTPAPI/2.0, X-Frame-Options: SAMEORIGIN, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=31536000, X-Content-Type-Options: nosniff, Date: Wed, 06 Nov 2024 07:38:54 GMT] ResponseEntityProxy{[Content-Type: application/xml,Content-Length: 264,Chunked: false]}}].
2024-11-06 07:38:54,643 DEBUG [o.a.c.b.VeeamBackupProvider] (API-Job-Executor-22:[ctx-f25b54d6, job-723, ctx-fd699c6a]) (logid:c2072895) VM was removed from the job so could not remove again, trying to delete the veeam job now. org.apache.cloudstack.api.ServerApiException: Got invalid API status code returned by the Veeam server
        at org.apache.cloudstack.backup.veeam.VeeamClient.checkResponseOK(VeeamClient.java:215)
        at org.apache.cloudstack.backup.veeam.VeeamClient.removeVMFromVeeamJob(VeeamClient.java:573)
        at org.apache.cloudstack.backup.VeeamBackupProvider.removeVMFromBackupOffering(VeeamBackupProvider.java:201)
```

##### STEPS TO REPRODUCE

~~~
1. Remove the backup offering from instance.
2. Watch the logs.
~~~

##### EXPECTED RESULTS

~~~
There shouldn't be any error in the management server log while removing an instance from the backup offering. 
~~~

##### ACTUAL RESULTS

~~~
There is an unexpected error in the management server log while removing an instance from the backup offering. 
~~~

**Comment by weizhouapache** [comment]
@rajujith 
just to confirm, irrespect to the error log, the operation still succeeded, right ?

**Comment by rajujith** [comment]
> @rajujith just to confirm, irrespect to the error log, the operation still succeeded, right ?

Yes.

**Comment by abh1sar** [comment]
@DaanHoogland yes, will work on this in the upcoming week.

**Comment by abh1sar** [comment]
Fixed by https://github.com/apache/cloudstack/pull/10562
