### ISSUE TITLE
Error when using CLVM in KVM Hypervisor

### ISSUE THREAD

**Issue by Luskan777** [apache/cloudstack#9915]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
STORAGE
CLVM
~~~

##### CLOUDSTACK VERSION

~~~
4.20
~~~

##### OS / ENVIRONMENT

- KVM/libvirt as Virtualization is used
- Ubuntu 22.04.5 LTS (Agent) 
- CLVM Primary Storage

##### SUMMARY

I am trying to use CLVM as Primary Storage, but when I try to add Primary Storage it gives me an error.

However, if I check the KVM agent hosts, it creates the storage pool in libvirt as expected, but it doesn't finish creating the Primary Storage in Cloudstack Management

Cloustack Agents KVM: 

![Captura de Tela 2024-11-08 às 13 57 38](https://github.com/user-attachments/assets/fa9e8bed-b48b-4950-86a5-61476c74a278)

##### STEPS TO REPRODUCE

~~~
Using KVM as Hypervisor, try adding a Primary Storage of type CLVM
~~~

##### EXPECTED RESULTS

~~~
Primary Storage created successfully
~~~

##### ACTUAL RESULTS

Cloudstack UI:
~~~
Request failed. (530)
Failed to add data store: Failed to access storage pool
~~~
<img width="992" alt="Captura de Tela 2024-11-08 às 11 40 36" src="https://github.com/user-attachments/assets/10b5f61d-74b7-43f8-a2a4-d6b8edba515c">

Cloudstack management (Logs):
~~~
DEBUG [c.c.a.t.Request] (AgentManager-Handler-1:[]) (logid:) Seq 18-5556597515245060226: Processing:  { Ans: , MgmtId: 42374915704331, via: 18, Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":"false","details":"java.lang.IllegalArgumentException: No enum constant com.cloud.hypervisor.kvm.resource.LibvirtStoragePoolDef.PoolType.LOGICAL
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.cloud.hypervisor.kvm.resource.LibvirtStoragePoolDef$PoolType.valueOf(LibvirtStoragePoolDef.java:26)
	at com.cloud.hypervisor.kvm.resource.LibvirtStoragePoolXMLParser.parseStoragePoolXML(LibvirtStoragePoolXMLParser.java:118)
	at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.getStoragePoolDef(LibvirtStorageAdaptor.java:502)
	at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.getStoragePool(LibvirtStorageAdaptor.java:534)
	at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.getStoragePool(LibvirtStorageAdaptor.java:519)
	at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.createStoragePool(LibvirtStorageAdaptor.java:763)
	at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.createStoragePool(KVMStoragePoolManager.java:392)
	at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.createStoragePool(KVMStoragePoolManager.java:386)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtModifyStoragePoolCommandWrapper.execute(LibvirtModifyStoragePoolCommandWrapper.java:42)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtModifyStoragePoolCommandWrapper.execute(LibvirtModifyStoragePoolCommandWrapper.java:35)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
	at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1944)
	at com.cloud.agent.Agent.processRequest(Agent.java:686)
	at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1109)
	at com.cloud.utils.nio.Task.call(Task.java:83)
	at com.cloud.utils.nio.Task.call(Task.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
","wait":"0","bypassHostMaintenance":"false"}}] }
~~~

**Comment by DaanHoogland** [comment]
@Luskan777 the exception trace means that at the agent side the requested pool type is not recognised. Can you look at the agent log some more related messages above the stack trace.

pooltypes are
```
ISCSI("iscsi"), NETFS("netfs"), LOGICAL("logical"), DIR("dir"), RBD("rbd"), GLUSTERFS("glusterfs"), POWERFLEX("powerflex")
```
it seems to be the 'logical' in
```
<pool type='logical'>
```
which is not recognised, so that seems a false negative.
any more info is welcome.

**Comment by slavkap** [comment]
Hi @DaanHoogland, @Luskan777, there was a typo in the PR for upgrading log4j
https://github.com/apache/cloudstack/blob/f7b7339bcfb2aeb2c5d5efc30c4b855da28ff359/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDef.java#L27

**Comment by Luskan777** [comment]
Hi @slavkap , @DaanHoogland sorry, I'm on version 4.20.0, I'm using 4.20 to test some features and forgot to revert to 4.19.

However, I noticed that the typo was from PR #7131 , I'll fix it and test to see if everything works as expected.

**Comment by weizhouapache** [comment]
> Hi @DaanHoogland, @Luskan777, there was a typo in the PR for upgrading log4j
> https://github.com/apache/cloudstack/blob/f7b7339bcfb2aeb2c5d5efc30c4b855da28ff359/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtStoragePoolDef.java#L27
> 
> after I spoke with @DaanHoogland, this typo is only in version 4.20 not in the version mentioned in the issue

Good finding
Can you create a pr ? @slavkap

**Comment by weizhouapache** [comment]
> @weizhouapache, @DaanHoogland already made a fix #9922 

Thanks @slavkap 

Sorry , I did not see your pr @DaanHoogland

**Comment by DaanHoogland** [comment]
> However, I noticed that the typo was from PR #7131 , I'll fix it and test to see if everything works as expected.

@Luskan777 , as a matter of formality we ask third party testing. Could you apply #9922 and confirm this solves your issue?

**Comment by JoaoJandre** [comment]
> > However, I noticed that the typo was from PR #7131 , I'll fix it and test to see if everything works as expected.
> 
> @Luskan777 , as a matter of formality we ask third party testing. Could you apply #9922 and confirm this solves your issue?

I'm sorry @DaanHoogland, I did not see your comment prior to merging. As the change was simple and all the basic merging criteria was met, I did not think we needed third party testing.

**Comment by JoaoJandre** [comment]
In any case, since the change in #9922 is tied to a bigger problem, we should wait for @Luskan777 to confirm that it fixes #9915. Otherwise, we can create another PR to solve this.

**Comment by Luskan777** [comment]
> > However, I noticed that the typo was from PR #7131 , I'll fix it and test to see if everything works as expected.
> 
> @Luskan777 , as a matter of formality we ask third party testing. Could you apply #9922 and confirm this solves your issue?

Hi @DaanHoogland, ok, I'm already testing this.

**Comment by Luskan777** [comment]
Hi @DaanHoogland  @JoaoJandre , 

I tested the PR and everything works fine now, I can create a Primary Storage as CLVM, thank you very much for your contributions 🙏
