### ISSUE TITLE
Cloudstack-agent failed to start

### ISSUE THREAD

**Issue by bwcxyk** [apache/cloudstack#9968]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Agent
~~~

##### CLOUDSTACK VERSION

~~~
4.18.2.5
~~~

##### CONFIGURATION

Advanced networking

##### OS / ENVIRONMENT

Ubuntu 22.04

##### SUMMARY

Cloudstack-agent is not running

##### STEPS TO REPRODUCE

~~~
Infrastructure -> Zones
Add zone

Advanced networking add the host in CloudStack is error
~~~

##### EXPECTED RESULTS

~~~
Cloudstack-agent is running
~~~

##### ACTUAL RESULTS

~~~
Cloudstack-agent is not running
~~~

My Bridged Network Configuration
```
network:
  version: 2
  ethernets:
    ens33: {}
    ens34: {}
  bridges:
    cloudbr0:
      addresses:
        - 192.168.10.41/23
      dhcp4: false
      routes:
        - to: default
          via: 192.168.11.1
      nameservers:
        addresses:
          - 233.5.5.5
          - 114.114.114.114
      interfaces:
        - ens33
      parameters:
        stp: true
    cloudbr1:
      dhcp4: false
      interfaces:
        - ens34
      parameters:
        stp: true
```
agent.log
```
2024-11-25 13:38:41,945 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Agent started
2024-11-25 13:38:41,949 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Implementation Version is 4.18.2.5
2024-11-25 13:38:41,952 INFO  [cloud.agent.AgentShell] (main:null) (logid:) agent.properties found at /etc/cloudstack/agent/agent.properties
2024-11-25 13:38:42,006 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Defaulting to using properties file for storage
2024-11-25 13:38:42,007 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Defaulting to the constant time backoff algorithm
2024-11-25 13:38:42,043 INFO  [cloud.utils.LogUtils] (main:null) (logid:) log4j configuration found at /etc/cloudstack/agent/log4j-cloud.xml
2024-11-25 13:38:42,044 INFO  [cloud.agent.AgentShell] (main:null) (logid:) Using default Java settings for IPv6 preference for agent connection
2024-11-25 13:38:42,126 INFO  [cloud.agent.Agent] (main:null) (logid:) id is 
2024-11-25 13:38:42,135 WARN  [cloud.resource.ServerResourceBase] (main:null) (logid:) Incorrect details for private Nic during initialization of ServerResourceBase
2024-11-25 13:38:42,136 ERROR [cloud.agent.AgentShell] (main:null) (logid:) Unable to start agent: 
javax.naming.ConfigurationException: Unable to configure LibvirtComputingResource
	at com.cloud.agent.Agent.<init>(Agent.java:192)
	at com.cloud.agent.AgentShell.launchNewAgent(AgentShell.java:452)
	at com.cloud.agent.AgentShell.launchAgentFromClassInfo(AgentShell.java:431)
	at com.cloud.agent.AgentShell.launchAgent(AgentShell.java:415)
	at com.cloud.agent.AgentShell.start(AgentShell.java:511)
	at com.cloud.agent.AgentShell.main(AgentShell.java:541)
```
Does cloudbr1 also need to be configured for networking?

**Comment by bwcxyk** [comment]
I found the cause, a network misconfiguration when adding the resource domain caused it.
In the traffic type, MANAGEMENT needs to be configured with a NIC that has an IP.
